### PR TITLE
examples: Set correct image pull policy

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/439)

### CODE REVIEW

**Comment by ivan4th** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/cirros-vm.yaml, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/439#-Kv7MF_yFsILLGgdiyDv:-Kv7MF_yFsILLGgdiyDw:bncpvnv) ([raw file](https://github.com/mirantis/virtlet/blob/ceab8aa2952033a02aabd308ed8eeeef1ed99fe5/examples/cirros-vm.yaml#L42)):*
> ```YAML
>     # of the image name is prepended with https:// and used to download the image
>     image: virtlet/cirros
>     imagePullPolicy: IfNotPresent
> ```

I think we should add a comment why it's done at least in this basic example.
E.g. 
`imagePullPolicy` defaults to `Always` here because Virtlet images don't have tags

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/439)*

**Comment by pigmej** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/cirros-vm.yaml, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/439#-Kv7MF_yFsILLGgdiyDv:-Kv7OZZVZCBaLsLJTMCN:b-id4oat) ([raw file](https://github.com/mirantis/virtlet/blob/ceab8aa2952033a02aabd308ed8eeeef1ed99fe5/examples/cirros-vm.yaml#L42)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I think we should add a comment why it's done at least in this basic example.
E.g. 
`imagePullPolicy` defaults to `Always` here because Virtlet images don't have tags
</blockquote></details>

+1 to that suggestion. Also we should probably documment it 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/439)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/cirros-vm.yaml, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/439#-Kv7MF_yFsILLGgdiyDv:-Kv7PO0WYrIe54HT3teT:b-cswzc5) ([raw file](https://github.com/mirantis/virtlet/blob/ceab8aa2952033a02aabd308ed8eeeef1ed99fe5/examples/cirros-vm.yaml#L42)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

+1 to that suggestion. Also we should probably documment it 
</blockquote></details>

@Ivan it's not because Virtlet images don't have tags (we are simply ignoring them there: https://github.com/Mirantis/virtlet/blob/d445f751c36171039863925363f182ad60cc8d90/pkg/libvirttools/image.go#L85

@Jedrzej: document what? It's already documented there: https://kubernetes.io/docs/concepts/containers/images/#updating-images - it's a bit misleading description, but in original place.

Anyway - will add additional description in commit message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/439)*

**Comment by jellonek** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/cirros-vm.yaml, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/439#-Kv7MF_yFsILLGgdiyDv:-Kv7ToovcklW1R682ohK:b-hiekp5) ([raw file](https://github.com/mirantis/virtlet/blob/ceab8aa2952033a02aabd308ed8eeeef1ed99fe5/examples/cirros-vm.yaml#L42)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

@Ivan it's not because Virtlet images don't have tags (we are simply ignoring them there: https://github.com/Mirantis/virtlet/blob/d445f751c36171039863925363f182ad60cc8d90/pkg/libvirttools/image.go#L85

@Jedrzej: document what? It's already documented there: https://kubernetes.io/docs/concepts/containers/images/#updating-images - it's a bit misleading description, but in original place.

Anyway - will add additional description in commit message.
</blockquote></details>

Description added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/439)*

**Comment by ivan4th** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/cirros-vm.yaml, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/439#-Kv7MF_yFsILLGgdiyDv:-Kv7R2Qq-vFLr6jjRqqb:bwf0hr3) ([raw file](https://github.com/mirantis/virtlet/blob/ceab8aa2952033a02aabd308ed8eeeef1ed99fe5/examples/cirros-vm.yaml#L42)):*
> imagePullPolicy defaults to Always here because Virtlet images don't have tags
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>
>               
>               
>                 
>                   18 minutes ago
>                 
>               
>             
>               
>                 New comments
>               
>               
>               pigmejJędrzej Nowak
</details>
> 
>               
>               
>                 

---

*[examples/cirros-vm.yaml, line 48 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/439#-Kv7fY-gaPPbgXUgF7ad:-Kv7fY-gaPPbgXUgF7ae:bwiapy9) ([raw file](https://github.com/mirantis/virtlet/blob/e3494ed13749f998dc40aab639605bf0cbff8817/examples/cirros-vm.yaml#L48)):*
> ```YAML
>     # https://kubernetes.io/docs/concepts/containers/images/#updating-images
>     # allows Virtlet to reuse already downloaded image if it's already in
>     # local store
> ```

This doesn't explain virtlet specific parts (imagePullPolicy is not Always for plain pods). Maybe this:
Kubelet defaults to imagePullPolicy: Always for Virtlet pod because Virtlet doesn't use image tags. This means that the image is always redownloaded when the pod is created. In order to make pod creation faster and more reliable, we set imagePullPolicy to IfNotPresent here so Virtlet reuses the previously downloaded image if there is one in Virtlet's image store. For more info, see https://kubernetes.io/docs/concepts/containers/images/#updating-images

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/439)*

**Comment by ivan4th** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/cirros-vm.yaml, line 48 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/439#-Kv7fY-gaPPbgXUgF7ad:-Kv7guKdo-7GJZ-hx3Hi:b-m412bw) ([raw file](https://github.com/mirantis/virtlet/blob/e3494ed13749f998dc40aab639605bf0cbff8817/examples/cirros-vm.yaml#L48)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

This doesn't explain virtlet specific parts (imagePullPolicy is not Always for plain pods). Maybe this:
Kubelet defaults to imagePullPolicy: Always for Virtlet pod because Virtlet doesn't use image tags. This means that the image is always redownloaded when the pod is created. In order to make pod creation faster and more reliable, we set imagePullPolicy to IfNotPresent here so Virtlet reuses the previously downloaded image if there is one in Virtlet's image store. For more info, see https://kubernetes.io/docs/concepts/containers/images/#updating-images
</blockquote></details>

s/for Virtlet pod/for Virtlet pods/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/439)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/439#-:-Kv7s-YapNFQbbUpXBQG:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/439#-:-Kv80VJqqoX4v4gf_EAV:bnfp4nl)*

**Pull request merged**
