### PR TITLE
Keep VM data during node restart

### PR DESCRIPTION
**Pull request by keyingliu**
Found during node restart, all VM data are deleted during GC. From my point of view, VM is different from Pod, the data should be kept, and virtlet keeps VM data during virtlet pod restart, kubelet restart, but always deleting VM data after node reboot. The virtlet GC is too aggressive, as during node reboot the  `IsPathAnNs ` always returns false, all sandboxes and containers are deleted from db. This pr only updated sandbox status, and make the /etc/libvirt/qemu be a host mount which makes sure libvirt can find the domain after node reboot.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/839)

### CODE REVIEW

**Comment by jellonek** [comment]
Please use `./build/cmd.sh update-bindata` to include your changes in DS definition into sources.

**Comment by keyingliu** [comment]
@jellonek how can I rerun the test jobs?

**Comment by keyingliu** [comment]
@jellonek all e2e reported error:
```        <*errors.errorString | 0xc4211015f0>: {
            s: "pod rootfs-cm is not Running phase: Pending",
        }
        pod rootfs-cm is not Running phase: Pending
```
could you please take a look why?

**Comment by jellonek** [comment]
Looks like there is an issue in master after merging #837 so it's disconnected with your changes.

**Pull request merged**
