### PR TITLE
Fix demo on darwin

### PR DESCRIPTION
**Pull request by pigmej**
There is a problem with mounting /boot on darwin.

Without that one will get:
```* Access dashboard at: http://localhost:8080/api/v1/namespaces/kube-system/services/kubernetes-dashboard:/proxy
* Marking mounts used by virtlet as shared in kube-node-1 container 
mount: /boot is not mountpoint or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/662)

### CODE REVIEW

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[deploy/demo.sh, line 266 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/662#-LAYg8ooE7a7J1qjqEPo:-LAYg8ooE7a7J1qjqEPp:b46nii8) ([raw file](https://github.com/mirantis/virtlet/blob/378657771ea347d1849325e459a51f9a509619d7/deploy/demo.sh#L266)):*
> ```Shell
>   # later anyway.
>   if [[ ${using_linuxkit} ]]; then
>     return
> ```

You should `return 1`there.

---

*[deploy/demo.sh, line 309 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/662#-LAYgFsx-K2Tn5tHtGoC:-LAYgFsx-K2Tn5tHtGoD:b8muyi7) ([raw file](https://github.com/mirantis/virtlet/blob/378657771ea347d1849325e459a51f9a509619d7/deploy/demo.sh#L309)):*
> ```Shell
>   fi
>   echo "Will run demo using Virtlet:${virtlet_release} for demo and ${virtlet_docker_tag} as docker tag"
>   if [[ demo::kvm-ok == 1 ]]; then
> ```

It's incorrect. If `kvm-ok` returns with other than 0 exit status that should mean "kvm is not supported".
In shell 0 as return value means success.
Also having exit below you are simply ending the script.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/662)*

**Comment by pigmej** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/demo.sh, line 266 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/662#-LAYg8ooE7a7J1qjqEPo:-LAYmvvt072Qz5Bt5oJf:b-7rl0jd) ([raw file](https://github.com/mirantis/virtlet/blob/378657771ea347d1849325e459a51f9a509619d7/deploy/demo.sh#L266)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

You should `return 1`there.
</blockquote></details>

done.

---

*[deploy/demo.sh, line 309 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/662#-LAYgFsx-K2Tn5tHtGoC:-LAYmwpt49eqsaopR62o:b-43w0k) ([raw file](https://github.com/mirantis/virtlet/blob/378657771ea347d1849325e459a51f9a509619d7/deploy/demo.sh#L309)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

It's incorrect. If `kvm-ok` returns with other than 0 exit status that should mean "kvm is not supported".
In shell 0 as return value means success.
Also having exit below you are simply ending the script.
</blockquote></details>

True.

exit was debug leftover :man_facepalming:

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/662)*

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/demo.sh, line 309 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/662#-LAYoOL7EI7d65kuuODF:-LAYoOL7EI7d65kuuODG:bt686yi) ([raw file](https://github.com/mirantis/virtlet/blob/378657771ea347d1849325e459a51f9a509619d7/deploy/demo.sh#L309)):*
> ```Shell
>   fi
>   echo "Will run demo using Virtlet:${virtlet_release} for demo and ${virtlet_docker_tag} as docker tag"
>   if [[ demo::kvm-ok == 1 ]]; then
> ```

hmm `[[ demo::kvm-ok == 1 ]]` is never true as it's same as `[[ "demo:kvm-ok" == "1" ]]`
you mean just `demo::kvm-ok` perhaps? And `exit 1` needs to be removed, yes

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/662)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/662#-:-LAZ0HQw04sCi2leqtTS:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/662#-:-LAmvXmM5fY7QNpvCe7n:bnfp4nl)*

**Pull request merged**
