### PR TITLE
[ci skip] CRI metrics proposal document

### PR DESCRIPTION
**Pull request by istalker2**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/399)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/design-proposals/cri-metrics.md, line 53 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/399#-KtLTZOs2YNCyi21qg5A:-KtLTZOs2YNCyi21qg5B:be9qfbo) ([raw file](https://github.com/mirantis/virtlet/blob/eea74734de3ec8d565758d70d76b2b154c663cbe/docs/design-proposals/cri-metrics.md#L53)):*
> ```Markdown
> ID of the underlying storage. It is not clear, how kubernetes is going to use this structure for disk
> metrics. Meanwhile we could set only the most important field `used_bytes` and ignore the rest.
> We can use `virt-df` from `libguestfs` to retrieve free space information from VM.
> ```

Yeah, it depends to what this information will be used, so for the start we can use size of image, and if that would be wrong, we can later switch to `virt-df`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/399#-:-KtLTrPIc8kjucrWWno9:bnfp4nl)*

**Comment by istalker2** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/design-proposals/cri-metrics.md, line 53 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/399#-KtLTZOs2YNCyi21qg5A:-KtLU92kqpWaqfDmcHJb:b-7r1olx) ([raw file](https://github.com/mirantis/virtlet/blob/eea74734de3ec8d565758d70d76b2b154c663cbe/docs/design-proposals/cri-metrics.md#L53)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Yeah, it depends to what this information will be used, so for the start we can use size of image, and if that would be wrong, we can later switch to `virt-df`.
</blockquote></details>

IMO, information on how much free space is left in VM is much more relevant for the monitoring than what is the image size (which is a static number). So I'd say, image size should be a plan B if something goes wrong with virt-df

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/399)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/design-proposals/cri-metrics.md, line 53 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/399#-KtLTZOs2YNCyi21qg5A:-KtLVbY9Ji7pB1GVckq8:b-wykzkj) ([raw file](https://github.com/mirantis/virtlet/blob/eea74734de3ec8d565758d70d76b2b154c663cbe/docs/design-proposals/cri-metrics.md#L53)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

IMO, information on how much free space is left in VM is much more relevant for the monitoring than what is the image size (which is a static number). So I'd say, image size should be a plan B if something goes wrong with virt-df
</blockquote></details>

Is virt-df safe to use on the volumes currently mounted by VMs? I suspect it'll be failing from time to time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/399)*

**Comment by istalker2** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/design-proposals/cri-metrics.md, line 53 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/399#-KtLTZOs2YNCyi21qg5A:-KtLWE9McsDOF6OH7XxL:b-o4ralr) ([raw file](https://github.com/mirantis/virtlet/blob/eea74734de3ec8d565758d70d76b2b154c663cbe/docs/design-proposals/cri-metrics.md#L53)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Is virt-df safe to use on the volumes currently mounted by VMs? I suspect it'll be failing from time to time. 
</blockquote></details>

I found this example: http://virtips.virtwind.com/2012/05/getting-disk-space-usage-from-running-vm/
So it should be. Will know for sure when we implement it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/399)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/399#-:-KtLY-lWn2DOfdDu_oSl:bnfp4nl)*

**Pull request merged**
