### PR TITLE
[docs] Feature update notes

### PR DESCRIPTION
**Pull request by ologvinova**
Added notes for the following periods:

- Q4'17-11-29 (minor updates only)
- Q4'17-12-13 (mounting multiple volumes)

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/529)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/update-notes/Q4'17-12-13.md, line 9 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/529#-L0JesIaI1yrWPu4SyBp:-L0JesIaI1yrWPu4SyBq:blv8ycd) ([raw file](https://github.com/mirantis/virtlet/blob/11a7df7c3739c2bb46eb7bfe817470758764c517/docs/update-notes/Q4'17-12-13.md#L9)):*
> ```Markdown
> For details, see the following sections:
> 
> * [Detailed structure of the generated files](docs/cloud-init-data-generation.md#detailed-structure-of-the-generated-files)
> ```

All these urls are broken.
They should have a form "../something.md#section" instead of "docs/something.md#section", because of directory structure.

You can always look how your files will look at the result looking into PRs "Files changed", clicking on "View" on right of each included in change file. That will bring you a file with all the changes which you made in a form which will be visible after the merge of your PR. That can be helpful in preparation of changes ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529)*

**Comment by ologvinova** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/update-notes/Q4'17-12-13.md, line 9 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/529#-L0JesIaI1yrWPu4SyBp:-L0JihGp7AI4yQak_ley:boshoej) ([raw file](https://github.com/mirantis/virtlet/blob/11a7df7c3739c2bb46eb7bfe817470758764c517/docs/update-notes/Q4'17-12-13.md#L9)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

All these urls are broken.
They should have a form "../something.md#section" instead of "docs/something.md#section", because of directory structure.

You can always look how your files will look at the result looking into PRs "Files changed", clicking on "View" on right of each included in change file. That will bring you a file with all the changes which you made in a form which will be visible after the merge of your PR. That can be helpful in preparation of changes ;)
</blockquote></details>

Thanks Piotr! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/update-notes/Q4'17-12-13.md, line 9 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/529#-L0JesIaI1yrWPu4SyBp:-L0JjpobJ_BJzn4K2W5I:bw7iaxi) ([raw file](https://github.com/mirantis/virtlet/blob/11a7df7c3739c2bb46eb7bfe817470758764c517/docs/update-notes/Q4'17-12-13.md#L9)):*
<details><summary><i>Previously, ologvinova wrote…</i></summary><blockquote>

Thanks Piotr! Done.
</blockquote></details>

Nope ;)
Still these links do not have `../` prefix ;)
Just try to click these links in https://github.com/ologvinova/virtlet/blob/cb8327695e08c17976e5e6355ee44ee382d8a6b7/docs/update-notes/Q4'17-12-13.md which is the view described by me above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529)*

**Comment by ologvinova** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/update-notes/Q4'17-12-13.md, line 9 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/529#-L0JesIaI1yrWPu4SyBp:-L0JmwDkKKB1K8p1gYrZ:b4stpv6) ([raw file](https://github.com/mirantis/virtlet/blob/11a7df7c3739c2bb46eb7bfe817470758764c517/docs/update-notes/Q4'17-12-13.md#L9)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Nope ;)
Still these links do not have `../` prefix ;)
Just try to click these links in https://github.com/ologvinova/virtlet/blob/cb8327695e08c17976e5e6355ee44ee382d8a6b7/docs/update-notes/Q4'17-12-13.md which is the view described by me above.
</blockquote></details>

Thanks again, Piotr! Done, hopefully, it will work this time. =)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529#-:-L0Jnm2ytvWe62-g9WhS:bnfp4nl)*

**Comment by ivan4th** [comment]
May add a passage about "Updated CRI Proxy to 0.9.3 which fixes some stability issues"

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529#-:-L0JpOwl34InXRfKmJVV:b8n5sa6)*

**Comment by ologvinova** [comment]
Thanks Ivan! Done.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529#-:-L0Jqc_7Dfox9i77c47q:b-fy5a3j)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529#-:-L0JrksT_YtDJ_prfPrw:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529#-:-L0OkYu6lUey7dBlj4Vp:bnfp4nl)*

**Comment by pigmej** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/529#-:-L0Okhe5vlWwgl-OGjey:bnfp4nl)*

**Pull request merged**
