### PR TITLE
Added possibility to set version in demo

### PR DESCRIPTION
**Pull request by pigmej**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/386)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[deploy/demo.sh, line 234 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/386#-KrGq4GPngmk0JKLc05J:-KrGq4GQ90nhdLjq29LS:b-idasuv) ([raw file](https://github.com/mirantis/virtlet/blob/8a79b314f88eb08cb0b07717e81b3b0e95dfb69d/deploy/demo.sh#L234)):*
> ```Shell
>   # will use most recently published virtlet release
>   # (virtlet releases are prerelease now so not returned in /latest)
>   local  __resultvar=$1
> ```

what's the reason for not just using `xxx="$(demo::get-correct-virtlet-release)"` when calling  this func instead of this `__resultvar`?

---

*[deploy/demo.sh, line 238 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/386#-KrGpuailMqlJ-8_xhYz:-KrGpuailMqlJ-8_xhZ-:b-h2ir52) ([raw file](https://github.com/mirantis/virtlet/blob/8a79b314f88eb08cb0b07717e81b3b0e95dfb69d/deploy/demo.sh#L238)):*
> ```Shell
>   local last_release
>   last_release=$(curl --silent https://api.github.com/repos/Mirantis/virtlet/releases | docker exec -i kube-master jq "${jq_filter}" | sed 's/^\"\(.*\)\"$/\1/')
>   if [[ "$__resultvar" ]]; then
> ```

when using `[[ ... ]]`, no need to quote var expansion (`$__resultvar`)

---

*[deploy/demo.sh, line 249 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/386#-KrGpYkw6tW2pa77HoXG:-KrGpYkw6tW2pa77HoXH:b-8031yu) ([raw file](https://github.com/mirantis/virtlet/blob/8a79b314f88eb08cb0b07717e81b3b0e95dfb69d/deploy/demo.sh#L249)):*
> ```Shell
>   local jq_filter='.items[0].spec.template.spec.containers[0].env|=.+[{"name": "VIRTLET_DOWNLOAD_PROTOCOL","value":"http"}]'
>   local ds_location
>   if [[ "${VIRTLET_DEMO_RELEASE}" = "master" ]]; then
> ```

when using `[[ ... ]]`, no need to quote var expansion (like `${VIRTLET_DEMO_RELEASE}`

---

*[deploy/demo.sh, line 254 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/386#-KrGpjBMPEwUT10jMSY5:-KrGpjBMPEwUT10jMSY6:b-r81upj) ([raw file](https://github.com/mirantis/virtlet/blob/8a79b314f88eb08cb0b07717e81b3b0e95dfb69d/deploy/demo.sh#L254)):*
> ```Shell
>       ds_location="${BASE_LOCATION}/deploy/virtlet-ds.yaml"
>   else
>     if [[ ! -z "${VIRTLET_DEMO_RELEASE}" ]]; then
> ```

`if [[ ! ${VIRTLET_DEMO_RELEASE} ]]; then`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/386)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[deploy/demo.sh, line 233 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/386#-KrGqJ_86DIfQe8uG053:-KrGqJ_86DIfQe8uG054:bmkfc5k) ([raw file](https://github.com/mirantis/virtlet/blob/c02778b1e661d299834881438cde8ec863d4f3ee/deploy/demo.sh#L233)):*
> ```Shell
> function demo::get-correct-virtlet-release {
>   # will use most recently published virtlet release
>   # (virtlet releases are prerelease now so not returned in /latest)
> ```

prereleased - missing ...d

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/386)*

**Comment by pigmej** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[deploy/demo.sh, line 234 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/386#-KrGq4GPngmk0JKLc05J:-KrGsmGnBOThCYLGbT3Z:b-w0liuo) ([raw file](https://github.com/mirantis/virtlet/blob/8a79b314f88eb08cb0b07717e81b3b0e95dfb69d/deploy/demo.sh#L234)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

what's the reason for not just using `xxx="$(demo::get-correct-virtlet-release)"` when calling  this func instead of this `__resultvar`?
</blockquote></details>

Initially thought to use that function in 2 ways that's why I kept this eval magic. Can remove if needed.

---

*[deploy/demo.sh, line 238 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/386#-KrGpuailMqlJ-8_xhYz:-KrGstydPjoK9zYL5Kf2:b3ksm) ([raw file](https://github.com/mirantis/virtlet/blob/8a79b314f88eb08cb0b07717e81b3b0e95dfb69d/deploy/demo.sh#L238)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

when using `[[ ... ]]`, no need to quote var expansion (`$__resultvar`)
</blockquote></details>

k

---

*[deploy/demo.sh, line 249 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/386#-KrGpYkw6tW2pa77HoXG:-KrGsvHajI7tGwj10qxX:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/8a79b314f88eb08cb0b07717e81b3b0e95dfb69d/deploy/demo.sh#L249)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

when using `[[ ... ]]`, no need to quote var expansion (like `${VIRTLET_DEMO_RELEASE}`
</blockquote></details>

Done.

---

*[deploy/demo.sh, line 254 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/386#-KrGpjBMPEwUT10jMSY5:-KrGtVW8rQhc9Ozbn8Is:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/8a79b314f88eb08cb0b07717e81b3b0e95dfb69d/deploy/demo.sh#L254)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`if [[ ! ${VIRTLET_DEMO_RELEASE} ]]; then`
</blockquote></details>

Done.

---

*[deploy/demo.sh, line 233 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/386#-KrGqJ_86DIfQe8uG053:-KrGsdBCBpPNU6fdpL0u:byshn5x) ([raw file](https://github.com/mirantis/virtlet/blob/c02778b1e661d299834881438cde8ec863d4f3ee/deploy/demo.sh#L233)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

prereleased - missing ...d
</blockquote></details>

prerelease is github name for "pre-release" versions :) I shoudl add `s` I think though :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/386)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/386#-:-KrWSuSmWT87DB_1Hn6n:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/386)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/386#-:-KrWUtqPVvJa4Sqa7ilJ:bnfp4nl)*

**Pull request merged**
