### PR TITLE
Make it possible to use pod name in cloudinit defs

### PR DESCRIPTION
**Pull request by ivan4th**
This is a change I had to make so as to enable StatefulSets of VMs.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/270)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 425 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/270#-KjIxZMsnsQ5DweLAwSQ:-KjIxZMsnsQ5DweLAwSR:bgl7n45) ([raw file](https://github.com/mirantis/virtlet/blob/7abdab06a5cc66a1c8677d4035923eb84ad58ecf/pkg/libvirttools/virtualization.go#L425)):*
> ```Go
> 
> 	config := in.Config
> 	name := config.Metadata.Name
> ```

Are you sure that always `Metadata` will be non-nil? 

---

*[pkg/libvirttools/virtualization.go, line 477 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/270#-KjIy3Bm_WIxPwXKYxcm:-KjIy3Bm_WIxPwXKYxcn:bdvtr58) ([raw file](https://github.com/mirantis/virtlet/blob/7abdab06a5cc66a1c8677d4035923eb84ad58ecf/pkg/libvirttools/virtualization.go#L477)):*
> ```Go
> 
> 	virtletVolsDesc, _ := sandBoxAnnotations[VirtletVolumesAnnotationKeyName]
> 	domXML, err = v.addAttachedVolumesXML(in.PodSandboxId, in.SandboxConfig.Metadata.Name, uuid, virtletVolsDesc, domXML)
> ```

Earlier in this func we have that set as `name`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/270)*

**Comment by vefimova** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 420 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/270#-KjJ-4sTWZSzdyYiW2IH:-KjJ-4sTWZSzdyYiW2II:brfw301) ([raw file](https://github.com/mirantis/virtlet/blob/7abdab06a5cc66a1c8677d4035923eb84ad58ecf/pkg/libvirttools/virtualization.go#L420)):*
> ```Go
> 	}
> 
> 	if in.Config == nil || in.Config.Metadata == nil || in.Config.Image == nil || in.SandboxConfig == nil || in.SandboxConfig.Metadata == nil {
> ```

But why you don't use provideed by API Get* here and in other places? You can use them in cascade as they all have check pointer on nil and return nil for complex structure, i.e. other than string, integer...

---

*[pkg/libvirttools/virtualization.go, line 454 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/270#-KjJ-fOmDBcSIjrxO1v9:-KjJ-fOmDBcSIjrxO1vA:b-m8qrj0) ([raw file](https://github.com/mirantis/virtlet/blob/7abdab06a5cc66a1c8677d4035923eb84ad58ecf/pkg/libvirttools/virtualization.go#L454)):*
> ```Go
> 	}
> 
> 	metadataStore.SetContainer(name, uuid, in.PodSandboxId, config.Image.Image, snapshotName, config.Labels, config.Annotations)
> ```

I would say we need to replace it with config.GetImage().GetImage() otherwise, as it provided by api?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/270)*

**Comment by vefimova** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 425 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/270#-KjIxZMsnsQ5DweLAwSQ:-KjJ1VwVNRXUJDOr4w9r:b-mc2986) ([raw file](https://github.com/mirantis/virtlet/blob/7abdab06a5cc66a1c8677d4035923eb84ad58ecf/pkg/libvirttools/virtualization.go#L425)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Are you sure that always `Metadata` will be non-nil? 
</blockquote></details>

yep, it should be replaced with config.GetMetadata().GetName()

---

*[pkg/libvirttools/virtualization.go, line 477 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/270#-KjIy3Bm_WIxPwXKYxcm:-KjJ2B6RfZH-jW6wP4Rw:br5phk4) ([raw file](https://github.com/mirantis/virtlet/blob/7abdab06a5cc66a1c8677d4035923eb84ad58ecf/pkg/libvirttools/virtualization.go#L477)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Earlier in this func we have that set as `name`.
</blockquote></details>

No, we actially have  container/VM name in`name`, and here we get pod's name. But I think it should be get as `in.GetSandboxConfig().GetMetadata().GetName()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/270)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 477 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/270#-KjIy3Bm_WIxPwXKYxcm:-KjJ4lJtBTG3mdK7btZt:btgowrb) ([raw file](https://github.com/mirantis/virtlet/blob/7abdab06a5cc66a1c8677d4035923eb84ad58ecf/pkg/libvirttools/virtualization.go#L477)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

No, we actially have  container/VM name in`name`, and here we get pod's name. But I think it should be get as `in.GetSandboxConfig().GetMetadata().GetName()`.
</blockquote></details>

ough, once this was `Config`, and once `SandboxConfig` - yeah, my mistake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/270)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 425 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/270#-KjIxZMsnsQ5DweLAwSQ:-KjJ5XY09Ud0Ca3Xbe-r:bgwolw8) ([raw file](https://github.com/mirantis/virtlet/blob/7abdab06a5cc66a1c8677d4035923eb84ad58ecf/pkg/libvirttools/virtualization.go#L425)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

yep, it should be replaced with config.GetMetadata().GetName()
</blockquote></details>

but `if` above will catch it - so it's ok there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/270#-:-KjJ5cuFkCOdE9pKHs12:bnfp4nl)*

**Comment by vefimova** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/270#-:-KjJ7MvQsTMorDQGGCpj:bnfp4nl)*

**Pull request merged**
