### PR TITLE
Make ImageFileStore.PullImage() support Context

### PR DESCRIPTION
**Pull request by ivan4th**
Image download cancellation is now handled properly.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/571)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:

Tests failed but looks like not on something provided in this branch. I just restarted them.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/571#-:-L4hD1-U2BHmCd2D4eGt:bswny7g)*

**Comment by lukaszo** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/image/download.go, line 199 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/571#-L4jmecuNmNe335jZQa8:-L4jmecuNmNe335jZQa9:b-gi4m2p) ([raw file](https://github.com/mirantis/virtlet/blob/f90c636504b0b5a41a6b6dd2b336e729be43d936/pkg/image/download.go#L199)):*
> ```Go
> 		return err
> 	}
> 	defer resp.Body.Close()
> ```

Why did you delete it? According to documentation  resp should be closed even when using Do method ```If the returned error is nil, the Response will contain a non-nil Body which the user is expected to close.```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/571)*

**Comment by ivan4th** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/image/download.go, line 199 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/571#-L4jmecuNmNe335jZQa8:-L4jnU17d3_yp0cDvPZ8:bnpz05g) ([raw file](https://github.com/mirantis/virtlet/blob/f90c636504b0b5a41a6b6dd2b336e729be43d936/pkg/image/download.go#L199)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

Why did you delete it? According to documentation  resp should be closed even when using Do method ```If the returned error is nil, the Response will contain a non-nil Body which the user is expected to close.```
</blockquote></details>

Thanks for pointing this out, deleted it by accident, will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/571)*

**Comment by ivan4th** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/image/download.go, line 199 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/571#-L4jmecuNmNe335jZQa8:-L4k3sUjetHQiFqJQogX:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f90c636504b0b5a41a6b6dd2b336e729be43d936/pkg/image/download.go#L199)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Thanks for pointing this out, deleted it by accident, will fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/571)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/571#-:-L4k4CfLPNzuF4HOV4kt:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/571#-:-L4kJHgUPgd8uebLVv34:bnfp4nl)*

**Pull request merged**
