### PR TITLE
Use local http server in integration tests

### LINKED ISSUE #274: Refactor image handling in tests
At present tests are dependent on external resources (cirrus images, which are be redownloaded multiple times during test session, after merging #272).
This user story is about changing test to once download all external resources (maybe something more used in tests, not only cirrus images) before real tests are started, start local http server (can be nginx, or simple `python -m SimpleHTTPServer 80`), and then start the tests.
That way we can fail earlier when there is network connection problem, and direct most network bound operations to localhost.
This will also allow us to add tests for images with the same name, but with different urls (was planned to be included in #273).

### PR DESCRIPTION
**Pull request by jellonek**
closes #274

This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/283)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/integration/image_test.go, line 49 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KkpQINOt_GLec3IGF0B:-KkpQINOt_GLec3IGF0C:b-wrx27l) ([raw file](https://github.com/mirantis/virtlet/blob/cf71f67b372fac12238cc82d3b5cac9cf52d946e/tests/integration/image_test.go#L49)):*
> ```Go
> }
> 
> func (it *imageTester) pullImage(url string) {
> ```

Maybe it's better to have another method like `PullSampleImage` that does `...PullImage(imageCirrosUrl)` ? Because `PullImage("")` calls below are slightly confusing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/283)*

**Comment by ivan4th** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/integration/go.test, line 28 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KkpQe37bhmg0kt2zfHF:-KkpQe37bhmg0kt2zfHG:b6q9i0f) ([raw file](https://github.com/mirantis/virtlet/blob/cf71f67b372fac12238cc82d3b5cac9cf52d946e/tests/integration/go.test#L28)):*
> ```
> fi
> 
> kill $HTTP_SERVER_PID
> ```

this should be done in a "trap" handler so the server gets killed even if the scripts stops before it completes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/283)*

**Comment by vefimova** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/integration/go.test, line 28 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KkpQe37bhmg0kt2zfHF:-KkpZMx0pdFxXYvwusxS:b32v57) ([raw file](https://github.com/mirantis/virtlet/blob/cf71f67b372fac12238cc82d3b5cac9cf52d946e/tests/integration/go.test#L28)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

this should be done in a "trap" handler so the server gets killed even if the scripts stops before it completes
</blockquote></details>

+1

---

*[tests/integration/image_test.go, line 49 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KkpQINOt_GLec3IGF0B:-KkpZzrnSqvypQD55Dkd:b-whdu2p) ([raw file](https://github.com/mirantis/virtlet/blob/cf71f67b372fac12238cc82d3b5cac9cf52d946e/tests/integration/image_test.go#L49)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Maybe it's better to have another method like `PullSampleImage` that does `...PullImage(imageCirrosUrl)` ? Because `PullImage("")` calls below are slightly confusing
</blockquote></details>

+1, or maybe to pass `kubeapi.ImageSpec{}` as arg

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/283)*

**Comment by ivan4th** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[tests/integration/go.test, line 2 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KktbAAE0L2MB5iJ74VH:-KktbAAE0L2MB5iJ74VI:b-thh5qr) ([raw file](https://github.com/mirantis/virtlet/blob/fa4dfe5f7506eb9f8367c6bb234bfc4965510988/tests/integration/go.test#L2)):*
> ```
> #!/bin/bash
> ```

perhaps Mirantis copyright section is needed here?

---

*[tests/integration/go.test, line 9 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KktazaQbZfQ9eqiGDIl:-KktazaQbZfQ9eqiGDIm:b-bwy1m) ([raw file](https://github.com/mirantis/virtlet/blob/fa4dfe5f7506eb9f8367c6bb234bfc4965510988/tests/integration/go.test#L9)):*
> ```
>     exit $retval
>   fi
> }
> ```

why is this needed? Perhaps using the standard set of bash directives is better
```
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
```

---

*[tests/integration/go.test, line 12 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KktbDEVfo56KwpVy4si:-KktbDEVfo56KwpVy4sj:b-vhcs3p) ([raw file](https://github.com/mirantis/virtlet/blob/fa4dfe5f7506eb9f8367c6bb234bfc4965510988/tests/integration/go.test#L12)):*
> ```
> 
> cleanup() {
>   if [ ! -z "${HTTP_SERVER_PID}" ] ; then
> ```

`if [[ ! ${HTTP_SERVER_PID} ]]; then` is a bit more idiomatic bash

---

*[tests/integration/go.test, line 17 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KktbL7z2Ay2Iw5KW11l:-KktbL7z2Ay2Iw5KW11m:bo6qdfn) ([raw file](https://github.com/mirantis/virtlet/blob/fa4dfe5f7506eb9f8367c6bb234bfc4965510988/tests/integration/go.test#L17)):*
> ```
> }
> 
> trap cleanup SIGHUP SIGINT SIGTERM EXIT
> ```

just use `trap cleanup EXIT`, it'll be called on other signals

---

*[tests/integration/go.test, line 30 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/283#-Kktc7cJSZcWUBjN6GIr:-Kktc7cJSZcWUBjN6GIs:b-2z1lco) ([raw file](https://github.com/mirantis/virtlet/blob/fa4dfe5f7506eb9f8367c6bb234bfc4965510988/tests/integration/go.test#L30)):*
> ```
> if [ $# -ne 0 ] ; then
>   go test -test.v -run $*
>   retval=$?
> ```

no need to use retval if you use `set -o errexit`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/283)*

**Comment by jellonek** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[tests/integration/go.test, line 2 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KktbAAE0L2MB5iJ74VH:-Kku50cOpexpgtWHo2mk:b-hxjy86) ([raw file](https://github.com/mirantis/virtlet/blob/fa4dfe5f7506eb9f8367c6bb234bfc4965510988/tests/integration/go.test#L2)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

perhaps Mirantis copyright section is needed here?
</blockquote></details>

We don't have it in any of scripts...

---

*[tests/integration/go.test, line 9 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KktazaQbZfQ9eqiGDIl:-Kku5ESxBkBjygVOGTJ1:b-tyr5r2) ([raw file](https://github.com/mirantis/virtlet/blob/fa4dfe5f7506eb9f8367c6bb234bfc4965510988/tests/integration/go.test#L9)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

why is this needed? Perhaps using the standard set of bash directives is better
```
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
```
</blockquote></details>

Yeah, it's better, will use this in the minute

---

*[tests/integration/go.test, line 12 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KktbDEVfo56KwpVy4si:-Kku5Yh_oP1e4IjoloUZ:byr4flj) ([raw file](https://github.com/mirantis/virtlet/blob/fa4dfe5f7506eb9f8367c6bb234bfc4965510988/tests/integration/go.test#L12)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`if [[ ! ${HTTP_SERVER_PID} ]]; then` is a bit more idiomatic bash
</blockquote></details>

Right.

---

*[tests/integration/go.test, line 17 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/283#-KktbL7z2Ay2Iw5KW11l:-Kku5aFaD1r_N2vRQErT:bb6sh2i) ([raw file](https://github.com/mirantis/virtlet/blob/fa4dfe5f7506eb9f8367c6bb234bfc4965510988/tests/integration/go.test#L17)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

just use `trap cleanup EXIT`, it'll be called on other signals
</blockquote></details>

Ack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/283)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/283#-:-KkvAK2Zl4T6wRP0gqti:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/283#-:-KlICDGEeRdhdVnYcf5Q:bnfp4nl)*

**Pull request merged**
