### PR TITLE
Follow upstream changes of libvirt-xml-go

### PR DESCRIPTION
**Pull request by nhlfr**
The "memoryBacking" field in Domain was recently added upstream,
so we only need a patch for "cputune".

When the patch for "cputune" [1] will be merged upstream, we
will be able to use vanilla libvirt-xml-go.

[1] https://www.redhat.com/archives/libvir-list/2017-October/msg01151.html

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/492)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm: this HexUint looks interesting...

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/492#-:-KxN7C20fWPu3AWJtorS:b-tgq9eo)*

**Comment by istalker2** [comment]
tests need to be updated. LGTM otherwise

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/492#-:-KxPB_--IjJxq2ZAqgQE:b-yzaq1)*

**Comment by nhlfr** [comment]
@jellonek @istalker2 PTAL

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/492#-:-Kxh2TTm3bHQbbsrSfGy:bnfp4nl)*

**Comment by istalker2** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/492#-:-KxigySPMG0ZjQpUEh5b:bnfp4nl)*

**Pull request merged**
