### PR TITLE
[docs] Update notes, Jan 25 - Feb 7

### PR DESCRIPTION
**Pull request by ologvinova**
[ci skip]

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/572)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/update-notes.md, line 7 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/572#-L4p4M4K8hJuvA3lVNEO:-L4p4M4K8hJuvA3lVNEP:bbe9gg0) ([raw file](https://github.com/mirantis/virtlet/blob/269d2430961239916eab83aaf79fd2bdcbe22437/docs/update-notes.md#L7)):*
> ```Markdown
> from October, 18 2017.
> 
> * [Q4-18-02-07](update-notes/Q4-18-02-07.md)
> ```

Broken links and old labels.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/572)*

**Comment by ologvinova** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/update-notes.md, line 7 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/572#-L4p4M4K8hJuvA3lVNEO:-L4p54jWieiEAg8qycu-:b-5mlu15) ([raw file](https://github.com/mirantis/virtlet/blob/269d2430961239916eab83aaf79fd2bdcbe22437/docs/update-notes.md#L7)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Broken links and old labels.
</blockquote></details>

woops, I need another coffee)) Thanks Piotr!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/572)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/572#-:-L4qE0nnPkWJF_32ov4B:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/572#-:-L4qUCSoX_jeu1lzkcup:bnfp4nl)*

**Pull request merged**
