### PR TITLE
Fix linter issues in pkg/dhcp/

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/602)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/602#-:-L6wZdMhRpt0daHQNAch:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/dhcp/server.go, line 48 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/602#-L6w_9rxy0wKrhib63CX:-L6w_9rxy0wKrhib63CY:b-l6t8sx) ([raw file](https://github.com/mirantis/virtlet/blob/1be8d4a30a8eae3c329b555f4940bcef248745dc/pkg/dhcp/server.go#L48)):*
> ```Go
> // Server describes an object prepared to be started in container namespace
> // as a goroutine, serving network configuration data to a client in
> // the same container namespace.
> ```

I'd rather say just "Server implements a DHCP server that runs in the container network namespace"

---

*[pkg/dhcp/server.go, line 60 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/602#-L6w_Ks1XKZS8XoLRM41:-L6w_Ks1XKZS8XoLRM42:b-pkbkp9) ([raw file](https://github.com/mirantis/virtlet/blob/1be8d4a30a8eae3c329b555f4940bcef248745dc/pkg/dhcp/server.go#L60)):*
> ```Go
> 
> // SetupListener prepares a dhcp4 listener to be listening on default dhcp port,
> // on provided IP address.
> ```

SetupListener sets up a DHCP4 listener that listens on the default DHCP port and the specified IP address.

---

*[pkg/dhcp/server.go, line 72 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/602#-L6w_WKTz1ZGj7iRvtT2:-L6w_WKTz1ZGj7iRvtT3:b-86nw8m) ([raw file](https://github.com/mirantis/virtlet/blob/1be8d4a30a8eae3c329b555f4940bcef248745dc/pkg/dhcp/server.go#L72)):*
> ```Go
> }
> 
> // Close shuts down dhcp listener.
> ```

Close shuts down the DHCP listener.

---

*[pkg/dhcp/server.go, line 77 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/602#-L6w_YS7NzTwClDyRc6l:-L6w_YS7NzTwClDyRc6m:b-hzwc9y) ([raw file](https://github.com/mirantis/virtlet/blob/1be8d4a30a8eae3c329b555f4940bcef248745dc/pkg/dhcp/server.go#L77)):*
> ```Go
> }
> 
> // Serve waits in a endless loop for dhcp client packets and reacts on them.
> ```

Serve waits in an endless loop for DHCP requests and answers them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/602)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/dhcp/server.go, line 48 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/602#-L6w_9rxy0wKrhib63CX:-L6wgv7zMUDsY1-sID0l:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/1be8d4a30a8eae3c329b555f4940bcef248745dc/pkg/dhcp/server.go#L48)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'd rather say just "Server implements a DHCP server that runs in the container network namespace"
</blockquote></details>

Done.

---

*[pkg/dhcp/server.go, line 60 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/602#-L6w_Ks1XKZS8XoLRM41:-L6wgw1MBA7svBqfw3W-:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/1be8d4a30a8eae3c329b555f4940bcef248745dc/pkg/dhcp/server.go#L60)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

SetupListener sets up a DHCP4 listener that listens on the default DHCP port and the specified IP address.
</blockquote></details>

Done.

---

*[pkg/dhcp/server.go, line 72 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/602#-L6w_WKTz1ZGj7iRvtT2:-L6wgwYMpw01hHRFex4p:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/1be8d4a30a8eae3c329b555f4940bcef248745dc/pkg/dhcp/server.go#L72)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Close shuts down the DHCP listener.
</blockquote></details>

Done.

---

*[pkg/dhcp/server.go, line 77 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/602#-L6w_YS7NzTwClDyRc6l:-L6wgx0cFJOYITOJl_cA:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/1be8d4a30a8eae3c329b555f4940bcef248745dc/pkg/dhcp/server.go#L77)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Serve waits in an endless loop for DHCP requests and answers them.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/602)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/602#-:-L6whzAYM6XaJqrItky2:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/602#-:-L744XSqJ86HVAGxBjE0:bnfp4nl)*

**Pull request merged**
