### PR TITLE
Add a proposal on VM isolation

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/379)

### CODE REVIEW

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/design-proposals/vm-isolation.md, line 90 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/379#-Kr5RfTndgrH9025fro7:-Kr5RfTndgrH9025fro8:bu5vu87) ([raw file](https://github.com/mirantis/virtlet/blob/e6b34a7b8e045190cb5374f1ee4059853ba6bab1/docs/design-proposals/vm-isolation.md#L90)):*
> ```Markdown
> * Provides reasonable level of security
> 
> Cons
> ```

Missing `:`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/379)*

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/design-proposals/vm-isolation.md, line 90 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/379#-Kr5RfTndgrH9025fro7:-Kr5UWJwEjx5NsSvuPiD:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/e6b34a7b8e045190cb5374f1ee4059853ba6bab1/docs/design-proposals/vm-isolation.md#L90)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Missing `:`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/379)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/379)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/379#-:-Kr5dUQpECFLfV6r7KQ-:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/379#-:-Kr5jZ24TlzsFWLlbvGb:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/379#-:-Kr5jZF8F4oP34QK60zv:bnfp4nl)*

**Pull request merged**
