### PR TITLE
Bump CRI Proxy to v0.11.1

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/702)

### CODE REVIEW

**Comment by jellonek** [comment]
https://github.com/Mirantis/virtlet/blame/master/docs/design-proposals/pv.md#L377 - last place to change.

---

Reviewed 3 of 3 files at r1.
Review status: 0 of 2 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/702#-:-LFrfcKU-51MtK-lkGNK:b-nzeoby)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: 0 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/702#-:-LFri1W7BZOrgglkq2c2:bnfp4nl)*

**Comment by ivan4th** [comment]
@jell fixed pv.md

---

Review status: 0 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/702#-:-LFriuCg4dbYy0sRIt_s:b-sba3nb)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: 0 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/702#-:-LFrjCNe9JFnmuEa2e79:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: 1 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/702#-:-LFvKI5N38cWkmN7IQX9:bnfp4nl)*

**Pull request merged**
