### PR TITLE
Use DNS from PodSandboxConfig.DnsConfig

### LINKED ISSUE #191: Get DNS config from PodSandboxConfig.DNSConfig in RunPodSandbox
That's how docker-shim works and we should do it, too.
What needs to be clarified: what takes precedence if both CNI and PodSandboxConfig include DNS settings. Or we should merge these?

### PR DESCRIPTION
**Pull request by ivan4th**
Fixes #191

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/200)

### CODE REVIEW

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/manager/manager.go, line 146 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/200#-KcNI1bePAt8clsY4yZa:-KcNI1bePAt8clsY4yZb:b70ksyv) ([raw file](https://github.com/mirantis/virtlet/blob/fb96395aabc6d493cf67f921b7d0fcdde0baf8a0/pkg/manager/manager.go#L146)):*
> ```Go
> 	// As of k8s 1.5.2, kubelet doesn't use any nameserver information from CNI.
> 	// CNI is used just to configure the network namespace and CNI DNS
> 	// info is ignored. Intead of this, DnsConfig from PodSandboxConfig
> ```

Typo. Instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/200)*

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/manager/manager.go, line 146 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/200#-KcNI1bePAt8clsY4yZa:-KcNKHGePDb_o58cejtb:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/fb96395aabc6d493cf67f921b7d0fcdde0baf8a0/pkg/manager/manager.go#L146)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Typo. Instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/200)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/200#-:-KcNMP8WPqZFtMXxB196:bnfp4nl)*

**Comment by ivan4th** [comment]
Also, it works -- merging.

**Pull request merged**
