### PR TITLE
Add an example with k8s on VM-based StatefulSet

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/271)

### CODE REVIEW

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/k8s.yaml, line 91 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/271#-Kjr3TI0a7UYXxs9wXY-:-Kjr3TI0a7UYXxs9wXY0:b-72mg1x) ([raw file](https://github.com/mirantis/virtlet/blob/865670b957ff6894d8c9b5cd8b5178fbf82a7ba2/examples/k8s.yaml#L91)):*
> ```YAML
>                   apt-get install -y --force-yes kubelet kubeadm kubectl kubernetes-cni jq
>                   # TODO: client-ca-file -- /etc/kubernetes/pki/ca.crt
>                   # XXX: misplaced --feature-gates=... option, but will dor for now
> ```

s/dor/do/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/271)*

**Comment by vefimova** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/README.md, line 46 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/271#-KjJK9sNHzWVWtMugaFI:-KjJK9sNHzWVWtMugaFJ:b2wshc0) ([raw file](https://github.com/mirantis/virtlet/blob/865670b957ff6894d8c9b5cd8b5178fbf82a7ba2/examples/README.md#L46)):*
> ```Markdown
> Kubernetes using `kubeadm` on it.
> 
> You can creeate the cluster like this:
> ```

typo in create

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/271)*

**Comment by ivan4th** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/k8s.yaml, line 91 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/271#-Kjr3TI0a7UYXxs9wXY-:-Kjr5LWkOa-smJS9dzId:bj3eoea) ([raw file](https://github.com/mirantis/virtlet/blob/865670b957ff6894d8c9b5cd8b5178fbf82a7ba2/examples/k8s.yaml#L91)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

s/dor/do/
</blockquote></details>

Fixed, thanks.

---

*[examples/README.md, line 46 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/271#-KjJK9sNHzWVWtMugaFI:-Kjr5HQI95JWW_1k8Lj4:bj3eoea) ([raw file](https://github.com/mirantis/virtlet/blob/865670b957ff6894d8c9b5cd8b5178fbf82a7ba2/examples/README.md#L46)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

typo in create
</blockquote></details>

Fixed, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/271)*

**Comment by vefimova** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/271#-:-Kjr7zcbIf3yGGi3ru7c:bnfp4nl)*

**Comment by vefimova** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/271)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/271#-:-KjrAHqsSjveYZKLt8cM:bnfp4nl)*

**Pull request merged**
