### PR TITLE
Fix TapFDSource netns recovery

### PR DESCRIPTION
**Pull request by ivan4th**
Don't try to "fix" the CNI result during the recovery.
Don't lose hwaddrs of VM network interfaces during the recovery.
Make VM network tests examine netns recovery.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/563)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/563#-:-L4Km9WYHtwJrC7_Gg_R:bnfp4nl)*

**Comment by jellonek** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/tapmanager/fdserver.go, line 172 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/563#-L4epQrlsUP5dcXALM2v:-L4epQrlsUP5dcXALM2w:b-x8ozge) ([raw file](https://github.com/mirantis/virtlet/blob/bb1724490bf442b640502caac963f49d96ce3497/pkg/tapmanager/fdserver.go#L172)):*
> ```Go
> 	defer s.Unlock()
> 	if _, found := s.fds[key]; found {
> 		return fmt.Errorf("fd key %q is already present and thus can't be properly recovered")
> ```

Missing `, key` after format string.

---

*[pkg/tapmanager/fdserver.go, line 557 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/563#-L4epfCmXayMojqm2QKK:-L4epfCmXayMojqm2QKL:bfyft3d) ([raw file](https://github.com/mirantis/virtlet/blob/bb1724490bf442b640502caac963f49d96ce3497/pkg/tapmanager/fdserver.go#L557)):*
> ```Go
> // Recover requests FDServer to recover the state regarding the
> // specified key. It's intended to be called after an application
> // restart
> ```

That can be misleading - which application? Someone can read that as user VM.
IMO `after Virtlet restart`. Btw. missing dot at the end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/563)*

**Comment by ivan4th** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/tapmanager/fdserver.go, line 172 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/563#-L4epQrlsUP5dcXALM2v:-L4erpXHmMZRZYdc1TNs:b-x52gbo) ([raw file](https://github.com/mirantis/virtlet/blob/bb1724490bf442b640502caac963f49d96ce3497/pkg/tapmanager/fdserver.go#L172)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Missing `, key` after format string.
</blockquote></details>

Thanks, fixed.

---

*[pkg/tapmanager/fdserver.go, line 557 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/563#-L4epfCmXayMojqm2QKK:-L4es53S6ckjxV-cWQPi:b-b319xq) ([raw file](https://github.com/mirantis/virtlet/blob/bb1724490bf442b640502caac963f49d96ce3497/pkg/tapmanager/fdserver.go#L557)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

That can be misleading - which application? Someone can read that as user VM.
IMO `after Virtlet restart`. Btw. missing dot at the end.
</blockquote></details>

I'd like to avoid mentioning Virtlet exceedingly because it may make it seem that the code is somehow tied to Virtlet some other aspects of Virtlet behavior. I try to make the code (including comments) to look more reusable when it's possible if it doesn't incur extra costs. In this case... IMO people rarely call VMs "applications". But ok, replaced it with "Virtlet" as FDClient / FDServer stuff evolved to be quite Virtlet-specific and hardly directly reusable. As of the dot, I've also added it but we're rather inconsistent overall concerning these dots...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/563)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/563#-:-L4ev7ox4_1ygZlZHKvL:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/563#-:-L5hp5lKww1Q-kkws6RX:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/563#-:-L5rgiYMG6h8wgXUkDCy:bnfp4nl)*

**Pull request merged**
