### PR TITLE
libvirt-go: Switch to official bindings

### PR DESCRIPTION
**Pull request by jellonek**
Instead of using own CGO based bindings to libvirt - this PR provides switch to libvirt-go official bindings, with additional level of separation (proposed by Ivan) using interfaces.
This allows to mock calls to libvirt.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/189)

### CODE REVIEW

**Comment by jellonek** [comment]
All things after moving onto libvirt-go looks working properly.

Looks like errors in tests are not connected to this PR, but to criproxy. Will try to reschedule them...

**Comment by jellonek** [comment]
Rerunning tests helped with flakes in criproxy.

**Comment by ivan4th** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/storage_interface.go, line 104 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/189#-KamHY6MiNQc8YC5aGj8:-KamHY6MiNQc8YC5aGj9:blxc48s) ([raw file](https://github.com/mirantis/virtlet/blob/9bbfa5ec301ee9d44caee33c6942c6b14049aca3/pkg/libvirttools/storage_interface.go#L104)):*
> ```Go
> 	stream, err := l.conn.NewStream(0)
> 	if err != nil {
> 		return err
> ```

Shouldn't we try to delete the volume in case if something fails here or further down in PullImageToVolume() ? We'll be getting some stale volumes otherwise. Note that if an error occurs and then volume deletion fails, too, we need to return an error containing messages from both errors so as not to confuse ourselves during debugging.

---

*[pkg/libvirttools/virtualization.go, line 431 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/189#-KamIytwJvHFCARNyHdB:-KamIytwJvHFCARNyHdC:bwsumff) ([raw file](https://github.com/mirantis/virtlet/blob/9bbfa5ec301ee9d44caee33c6942c6b14049aca3/pkg/libvirttools/virtualization.go#L431)):*
> ```Go
> 	return utils.WaitLoop(func() (bool, error) {
> 		domain, err := v.tool.LookupByUUIDString(containerId)
> 		if domain != nil {
> ```

Perhaps should make sure err is nil here just to be on the safe side? Not that such a situation is likely to happen, but still... (e.g. there theoretically may be problems due to some bad code when using fake libvirt in future)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/189)*

**Comment by jellonek** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/storage_interface.go, line 104 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/189#-KamHY6MiNQc8YC5aGj8:-Kam_4vTu21VxG5nfrDF:bc79hbr) ([raw file](https://github.com/mirantis/virtlet/blob/9bbfa5ec301ee9d44caee33c6942c6b14049aca3/pkg/libvirttools/storage_interface.go#L104)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Shouldn't we try to delete the volume in case if something fails here or further down in PullImageToVolume() ? We'll be getting some stale volumes otherwise. Note that if an error occurs and then volume deletion fails, too, we need to return an error containing messages from both errors so as not to confuse ourselves during debugging.
</blockquote></details>

This PR only reproduces old behavior of our own CGO bindings.
As this seems reasonable to me - i'll open an issue for that, but i would like to keep this separated from this task.

---

*[pkg/libvirttools/virtualization.go, line 431 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/189#-KamIytwJvHFCARNyHdB:-Kam_gWiGx4rbOs6sg5c:bsw7723) ([raw file](https://github.com/mirantis/virtlet/blob/9bbfa5ec301ee9d44caee33c6942c6b14049aca3/pkg/libvirttools/virtualization.go#L431)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Perhaps should make sure err is nil here just to be on the safe side? Not that such a situation is likely to happen, but still... (e.g. there theoretically may be problems due to some bad code when using fake libvirt in future)
</blockquote></details>

Ok. Will change this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/189)*

**Comment by ivan4th** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/storage_interface.go, line 104 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/189#-KamHY6MiNQc8YC5aGj8:-Kamdq-5ThW-NQ-H1Nki:b2nhll9) ([raw file](https://github.com/mirantis/virtlet/blob/9bbfa5ec301ee9d44caee33c6942c6b14049aca3/pkg/libvirttools/storage_interface.go#L104)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This PR only reproduces old behavior of our own CGO bindings.
As this seems reasonable to me - i'll open an issue for that, but i would like to keep this separated from this task.
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/189)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 18 of 19 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/189#-:-KaqH_ektMurmGtAGpW2:bnfp4nl)*

**Pull request merged**
