### PR TITLE
Fix cleanup

### LINKED ISSUE #241: Fix cleanup in case of VM-pod's container start failure and re-trying
On PodSync in case if VM failed to start virtlet produces a lot of copies of the same domain's definitions and boot snapshots. Need to do cleanup in case if VM failed to start.

```
# virsh list --all
 Id    Name                           State
----------------------------------------------------
 -     16b408c0-1bf4-4cc4-7b92-117a15158b02-test-vm shut off
 -     379a82e8-a5ab-426e-5134-6a603bef0519-test-vm shut off
 -     43f0defc-1537-4187-727c-1bf8eeed1250-test-vm shut off
 -     4c9779af-6d2c-47a2-604f-f3c28b5785cf-test-vm shut off
...............

# virsh vol-list --pool volumes
 Name                 Path
------------------------------------------------------------------------------
 snapshot_16b408c0-1bf4-4cc4-7b92-117a15158b02 /var/lib/virtlet/snapshot_16b408c0-1bf4-4cc4-7b92-117a15158b02
 snapshot_278b1621-bd65-44a5-59b9-548d598369d2 /var/lib/virtlet/snapshot_278b1621-bd65-44a5-59b9-548d598369d2
 snapshot_3530379b-5a66-473d-5c82-da2995bba50e /var/lib/virtlet/snapshot_3530379b-5a66-473d-5c82-da2995bba50e
 snapshot_379a82e8-a5ab-426e-5134-6a603bef0519 /var/lib/virtlet/snapshot_379a82e8-a5ab-426e-5134-6a603bef0519
 snapshot_42cb8f25-509c-4fbb-48b5-826a298fbc82 /var/lib/virtlet/snapshot_42cb8f25-509c-4fbb-48b5-826a298fbc82
 snapshot_43f0defc-1537-4187-727c-1bf8eeed1250 /var/lib/virtlet/snapshot_43f0defc-1537-4187-727c-1bf8eeed1250
 snapshot_4c9779af-6d2c-47a2-604f-f3c28b5785cf /var/lib/virtlet/snapshot_4c9779af-6d2c-47a2-604f-
.........

```

### PR DESCRIPTION
**Pull request by vefimova**
fixes #241

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/306)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/libvirttools/storage_tool.go, line 125 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/306#-KlweiaWg9mTG7y42J4U:-KlweiaXJUeoNAaIFLKf:bykqjk7) ([raw file](https://github.com/mirantis/virtlet/blob/07cf18e3f8e3dcfd41e657990f9a1fafc45f5d35/pkg/libvirttools/storage_tool.go#L125)):*
> ```Go
> 
> 		err := s.RemoveVolume(volName)
> 		if err != nil && err != virt.ErrStorageVolumeNotFound {
> ```

Why this line was divided into two? IMO it would be better to keep them in single scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/306)*

**Comment by vefimova** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/libvirttools/storage_tool.go, line 125 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/306#-KlweiaWg9mTG7y42J4U:-KlxLtWmee7xVVH5Jx1h:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/07cf18e3f8e3dcfd41e657990f9a1fafc45f5d35/pkg/libvirttools/storage_tool.go#L125)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Why this line was divided into two? IMO it would be better to keep them in single scope.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/306)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/306#-:-KlxMkjlWVRJmyypt0Pq:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/306#-:-KlyfDMWVnz4-rMZze_W:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/306)*

**Pull request merged**
