### PR TITLE
 Support multiple tap interfaces in vmwrapper

### PR DESCRIPTION
**Pull request by jellonek**
Do not merge before #490

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/496)

### CODE REVIEW

**Comment by ivan4th** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/vmwrapper/vmwrapper.go, line 174 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/496#-KyXuOkR749PEQdcmiO-:-KyXuOkR749PEQdcmiO0:b9gsrq4) ([raw file](https://github.com/mirantis/virtlet/blob/fdaee2d4cef419c129ffc0b596462621d6f6b7f8/cmd/vmwrapper/vmwrapper.go#L174)):*
> ```Go
> 			}
> 			if len(tapFds) != len(hwAddrs) {
> 				glog.Error("Received different number of open tap file descriptors than hardware addresses")
> ```

The number of open tap fds is different from the number of hardware addresses

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/496)*

**Comment by ivan4th** [comment]
Reviewed 8 of 14 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/496)*

**Comment by jellonek** [comment]
Review status: 7 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/vmwrapper/vmwrapper.go, line 174 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/496#-KyXuOkR749PEQdcmiO-:-KypKrHDHUebJgMOwhDA:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/fdaee2d4cef419c129ffc0b596462621d6f6b7f8/cmd/vmwrapper/vmwrapper.go#L174)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

The number of open tap fds is different from the number of hardware addresses
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/496)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/496#-:-KyvR7tpbA8Swcnpc9KB:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/496#-:-KyvRKIyW4YherHiaGky:bnfp4nl)*

**Pull request merged**
