### PR TITLE
gc: Refactor error handling

### PR DESCRIPTION
**Pull request by jellonek**
This PR provides the change in error handling, so during GC they are collected and logged in single place, instead of breaking GC on first error.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/385)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/libvirttools/gc.go, line 64 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrF_45DH-ePPuIRtA5i:-KrF_45E--CZ5cvxCgVh:b-3btmwj) ([raw file](https://github.com/mirantis/virtlet/blob/e4604a65cfed922cb52de210f531aadb3a60d216/pkg/libvirttools/gc.go#L64)):*
> can not 
cannot is more correct. can not is kinda "old" form. (same error is several times 
below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385)*

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/libvirttools/gc.go, line 64 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrF_45DH-ePPuIRtA5i:-KrFaCzGN8uJFVZSFFBv:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/e4604a65cfed922cb52de210f531aadb3a60d216/pkg/libvirttools/gc.go#L64)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> can not 
cannot is more correct. can not is kinda "old" form. (same error is several times 
below)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385)*

**Comment by ivan4th** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/libvirttools/gc.go, line 90 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrFa7uvR78xw8H7iNtv:-KrFa7uvR78xw8H7iNtw:bkdydls) ([raw file](https://github.com/mirantis/virtlet/blob/d3ec9646fab956c2bb4a9f668b97dae415433f7b/pkg/libvirttools/gc.go#L90)):*
> ```Go
> 	}
> 
> 	return containerIDs, false, nil
> ```

you're not returning `allErrors`, it's lost

---

*[pkg/libvirttools/gc.go, line 267 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrFaF-iSYQ26zrvhQIO:-KrFaF-iSYQ26zrvhQIP:bkdydls) ([raw file](https://github.com/mirantis/virtlet/blob/d3ec9646fab956c2bb4a9f668b97dae415433f7b/pkg/libvirttools/gc.go#L267)):*
> ```Go
> 	}
> 
> 	return nil
> ```

you're not returning `allErrors`, it's lost

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385)*

**Comment by istalker2** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385#-:-KrFaNTtlYUXwAafsTAe:bnfp4nl)*

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/libvirttools/gc.go, line 90 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrFa7uvR78xw8H7iNtv:-KrFbz1czUU17zxt3-FB:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d3ec9646fab956c2bb4a9f668b97dae415433f7b/pkg/libvirttools/gc.go#L90)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

you're not returning `allErrors`, it's lost
</blockquote></details>

Done.

---

*[pkg/libvirttools/gc.go, line 267 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrFaF-iSYQ26zrvhQIO:-KrFc646LBOJJdXAtE25:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d3ec9646fab956c2bb4a9f668b97dae415433f7b/pkg/libvirttools/gc.go#L267)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

you're not returning `allErrors`, it's lost
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385)*

**Comment by istalker2** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385)*

**Comment by istalker2** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385#-:-KrFcd7SbKrson8AEI5Y:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/libvirttools/gc.go, line 35 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrFd9PZ-pu80xPcKkLE:-KrFd9PZ-pu80xPcKkLF:b-q936ww) ([raw file](https://github.com/mirantis/virtlet/blob/773531cc46038c5a55567dccb8c63ef4dcfa4f5b/pkg/libvirttools/gc.go#L35)):*
> ```Go
> func (v *VirtualizationTool) GarbageCollect() (allErrors []error) {
> 	ids, fatal, errors := v.retrieveListOfContainerIDs()
> 	if errors != nil {
> ```

why this if? append will just do nothing if `errors` is `nil`

---

*[pkg/libvirttools/gc.go, line 43 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrFdvEjoeAMxVLRaOPt:-KrFdvEjoeAMxVLRaOPu:b-nz8816) ([raw file](https://github.com/mirantis/virtlet/blob/773531cc46038c5a55567dccb8c63ef4dcfa4f5b/pkg/libvirttools/gc.go#L43)):*
> ```Go
> 
> 	if errors := v.removeOrphanDomains(ids); errors != nil {
> 		allErrors = append(allErrors, errors...)
> ```

no need for if, just append

---

*[pkg/libvirttools/gc.go, line 47 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrFewdecxqI8oOlTYck:-KrFewdecxqI8oOlTYcl:b-nz8816) ([raw file](https://github.com/mirantis/virtlet/blob/773531cc46038c5a55567dccb8c63ef4dcfa4f5b/pkg/libvirttools/gc.go#L47)):*
> ```Go
> 
> 	if errors := v.removeOrphanRootVolumes(ids); errors != nil {
> 		allErrors = append(allErrors, errors...)
> ```

no need for if, just append

---

*[pkg/libvirttools/gc.go, line 51 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrFexRRxzYXocFy7Tem:-KrFexRRxzYXocFy7Ten:b-nz8816) ([raw file](https://github.com/mirantis/virtlet/blob/773531cc46038c5a55567dccb8c63ef4dcfa4f5b/pkg/libvirttools/gc.go#L51)):*
> ```Go
> 
> 	if errors := v.removeOrphanQcow2Volumes(ids); errors != nil {
> 		allErrors = append(allErrors, errors...)
> ```

no need for if, just append

---

*[pkg/libvirttools/gc.go, line 55 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/385#-KrFey0YsxBTxse-8H7U:-KrFey0YsxBTxse-8H7V:b-nz8816) ([raw file](https://github.com/mirantis/virtlet/blob/773531cc46038c5a55567dccb8c63ef4dcfa4f5b/pkg/libvirttools/gc.go#L55)):*
> ```Go
> 
> 	if errors := v.removeOrphanNoCloudImages(ids); errors != nil {
> 		allErrors = append(allErrors, errors...)
> ```

no need for if, just append

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385#-:-KrFkoHZpE17L6ljaO7k:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385)*

**Comment by istalker2** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/385#-:-KrFkvZQdyK0tHC_mo2o:bnfp4nl)*

**Pull request merged**
