### PR TITLE
[docs] Update notes for Feb, 8-21

### PR DESCRIPTION
**Pull request by ologvinova**
[ci skip]

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/584)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/584#-:-L5yjBMtnmNoNOLBKeMK:bnfp4nl)*

**Comment by ologvinova** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/update-notes/Q1-18-02-21.md, line 5 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/584#-L6-S3VPoUr75WBcVlxA:-L60mf5RX1-BIqk2pOgy:b5akhn5) ([raw file](https://github.com/mirantis/virtlet/blob/f81282f049aebdd525278b1af24a3730d8969025/docs/update-notes/Q1-18-02-21.md#L5)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

These are just examples, not images examples
</blockquote></details>

Done. Changed to 'Virtlet examples'.

---

*[docs/update-notes/Q1-18-02-21.md, line 10 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/584#-L6-SUN_1_yZCYn-yGJw:-L60mtBK_t3UrK_7CjTl:bllxky4) ([raw file](https://github.com/mirantis/virtlet/blob/f81282f049aebdd525278b1af24a3730d8969025/docs/update-notes/Q1-18-02-21.md#L10)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Well it was not exactly added, it was there for quite some time, but done in a hacky way...
</blockquote></details>

Changed to 'Fixed the mount propagation'.

---

*[docs/update-notes/Q1-18-02-21.md, line 11 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/584#-L6-SD8CZuSFH8PlcinW:-L60nLDDlorz0x7rraXm:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f81282f049aebdd525278b1af24a3730d8969025/docs/update-notes/Q1-18-02-21.md#L11)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Well maybe "a startup race"? Let's be honest, we can't know for sure if there are no more startup races ;)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/584)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/584#-:-L62D3jhgrcp7u2FdP88:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/584#-:-L6GpNOeLfTgznAACNPn:bnfp4nl)*

**Pull request merged**
