### PR TITLE
Add e2e test for stopping QEMU

### LINKED ISSUE #441: Add e2e test for stopping QEMU
Failing to stop the emulator is a serious issue with hard-to-debug consequences like VNC glitches and libvirt heap crashes. Although fixed in #436, the issue may reappear after e.g. some vmwrapper changes in future, so we *must* guard against it.

### PR DESCRIPTION
**Pull request by ivan4th**
Fixes #441

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/456)

### CODE REVIEW

**Comment by istalker2** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/e2e/stop_qemu_test.go, line 70 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/456#-Kvi3ZoJj1ybM1SDJy84:-Kvi3ZoJj1ybM1SDJy85:b-qsidd4) ([raw file](https://github.com/mirantis/virtlet/blob/22d228bb247b726249ec0bd3c32669b2100cf1b8/tests/e2e/stop_qemu_test.go#L70)):*
> ```Go
> 	scheduleWaitSSH(&vm, &ssh)
> 
> 	qemuRunning := func() bool {
> ```

either declare regular function outside of Describe() or move the variable into It() for consistency 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/456)*

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/e2e/stop_qemu_test.go, line 70 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/456#-Kvi3ZoJj1ybM1SDJy84:-Kvt7Nm8kT57EbgopTFm:bwti3et) ([raw file](https://github.com/mirantis/virtlet/blob/22d228bb247b726249ec0bd3c32669b2100cf1b8/tests/e2e/stop_qemu_test.go#L70)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

either declare regular function outside of Describe() or move the variable into It() for consistency 
</blockquote></details>

Moving the code into a function outside `Describe()` wouldn't make much sense because the point of the construct is to make use of local vars easily. I declared it on the same level as the vars it's used, but I don't insist that's the right way to do it, so I moved it into `It()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/456)*

**Comment by istalker2** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/e2e/stop_qemu_test.go, line 70 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/456#-Kvi3ZoJj1ybM1SDJy84:-Kvy_dIRf8o0pIuVIpF9:b-p56mo) ([raw file](https://github.com/mirantis/virtlet/blob/22d228bb247b726249ec0bd3c32669b2100cf1b8/tests/e2e/stop_qemu_test.go#L70)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Moving the code into a function outside `Describe()` wouldn't make much sense because the point of the construct is to make use of local vars easily. I declared it on the same level as the vars it's used, but I don't insist that's the right way to do it, so I moved it into `It()`
</blockquote></details>

I see nothing wrong with passing local variables as arguments rather than using closures, but I'm okay with moving it to the `It()` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/456#-:-Kvy_xEuUnWFgNxQH46K:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/456#-:-Kw0JuIaTXtTeSMu1V46:bnfp4nl)*

**Pull request merged**
