### PR TITLE
Add e2e test for ephemeral volume and raw device mounting

### PR DESCRIPTION
**Pull request by ivan4th**
- [X] implement the test
- [x] use less DIND-dependent node selection in the test

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/457)

### CODE REVIEW

**Comment by ivan4th** [comment]
Removed the note about testuser in ubuntu, it must be done separately.

**Comment by ivan4th** [comment]
Disabled the new tests by default, must be enabled with `-include-cloud-init-tests` option.
Made e2e options more flexible by renaming `-cirros` to `-image` and adding `-sshuser` (so as to be able to use e.g. ubuntu instead CirrOS in the envs that support KVM)

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 4 of 12 files at r1, 4 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/457#-:-KwQnyC_SQ57WuHj_I2y:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 4 of 12 files at r1, 4 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/457#-:-KwWGRUQT8dCNTtUEQ5-:bnfp4nl)*

**Pull request merged**
