### PR TITLE
Cri tools compatibility

### PR DESCRIPTION
**Pull request by vefimova**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/350)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/cri-tools.md, line 3 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KnfAe_qPHiznuu77Dox:-KnfAe_qPHiznuu77Doy:b-1te40f) ([raw file](https://github.com/mirantis/virtlet/blob/21f661331d2763c8dd6f9d70c9f7ab8e6686881b/docs/cri-tools.md#L3)):*
> ```Markdown
> # [CRI-tools](https://github.com/kubernetes-incubator/cri-tools) compatibility status
> 
> CRI-tools project utilizes [ginkgo](https://onsi.github.io/ginkgo) package, which provides means for setup/teardown, organizing tests in groups, and flags for running/skipping specific subsets of tests.
> ```

It's either "CRI tools" or "cri-tools", but not "CRI-tools" apparently

---

*[docs/cri-tools.md, line 18 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KnfANSDkGHx1-jAg81q:-KnfANSDkGHx1-jAg81r:bx3dpz) ([raw file](https://github.com/mirantis/virtlet/blob/21f661331d2763c8dd6f9d70c9f7ab8e6686881b/docs/cri-tools.md#L18)):*
> ```Markdown
> | **overall**           | 36 | 20 | 14 |
> 
> Use `Spec names` from the first column above to run specif subsets of tests:
> ```

specific

---

*[docs/cri-tools.md, line 68 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KnfB-baoea7N7BY1UBL:-KnfB-baoea7N7BY1UBM:b61ds5p) ([raw file](https://github.com/mirantis/virtlet/blob/21f661331d2763c8dd6f9d70c9f7ab8e6686881b/docs/cri-tools.md#L68)):*
> ```Markdown
> | -----------------------|:---------------------:|:---------------------------:|:----------:|
> | support HostPID |  created sandbox with nginx and busybox containers with with hostPID. Nginx pid must be seen from within busybox. Using execSync for checking. | n | n |
> | HostIpc is true | check shared memory segment in included in the “busybox” container created with hostIPC set. Using execSync for check. | n | n |
> ```

is included

---

*[docs/cri-tools.md, line 69 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KnfASFcR0h3EYiQnpfg:-KnfASFcR0h3EYiQnpfh:b-7tgnyg) ([raw file](https://github.com/mirantis/virtlet/blob/21f661331d2763c8dd6f9d70c9f7ab8e6686881b/docs/cri-tools.md#L69)):*
> ```Markdown
> | support HostPID |  created sandbox with nginx and busybox containers with with hostPID. Nginx pid must be seen from within busybox. Using execSync for checking. | n | n |
> | HostIpc is true | check shared memory segment in included in the “busybox” container created with hostIPC set. Using execSync for check. | n | n |
> | HostIpc is false | the same as abive but check that memory is not included | n | n |
> ```

above

---

*[docs/cri-tools.md, line 88 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KnfB71jxpZ7n-JC-HpJ:-KnfB71jxpZ7n-JC-HpK:b4tu9a) ([raw file](https://github.com/mirantis/virtlet/blob/21f661331d2763c8dd6f9d70c9f7ab8e6686881b/docs/cri-tools.md#L88)):*
> ```Markdown
> 
> ## critest running steps
> 1.  To be able to run virtlet compatible tests you need to fix following issues in cri-tools"
> ```

typo: " insead of : at the end. Also probably "in cri-tools" needs to be skipped because 2nd issue is actually in Virtlet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/350)*

**Comment by vefimova** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/cri-tools.md, line 3 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KnfAe_qPHiznuu77Dox:-KnfL79BfjmXdzrwjQE1:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/21f661331d2763c8dd6f9d70c9f7ab8e6686881b/docs/cri-tools.md#L3)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

It's either "CRI tools" or "cri-tools", but not "CRI-tools" apparently
</blockquote></details>

Done.

---

*[docs/cri-tools.md, line 18 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KnfANSDkGHx1-jAg81q:-KnfLf6OrmaqpPCcHdfa:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/21f661331d2763c8dd6f9d70c9f7ab8e6686881b/docs/cri-tools.md#L18)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

specific
</blockquote></details>

Done.

---

*[docs/cri-tools.md, line 68 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KnfB-baoea7N7BY1UBL:-KnfLoz-oRPp1DbDnVzW:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/21f661331d2763c8dd6f9d70c9f7ab8e6686881b/docs/cri-tools.md#L68)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

is included
</blockquote></details>

Done.

---

*[docs/cri-tools.md, line 69 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KnfASFcR0h3EYiQnpfg:-KnfLonVXkJEfLyOgskC:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/21f661331d2763c8dd6f9d70c9f7ab8e6686881b/docs/cri-tools.md#L69)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

above
</blockquote></details>

Done.

---

*[docs/cri-tools.md, line 88 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KnfB71jxpZ7n-JC-HpJ:-KnfMDesPVZxv9rgidcY:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/21f661331d2763c8dd6f9d70c9f7ab8e6686881b/docs/cri-tools.md#L88)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

typo: " insead of : at the end. Also probably "in cri-tools" needs to be skipped because 2nd issue is actually in Virtlet.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/350)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/350#-:-KniX3xUS14v4HJWy7-K:bnfp4nl)*

**Comment by jellonek** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/cri-tools.md, line 146 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniXdL3EJnV8bbWs3R0:-KniXdL3EJnV8bbWs3R1:b6o9djt) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/docs/cri-tools.md#L146)):*
> ```Markdown
> hdishd83djaidwnduwk28bcsb
> #
> # crictl --runtime-endpoint=/run/virtlet.sock --image-endpoint=/run/virtlet.sock sandbox ls                   
> ```

Whitespaces at the EOL.

---

*[docs/cri-tools.md, line 155 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniXmnEwvJKvX18bgRS:-KniXmnEwvJKvX18bgRT:b6o9djt) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/docs/cri-tools.md#L155)):*
> ```Markdown
> 
> # virsh vol-list --pool default
>  Name                 Path                                    
> ```

Whitespaces at the EOL.

---

*[docs/cri-tools.md, line 163 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniXnz_bqK-hNDCQUvr:-KniXnz_bqK-hNDCQUvs:b6o9djt) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/docs/cri-tools.md#L163)):*
> ```Markdown
> 
> # virsh vol-list --pool volumes
>  Name                 Path                                    
> ```

Whitespaces at the EOL.

---

*[docs/cri-tools.md, line 167 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniXoknruBRjP3g6UKE:-KniXokoXXfPLnEl_TBv:b6o9djt) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/docs/cri-tools.md#L167)):*
> ```Markdown
>  root_264e1739-7b6a-5a3d-564c-baae69b5bdb0 /var/lib/virtlet/root_264e1739-7b6a-5a3d-564c-baae69b5bdb0
> 
> root@3ef5de7d492b:/go/src/github.com/Mirantis/virtlet# virsh list --all             
> ```

Whitespaces at the EOL.

---

*[docs/cri-tools.md, line 175 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniXqJTiIWtT8LRxR08:-KniXqJTiIWtT8LRxR09:b6o9djt) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/docs/cri-tools.md#L175)):*
> ```Markdown
> 264e1739-7b6a-5a3d-564c-baae69b5bdb0
> 
> # crictl --runtime-endpoint=/run/virtlet.sock --image-endpoint=/run/virtlet.sock container ls                                        
> ```

Whitespaces at the EOL.

---

*[pkg/manager/manager_test.go, line 36 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniY5D_eYZv-SyW0H8s:-KniY5D_eYZv-SyW0H8t:b8syely) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/pkg/manager/manager_test.go#L36)):*
> ```Go
> 		if sandbox != nil {
> 			if err := validatePodSandboxConfig(sandbox); err == nil {
> 				t.Errorf("Invalid pod sandbox passed to validation:\n%s", spew.Sdump(sandbox))
> ```

Seems wrong for me - this test passes validation - so previous version of this message was imo correct.
Whole change in validation seems strange to me - should we pass sandboxes without `Linux` part filled?
Same for `SecurityContext` and `NamespaceOptions` in it.
CRI allows to it, or only these cri tools require that?

Also if we have there only one invalid sandbox, with `nil` as `Metadata` - why there is still a loop over ... list with single item?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/350)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/manager/manager_test.go, line 36 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniY5D_eYZv-SyW0H8s:-Knid3v2s5_jYFUAUYDc:b-u5aaqr) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/pkg/manager/manager_test.go#L36)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Seems wrong for me - this test passes validation - so previous version of this message was imo correct.
Whole change in validation seems strange to me - should we pass sandboxes without `Linux` part filled?
Same for `SecurityContext` and `NamespaceOptions` in it.
CRI allows to it, or only these cri tools require that?

Also if we have there only one invalid sandbox, with `nil` as `Metadata` - why there is still a loop over ... list with single item?
</blockquote></details>

After discussing that with Ivan - I'm ok with removing from validation (in manager.go) these parts.
Still change in comment seems to me be invalid.
Also loop is there unnecessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/350)*

**Comment by vefimova** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/cri-tools.md, line 146 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniXdL3EJnV8bbWs3R0:-KnnKSYtzn7cJc55jtUY:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/docs/cri-tools.md#L146)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Whitespaces at the EOL.
</blockquote></details>

Done.

---

*[docs/cri-tools.md, line 155 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniXmnEwvJKvX18bgRS:-KnnKTE5sfDzCpMjiQJD:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/docs/cri-tools.md#L155)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Whitespaces at the EOL.
</blockquote></details>

Done.

---

*[docs/cri-tools.md, line 163 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniXnz_bqK-hNDCQUvr:-KnnKTjVbZBUM5f_VDoP:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/docs/cri-tools.md#L163)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Whitespaces at the EOL.
</blockquote></details>

Done.

---

*[docs/cri-tools.md, line 167 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniXoknruBRjP3g6UKE:-KnnKUIiK4U8yR0-NiBg:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/docs/cri-tools.md#L167)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Whitespaces at the EOL.
</blockquote></details>

Done.

---

*[docs/cri-tools.md, line 175 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniXqJTiIWtT8LRxR08:-KnnKUuD9oM15YrYjAZc:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/docs/cri-tools.md#L175)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Whitespaces at the EOL.
</blockquote></details>

Done.

---

*[pkg/manager/manager_test.go, line 36 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/350#-KniY5D_eYZv-SyW0H8s:-KnnKWz44rjaI7l-VWZP:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/bb3db257afd68f1fe1957fc12e8c007c6329e4c8/pkg/manager/manager_test.go#L36)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

After discussing that with Ivan - I'm ok with removing from validation (in manager.go) these parts.
Still change in comment seems to me be invalid.
Also loop is there unnecessary.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/350)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/350#-:-KnnMRfvALrFqpe37Cvd:bnfp4nl)*

**Pull request merged**
