### PR TITLE
Handle image redownloading always when kubelet asks for it

### LINKED ISSUE #228: Respect `imagePullPolicy` for VMs
I'm working on DIND cluster that is set up with:
```bash
./demo.sh
```
There is `image-server` pod that serves QCOW2 images to `virtlet` daemon pod. Everything works fine, but if you update QCOW2 image inside `image-server` (folder /usr/share/nginx/html/), the update is not reflected on virtlet daemon. In fact, I can delete QCOW2 image from `image-server` and virtlet daemon can still spawn new pods based on this image 😅 

Does virtlet daemon cache images somewhere? Is it possible to disable caching?

### LINKED ISSUE #244: Image handling needs improvement
Actually volume name for image is constructed from container image using this algorithm:
* remove tag from image (return first part after splitting string by `:`)
* parse result as url (there is no protocol, and `://`)
* split result by `/`, then return last part

In result, for images like `some.url/to/v1/image` and `some.url/to/v2/image` we have a conflict and race during download process (in both there will be attempt to download data from url to the same temporary file `/tmp/image`, and then also under same name in libvirt store).

Proposed solutions:
* use hash from container image name as file name in `/tmp`
* add this hash as suffix or prefix to image name in libvirt storre

This will not eliminate possible race with parallel call to PullImage with same container image name. That would require also adding some random value to temp file name different for each call to PullImage.

### PR DESCRIPTION
**Pull request by jellonek**
- [x] switch root disks usage from taking/using snapshots to using volume clones
- [x] remove tests for volume existence during image import
- [x] make sure that temporary file have unique name
- [x] (re)create volume from downloaded image
- [x] remove temporary file
- [x] update docs

Partially resolves #244 - removes names conflict in `/tmp` during image download.
Closes #228

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/272)

### CODE REVIEW

**Comment by ivan4th** [comment]
Any chance to add tests for this?.. E.g. adding a test that would break with the old behavior.

---

Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/volumes.md, line 57 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmUqxGvanxRCAosRlS:-KjmUqxGvanxRCAosRlT:b-r13r30) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/volumes.md#L57)):*
> ```Markdown
> ```
> 
> All ephemeral volumes created by request as well as clones for boot image are stored
> ```

maybe "copies" is better here? (wdyt?)
All ephemeral volumes created by the request as well as copies of the boot image are stored

---

*[docs/volumes.md, line 100 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmV3xOEMz2lfHeN8_v:-KjmV3xOEMz2lfHeN8_w:b-ujr4ri) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/volumes.md#L100)):*
> ```Markdown
> 
> According to this definition will be created VM-POD with VM with 2 equal volumes, attached, which can be found in "volumes" pool under `<domain-uuid>-vol1` and `<domain-uuid>-vol2`
> Boot image is exposed as volume clone to the guest OS under **vda** device.
> ```

A copy of boot image is exposed as **vda** device to the guest OS.

---

*[docs/volumes.md, line 103 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmVF5rCvykjqxqYYjb:-KjmVF5sq_uGSCXbea7M:b-jh46g3) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/volumes.md#L103)):*
> ```Markdown
> On a typical linux system the additional volume disks are assigned to /dev/vdX devices in an alphabetical order, so vol1 will be /dev/vdb and vol2 will be /dev/vdc, but please refer to caveat #3 at the beginning of this document.
> 
> On pod remove expected all volumes and root disk (clone of boot image) related to VM should be removed.
> ```

I'm not 100% sure I understand what is meant there... Is it "expected" or is it what Virtlet actually does?
I'd say it like this: "When a pod is removed, all the volumes related to it are removed too. This includes the root disk (a copy of the boot image) and any additional volumes."

---

*[pkg/libvirttools/storage_pool.go, line 289 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmW6_2o30B7ef1kPpI:-KjmW6_3ODtMhDL4iVjX:b-c97qdv) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/pkg/libvirttools/storage_pool.go#L289)):*
> ```Go
> }
> 
> func (s *StorageTool) CreateVolumeClone(name string, from *Volume) (*Volume, error) {
> ```

Maybe just `CloneVolume` ? (I don't insist)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/272#-:-KjmWV7E0NymwRFPHRsI:b-j5xnyz)*

**Comment by vefimova** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/images.md, line 24 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmQkBJAVkC8LbECGlG:-KjmQkBJAVkC8LbECGlH:bpxn1z2) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/images.md#L24)):*
> ```Markdown
> (Note, that `PullImage` request can be skipped by kubelet unless the pod has `imagePullPolicy: PullAlways` or `imagePullPolicy: PullIfNotPreset` and the image is not pulled yet.)
> 1. Virtlet uses image url fragment after last slash as internal image name that it looks up in the list of existent images on the host.
> 1. The image will be downloaded using specified url prepended with `scheme://`. After that Virtlet creates libvirt volume in "**default**" libvirt pool under `/var/lib/libvirt/images` and copies the image content to it.
> ```

As there's no versioning for qcow2 images Virtlet downloads image each time using specified url prepended with `scheme://`.

---

*[docs/images.md, line 26 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmTav7ku2IZLwVEIfm:-KjmResWLJlhTtKkklYx:bk7za7c) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/images.md#L26)):*
> ```Markdown
> 1. The image will be downloaded using specified url prepended with `scheme://`. After that Virtlet creates libvirt volume in "**default**" libvirt pool under `/var/lib/libvirt/images` and copies the image content to it.
> 
> **Note:** Virtual machines are started from volumes which are clones of boot images. They are stored 
> ```

Propose to add here
**Note:** Due to CRI design assumes separate implementation of two independent services for image and containers handling we have two different pools for both and store two identical volumes in `default` and `volumes` pools. So 

to explain why we're using volume clones.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/272)*

**Comment by jellonek** [comment]
Old behavior was to return success when file was already in libvirt store - i have no idea how to test this change in integration tests. Unit tests would require a lot of mocking using storage interfaces (it's possible, but imo should be extracted from this PR).

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/272#-:-KjmXQgAlFFkP_spspCV:b-gnj67r)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/images.md, line 24 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmQkBJAVkC8LbECGlG:-KjmZ9ujoHIsCyMkF2FJ:b-b5qy96) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/images.md#L24)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

As there's no versioning for qcow2 images Virtlet downloads image each time using specified url prepended with `scheme://`.
</blockquote></details>

Ok, will add this info.

---

*[docs/images.md, line 26 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmTav7ku2IZLwVEIfm:-KjmZNGNO2HODrW0gFfj:bofrwco) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/images.md#L26)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Propose to add here
**Note:** Due to CRI design assumes separate implementation of two independent services for image and containers handling we have two different pools for both and store two identical volumes in `default` and `volumes` pools. So 

to explain why we're using volume clones.
</blockquote></details>

Will ask Ivan how to properly describe this in English.

---

*[docs/volumes.md, line 57 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmUqxGvanxRCAosRlS:-KjmZ_Rpka3Z1wJ0Wqp-:b-thsf0w) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/volumes.md#L57)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe "copies" is better here? (wdyt?)
All ephemeral volumes created by the request as well as copies of the boot image are stored
</blockquote></details>

It sounds better, but under the hood they are clones, not copies. If you will use `btrfs` as fs under `/var/lib/libvirt` file will not be copied, but there will be done fs based COW clone of it almost instantly. Info worth to add...

---

*[docs/volumes.md, line 100 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmV3xOEMz2lfHeN8_v:-Kjm_5FjfUDEfx7K7Ig7:b-q64pkt) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/volumes.md#L100)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

A copy of boot image is exposed as **vda** device to the guest OS.
</blockquote></details>

See above.

---

*[docs/volumes.md, line 103 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmVF5rCvykjqxqYYjb:-Kjm_F-U36ff6Cc_jGFo:bkw8fnx) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/volumes.md#L103)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'm not 100% sure I understand what is meant there... Is it "expected" or is it what Virtlet actually does?
I'd say it like this: "When a pod is removed, all the volumes related to it are removed too. This includes the root disk (a copy of the boot image) and any additional volumes."
</blockquote></details>

It is expected by user, that virtlet will do that. These are Vika's words which I understand in that way.
Your version (with adjustment - clone, not copy) - seems better to me.

---

*[pkg/libvirttools/storage_pool.go, line 289 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmW6_2o30B7ef1kPpI:-KjmYx3ma1LP_XNDTkV-:b-agpzis) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/pkg/libvirttools/storage_pool.go#L289)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Maybe just `CloneVolume` ? (I don't insist)
</blockquote></details>

Seems ok, will change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/272)*

**Comment by ivan4th** [comment]
BTW also pls fix typo ("allways") in the title.

---

Reviewed 7 of 12 files at r1, 4 of 6 files at r2.
Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/images.md, line 24 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmQkBJAVkC8LbECGlG:-Kjr3_jdWFCWCJvYAx2o:bwwrpza) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/images.md#L24)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Ok, will add this info.
</blockquote></details>

As there is no versioning of QCOW2 images Virtlet downloads the image each time, using the image name with `scheme://` prefix added.

"perpended" is a typo, also image name without `scheme://` is not really an URL...

---

*[docs/images.md, line 26 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmTav7ku2IZLwVEIfm:-Kjr31o971DY17GaIUXm:b-17fgwk) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/images.md#L26)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Will ask Ivan how to properly describe this in English.
</blockquote></details>

Perhaps skipping this as discussed in the chat? Separate impls don't have much to do with separate pools.

---

*[pkg/libvirttools/storage_interface.go, line 91 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/272#-Kjr3zu8KedBK49Ea_Fy:-Kjr3zu8KedBK49Ea_Fz:b-uoyeqh) ([raw file](https://github.com/mirantis/virtlet/blob/f211c24b8cf9fc2e7a2a70b76067d22b629b5105/pkg/libvirttools/storage_interface.go#L91)):*
> ```Go
> func (l LibvirtStorageOperations) PullImageToVolume(pool *libvirt.StoragePool, shortName, filepath, volXML string) error {
> 	// if we have such image already in store - remove it
> 	existing_vol, _ := l.LookupVolumeByName(pool, shortName)
> ```

We probably shouldn't use underscores in var names. This was there already, but as we're touching this part of code now, we should fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/272#-:-KjmZJ1Nlafc4X1AKFIB:bedmd6r)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r2.
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/272#-:-Kjr7IQI26H59kOKztbW:bnfp4nl)*

**Comment by vefimova** [comment]
Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/272)*

**Comment by jellonek** [comment]
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/images.md, line 24 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmQkBJAVkC8LbECGlG:-KjrCfiSatK6B93-Ufht:bt2vr1b) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/images.md#L24)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

As there is no versioning of QCOW2 images Virtlet downloads the image each time, using the image name with `scheme://` prefix added.

"perpended" is a typo, also image name without `scheme://` is not really an URL...
</blockquote></details>

Fixed.

---

*[docs/images.md, line 26 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/272#-KjmTav7ku2IZLwVEIfm:-KjrCJ7kN1mwSloZUfB2:b7o5vza) ([raw file](https://github.com/mirantis/virtlet/blob/4d2e847689e7b24c853476c4889b9d9ca35b5daa/docs/images.md#L26)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Perhaps skipping this as discussed in the chat? Separate impls don't have much to do with separate pools.
</blockquote></details>

I described this in other words below, without mentioning that this is connected with CRI design.

---

*[pkg/libvirttools/storage_interface.go, line 91 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/272#-Kjr3zu8KedBK49Ea_Fy:-KjrEgu4rxoBDSK_y0d5:bt2vr1b) ([raw file](https://github.com/mirantis/virtlet/blob/f211c24b8cf9fc2e7a2a70b76067d22b629b5105/pkg/libvirttools/storage_interface.go#L91)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

We probably shouldn't use underscores in var names. This was there already, but as we're touching this part of code now, we should fix it.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/272)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/272#-:-KjrppoF1ePqYIDytLon:bnfp4nl)*

**Pull request merged**
