### PR TITLE
Remove misleading log messages about flexvolume

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/673)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/673#-:-LC38OyUEUP8wzNJAIm2:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/673#-:-LC3XPo3AqIZxcugDx4R:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/673#-:-LC3XVXg9XC0TjCV0zT7:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/673)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/673#-:-LC3aLME1bAZ7Ra7I0x4:bnfp4nl)*

**Pull request merged**
