### PR TITLE
Add possibility to use nested virtualization

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/696)

### CODE REVIEW

**Comment by ivan4th** [comment]
Reviewed 36 of 36 files at r1.
Review status: 0 of 2 LGTMs obtained

---

*[docs/resource_managment.md, line 6 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJZuPVB0nhMkApNYAc:-LFJZuPVB0nhMkApNYAd:b-6dnthm) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/docs/resource_managment.md#L6)):*
> ```Markdown
> By default libvirt configures qemu to use cpu model which does not allow to work nested virtualization
> in VMs controlled by it. To change that you have to add annotation `VirtletCPUModel` in VM-Pod definition
> with value `host-model`.
> ```

By default, libvirt runs QEMU with a CPU model that doesn't support nested virtualization. It's possible to change this behavior by using `VirtletCPUModel: host-model` annotation in the pod definition. You can also use `cpuModel` value in Virtlet config to override the value globally for the cluster or for a particular subset of nodes.

---

*[examples/ubuntu-vm-with-nesed-virtualization.yaml, line 10 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJ_VTbDkaTm4KjDyUT:-LFJ_VTbDkaTm4KjDyUU:btgl52l) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/examples/ubuntu-vm-with-nesed-virtualization.yaml#L10)):*
> ```YAML
>     VirtletSSHKeys: |
>       ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJEcFDXEK2ZbX0ZLS1EIYFZRbDAcRfuVjpstSc0De8+sV1aiu+dePxdkuDRwqFtCyk6dEZkssjOkBXtri00MECLkir6FcH3kKOJtbJ6vy3uaJc9w1ERo+wyl6SkAh/+JTJkp7QRXj8oylW5E20LsbnA/dIwWzAF51PPwF7A7FtNg9DnwPqMkxFo1Th/buOMKbP5ZA1mmNNtmzbMpMfJATvVyiv3ccsSJKOiyQr6UG+j7sc/7jMVz5Xk34Vd0l8GwcB0334MchHckmqDB142h/NCWTr8oLakDNvkfC1YneAfAO41hDkUbxPtVBG5M/o7P4fxoqiHEX+ZLfRxDtHB53 me@localhost
>     VirtletCPUModel: host-model
> ```

please add the following comment before this line:
`# Set VirtletCPUModel to host-model to enable nested virtualization`

---

*[pkg/api/virtlet.k8s/v1/virtletconfig.go, line 64 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJ_v6O6XMKFAm0_2Pv:-LFJ_v6O6XMKFAm0_2Pw:b-t84c1e) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/api/virtlet.k8s/v1/virtletconfig.go#L64)):*
> ```Go
> 	// CPUModel specifies default cpu model to set in libvirt domain.
> 	// This option can be overriden by pod annotation. Empty value
> 	// means libvirt default.
> ```

CPUModel specifies the default CPU model to use in the libvirt domain definition.
It can be overridden using `VirtletCPUModel` pod annotation.

---

*[pkg/config/config.go, line 97 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJaAByBKK4PP5ScOCp:-LFJaAByBKK4PP5ScOCq:b-giiwcx) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/config/config.go#L97)):*
> ```Go
> 	fs.addIntField("calicoSubnetSize", "calico-subnet-size", "", "Calico subnet size to use", calicoSubnetEnv, defaultCalicoSubnet, 0, 32, &c.CalicoSubnetSize)
> 	fs.addBoolField("enableRegexpImageTranslation", "enable-regexp-image-translation", "", "Enable regexp image name translation", enableRegexpImageTranslationEnv, true, &c.EnableRegexpImageTranslation)
> 	fs.addStringField("cpuModel", "cpu-model", "", "CPU model to set in libvirt domain definition (lack of it means libvirt defaults)", cpuModelEnv, defaultCPUModel, &c.CPUModel)
> ```

"CPU model to use in libvirt domain definition (libvirt's default value will be used if not set)"

---

*[pkg/config/TestConfigForNode__mapping_by_node_name.out.yaml, line 4 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJaPkQ1r0eeGh3magw:-LFJaPkQ1r0eeGh3magx:bcqf92h) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/config/TestConfigForNode__mapping_by_node_name.out.yaml#L4)):*
> ```YAML
> cniConfigDir: /some/cni/conf/dir
> cniPluginDir: /some/cni/bin/dir
> cpuModel: ""
> ```

Please set `cpuModel` to something (e.g. `host-model`) in `fullConfig = ...` in `pkg/config/config_test.go`

---

*[pkg/config/TestMergeConfigs__all_cli_opts_and_explicit_default_config.out.yaml, line 4 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJavZwBGZLqBLzYeD9:-LFJavZwBGZLqBLzYeDA:b-afr4x9) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/config/TestMergeConfigs__all_cli_opts_and_explicit_default_config.out.yaml#L4)):*
> ```YAML
> cniConfigDir: /some/cni/conf/dir
> cniPluginDir: /some/cni/bin/dir
> cpuModel: ""
> ```

please add `--cpu-model=host-model` to the list of options to `all cli opts` and`all cli opts and explicit default config` test cases in `TestMergeConfigs` (pkg/config/config_test.go).

---

*[pkg/config/TestMergeConfigs__all_cli_opts_and_explicit_default_config__env.out.txt, line 16 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJb7F-8TbkDOB3ySYl:-LFJb7F-8TbkDOB3ySYm:b-afr4x9) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/config/TestMergeConfigs__all_cli_opts_and_explicit_default_config__env.out.txt#L16)):*
> ```
> export VIRTLET_CALICO_SUBNET=22
> export IMAGE_REGEXP_TRANSLATION=''
> export VIRTLET_CPU_MODEL=''
> ```

please add `--cpu-model=host-model` to the list of options to `all cli opts` and`all cli opts and explicit default config` test cases in `TestMergeConfigs` (pkg/config/config_test.go).

---

*[pkg/libvirttools/virtualization.go, line 154 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJbnrP6BGJGnjOzpth:-LFJbnrP6BGJGnjOzpti:bmpjiva) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/libvirttools/virtualization.go#L154)):*
> ```Go
> 	// In case of intel processors it requires nested=1 option
> 	// for kvm_intel module. That can be passed like this:
> 	// modprobe kvm_intel nested=1
> ```

Please move this comment further down, after `case types.CPUModelHostModel:`

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/696)*

**Comment by jellonek** [comment]
Review status: 0 of 2 LGTMs obtained

---

*[docs/resource_managment.md, line 6 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJZuPVB0nhMkApNYAc:-LFLaQfi5tT1AlOsIrYC:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/docs/resource_managment.md#L6)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

By default, libvirt runs QEMU with a CPU model that doesn't support nested virtualization. It's possible to change this behavior by using `VirtletCPUModel: host-model` annotation in the pod definition. You can also use `cpuModel` value in Virtlet config to override the value globally for the cluster or for a particular subset of nodes.
</blockquote></details>

Done.

---

*[examples/ubuntu-vm-with-nesed-virtualization.yaml, line 10 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJ_VTbDkaTm4KjDyUT:-LFLaR_xAOP-W0k71k0G:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/examples/ubuntu-vm-with-nesed-virtualization.yaml#L10)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

please add the following comment before this line:
`# Set VirtletCPUModel to host-model to enable nested virtualization`
</blockquote></details>

Done.

---

*[pkg/api/virtlet.k8s/v1/virtletconfig.go, line 64 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJ_v6O6XMKFAm0_2Pv:-LFLaVDd8YZG4NOBGgo7:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/api/virtlet.k8s/v1/virtletconfig.go#L64)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

CPUModel specifies the default CPU model to use in the libvirt domain definition.
It can be overridden using `VirtletCPUModel` pod annotation.
</blockquote></details>

Done.

---

*[pkg/config/config.go, line 97 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJaAByBKK4PP5ScOCp:-LFLaVvyDOm21XRN_jIK:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/config/config.go#L97)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

"CPU model to use in libvirt domain definition (libvirt's default value will be used if not set)"
</blockquote></details>

Done.

---

*[pkg/config/TestConfigForNode__mapping_by_node_name.out.yaml, line 4 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJaPkQ1r0eeGh3magw:-LFLaXAS6uc1O_Y85oDT:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/config/TestConfigForNode__mapping_by_node_name.out.yaml#L4)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Please set `cpuModel` to something (e.g. `host-model`) in `fullConfig = ...` in `pkg/config/config_test.go`
</blockquote></details>

Done.

---

*[pkg/config/TestMergeConfigs__all_cli_opts_and_explicit_default_config.out.yaml, line 4 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJavZwBGZLqBLzYeD9:-LFLaY1a0tG3uy_jIpFX:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/config/TestMergeConfigs__all_cli_opts_and_explicit_default_config.out.yaml#L4)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

please add `--cpu-model=host-model` to the list of options to `all cli opts` and`all cli opts and explicit default config` test cases in `TestMergeConfigs` (pkg/config/config_test.go).
</blockquote></details>

Done.

---

*[pkg/config/TestMergeConfigs__all_cli_opts_and_explicit_default_config__env.out.txt, line 16 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJb7F-8TbkDOB3ySYl:-LFLaZHr5NfJPhccQ_cN:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/config/TestMergeConfigs__all_cli_opts_and_explicit_default_config__env.out.txt#L16)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

please add `--cpu-model=host-model` to the list of options to `all cli opts` and`all cli opts and explicit default config` test cases in `TestMergeConfigs` (pkg/config/config_test.go).
</blockquote></details>

Done.

---

*[pkg/libvirttools/virtualization.go, line 154 at r1](https://reviewable.io/reviews/mirantis/virtlet/696#-LFJbnrP6BGJGnjOzpth:-LFLaZuJ5pVWJqvFsDyl:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/94a3788f8cc4261b2b1a62e36f92360adf378380/pkg/libvirttools/virtualization.go#L154)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Please move this comment further down, after `case types.CPUModelHostModel:`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/696)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r2.
Review status: 0 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/696#-:-LFNXUpg-KHPJ_Y-f_cJ:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: 1 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/696#-:-LFSQGHw7iV_O64qf76M:bnfp4nl)*

**Pull request merged**
