### PR TITLE
Fix linter issues in pkg/image/

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/603)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/603#-:-L73rH2C2DJvIgLPCl3T:bnfp4nl)*

**Comment by jellonek** [comment]
Hold your horses - there is an issue pointed by integration tests. I'm fixing it.

**Comment by jellonek** [comment]
Ok. Updated.

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/603#-:-L73tqIe5w6k_vi_-6qe:bnfp4nl)*

**Pull request merged**
