### PR TITLE
Upgrade to k8s 1.9

### PR DESCRIPTION
**Pull request by ivan4th**
- [X] upgrade to use k8s 1.9
- [x] use new CRI Proxy release with 1.9 support
- [x] retest with k8s 1.7, 1.8 and 1.9 (via `build/cmd.sh`)

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/586)

### CODE REVIEW

**Comment by jellonek** [comment]
https://github.com/Mirantis/virtlet/blame/master/examples/README.md#L48 also needs an update ;)

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/586#-:-L6Nnmr0_3xIWMGfTcJQ:bfssvk1)*

**Comment by ivan4th** [comment]
The PR is ready. I verified it with k8s 1.7 / 1.8 / 1.9 using `build/cmd.sh` and with 1.9 using `deploy/demo.sh` (the demo supports only one k8s version which is set to 1.9 in this PR), but feel free to re-verify to make sure.

**Comment by jellonek** [comment]
If you can - please update an info about plugin usage, as there is no need for "newer" kubectl if virtlet is deployed on 1.9.x.
It would be better to update that in this PR, but imo it's not a blocker and can be done also in a follow up, so :lgtm: from my side.

---

Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/README.md, line 48 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/586#-L6vBDDeu_72GUmnedPU:-L6vBDDeu_72GUmnedPV:baax2bs) ([raw file](https://github.com/mirantis/virtlet/blob/3a7df28d0f77b9f482c8c91854e674348c34c364/examples/README.md#L48)):*
> ```Markdown
> 
> Another option to use this script is to install it as a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/).
> At the moment, Virtlet only supports Kubernetes 1.7.x, 1.8.x and 1.9.x.
> ```

That probably needs a rephrase, because when we are using 1.9.x. there is no need to use `newer kubectl with these kubernetes versions`.
Under 1.9.x it simply should work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/586#-:-L6vBaupxGpDgw756bIc:b-e333j4)*

**Comment by ivan4th** [comment]
My idea was to fix this in virtletctl PR because that part of the doc will be completely rewritten there.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/586#-:-L6vCGEnVpWqBTn9dnuC:b-oxk3bq)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/586#-:-L73qyh0kxE5BsVRBhvQ:bnfp4nl)*

**Pull request merged**
