### PR TITLE
Config maps and secrets support in volumes

### PR DESCRIPTION
**Pull request by jellonek**
To be easier reviewable - PR is to flexvolumes branch, what can be later changed to master when it will be merged.

Tested manually - creates correct entries in `user-data` in no cloud iso image.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/319)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/libvirttools/virtualization.go, line 378 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaFNmVDXrkiwPrTCeC:-KmaFNmWbsbjGjsNxIM9:bbfggz4) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/virtualization.go#L378)):*
> ```Go
> 			config.PodSandboxId, config.Image, cloneName,
> 			config.ContainerLabels, config.ContainerAnnotations,
> 			nocloudFile, v.timeFunc)
> ```

no actual changes here, just formatting, right? asking to make sure

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/libvirttools/virtualization.go, line 378 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaFNmVDXrkiwPrTCeC:-KmaIJzsVaBCX4G370He:b-dgb009) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/virtualization.go#L378)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

no actual changes here, just formatting, right? asking to make sure
</blockquote></details>

Yes, exactly - it's also in separate commit called "cleanup".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319)*

**Comment by gberginc** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/libvirttools/cloudinit.go, line 86 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaIfQQWoLqfRD8Iv9f:-KmaIfQQWoLqfRD8Iv9g:b-b7zl7t) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L86)):*
> ```Go
> 	g.addEnvVarsFileToWriteFiles(userData)
> 
> 	writeFilesManipulator := NewWriteFilesManipulator(userData, g.config.Mounts)
> ```

Would it make sense to replace this with a "simple" function that would take `userData` and `g.config.Mounts` and hide all the details (including `AddSecrets` and `AddConfigMapEntries`?

Currently, it looks to me that having an object to which you always add these two special types, make a little sense.

---

*[pkg/libvirttools/cloudinit.go, line 88 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaJNfT7XUV4cZS0Ul0:-KmaJNfT7XUV4cZS0Ul1:bi8z5a9) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L88)):*
> ```Go
> 	writeFilesManipulator := NewWriteFilesManipulator(userData, g.config.Mounts)
> 	writeFilesManipulator.AddSecrets()
> 	writeFilesManipulator.AddConfigMapEntris()
> ```

Rename to `AddConfigMapEntries`

---

*[pkg/libvirttools/cloudinit.go, line 288 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaJUoF64xmx-LQ-xIF:-KmaJUoF64xmx-LQ-xIG:b-a6qwi9) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L288)):*
> ```Go
> 		encodedContent := base64.StdEncoding.EncodeToString(content)
> 		writeFiles = append(writeFiles, map[string]interface{}{
> 			"path":        path.Join(mount.ContainerPath, relativePath),
> ```

I think I am missing something, so I rather ask: the relative location of the file has to be in the same path as it will be in the target VM? So, I cannot put a file `/home/lemmy/test/files/user1/secrets` to for example `/etc/app/secrets`?

Would it be possible to add a simple example somewhere in the readme or test case? Perhaps it will be much clearer how this is to be used.

---

*[pkg/libvirttools/cloudinit.go, line 317 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaKa3hblJHvd3QPF2i:-KmaKa3hblJHvd3QPF2j:bguyy39) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L317)):*
> ```Go
> 			// .. or for symlinks for regular files
> 			if entry.Mode()&os.ModeSymlink != 0 {
> 				glog.Infof("Found symlink: %s", entry.Name())
> ```

What is the diff between `glog` and `glog.V(3)`? Is one implicitly using a specific version?

---

*[pkg/libvirttools/cloudinit.go, line 323 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaKNz4j6Rr53KECjgQ:-KmaKNz4j6Rr53KECjgR:b-chu4s1) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L323)):*
> ```Go
> 				}
> 				if fi.Mode().IsRegular() {
> 					err := addFileContent(fullPath)
> ```

Do you think it makes sense to make copies of files that are symlinked?

---

*[pkg/libvirttools/cloudinit.go, line 336 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaKy_DSr866-KPNnvk:-KmaKy_DSr866-KPNnvl:bbqqtwk) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L336)):*
> ```Go
> 
> 	scanner := func(name string, f os.FileInfo, err error) error {
> 		if f.IsDir() {
> ```

Why don't you walk the entire tree in one function? Since you are only looking for regular files (and symlinks) in scanDirectory, I think you could do this in a single walker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/libvirttools/cloudinit.go, line 86 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaIfQQWoLqfRD8Iv9f:-KmaQn6qvjzjdmZsIOfk:b-ltoyrg) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L86)):*
<details><summary><i>Previously, gberginc (Gregor Berginc) wrote…</i></summary><blockquote>

Would it make sense to replace this with a "simple" function that would take `userData` and `g.config.Mounts` and hide all the details (including `AddSecrets` and `AddConfigMapEntries`?

Currently, it looks to me that having an object to which you always add these two special types, make a little sense.
</blockquote></details>

This object allows me to not pass again and again the same arguments. For sure this can be connected into single func, but there I wanted to explicitly note on this level that there are added two separate things (with almost same internals, but configured/used by kubelet in different way).

I plan in near future to refactor this adding to same place EnvVars generation/adding, and then this will for sure be hidden in a single func.

---

*[pkg/libvirttools/cloudinit.go, line 88 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaJNfT7XUV4cZS0Ul0:-KmaUV6IiiFm4sq2MBZ-:b-hq0tjl) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L88)):*
<details><summary><i>Previously, gberginc (Gregor Berginc) wrote…</i></summary><blockquote>

Rename to `AddConfigMapEntries`
</blockquote></details>

Thx. Will do that.

---

*[pkg/libvirttools/cloudinit.go, line 288 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaJUoF64xmx-LQ-xIF:-KmaT_5hapjUN4DpvM5X:b2kgzwp) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L288)):*
<details><summary><i>Previously, gberginc (Gregor Berginc) wrote…</i></summary><blockquote>

I think I am missing something, so I rather ask: the relative location of the file has to be in the same path as it will be in the target VM? So, I cannot put a file `/home/lemmy/test/files/user1/secrets` to for example `/etc/app/secrets`?

Would it be possible to add a simple example somewhere in the readme or test case? Perhaps it will be much clearer how this is to be used.
</blockquote></details>

You can - but you are operating on directory level, so you can make secret or config map from mentioned file, and then use it in pod definition as a thing which has to be "mounted" (in our case - filled with files which can be in subdirs) to `/etc/app`.

---

*[pkg/libvirttools/cloudinit.go, line 317 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaKa3hblJHvd3QPF2i:-KmaTHXi6Q7p5FeHfYv5:b-8olwx7) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L317)):*
<details><summary><i>Previously, gberginc (Gregor Berginc) wrote…</i></summary><blockquote>

What is the diff between `glog` and `glog.V(3)`? Is one implicitly using a specific version?
</blockquote></details>

There should be `glog.V(3)` - what means that this info will go to logs only if binary is started with 3rd verbose level (`-v 3`).

---

*[pkg/libvirttools/cloudinit.go, line 323 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaKNz4j6Rr53KECjgQ:-KmaS6OaxsXgwQfs-GDA:b-7rweij) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L323)):*
<details><summary><i>Previously, gberginc (Gregor Berginc) wrote…</i></summary><blockquote>

Do you think it makes sense to make copies of files that are symlinked?
</blockquote></details>

This is exactly needed, because of how kubelet generates content in source dir. These entries are symlinks.
You can see them in `/var/lib/kubelet/pods/pod_uuid/volumes/kubernetes.io~secret/secret_name/` in any pod on node where it was started.
As we don't have a way to specify in `write_file` an entry for symlink - we need to copy whole content of them.

---

*[pkg/libvirttools/cloudinit.go, line 336 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaKy_DSr866-KPNnvk:-KmaQyypK-2Jolx0I8GX:bou43cl) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L336)):*
<details><summary><i>Previously, gberginc (Gregor Berginc) wrote…</i></summary><blockquote>

Why don't you walk the entire tree in one function? Since you are only looking for regular files (and symlinks) in scanDirectory, I think you could do this in a single walker.
</blockquote></details>

Initially had an issue with symlinks (entries on fs are generated by kubelet are quite strange way, using symlinks to `..data/` dir, which is a symlink to other dir with cryptic name) - but will try again with simple single level walker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/libvirttools/cloudinit.go, line 88 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaJNfT7XUV4cZS0Ul0:-KmaZl26K8Y4meCMTQbx:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L88)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Thx. Will do that.
</blockquote></details>

Done.

---

*[pkg/libvirttools/cloudinit.go, line 288 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaJUoF64xmx-LQ-xIF:-Kma_RW59ClbxcBokFyJ:blcgz3p) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L288)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

You can - but you are operating on directory level, so you can make secret or config map from mentioned file, and then use it in pod definition as a thing which has to be "mounted" (in our case - filled with files which can be in subdirs) to `/etc/app`.
</blockquote></details>

Docs postponed into separate https://github.com/Mirantis/virtlet/issues/320 issue.
Will do the same for tests.

---

*[pkg/libvirttools/cloudinit.go, line 317 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmaKa3hblJHvd3QPF2i:-KmaZm6DjzUYGrCi1JNo:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a0ebe40032b2743352f263065445de196c9b6fea/pkg/libvirttools/cloudinit.go#L317)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

There should be `glog.V(3)` - what means that this info will go to logs only if binary is started with 3rd verbose level (`-v 3`).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319)*

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/libvirttools/cloudinit.go, line 267 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/319#-Kmab5jIt61qGdN3DSJm:-Kmab5jIt61qGdN3DSJn:b-cnmjfw) ([raw file](https://github.com/mirantis/virtlet/blob/8c49caa8feba41cf81d975593de610f2e6093e22/pkg/libvirttools/cloudinit.go#L267)):*
> ```Go
> 			continue
> 		}
> 		if entries := m.addFilesForMount(mount, permissions); entries != nil {
> ```

you don't need this `entries != nil` check before append

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/libvirttools/cloudinit.go, line 267 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/319#-Kmab5jIt61qGdN3DSJm:-Kmad-5JwQvn7t3JIPab:b-ll4rxd) ([raw file](https://github.com/mirantis/virtlet/blob/8c49caa8feba41cf81d975593de610f2e6093e22/pkg/libvirttools/cloudinit.go#L267)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

you don't need this `entries != nil` check before append
</blockquote></details>

Yes, you are right. That was added because I mistakenly had at the beginning `entires` in append call, without the `...`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319)*

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[deploy/virtlet-ds-dev.yaml, line 99 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/319#-KmbnppHZtY9Ty2w0Zsg:-KmbnppHZtY9Ty2w0Zsh:b-4tauks) ([raw file](https://github.com/mirantis/virtlet/blob/6e3018c17e18db7485a332bc4db9f939bfdf27d3/deploy/virtlet-ds-dev.yaml#L99)):*
> ```YAML
>         - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
>           name: k8s-flexvolume-plugins-dir
>         - mountPath: /var/lib/kubelet/pods:shared
> ```

Please add a comment about this being a hack to overcome forced private mounting problem. This is not "official" mountPath syntax

---

*[deploy/virtlet-ds.yaml, line 95 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/319#-Kmbnx_VbDmFMXgB2VSu:-Kmbnx_WVmrczNW5ZZ6Y:b-bomtgg) ([raw file](https://github.com/mirantis/virtlet/blob/6e3018c17e18db7485a332bc4db9f939bfdf27d3/deploy/virtlet-ds.yaml#L95)):*
> ```YAML
>         - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
>           name: k8s-flexvolume-plugins-dir
>         - mountPath: /var/lib/kubelet/pods:shared
> ```

Same as above, pls add a comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319#-:-Kmbr6FZ_sYOeWu35KSF:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/libvirttools/cloudinit.go, line 270 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/319#-Kmbtqj22sRhZaNIi6AG:-Kmbtqj22sRhZaNIi6AH:bk64prc) ([raw file](https://github.com/mirantis/virtlet/blob/6e3018c17e18db7485a332bc4db9f939bfdf27d3/pkg/libvirttools/cloudinit.go#L270)):*
> ```Go
> 		writeFiles = append(writeFiles, entries...)
> 	}
> 	m.userData["write_files"] = append(oldWriteFiles, writeFiles...)
> ```

don't set `write_files` in `m.userData` when writeFiles is nil (this is causing diff in golden master)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319#-:-Kmc7Zp3L5ZjGcGIhITa:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/319#-:-KmcH7EVW82XuvSrTk4I:bnfp4nl)*

**Pull request merged**
