### PR TITLE
Test for breaking RunPodSandbox by CNI failure

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/672)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[pkg/manager/runtime_test.go, line 347 at r1](https://reviewable.io/reviews/mirantis/virtlet/672#-LC8aIWq1Y51h05pkTvZ:-LC8aIWq1Y51h05pkTv_:bj8z288) ([raw file](https://github.com/mirantis/virtlet/blob/500215eb6ef0ef89173f6cb95ab3c988716bf9b5/pkg/manager/runtime_test.go#L347)):*
> ```Go
> }
> 
> func (tst *virtletCRITester) expectFailingPodSandbox(config *kubeapi.PodSandboxConfig) {
> ```

`expectSmth` is naming is used for mock methods that set expectations but don't do anything else I think. Maybe `runPodSandboxAndExpectError`?

---

*[pkg/manager/runtime_test.go, line 350 at r1](https://reviewable.io/reviews/mirantis/virtlet/672#-LC8aaal4ksWegaz-dzy:-LC8aaal4ksWegaz-dzz:biprdcd) ([raw file](https://github.com/mirantis/virtlet/blob/500215eb6ef0ef89173f6cb95ab3c988716bf9b5/pkg/manager/runtime_test.go#L350)):*
> ```Go
> 	_, err := tst.invoke("RunPodSandbox", &kubeapi.RunPodSandboxRequest{Config: config}, false)
> 	if err == nil {
> 		tst.t.Errorf("expected error from RunPodSanbox but received success")
> ```

"didn't get an expected error from RunPodSandbox"

---

*[pkg/manager/runtime_test.go, line 501 at r1](https://reviewable.io/reviews/mirantis/virtlet/672#-LC8bFUX8_sOFvuYIo5z:-LC8bFUX8_sOFvuYIo6-:byr9f3b) ([raw file](https://github.com/mirantis/virtlet/blob/500215eb6ef0ef89173f6cb95ab3c988716bf9b5/pkg/manager/runtime_test.go#L501)):*
> ```Go
> 	sandboxes := criapi.GetSandboxes(1)
> 	sandboxes[0].Metadata.Uid = "should-fail-cni"
> 	tst.expectFailingPodSandbox(sandboxes[0])
> ```

Does this call produce any output if you add `tst.verify()` at the end?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/672)*

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/manager/runtime_test.go, line 501 at r1](https://reviewable.io/reviews/mirantis/virtlet/672#-LC8bFUX8_sOFvuYIo5z:-LC8bQLI4Mw2eVoAyz5E:bpn6unt) ([raw file](https://github.com/mirantis/virtlet/blob/500215eb6ef0ef89173f6cb95ab3c988716bf9b5/pkg/manager/runtime_test.go#L501)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Does this call produce any output if you add `tst.verify()` at the end?
</blockquote></details>

Probably `tst.verify()` should be called in any case to record FDManager calls etc.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/672)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/manager/runtime_test.go, line 501 at r1](https://reviewable.io/reviews/mirantis/virtlet/672#-LC8bFUX8_sOFvuYIo5z:-LC8brew4QjWjx64I50Z:b-z7dau3) ([raw file](https://github.com/mirantis/virtlet/blob/500215eb6ef0ef89173f6cb95ab3c988716bf9b5/pkg/manager/runtime_test.go#L501)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Probably `tst.verify()` should be called in any case to record FDManager calls etc.
</blockquote></details>

Yes, as there is used recorder `.verify()` should be called at the end.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/672)*

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/manager/runtime_test.go, line 347 at r1](https://reviewable.io/reviews/mirantis/virtlet/672#-LC8aIWq1Y51h05pkTvZ:-LCD6v294e5NstLYLfNI:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/500215eb6ef0ef89173f6cb95ab3c988716bf9b5/pkg/manager/runtime_test.go#L347)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`expectSmth` is naming is used for mock methods that set expectations but don't do anything else I think. Maybe `runPodSandboxAndExpectError`?
</blockquote></details>

Done.

---

*[pkg/manager/runtime_test.go, line 350 at r1](https://reviewable.io/reviews/mirantis/virtlet/672#-LC8aaal4ksWegaz-dzy:-LCD74xOBsI-uKVl0mVe:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/500215eb6ef0ef89173f6cb95ab3c988716bf9b5/pkg/manager/runtime_test.go#L350)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

"didn't get an expected error from RunPodSandbox"
</blockquote></details>

Done.

---

*[pkg/manager/runtime_test.go, line 501 at r1](https://reviewable.io/reviews/mirantis/virtlet/672#-LC8bFUX8_sOFvuYIo5z:-LCD7AetE9NB4fLDgCZs:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/500215eb6ef0ef89173f6cb95ab3c988716bf9b5/pkg/manager/runtime_test.go#L501)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Yes, as there is used recorder `.verify()` should be called at the end.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/672)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/672#-:-LCTHOEc2OAYKOUNEAUh:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/672#-:-LCYebdO9R4dx_Afmg2u:bnfp4nl)*

**Comment by pigmej** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/672)*

**Pull request merged**
