### PR TITLE
Fix build quirks

### PR DESCRIPTION
**Pull request by ivan4th**
* Inject virtlet image into the dind node upon `build/cmd.sh start-dind`
* Fix VIRTLET_ON_MASTER
* Update build tool docs

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/421)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/devel/build-tool.md, line 30 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/421#-KuQie559GZ1LfVADLmd:-KuQie559GZ1LfVADLme:blnalqn) ([raw file](https://github.com/mirantis/virtlet/blob/0d56738f6393c4b2748aedbbf5e4297eb3db0881/docs/devel/build-tool.md#L30)):*
> ```Markdown
> ## build
> 
> Performs full build based on autotools. Also builds
> ```

Are you sure about that autotools? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/421)*

**Comment by ivan4th** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/devel/build-tool.md, line 30 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/421#-KuQie559GZ1LfVADLmd:-KuTILVw3KfJw8288Jod:b-sj7h3a) ([raw file](https://github.com/mirantis/virtlet/blob/0d56738f6393c4b2748aedbbf5e4297eb3db0881/docs/devel/build-tool.md#L30)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Are you sure about that autotools? :)
</blockquote></details>

Fixed. (Didn't fix in #420 to avoid conflicts)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/421)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/421#-:-KuTIn6BSlI4oUcErhzm:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/421#-:-KuTKCjYfMM4QDdN3lv_:bnfp4nl)*

**Pull request merged**
