### PR TITLE
Add info about ConfigMaps/Secrets as volumes

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/333)

### CODE REVIEW

**Comment by vefimova** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/volumes.md, line 404 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn8rvySBVvrg6qPTS0c:-Kn8rvySBVvrg6qPTS0d:b-o45g5u) ([raw file](https://github.com/mirantis/virtlet/blob/a9ccd3830f16fdefe5140bc6afeed172088de57f/docs/volumes.md#L404)):*
> ```Markdown
> ```
> 
> ## Providing files to VM using Secretes or ConfigMaps
> ```

s/Secretes/Secrets/

---

*[docs/volumes.md, line 406 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn8tFkqS_GuUBTDvNEW:-Kn8tFkqS_GuUBTDvNEX:bqa8p5u) ([raw file](https://github.com/mirantis/virtlet/blob/a9ccd3830f16fdefe5140bc6afeed172088de57f/docs/volumes.md#L406)):*
> ```Markdown
> ## Providing files to VM using Secretes or ConfigMaps
> 
> Virtlet supports passing files to VM contained in Secrets and ConfigMaps.
> ```

Probably better to say here that "Virtlet supports standard definitions of Secrets and ConfigMaps. It generates configuration for `write_files`  [cloud-init](http://cloudinit.readthedocs.io/en/latest/index.html) module basing on populated by kubelet Secret's/ConfigMap specific directory content."

---

*[docs/volumes.md, line 421 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9AkIg072HWei9OheU:-Kn9AkIg072HWei9OheV:b-9xsck3) ([raw file](https://github.com/mirantis/virtlet/blob/a9ccd3830f16fdefe5140bc6afeed172088de57f/docs/volumes.md#L421)):*
> ```Markdown
> ### Secret as volume
> 
> In same manner as files in ConfigMaps user can use Secret according to
> ```

in `the` same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/333)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/volumes.md, line 404 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn8rvySBVvrg6qPTS0c:-Kn9UV9P5tWS0dKAsDni:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a9ccd3830f16fdefe5140bc6afeed172088de57f/docs/volumes.md#L404)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

s/Secretes/Secrets/
</blockquote></details>

Done.

---

*[docs/volumes.md, line 406 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn8tFkqS_GuUBTDvNEW:-Kn9UTv9ilRdeANoITkf:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a9ccd3830f16fdefe5140bc6afeed172088de57f/docs/volumes.md#L406)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Probably better to say here that "Virtlet supports standard definitions of Secrets and ConfigMaps. It generates configuration for `write_files`  [cloud-init](http://cloudinit.readthedocs.io/en/latest/index.html) module basing on populated by kubelet Secret's/ConfigMap specific directory content."
</blockquote></details>

Done.

---

*[docs/volumes.md, line 421 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9AkIg072HWei9OheU:-Kn9UWXuGBLdXYhInvnb:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a9ccd3830f16fdefe5140bc6afeed172088de57f/docs/volumes.md#L421)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

in `the` same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/333)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/333#-:-Kn9WDioYb6E_oEe3wq9:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/volumes.md, line 404 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn8rvySBVvrg6qPTS0c:-Kn9bbPFk0AEj_Ddu3xr:b-zee5tl) ([raw file](https://github.com/mirantis/virtlet/blob/a9ccd3830f16fdefe5140bc6afeed172088de57f/docs/volumes.md#L404)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe "Injecting Secret and ConfigMap content into the VMs as files"?

---

*[docs/volumes.md, line 406 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn8tFkqS_GuUBTDvNEW:-Kn9cAEJzic9-s70Musq:bd2i0nt) ([raw file](https://github.com/mirantis/virtlet/blob/a9ccd3830f16fdefe5140bc6afeed172088de57f/docs/volumes.md#L406)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It does so using `write_files` [cloud-init](...) module which is used to write Secret/ConfigMap content to appropriate locations.

---

*[docs/volumes.md, line 406 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9bosi4DiRfKqJPsOF:-Kn9bosi4DiRfKqJPsOG:b-vmct4b) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L406)):*
> ```Markdown
> ## Providing files to VM using Secrets or ConfigMaps
> 
> Virtlet supports standard definitions of Secrets and ConfigMaps.
> ```

Virtlet supports the standard `volumeMounts` notation for placing ConfigMap and Secret content into the VM filesystem.

---

*[docs/volumes.md, line 413 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9c_0dia6NoJ_aqzUE:-Kn9c_0eX4rAuy2qwIiu:b-ngm4mv) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L413)):*
> ```Markdown
> 
> Current limitation is that only files from top level directory will be
> delivered to VM.
> ```

Virtlet only handles files in the top level directory for each Secret/ConfigMap `VolumeMounts` entry. This limitation is to be lifted soon.

---

*[docs/volumes.md, line 415 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9cqQq21483UeB7Vnq:-Kn9cqQq21483UeB7Vnr:bs25ix3) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L415)):*
> ```Markdown
> delivered to VM.
> 
> ### ConfigMap as volume
> ```

Consuming a ConfigMap using Kubernetes volume

---

*[docs/volumes.md, line 418 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9eKkV4c9X1Cu1Qq1U:-Kn9eKkWjR-fNPDJGYS_:b2n44rn) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L418)):*
> ```Markdown
> 
> User can pass data to VM using ConfigMap following
> [this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume) example.
> ```

See [the following example] that demonstrates how to pass ConfigMap data to a VM.

---

*[docs/volumes.md, line 420 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9d4uJ2h2q5KXfTULZ:-Kn9d4uJ2h2q5KXfTUL_:b-uv9ema) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L420)):*
> ```Markdown
> [this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume) example.
> 
> [Example of passing file in ConfigMap through volume](https://asciinema.org/a/084dbr1V0zpxNbF4iaTJpEgJA)
> ```

ConfigMap volume demo

---

*[docs/volumes.md, line 422 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9czLZZ3iIyVLPt51l:-Kn9czLZZ3iIyVLPt51m:bbvcks3) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L422)):*
> ```Markdown
> [Example of passing file in ConfigMap through volume](https://asciinema.org/a/084dbr1V0zpxNbF4iaTJpEgJA)
> 
> ### Secret as volume
> ```

Consuming a Secret using Kubernetes volume

---

*[docs/volumes.md, line 426 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9hbBmG-bNz1ASoutJ:-Kn9hbBmG-bNz1ASoutK:b-2wi1ic) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L426)):*
> ```Markdown
> In the same manner as files in ConfigMaps user can use Secret according to
> [example](https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pod-with-ssh-keys)
> in kubernetes documentation.
> ```

Secrets can be consumed in the same manner as ConfigMaps, see [the example] in kubernetes documentation.

---

*[docs/volumes.md, line 428 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9hrgdabKm02CebxAF:-Kn9hrgdabKm02CebxAG:b-4wpgns) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L428)):*
> ```Markdown
> in kubernetes documentation.
> Each started VM also has predefined secret containing api access token which
> is propagated to `/var/run/secrets/kubernetes.io/serviceaccount` directory.
> ```

Like any other pod, Virtlet VM pods have predefined secret with Kubernetes API access token which is written into `/var/run/secrets/kubernetes.io/serviceaccount` directory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/333)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/volumes.md, line 404 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn8rvySBVvrg6qPTS0c:-Kn9keHlWLaI5Ie_UzVN:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a9ccd3830f16fdefe5140bc6afeed172088de57f/docs/volumes.md#L404)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Maybe "Injecting Secret and ConfigMap content into the VMs as files"?
</blockquote></details>

Done.

---

*[docs/volumes.md, line 406 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn8tFkqS_GuUBTDvNEW:-Kn9kfWvi8wdLHNM6doL:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a9ccd3830f16fdefe5140bc6afeed172088de57f/docs/volumes.md#L406)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

It does so using `write_files` [cloud-init](...) module which is used to write Secret/ConfigMap content to appropriate locations.
</blockquote></details>

Done.

---

*[docs/volumes.md, line 406 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9bosi4DiRfKqJPsOF:-Kn9kebc0hkPw7I5vnye:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L406)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Virtlet supports the standard `volumeMounts` notation for placing ConfigMap and Secret content into the VM filesystem.
</blockquote></details>

Done.

---

*[docs/volumes.md, line 413 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9c_0dia6NoJ_aqzUE:-Kn9kvKIS_vcyyaGJzCB:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L413)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Virtlet only handles files in the top level directory for each Secret/ConfigMap `VolumeMounts` entry. This limitation is to be lifted soon.
</blockquote></details>

Done.

---

*[docs/volumes.md, line 415 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9cqQq21483UeB7Vnq:-Kn9kvjsDHCbPDNyIfLI:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L415)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Consuming a ConfigMap using Kubernetes volume
</blockquote></details>

Done.

---

*[docs/volumes.md, line 418 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9eKkV4c9X1Cu1Qq1U:-Kn9kw7FV47_JM4RSfqy:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L418)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

See [the following example] that demonstrates how to pass ConfigMap data to a VM.
</blockquote></details>

Done.

---

*[docs/volumes.md, line 420 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9d4uJ2h2q5KXfTULZ:-Kn9kwT6LC6qEK79v9YL:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L420)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

ConfigMap volume demo
</blockquote></details>

Done.

---

*[docs/volumes.md, line 422 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9czLZZ3iIyVLPt51l:-Kn9kwmNj0RjbPhVG1Sk:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L422)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Consuming a Secret using Kubernetes volume
</blockquote></details>

Done.

---

*[docs/volumes.md, line 426 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9hbBmG-bNz1ASoutJ:-Kn9kxpYx44o8YcShD4X:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L426)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Secrets can be consumed in the same manner as ConfigMaps, see [the example] in kubernetes documentation.
</blockquote></details>

Done.

---

*[docs/volumes.md, line 428 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/333#-Kn9hrgdabKm02CebxAF:-Kn9kyFMv5naA0n9Ueds:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d1ba35634b211ef86ae753139049346120cbd341/docs/volumes.md#L428)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Like any other pod, Virtlet VM pods have predefined secret with Kubernetes API access token which is written into `/var/run/secrets/kubernetes.io/serviceaccount` directory.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/333)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/333#-:-KnAQrl3ujufe5q3xKuI:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/333)*

**Pull request merged**
