### PR TITLE
Use vfio-pci instead of pci-assign for SR-IOV devices.

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/656)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---

*[images/image_skel/libvirt.sh, line 22 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/656#-LAMXTru2fZjheVWBgN6:-LAMXTru2fZjheVWBgN7:bkrnlcv) ([raw file](https://github.com/mirantis/virtlet/blob/64b355016f432a010ef2218548cad8e81a89c0ba/images/image_skel/libvirt.sh#L22)):*
> ```Shell
>     ls -l /sys/class/net/*/device/iommu_group | sed -e "s/.*\//    \"\/dev\/vfio\//" -e "s/\$/\",/"
>     tail -n +$((marker_line+1)) /etc/libvirt/qemu.conf.tmpl
>   } >/etc/libvirt/qemu.conf
> ```

just use `# @DEVS@` in `qemu.conf` instead of using the template file and marker line
then just
```
files=$(ls /sys/class/net/*/device/iommu_group | sed 's@\(.*\)@/dev/vfio/\1,@')
sed -i "s/.*\(# @DEVS@\)/${files} /dev/vfio/vfio \1/" /etc/libvirt/qemu.conf
```
pls verify if it works this way, it would be simpler

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/656)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 10 of 12 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/656#-:-LANHZAj3Ryt0ofaZMon:bnfp4nl)*

**Comment by pigmej** [comment]
Reviewed 10 of 12 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/656)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/656#-:-LAOAY2hDdISgwztdmcr:bnfp4nl)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://beta.reviewable.io/reviews/mirantis/virtlet/656#-LAOB-Uy1fnS7iIghpG1:-LAOB-Uy1fnS7iIghpG2:blzhxrh) (no related file):*
Seems that there is some error during e2e, removing my lgtm

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/656)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/656#-:-LAObCUtBYQfiDx980kt:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/656#-:-LAOdNBz0XJo_qsiipkF:bnfp4nl)*

**Pull request merged**
