### PR TITLE
docs: Document cmd.sh usage

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/220)

### CODE REVIEW

**Comment by vefimova** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[docs/devel/build_tool.md, line 15 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgVVenz8-6fvv5GCii:-KfgVVeoyu2sHoTc0Eye:b-vvqsq9) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L15)):*
> ```Markdown
>  * `./build/cmd.sh gobuild [BUILD_ARGS...]`
>  * `./build/cmd.sh run CMD...`
> ```

For build, test, gotest, gobuild, run commands, probably need to mention that in case of build image is not available, it will build it.

---

*[docs/devel/build_tool.md, line 18 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgLK91nrndwSFRSIX-:-KfgLK91nrndwSFRSIX0:b-xvxxpz) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L18)):*
> ```Markdown
> ## build
> 
> Performs full build based on autotools.
> ```

I would add here, that on each run it copies the content of local virtlet dir inside container and so build includes latest local changes.

---

*[docs/devel/build_tool.md, line 23 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgLgsk_nPRKFlRi8XJ:-KfgLgsk_nPRKFlRi8XK:b-9hvmkr) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L23)):*
> ```Markdown
> 
> Runs tests on libvirt/qemu with KVM disabled - suitable for CI on platforms
> (like Travis) not supporting kernel virtualization.
> ```

Probably it's worth to mention, that tests are run inside build container and that before tests run local virtlet content is copied and full build based on auto tools is performed (it is called inside virtlet/build/do-test.sh).

---

*[docs/devel/build_tool.md, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgTh0T7lknKfshG9QX:-KfgTh0UMQ5P3HrMGCk3:b-spqmwy) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L41)):*
> ```Markdown
> ## gotest
> 
> Runs unit tests suite in build container - suitable for connecting with IDE.
> ```

Also would add here, that on each run it copies the content of local virtlet dir inside container.

---

*[docs/devel/build_tool.md, line 43 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgTt4Pbac_adi7pbFd:-KfgTt4Pbac_adi7pbFe:b2nreh6) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L43)):*
> ```Markdown
> Runs unit tests suite in build container - suitable for connecting with IDE.
> 
> ## gobuild
> ```

Same as above.

---

*[docs/devel/build_tool.md, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgURKpCha6CBiefwA_:-KfgURKqcfmgfkQd8lgh:b2nreh6) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L50)):*
> ```Markdown
> 
> ## run
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/220)*

**Comment by jellonek** [comment]
All comments addressed.

---

Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/devel/build_tool.md, line 15 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgVVenz8-6fvv5GCii:-KfgivooVeEECpfZVqDf:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L15)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

For build, test, gotest, gobuild, run commands, probably need to mention that in case of build image is not available, it will build it.
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 18 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgLK91nrndwSFRSIX-:-KfgiwIJnaNzZL8Ygm-P:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L18)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

I would add here, that on each run it copies the content of local virtlet dir inside container and so build includes latest local changes.
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 23 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgLgsk_nPRKFlRi8XJ:-KfgiwZqUXXjgM2mMy7j:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L23)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Probably it's worth to mention, that tests are run inside build container and that before tests run local virtlet content is copied and full build based on auto tools is performed (it is called inside virtlet/build/do-test.sh).
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgTh0T7lknKfshG9QX:-KfgiwtrTJjoYIXw8B8t:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L41)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Also would add here, that on each run it copies the content of local virtlet dir inside container.
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgURKpCha6CBiefwA_:-KfgixJoLiN0QJB1wiD0:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L50)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/220#-:-KfgirogWE5qpCG4rau-:b1ki02r)*

**Comment by ivan4th** [comment]
Review status: 1 of 2 files reviewed at latest revision, 14 unresolved discussions.

---

*[docs/devel/build_tool.md, line 18 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgLK91nrndwSFRSIX-:-KfgknKBKyF_QAe5wQ5p:b9ftt0k) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L18)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

based on -> using

---

*[docs/devel/build_tool.md, line 23 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgLgsk_nPRKFlRi8XJ:-Kfgks91kHBgrAJ-HZ2T:bg4nild) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L23)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

move (like Travis) to the end of the sentence

---

*[docs/devel/build_tool.md, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgTh0T7lknKfshG9QX:-KfglMJzNag-bEl_tOZ8:b38l6pi) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L41)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

suitable for use with IDEs/editors

---

*[docs/devel/build_tool.md, line 3 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgjZpD5HoSz5qRtyEt:-KfgjZpD5HoSz5qRtyEu:b-dap9qp) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L3)):*
> ```Markdown
> # build/cmd.sh usage
> 
> In general, `build/cmd.sh` script help automating usage of docker build
> ```

helps

Also, I'm not sure "In general, " is needed here ...

---

*[docs/devel/build_tool.md, line 6 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-Kfgje1nuaiLPfYao0b-:-Kfgje1nuaiLPfYao0b0:bzhy20v) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L6)):*
> ```Markdown
> container based on [Dockerfile.build](../../Dockerfile.build).
> 
> Currently it has this list of commands:
> ```

Currently the script supports the following commands:

---

*[docs/devel/build_tool.md, line 18 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-Kfgjjpq2Iryzh30_qZ5:-Kfgjjpq2Iryzh30_qZ6:b-c5fnuu) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L18)):*
> ```Markdown
> Each command of `build`, `test`, `run`, `gobuild`, `gotest` verifies if build
> container is available and if not - one will be build at command start. Each
> of them also copies local sources into build container at it's start.
> ```

`build`, `test`, `run`, `gobuild`, `gotest` commands check  whether the build container image and data volumes are available before proceeding. They build the image if necessary and create the data volumes if they don't exist, then copy the local sources into `virtlet_src` data volume.

---

*[docs/devel/build_tool.md, line 28 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgkvzlgCKLeZoHIFKq:-KfgkvzmlB-308wlo7Xc:b9ftt0k) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L28)):*
> ```Markdown
> Runs tests inside a build container on libvirt/qemu with KVM disabled - suitable
> for CI on platforms (like Travis) not supporting kernel virtualization.
> Tests run is preceded by full build based on autotools.
> ```

based on -> using

---

*[docs/devel/build_tool.md, line 37 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-Kfgl4AtPYeGZjjkybXw:-Kfgl4AtPYeGZjjkybXx:b-i1ez12) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L37)):*
> ```Markdown
> ## stop
> 
> Removes build container.
> ```

Removes the build container

---

*[docs/devel/build_tool.md, line 42 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-Kfgl6pgJCOC9aW5o_kq:-Kfgl6pgJCOC9aW5o_kr:beeqzb3) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L42)):*
> ```Markdown
> 
> Removes build container, it's image, it's volumes used during build process
> as also output binaries.
> ```

Removes the build container and image along with data volumes as well as the binaries in local `_output` directory.

---

*[docs/devel/build_tool.md, line 52 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfglUN1ukkKU9wSNIGM:-KfglUN2jIunSi7qdBtC:b-f5hq2q) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L52)):*
> ```Markdown
> Runs build process (assumes that there was called `build` command at last once
> from last time of change autotools configuration) of sources in build
> container - suitable as syntax check for IDE integration.
> ```

Runs `go build` in the build container. This command can be used for syntax checking in IDEs/editors. It assumes that `build` command was invoked at least once since the last `clean`.

---

*[docs/devel/build_tool.md, line 57 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-Kfgm0aogeVTzKzQBhGl:-Kfgm0aogeVTzKzQBhGm:b-ol5iu7) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L57)):*
> ```Markdown
> 
> Runs `CMD` inside a build container, suitable for checking it's internals
> during debug of build process session.
> ```

Runs the specified command inside the build container. This command can be used to debug the build scripts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/220)*

**Comment by jellonek** [comment]
Review status: 1 of 2 files reviewed at latest revision, 14 unresolved discussions.

---

*[docs/devel/build_tool.md, line 18 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgLK91nrndwSFRSIX-:-Kfk40NB9MdAV0BC3QR5:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L18)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

based on -> using
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 23 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgLgsk_nPRKFlRi8XJ:-Kfk40n4TtWCNflB_oAC:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L23)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

move (like Travis) to the end of the sentence
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgTh0T7lknKfshG9QX:-Kfk430HXkRDNodjYMlB:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L41)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

suitable for use with IDEs/editors
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 43 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgTt4Pbac_adi7pbFd:-Kfk47YzpTzis6iNjsU1:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L43)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 3 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgjZpD5HoSz5qRtyEt:-Kfk3yEeUIeGrF8TGFWz:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L3)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

helps

Also, I'm not sure "In general, " is needed here ...
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 6 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-Kfgje1nuaiLPfYao0b-:-Kfk3y0gHXvsr1ChKalB:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L6)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Currently the script supports the following commands:
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 18 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-Kfgjjpq2Iryzh30_qZ5:-Kfk468XP6in48br3pVp:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L18)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`build`, `test`, `run`, `gobuild`, `gotest` commands check  whether the build container image and data volumes are available before proceeding. They build the image if necessary and create the data volumes if they don't exist, then copy the local sources into `virtlet_src` data volume.
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 28 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgkvzlgCKLeZoHIFKq:-Kfk41FZww2EgL1GrF9-:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L28)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

based on -> using
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 37 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-Kfgl4AtPYeGZjjkybXw:-Kfk41qphqwHqbLX7adp:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L37)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Removes the build container
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 42 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-Kfgl6pgJCOC9aW5o_kq:-Kfk42OeJleqlGlWoRU3:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L42)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Removes the build container and image along with data volumes as well as the binaries in local `_output` directory.
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 52 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfglUN1ukkKU9wSNIGM:-Kfk43uliUV0DSlgnY6o:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L52)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Runs `go build` in the build container. This command can be used for syntax checking in IDEs/editors. It assumes that `build` command was invoked at least once since the last `clean`.
</blockquote></details>

Done.

---

*[docs/devel/build_tool.md, line 57 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/220#-Kfgm0aogeVTzKzQBhGl:-Kfk44jI4UltbIos6fAo:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2a163dc7d1300625d712063bcb5482c63074f791/docs/devel/build_tool.md#L57)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Runs the specified command inside the build container. This command can be used to debug the build scripts.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/220)*

**Comment by vefimova** [comment]
Review status: 1 of 2 files reviewed at latest revision, 16 unresolved discussions.

---

*[docs/devel/build_tool.md, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgTh0T7lknKfshG9QX:-KfklNBZ5PkJucfXbC7i:b82tpep) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L41)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

afis, Ivan also asked to s/connecting/use/

---

*[docs/devel/build_tool.md, line 19 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfkkoPsconauy_t2Zs7:-KfkkoPsconauy_t2Zs8:b-493t2m) ([raw file](https://github.com/mirantis/virtlet/blob/2628bba3b208b7fa9fc1df68a244ee59bfc593bd/docs/devel/build_tool.md#L19)):*
> ```Markdown
> the build container image and data volumes are available
> before proceeding. They build the image if necessary and create
> the data volumes if they don't exist, then copy the local sources
> ```

would still add "on each run they copy..." just to underline a bit.

---

*[docs/devel/build_tool.md, line 22 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfkiG0ursfrwJQYDnla:-KfkiA97oXIzVMN2WXiT:b-sqxubi) ([raw file](https://github.com/mirantis/virtlet/blob/2628bba3b208b7fa9fc1df68a244ee59bfc593bd/docs/devel/build_tool.md#L22)):*
> ```Markdown
> into `virtlet_src` data volume.
> 
> Each command of `build`, `test`, `run`, `gobuild`, `gotest` verifies if build
> ```

Looks like this paragraph is now redundant, and even lacks of some details comparing with above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/220)*

**Comment by vefimova** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/220)*

**Comment by jellonek** [comment]
Review status: 1 of 2 files reviewed at latest revision, 16 unresolved discussions.

---

*[docs/devel/build_tool.md, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfgTh0T7lknKfshG9QX:-KfkqdCRMeLni1nSVUxS:bjhrbs9) ([raw file](https://github.com/mirantis/virtlet/blob/ab7ea30d1b12f9801392cdfceef9d0ba58bb8a05/docs/devel/build_tool.md#L41)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

afis, Ivan also asked to s/connecting/use/
</blockquote></details>

Yes, updated.

---

*[docs/devel/build_tool.md, line 19 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfkkoPsconauy_t2Zs7:-KfkpyrobOYs-pCmMn-J:b-zegky9) ([raw file](https://github.com/mirantis/virtlet/blob/2628bba3b208b7fa9fc1df68a244ee59bfc593bd/docs/devel/build_tool.md#L19)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

would still add "on each run they copy..." just to underline a bit.
</blockquote></details>

Yeah, this seems to be more clear that way.

---

*[docs/devel/build_tool.md, line 22 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/220#-KfkiG0ursfrwJQYDnla:-KfkqTB6IEalpE3fr9-A:b-t0n3d0) ([raw file](https://github.com/mirantis/virtlet/blob/2628bba3b208b7fa9fc1df68a244ee59bfc593bd/docs/devel/build_tool.md#L22)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Looks like this paragraph is now redundant, and even lacks of some details comparing with above.
</blockquote></details>

Ough, leaved by mistake.
Now removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/220)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/220#-:-Kfkrp7Va9gve_sqqJsa:bnfp4nl)*

**Pull request merged**
