### PR TITLE
Added scripts for automated development of dev environment

### PR DESCRIPTION
**Pull request by vefimova**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/100)

### CODE REVIEW

**Comment by vefimova** [comment]
@ivan4th @jellonek 
Guys, updated PR, please, review and try it out.

**Comment by jellonek** [comment]
Will try this tomorrow.

**Comment by ivan4th** [comment]
Review status: 0 of 11 files reviewed at latest revision, 14 unresolved discussions.

---

*[contrib/cluster/lxc_utils.sh, line 3 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc3QDsmWDUfKWsoQrP:-KWc3QDsmWDUfKWsoQrQ:bqgl1k8) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> set -o errexit
> ```

I'd suggest using `set -o nounset` (-u), too. 

---

*[contrib/cluster/lxc_utils.sh, line 65 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcCMdig6QaJnLAzPGe:-KWcCMdig6QaJnLAzPGf:b-c218ku) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L65)):*
> ```Shell
> "
> 
>     lxc-attach -n $1  -- sudo /bin/bash -c "echo \"$cmd\" > ${BASE_IMAGE_WORK_DIR}/start_master.sh"
> ```

can't you kust do ```lxc-attach -n $1  -- sudo /bin/bash -c "${BASE_IMAGE_WORK_DIR}/start_master.sh" <<EOF
... $cmd content goes here ...
EOF
?

---

*[contrib/cluster/lxc_utils.sh, line 90 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc25JKaGPFBtP-Xq9h:-KWc25JKaGPFBtP-Xq9i:b-3ispgt) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L90)):*
> ```Shell
> }
> 
> function setup_minion() {
> ```

minion is considered obsolete term, maybe 'node' is better?

---

*[contrib/cluster/lxc_utils.sh, line 105 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcEBw2xwwxNhQbUJKK:-KWcEBw2xwwxNhQbUJKL:b-pnrqyq) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L105)):*
> ```Shell
> ${BASE_IMAGE_WORK_DIR}/kube-proxy ${PROXY_OPTS} > /var/log/kube-proxy.log 2>&1 &
> "
>     lxc-attach -n $1  --  sudo /bin/bash -c "echo \"$cmd\" > ${BASE_IMAGE_WORK_DIR}/start_minion.sh"
> ```

can't you kust do ```lxc-attach -n $1  -- sudo /bin/bash -c "${BASE_IMAGE_WORK_DIR}/start_minion.sh" <<EOF
... $cmd content goes here ...
EOF
?

---

*[contrib/cluster/lxc_utils.sh, line 112 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc2Uwwj8pHkaeW5zhn:-KWc2Uwwj8pHkaeW5zho:bapiq07) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L112)):*
> ```Shell
> 
> function create-update-base-container() {
>     if [ -z "`lxc-ls | grep ${BASE_CONTAINER_NAME}`" ]; then
> ```

`if lxc-ls | grep -q ${BASE_CONTAINER_NAME}; then` maybe?

---

*[contrib/cluster/lxc_utils.sh, line 133 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcDjSVfwf4KS4D7Ddv:-KWcDjSVfwf4KS4D7Ddw:bv3rxx2) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L133)):*
> ```Shell
>     fi
> 
>     #Update directory content
> ```

Sorry for such nitpicking, but maybe `# Update ...` (with space after `#`) would look better?

---

*[contrib/cluster/lxc_utils.sh, line 144 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcDrzaGpQ8uwMS20pA:-KWcDrzaGpQ8uwMS20pB:b-keh3v6) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L144)):*
> ```Shell
>     cp -rf ./k8s_master_pods ${container_dir}
> 
>     #Prepare virtlet images and docker-cimpose yaml
> ```

Same as above re space after `#`

---

*[contrib/cluster/lxc_utils.sh, line 173 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcDZhPs3Qinfi-Kg-F:-KWcDZhPs3Qinfi-Kg-G:bbr8saz) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L173)):*
> ```Shell
>     if [ -f "./${VIRTLET_IMAGE_NAME}.tar" ]; then
>        rm "./${VIRTLET_IMAGE_NAME}.tar"
>     fi
> ```

`rm -f ./${VIRTLET_IMAGE_NAME}.tar` - it'll be silent if the file doesn't exist

---

*[contrib/cluster/lxc_utils.sh, line 177 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcDdrE3hwNDubYYgBK:-KWcDdrE3hwNDubYYgBL:b-7x8419) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L177)):*
> ```Shell
>     if [ -f "./${LIBVIRT_IMAGE_NAME}.tar" ]; then
>        rm "./${LIBVIRT_IMAGE_NAME}.tar"
>     fi
> ```

same as above (`rm -f`)

---

*[contrib/cluster/README.md, line 14 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc9RiZM3_jX3HoF7cV:-KWc9RiZM3_jX3HoF7cW:b8ckqrn) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/README.md#L14)):*
> ```Markdown
> /etc/init.d/apparmor stop
> /etc/init.d/apparmor teardown
> ```sh
> ```

This seems to be a mistake. I see a lot of these in rendered README.md here: https://github.com/vefimova/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/README.md
And overall README formatting is broken

---

*[contrib/cluster/README.md, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcAjJogzq-mEDdfQoP:-KWcAjJogzq-mEDdfQoQ:bb18zqu) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/README.md#L50)):*
> ```Markdown
> * Start cluster, 
> ```sh
> ./lxc_utils.sh up
> ```

This died with the following error:
```Update pods yamls
./lxc_utils.sh: line 153: ./k8s_master_pods/kube-apiserver.yaml: No such file or directory```

Trying it on Xenial
```


---

*[contrib/cluster/setup_base_container.sh, line 22 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcDMkFeL1edFTVuA-j:-KWcDMkGEil_nCK4rSrb:bpxmidj) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/setup_base_container.sh#L22)):*
> ```Shell
> set +e
> docker ps 2> /dev/null 1> /dev/null
> if [ "$?" != "0" ]; then
> ```

`if !docker ps >& /dev/null; then` maybe?

---

*[contrib/cluster/setup_base_container.sh, line 32 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc50zWbuEiDijdAL6h:-KWc50zWbuEiDijdAL6i:b-sjk78d) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/setup_base_container.sh#L32)):*
> ```Shell
> sudo chmod +x /usr/local/bin/docker-compose
> docker-compose -v 2> /dev/null 1> /dev/null
> if [ "$?" != "0" ]; then
> ```

`[ $? -ne 0 ]` maybe?

---

*[contrib/cluster/setup_base_container.sh, line 37 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc4o0F2DcjSozs67BC:-KWc4o0HXyuGq3a6P73E:bi40o67) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/setup_base_container.sh#L37)):*
> ```Shell
> fi
> 
> sudo chown root:root /dev/kvm
> ```

This may break stuff some machines, e.g. on a lab we use:
```
$ ls -l /dev/kvm
crw-rw---- 1 root kvm 10, 232 Nov 11 11:42 /dev/kvm
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/100)*

**Comment by pigmej** [comment]
Review status: 0 of 11 files reviewed at latest revision, 14 unresolved discussions.

---

*[contrib/cluster/lxc_utils.sh, line 90 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc25JKaGPFBtP-Xq9h:-KWcJ8J5VxDTR_-BI5Eb:b-8fx2u7) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L90)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> minion is considered obsolete term, maybe 'node' is better?
</details>
:+1: 

---

*[contrib/cluster/lxc_utils.sh, line 133 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcDjSVfwf4KS4D7Ddv:-KWcJE_l3npwjPslcfy-:bb6mt9b) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L133)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> Sorry for such nitpicking, but maybe `# Update ...` (with space after `#`) would look better?
</details>
:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/100)*

**Comment by ivan4th** [comment]
Review status: 0 of 11 files reviewed at latest revision, 15 unresolved discussions.

---

*[contrib/cluster/lxc_utils.sh, line 139 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcKDeFYRBAB7t2FX2X:-KWcKDeFYRBAB7t2FX2Y:bqewoir) ([raw file](https://github.com/mirantis/virtlet/blob/b9f1b27db648bdce8e4664a8e5e0e511d51214aa/contrib/cluster/lxc_utils.sh#L139)):*
> ```Shell
>     echo_green "Create new container virtlet dir and fill it with k8s and virtlet images"
>     mkdir ${container_dir}
>     cp -f ${K8S_OUTPUT_DIR}/kube-*.tar ${container_dir}
> ```

I'd suggest checking that these files exist beforehand and displaying a nicer message asking the user to build k8s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/100)*

**Comment by ivan4th** [comment]
Review status: 0 of 11 files reviewed at latest revision, 16 unresolved discussions.

---

*[contrib/cluster/lxc_utils.sh, line 7 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcOgY3I4vF7lzLbF-v:-KWcOgY3I4vF7lzLbF-w:b-g9f2ek) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L7)):*
> ```Shell
> LXC_PATH="/var/lib/lxc/"
> 
> K8S_OUTPUT_DIR=${K8S_OUTPUT_DIR:-$GOPATH/src/k8s.io/kubernetes/_output/release-stage/server/linux-amd64/kubernetes/server/bin}
> ```

A note for future: requiring even `make quick-release` is not very good, as it's very slow. It would be better to use e.g. hyperkube image, or, even better, a custom image that can be build even faster, along the lines of https://github.com/sttts/kubernetes-dind-cluster/tree/master/image or https://github.com/Mirantis/kubeadm-dind-cluster/tree/master/image/hypokube

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/100)*

**Comment by vefimova** [comment]
Review status: 0 of 11 files reviewed at latest revision, 15 unresolved discussions.

---

*[contrib/cluster/lxc_utils.sh, line 3 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc3QDsmWDUfKWsoQrP:-KWcMmWTR00ZdKnzxYcd:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L3)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> I'd suggest using `set -o nounset` (-u), too. 
</details>
Done.

---

*[contrib/cluster/lxc_utils.sh, line 65 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcCMdig6QaJnLAzPGe:-KWcL6nVfdaxVSZqBRJY:b-r3k161) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L65)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> can't you kust do ```lxc-attach -n $1  -- sudo /bin/bash -c "${BASE_IMAGE_WORK_DIR}/start_master.sh" <<EOF
> ... $cmd content goes here ...
> EOF
> ?
</details>
I wish I could, I did it that way at first) But EOF doesn't work with lxc-attach, I mean smth breaks in formatting and it retruns "file does not exist or not find'.

---

*[contrib/cluster/lxc_utils.sh, line 90 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc25JKaGPFBtP-Xq9h:-KWcMltveEI-i-7_rIqz:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L90)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary>
> :+1: 
</details>
Done.

---

*[contrib/cluster/lxc_utils.sh, line 112 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc2Uwwj8pHkaeW5zhn:-KWcQT-ZPXONfL6uNkKb:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L112)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> `if lxc-ls | grep -q ${BASE_CONTAINER_NAME}; then` maybe?
</details>
Done.

---

*[contrib/cluster/lxc_utils.sh, line 133 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcDjSVfwf4KS4D7Ddv:-KWcQayw7qPVf6yFhBI7:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L133)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary>
> :+1:
</details>
Done.

---

*[contrib/cluster/lxc_utils.sh, line 144 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcDrzaGpQ8uwMS20pA:-KWcQm4BuQ8seU1JKtXE:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L144)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> Same as above re space after `#`
</details>
Done.

---

*[contrib/cluster/lxc_utils.sh, line 173 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcDZhPs3Qinfi-Kg-F:-KWcSA9E3FUYsfMvs9Kk:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L173)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> `rm -f ./${VIRTLET_IMAGE_NAME}.tar` - it'll be silent if the file doesn't exist
</details>
Done.

---

*[contrib/cluster/lxc_utils.sh, line 177 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcDdrE3hwNDubYYgBK:-KWcSAhlLi9SJIcRWGz6:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/lxc_utils.sh#L177)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> same as above (`rm -f`)
</details>
Done.

---

*[contrib/cluster/lxc_utils.sh, line 139 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWcKDeFYRBAB7t2FX2X:-KWcROZ6YoKcyylsWFpq:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/b9f1b27db648bdce8e4664a8e5e0e511d51214aa/contrib/cluster/lxc_utils.sh#L139)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> I'd suggest checking that these files exist beforehand and displaying a nicer message asking the user to build k8s
</details>
Done.

---

*[contrib/cluster/setup_base_container.sh, line 37 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/100#-KWc4o0F2DcjSozs67BC:-KWcUu0FRrN_G83KjnmB:b-l9hefi) ([raw file](https://github.com/mirantis/virtlet/blob/4965847906b78b6af168280141a6fb4bcf24d035/contrib/cluster/setup_base_container.sh#L37)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> This may break stuff some machines, e.g. on a lab we use:
> ```
> $ ls -l /dev/kvm
> crw-rw---- 1 root kvm 10, 232 Nov 11 11:42 /dev/kvm
> ```
</details>
Ok will check it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/100)*

**Pull request closed without merging**
