### PR TITLE
New metadata store

### PR DESCRIPTION
**Pull request by istalker2**
This PR introduces new metadata store which is heavily refactored
bolttools we used to have:

* No more per-field accessors. Instead the whole sandbox/container data
is accessed and stored as a single structure
* New simpler store APIs that allows to do CRUD with minimal number
  of functions making changes and yet safe for concurrent changes
* Similar and more universasl interfaces for both sandboxes and containers
* bolttools and metadata packages were merged together
* doc-strings and unit tests included

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/368)

### CODE REVIEW

**Comment by jellonek** [comment]
Almost perfect :)

---

Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/metadata/containers.go, line 125 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/368#-KpyNUezctoHaCEGBhuN:-KpyNUezctoHaCEGBhuO:b-onxxjl) ([raw file](https://github.com/mirantis/virtlet/blob/68f5b22274315683c1c127f87e2e7b34f9ea49c4/pkg/metadata/containers.go#L125)):*
> ```Go
> }
> 
> func removeContainerFrmSandbox(tx *bolt.Tx, containerID, sandboxID string) error {
> ```

Typo? Should be `From`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368#-:-KpyOqJ4coLmqwbMWan5:bkgkgy7)*

**Comment by istalker2** [comment]
Review status: 26 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/metadata/containers.go, line 125 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/368#-KpyNUezctoHaCEGBhuN:-KpyPZxa17J0ODn9p3QN:b-7ql1td) ([raw file](https://github.com/mirantis/virtlet/blob/68f5b22274315683c1c127f87e2e7b34f9ea49c4/pkg/metadata/containers.go#L125)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Typo? Should be `From`?
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368)*

**Comment by ivan4th** [comment]
I didn't dig too deep into BoltDB workings frankly, so... what's the advantage of having `sandboxes/` and `containers/` prefixes as opposed to having separate buckets for these and storing items in subbuckets? I think given the amount of data we have the speed difference is minimal, but maybe separate container bucket would make a code a bit simpler? (or quite likely I'm missing something)

---

Review status: 26 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368#-:-KpyPjhfHBhFbLyx_8cY:bgrag3w)*

**Comment by istalker2** [comment]
As for containers, all of them are stored in a bucket with static name "containers". containers/ prefixes are used for the keys in bod bucket to express collection of container IDs bound to the pod sandbox. It is possible to refactor them (and sandboxes/) into a nested bucket, but I find prefix approach a little bit easier because you don't need to create nested buckets and handle errors on each level. So it makes the code couple of lines shorter and simpler with exactly the same performance. Also it makes DB dumps look simpler because there is less nesting. But that's IMO. It is quite easy to change the code to nested buckets if this is important for you 

---

Review status: 26 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368#-:-KpyR2Q3g1Vgq9Vu6Lkx:byql9ge)*

**Comment by ivan4th** [comment]
No, nested buckets are not really important and what you wrote makes sense. Will review the PR in more detail a bit later today.

---

Review status: 26 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368#-:-KpyTkvd7FyhmeW_tUut:b-f5d509)*

**Comment by ivan4th** [comment]
`pkg/diskimage/guestfs/guestfs.go` - just reindent? If so, would you please make it a separate PR or commit because it makes the patch big.

`pkg/libvirttools/ceph_flexvolume.go`, `pkg/libvirtrools/libvirt_domain.go`, `pkg/virt/fake/fake_domain.go` - also just indent fixes, perhaps also should be another commit / PR (may just use `go fmt ...` on the files using a script and make a separate PR given that some indentation problems made it into our code)

`pkg/metadata/sendboxes_test.go` - typo in filename

---

Reviewed 18 of 33 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 455 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-njaTrrSLHhp91NwN:-Kq-njaTrrSLHhp91NwO:brzevf7) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/libvirttools/virtualization.go#L455)):*
> ```Go
> 			c.StartedAt = v.clock.Now().UnixNano()
> 			return c, nil
> 		})
> ```

:+1:  Great! Here you're also fixing non-atomic update issue.

---

*[pkg/libvirttools/virtualization.go, line 838 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-lnKLqEY1-53ZLT07:-Kq-lnKLqEY1-53ZLT08:bdq1dzt) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/libvirttools/virtualization.go#L838)):*
> ```Go
> 			return containers, nil
> 		} else if filter.PodSandboxId != "" {
> 			domainContainers, err := v.metadataStore.ListPodContainers(filter.PodSandboxId)
> ```

Thing is, there's currently just one "container" (VM) per pod and there are no plans to support more, as it's not possible to e.g. share a network ns between VMs. So maybe just `GetPodContainer` ?

---

*[pkg/metadata/containers_test.go, line 38 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-tz0cwyyCd306DM33:-Kq-tz0cwyyCd306DM34:b4qmjq7) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/containers_test.go#L38)):*
> ```Go
> 		}
> 
> 		if containerInfo.SandboxID != container.SandboxId {
> ```

Perhaps it's now possible to just use `reflect.DeepEqual()` to verify that `ContainerInfo` is stored as-is?

---

*[pkg/metadata/fake_client.go, line 60 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-pG7Ocqmj4Izrm74H:-Kq-pG7Ocqmj4Izrm74I:b1pkxza) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/fake_client.go#L60)):*
> ```Go
> 	err := db.View(func(tx *bolt.Tx) error {
> 		var iterateOverElements func(tx *bolt.Tx, bucket *bolt.Bucket, indent string)
> 		iterateOverElements = func(tx *bolt.Tx, bucket *bolt.Bucket, indent string) {
> ```

maybe just `iterateOverElements :=` ... ?

---

*[pkg/metadata/fake_client.go, line 72 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-pMGvL8X3L9nJkKFv:-Kq-pMGvL8X3L9nJkKFw:b-9wyezh) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/fake_client.go#L72)):*
> ```Go
> 					t.Logf(" %s BUCKET: %s", indent, string(k))
> 					if bucket == nil {
> 						//root bucket
> ```

need space after `//`

---

*[pkg/metadata/fake_client.go, line 104 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-pp0xsUtzqDsjNoOp:-Kq-pp0xsUtzqDsjNoOq:b-mpl2ri) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/fake_client.go#L104)):*
> ```Go
> 	}
> 
> 	clock := clockwork.NewRealClock()
> ```

it appears that you're populating `CreatedAt` etc. outside metadata code, so looks like there's no need to pass clock to metadata code at all, or do I miss something?

---

*[pkg/metadata/sandboxes.go, line 172 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-roJpiFIChCEQF_bO:-Kq-roJpiFIChCEQF_bP:b962dre) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/sandboxes.go#L172)):*
> ```Go
> 	if filterSelector != nil {
> 		filterSelector := filter.GetLabelSelector()
> 		if filterSelector != nil {
> ```

This code comes from original metadata code... But it doesn't make much sense, looks like there's unneeded check here

---

*[pkg/metadata/sendboxes_test.go, line 83 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-tRz9j-Qul-dWSnf4:-Kq-tRz9j-Qul-dWSnf5:bk3ab51) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/sendboxes_test.go#L83)):*
> ```Go
> }
> 
> func TestSetGetPodSandboxStatus(t *testing.T) {
> ```

It would be nice to add tests that check that Retrieve() gives the complete info that was originally stored. May use `reflect.DeepEqual` for checks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368#-:-Kq-jgiANNRv_fw52z8z:b-x6llp4)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/metadata/fake_client.go, line 60 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-pG7Ocqmj4Izrm74H:-Kq03BSjuAFpn_mfeddp:b32v57) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/fake_client.go#L60)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe just `iterateOverElements :=` ... ?
</blockquote></details>

+1

---

*[pkg/metadata/fake_client.go, line 95 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq03mVR5vf8fYG3Np-j:-Kq03mVR5vf8fYG3Np-k:b-z9zggg) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/fake_client.go#L95)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	//Check filter on empty DB
> ```

same as above, missing space after `//`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368)*

**Comment by istalker2** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/metadata/fake_client.go, line 60 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-pG7Ocqmj4Izrm74H:-Kq04vPlOXIyLEFPoUH3:bgygfqw) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/fake_client.go#L60)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

This just won't compile :) The thing here is that the lambda here recursively calls itself and in order for it to do so iterateOverElements variable has to be declared prior to the lambda body. This function was copied from old bolttools with little enhancements, so it's not my code :) 

---

*[pkg/metadata/fake_client.go, line 104 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-pp0xsUtzqDsjNoOp:-Kq05gugtI-srLM9bGSm:bw0zr8r) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/fake_client.go#L104)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

it appears that you're populating `CreatedAt` etc. outside metadata code, so looks like there's no need to pass clock to metadata code at all, or do I miss something?
</blockquote></details>

ContainerInfo is populated later in this function and thus it needs a clock. But I'm going to add clock to parameter list so that it would be possible to pass fake clock

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368)*

**Comment by istalker2** [comment]
Those unrelated changes are coming from the fact that current master doesn't pass gofmt check so several additional files were fixed by the IDE. I will split this PR in two. Btw, I'm wondering how could it happen? Don't we have CI that checks gofmt?

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368#-:-Kq063vdh-WxrotFJNIW:b-h3bzei)*

**Comment by istalker2** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 838 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-lnKLqEY1-53ZLT07:-Kq06Sk8EOFd3zxnlKbR:b3vj2tx) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/libvirttools/virtualization.go#L838)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Thing is, there's currently just one "container" (VM) per pod and there are no plans to support more, as it's not possible to e.g. share a network ns between VMs. So maybe just `GetPodContainer` ?
</blockquote></details>

I know. The reason I decided to go with the list is because it corresponds to k8s data model so with the list it is more error-prone. For example you can push and then pop a value to/from the list and it will remain the same, but if it would be just a single value all the time it will become corrupted. I'm sure k8s won't do such kind of things, but implementation may change over time. Also if we get pod with several containers it will leave a trace in DB. And who knows, maybe we'll find a way to have several VMs in one pod someday. There are clear business value in such feature if it could be implemented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368)*

**Comment by istalker2** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/metadata/containers_test.go, line 38 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-tz0cwyyCd306DM33:-Kq0B80MZUnnFQAjo1ai:bq978s) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/containers_test.go#L38)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Perhaps it's now possible to just use `reflect.DeepEqual()` to verify that `ContainerInfo` is stored as-is?
</blockquote></details>

Here container is of a type *criapi.ContainerTestonfig containerInfo is of *metadata.ContainerInfo. They are similar but not for DeepEqual 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368)*

**Comment by istalker2** [comment]
All acknowledged issues were addressed. PTAL

**Comment by ivan4th** [comment]
Reviewed 8 of 34 files at r1.
Review status: 22 of 27 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 838 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-lnKLqEY1-53ZLT07:-Kq27kjNAXa2voJN08b-:b-9eqoka) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/libvirttools/virtualization.go#L838)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

I know. The reason I decided to go with the list is because it corresponds to k8s data model so with the list it is more error-prone. For example you can push and then pop a value to/from the list and it will remain the same, but if it would be just a single value all the time it will become corrupted. I'm sure k8s won't do such kind of things, but implementation may change over time. Also if we get pod with several containers it will leave a trace in DB. And who knows, maybe we'll find a way to have several VMs in one pod someday. There are clear business value in such feature if it could be implemented.
</blockquote></details>

Ok, let's keep it this way then.

---

*[pkg/metadata/fake_client.go, line 60 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-pG7Ocqmj4Izrm74H:-Kq282wFxNG2IAKXIFe7:b-ixi310) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/fake_client.go#L60)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

This just won't compile :) The thing here is that the lambda here recursively calls itself and in order for it to do so iterateOverElements variable has to be declared prior to the lambda body. This function was copied from old bolttools with little enhancements, so it's not my code :) 
</blockquote></details>

ok, I see, sorry.

---

*[pkg/metadata/fake_client.go, line 104 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-pp0xsUtzqDsjNoOp:-Kq28kXRdsQFxUNOMJYp:b-uojrvt) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/fake_client.go#L104)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

ContainerInfo is populated later in this function and thus it needs a clock. But I'm going to add clock to parameter list so that it would be possible to pass fake clock
</blockquote></details>

Ok, actually I see that `NewPodSandboxInfo` uses the clock, so my complaint is not valid, sorry.

---

*[pkg/metadata/sandboxes_test.go, line 83 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-tRz9j-Qul-dWSnf4:-Kq296PoP-1Br9gX874E:b-ezowqx) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/sandboxes_test.go#L83)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

It would be nice to add tests that check that Retrieve() gives the complete info that was originally stored. May use `reflect.DeepEqual` for checks
</blockquote></details>

(ok, let's skip this for now)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 22 of 27 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368#-:-Kq29Fj8bsWEb203X-J5:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 2 of 34 files at r1, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/metadata/containers_test.go, line 38 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/368#-Kq-tz0cwyyCd306DM33:-Kq29Imty_IQIP_L3zfe:b2nhll9) ([raw file](https://github.com/mirantis/virtlet/blob/b1ac01efc7374d41d02fc8c0368d7aa5da073987/pkg/metadata/containers_test.go#L38)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

Here container is of a type *criapi.ContainerTestonfig containerInfo is of *metadata.ContainerInfo. They are similar but not for DeepEqual 
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/368#-:-Kq2J_m6Gova9uXlOr5J:bnfp4nl)*

**Pull request merged**
