### PR TITLE
Fix VF handling after virtlet restart while VMs are running

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/703)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 2 LGTMs obtained

---

*[pkg/nettools/nettools.go, line 388 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-eSwBAOpysFcbzAge:-LG-eSwBAOpysFcbzAgf:bt1u3hn) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/nettools/nettools.go#L388)):*
> ```Go
> 		// nil to slice
> 		// TODO: differentiate missing link from other possible errors
> 		link, _ := netlink.LinkByName(iface.Name)
> ```

I'd check for err anyway. Is it documented that LinkByName always returns nil in case of error and not some dummy link? Is it guaranteed to be so in future netlink library versions? I understand that this is unlikely, but still, it's better to be explicit here & follow the documented interface.

---

*[pkg/nettools/nettools.go, line 704 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-fKX98SH7ut2l-5C0:-LG-fKX98SH7ut2l-5C1:bd92gms) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/nettools/nettools.go#L704)):*
> ```Go
> 	for i, link := range contLinks {
> 		if link == nil {
> 			return nil, fmt.Errorf("have missing %d interface in list of container links what should be possible only during recovery after virtlet pod restart", i)
> ```

"missing link #%d in the container network namespace (Virtlet pod restarted?)"

---

*[pkg/tapmanager/tapfdsource.go, line 68 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-e8Q7-fEzyq0b0ptQ:-LG-e8Q7-fEzyq0b0ptR:b-vnlr6x) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L68)):*
> ```Go
> 
> // GetFDPayload contains the data that are required by TapFDSource
> // to create the tap device
> ```

a tap device

---

*[pkg/tapmanager/tapfdsource.go, line 71 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-dUUMBnHZWmPzdunI:-LG-dUUMBnHZWmPzdunJ:b-xj91sl) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L71)):*
> ```Go
> type GetFDPayload struct {
> 	// Description specifies pod network description for already
> 	// prepared network configuration
> ```

Description contains the pod information necessary to set up the tap device

---

*[pkg/tapmanager/tapfdsource.go, line 76 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-e7aj5BkICSgxiXsH:-LG-dKb86XBQbZmxyJZ8:b-vnlr6x) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L76)):*
> ```Go
> 
> // RecoverPayload contains the data that are required by TapFDSource
> // to recover the tap device that was already configured
> ```

a tap device

---

*[pkg/tapmanager/tapfdsource.go, line 79 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-dMZIBB_8GG8Pl3kz:-LG-dMZIBB_8GG8Pl3l-:bv6t8sc) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L79)):*
> ```Go
> type RecoverPayload struct {
> 	// Description specifies pod network description for already
> 	// prepared network configuration
> ```

Description contains the pod information necessary to recover the tap device

---

*[pkg/tapmanager/tapfdsource.go, line 86 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-eAQeDiXayH5EZ1aS:-LG-eAQeDiXayH5EZ1aT:b-4ibwb3) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L86)):*
> ```Go
> 	// HaveRunningContainers contains the information about running
> 	// containers (domains). If there is one - VF reconfiguration
> 	// has to be skipped.
> ```

HaveRunningContainers is true if any domains are currently running for this pod. VF reconfiguration is to be skipped if that's the case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/703)*

**Comment by jellonek** [comment]
Review status: 0 of 2 LGTMs obtained

---

*[pkg/nettools/nettools.go, line 704 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-fKX98SH7ut2l-5C0:-LG-okSM-9QlSzSx7hen:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/nettools/nettools.go#L704)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

"missing link #%d in the container network namespace (Virtlet pod restarted?)"
</blockquote></details>

Done.

---

*[pkg/tapmanager/tapfdsource.go, line 71 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-dUUMBnHZWmPzdunI:-LG-p3u778bzHGGYN5-d:bp0qtls) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L71)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Description contains the pod information necessary to set up the tap device
</blockquote></details>

It's not used only for setting up tap device. Btw. why there should be inconsistent use of "a tap device", and "the tap device" (above comment)?

---

*[pkg/tapmanager/tapfdsource.go, line 79 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-dMZIBB_8GG8Pl3kz:-LG-pdzv6NpUvVC-Qh7k:bribihm) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L79)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Description contains the pod information necessary to recover the tap device
</blockquote></details>

As above.

---

*[pkg/tapmanager/tapfdsource.go, line 86 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-eAQeDiXayH5EZ1aS:-LG-pchm2jbZzwwW1mL4:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L86)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

HaveRunningContainers is true if any domains are currently running for this pod. VF reconfiguration is to be skipped if that's the case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/703)*

**Comment by ivan4th** [comment]
Review status: 0 of 2 LGTMs obtained

---

*[pkg/tapmanager/tapfdsource.go, line 71 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-dUUMBnHZWmPzdunI:-LG-wJ_-9NzFCfcBV9e8:b-t2ta3v) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L71)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

It's not used only for setting up tap device. Btw. why there should be inconsistent use of "a tap device", and "the tap device" (above comment)?
</blockquote></details>

The above comment is about GetFDPayload being applicable to any tap device used by Virtlet, and the `Description` field concerns the concrete tap device this GetFDPayload instance is about. Can we change comment to "Description contains the pod information and DNS settings for the pod" maybe?

---

*[pkg/tapmanager/tapfdsource.go, line 79 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-dMZIBB_8GG8Pl3kz:-LG-wtrl84G53CD9ExYB:by9n9cy) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L79)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

As above.
</blockquote></details>

As above, too.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/703)*

**Comment by jellonek** [comment]
Review status: 0 of 2 LGTMs obtained

---

*[pkg/nettools/nettools.go, line 388 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-eSwBAOpysFcbzAge:-LG0-2nmBP7odb9pWSji:b-x0i3o3) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/nettools/nettools.go#L388)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'd check for err anyway. Is it documented that LinkByName always returns nil in case of error and not some dummy link? Is it guaranteed to be so in future netlink library versions? I understand that this is unlikely, but still, it's better to be explicit here & follow the documented interface.
</blockquote></details>

Documentation for that is ... I've read that part of netlink library quite a lot (and extended it already) and I'm sure that there would be a `nil` value in case of any error, but better would be to verify there error type, if it's `netlink.LinkNotFoundError` instance.
Also i've unexported this func as it's used only in this file.

---

*[pkg/tapmanager/tapfdsource.go, line 68 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-e8Q7-fEzyq0b0ptQ:-LG-zvIaCDTgNsMEmSCO:bee8yv8) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L68)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

a tap device
</blockquote></details>

I used there a more precise wording.

---

*[pkg/tapmanager/tapfdsource.go, line 71 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-dUUMBnHZWmPzdunI:-LG-zj-P0R_jsANItAwh:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L71)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

The above comment is about GetFDPayload being applicable to any tap device used by Virtlet, and the `Description` field concerns the concrete tap device this GetFDPayload instance is about. Can we change comment to "Description contains the pod information and DNS settings for the pod" maybe?
</blockquote></details>

Done.

---

*[pkg/tapmanager/tapfdsource.go, line 76 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-e7aj5BkICSgxiXsH:-LG-zm2i6fR4BsNZ1zsb:b-umo1b1) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L76)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

a tap device
</blockquote></details>

Used more precise wording (it's not only a tap device).

---

*[pkg/tapmanager/tapfdsource.go, line 79 at r1](https://reviewable.io/reviews/mirantis/virtlet/703#-LG-dMZIBB_8GG8Pl3kz:-LG-zsEa7YNfb8_FwPVE:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb87d68280e4e41fdbba0856b5e1e70c70ed5554/pkg/tapmanager/tapfdsource.go#L79)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

As above, too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/703)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/703#-:-LG4ZgBT2-Hdc34MJi10:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: 1 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/703#-:-LG9XyBn57CkiQbbUaPy:bnfp4nl)*

**Comment by leyao-daily** [comment]
So what should i do to solve:
 missing link #0 in the container network namespace (Virtlet pod restarted?)

**Pull request merged**
