### PR TITLE
Added e2e test and examples of definition VM-pod with rbd volume using PV/PVC

### PR DESCRIPTION
**Pull request by vefimova**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/316)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/e2e/e2e.sh, line 186 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/316#-KmCIfuJ-LtApKsSRRlj:-KmCIfuJ-LtApKsSRRlk:b32vin) ([raw file](https://github.com/mirantis/virtlet/blob/aade9206ca741a29779846719a4c2cf9dac65e12/tests/e2e/e2e.sh#L186)):*
> ```Shell
> 
> if ! kubectl exec "${virtlet_pod_name}" -c virtlet --namespace=kube-system -- /bin/sh -c "vncsnapshot :1 /domain_2.jpeg"; then
>   echo "Failed to attach and get screenshot for vnc console for domain with 2 id" >&2
> ```

:D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/316#-:-KmCIq3igf-e5tosyIQS:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/e2e/e2e.sh, line 145 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/316#-KmWzUgfWjSjO5IuseCw:-KmWzUgfWjSjO5IuseCx:b-ldw4is) ([raw file](https://github.com/mirantis/virtlet/blob/aade9206ca741a29779846719a4c2cf9dac65e12/tests/e2e/e2e.sh#L145)):*
> ```Shell
> "${SCRIPT_DIR}/run_ceph.sh" "${SCRIPT_DIR}"
> 
> # check rbd device attaching specified within pod
> ```

# check attaching RBD device that's specified in the pod definition

---

*[tests/e2e/e2e.sh, line 155 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/316#-KmWzLrgHd03PnVbY14Y:-KmWzLrgHd03PnVbY14Z:b-n8xhop) ([raw file](https://github.com/mirantis/virtlet/blob/aade9206ca741a29779846719a4c2cf9dac65e12/tests/e2e/e2e.sh#L155)):*
> ```Shell
> # check rbd device attaching specified using PV/PVC
> # tmp workaround: clear secret
> if ! kubectl exec "${virtlet_pod_name}" -c virtlet --namespace=kube-system -- /bin/sh -c "virsh secret-list | grep ceph | awk '{system(\"virsh secret-undefine \"\$1)}'"; then
> ```

why can't we do `"${virsh}" secret-list` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/316)*

**Comment by vefimova** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/e2e/e2e.sh, line 145 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/316#-KmWzUgfWjSjO5IuseCw:-KmbZRocJpwacmlkaP6k:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/aade9206ca741a29779846719a4c2cf9dac65e12/tests/e2e/e2e.sh#L145)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

# check attaching RBD device that's specified in the pod definition
</blockquote></details>

Done.

---

*[tests/e2e/e2e.sh, line 155 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/316#-KmWzLrgHd03PnVbY14Y:-KmbZmNluyZdpn9SF6J2:b-1ielhl) ([raw file](https://github.com/mirantis/virtlet/blob/aade9206ca741a29779846719a4c2cf9dac65e12/tests/e2e/e2e.sh#L155)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

why can't we do `"${virsh}" secret-list` here?
</blockquote></details>

ok, divided it into two.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/316)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/316#-:-Kmbj-eaLReFRE0uHnSJ:bnfp4nl)*

**Comment by pigmej** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/316)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/316#-:-KmbjQUnKRwFxKd9LJW6:bnfp4nl)*

**Pull request merged**
