### PR TITLE
Fix hung domains and other VM lifecycle edge cases

### PR DESCRIPTION
**Pull request by ivan4th**
Support `terminationGracePeriodSeconds` for VM pods.
Virtlet will try to wait for this number of seconds for VM
to shut down gracefully, then it will destroy the domain.
Update container statuses on `StartContainer()`/`StopContainer()`.
Wait for domain to become running in StartContainer().
Lessen the dependency on `ContainerStatus()`/`ListContainers()` call
sequence.
Add a comment on why we're removing the domain upon
failed `StartContainer()` call.
Add libvirttools test for hung domains.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/328)

### CODE REVIEW

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/328#-:-Kn4QXedxU0Z2LD67N42:bnfp4nl)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/libvirttools/virtualization.go, line 507 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/328#-Kn4fp_xEeA8rZnRAS24:-Kn4fp_ynrYLn1xOxCuK:bv2yg4y) ([raw file](https://github.com/mirantis/virtlet/blob/d3ee5ecc5840341e2ef73e8f7984a9fa9998c3d1/pkg/libvirttools/virtualization.go#L507)):*
> ```Go
> 	}
> 
> 	if err == nil {
> ```

Why next if, instead of using `else`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/328)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/libvirttools/virtualization.go, line 507 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/328#-Kn4fp_xEeA8rZnRAS24:-Kn4hPACjPW5hNrLusHy:b8w32v2) ([raw file](https://github.com/mirantis/virtlet/blob/d3ee5ecc5840341e2ef73e8f7984a9fa9998c3d1/pkg/libvirttools/virtualization.go#L507)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Why next if, instead of using `else`?
</blockquote></details>

Actually, in case if `err != nil` after the `WaitLoop()`, it may become nil if `domain.Destroy()` succeeds. `StopContainer()` is considered successful if it manages to kill the VM, even if it had to destroy the domain to do so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/328)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/libvirttools/virtualization.go, line 507 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/328#-Kn4fp_xEeA8rZnRAS24:-Kn4iIkH_XzjaGqp5SKz:b-98p4wy) ([raw file](https://github.com/mirantis/virtlet/blob/d3ee5ecc5840341e2ef73e8f7984a9fa9998c3d1/pkg/libvirttools/virtualization.go#L507)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Actually, in case if `err != nil` after the `WaitLoop()`, it may become nil if `domain.Destroy()` succeeds. `StopContainer()` is considered successful if it manages to kill the VM, even if it had to destroy the domain to do so.
</blockquote></details>

Yeah, right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/328#-:-Kn4invamhD6INtvtEO7:bnfp4nl)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/328#-:-Kn52GFiKZxQQnbkfBMx:bnfp4nl)*

**Pull request merged**
