### PR TITLE
tests: Use own cirros image in integration tests

### PR DESCRIPTION
**Pull request by jellonek**
TODO:
- [x] update image size in vars

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/397)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/integration/go.test, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/397#-Ksc5UrJJFHXe-Qufadu:-Ksc5UrJJFHXe-Qufadv:b-3qocj2) ([raw file](https://github.com/mirantis/virtlet/blob/70f5f29156d087a0e49a892d53e87c3b9dc99e39/tests/integration/go.test#L17)):*
> v0.8.2/cirros.img
It's master so we should be able to fetch from latest release, check https://github.com/Mirantis/virtlet/blob/master/deploy/demo.sh#L242 how the latest version could be fetched (would be way simpler if Virtlet would have releases not marked as pre-releases)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/397)*

**Comment by jellonek** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/integration/go.test, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/397#-Ksc5UrJJFHXe-Qufadu:-Ksc6d5yv1jnYLC-0n0Q:b-e1ujva) ([raw file](https://github.com/mirantis/virtlet/blob/70f5f29156d087a0e49a892d53e87c3b9dc99e39/tests/integration/go.test#L17)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> v0.8.2/cirros.img
It's master so we should be able to fetch from latest release, check https://github.com/Mirantis/virtlet/blob/master/deploy/demo.sh#L242 how the latest version could be fetched (would be way simpler if Virtlet would have releases not marked as pre-releases)
</blockquote></details>

I'm against automatic picking newest image. That could lead to situation when some patch worked correctly at some point of time, but later re-runned tests for it will fail, even if nothing in code was not changed.
Imo if image will be modified - it should be verified by human, and then, later - tests should be updated to use the new binary blob.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/397)*

**Comment by pigmej** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/integration/go.test, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/397#-Ksc5UrJJFHXe-Qufadu:-Ksc7thfYpuNjeG4B-KU:b-2v1r3i) ([raw file](https://github.com/mirantis/virtlet/blob/70f5f29156d087a0e49a892d53e87c3b9dc99e39/tests/integration/go.test#L17)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

I'm against automatic picking newest image. That could lead to situation when some patch worked correctly at some point of time, but later re-runned tests for it will fail, even if nothing in code was not changed.
Imo if image will be modified - it should be verified by human, and then, later - tests should be updated to use the new binary blob.
</blockquote></details>

What if we will add something to master and then build stuff? And the situation that you described is perfect situation, when your patch is failing with "master" then your patch needs to be updated BEFORE merge, with hardcoded image you will never know about that requirement, and we may accidentally merge broken code (because it was tested with different image than is in master).  It's exactly the same situation that is with k-d-c, we should be consistent I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/397)*

**Comment by jellonek** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/integration/go.test, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/397#-Ksc5UrJJFHXe-Qufadu:-KscFUuQb3FyfWN00BTl:b-u8psfc) ([raw file](https://github.com/mirantis/virtlet/blob/70f5f29156d087a0e49a892d53e87c3b9dc99e39/tests/integration/go.test#L17)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

What if we will add something to master and then build stuff? And the situation that you described is perfect situation, when your patch is failing with "master" then your patch needs to be updated BEFORE merge, with hardcoded image you will never know about that requirement, and we may accidentally merge broken code (because it was tested with different image than is in master).  It's exactly the same situation that is with k-d-c, we should be consistent I think.
</blockquote></details>

I don't get it.
How you want to add something to master? Without passing tests?
IMO there is no need to include this image in each release, so simply tests can point to v0.8.2 in which image was introduced (and pinned into release).
If you will want to update image, you will upload it into next-current release, and THEN update tests to use them.
Imo such scenario is quite simple.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/397)*

**Comment by pigmej** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/integration/go.test, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/397#-Ksc5UrJJFHXe-Qufadu:-KscKucQ5lfZmNz4QAIB:bws1brk) ([raw file](https://github.com/mirantis/virtlet/blob/70f5f29156d087a0e49a892d53e87c3b9dc99e39/tests/integration/go.test#L17)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

I don't get it.
How you want to add something to master? Without passing tests?
IMO there is no need to include this image in each release, so simply tests can point to v0.8.2 in which image was introduced (and pinned into release).
If you will want to update image, you will upload it into next-current release, and THEN update tests to use them.
Imo such scenario is quite simple.
</blockquote></details>

seems that we need basically separate versioned storage for binaries. Then problem would be solved. I'm ok with this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/397)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/397#-:-Ksr_hWyVAYeoMh_ox-i:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/397#-:-Ku3xr6JqVCB_0JlzmOq:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/397#-:-Ku46qySA280nYF6IRTf:bnfp4nl)*

**Pull request merged**
