### PR TITLE
Fix most of linter issues in pkg/cni/

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/601)

### CODE REVIEW

**Comment by jellonek** [comment]
Thing reported by codeclimate is not an error.

**Comment by pigmej** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cni/configuration.go, line 45 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/601#-L6wb4lXb0UiogIqlP9y:-L6wb4lXb0UiogIqlP9z:b7ti5z7) ([raw file](https://github.com/mirantis/virtlet/blob/0001ca119a3eb8b52d3e256d18564e26d30c54a9/pkg/cni/configuration.go#L45)):*
> ```Go
> 
> // ReadConfiguration given a path to directory with CNI configs iterates over
> // config files and returns first configuration with non empty Plugins list.
> ```

Maybe: `ReadConfiguration iterates over CNI config files in a directory and returns first configraution with non empty Plugins list` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/601)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cni/configuration.go, line 45 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/601#-L6wb4lXb0UiogIqlP9y:-L6wj4vXRym_Q3HB5C8o:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/0001ca119a3eb8b52d3e256d18564e26d30c54a9/pkg/cni/configuration.go#L45)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

Maybe: `ReadConfiguration iterates over CNI config files in a directory and returns first configraution with non empty Plugins list` ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/601)*

**Comment by lukaszo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cni/client.go, line 114 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/601#-L746VV-tmXI_yp9tfuh:-L746VV0uB-cECaCf7w_:bpcpd8) ([raw file](https://github.com/mirantis/virtlet/blob/328b085da1332abaaac632b65ab724895340dc74/pkg/cni/client.go#L114)):*
> ```Go
> }
> 
> type realclient struct {
> ```

I think this should be uppercase `realClient` and all "realclients" bellow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/601)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cni/client.go, line 114 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/601#-L746VV-tmXI_yp9tfuh:-L74KkLO9jwjtqERz74t:b-p3q3x3) ([raw file](https://github.com/mirantis/virtlet/blob/328b085da1332abaaac632b65ab724895340dc74/pkg/cni/client.go#L114)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

I think this should be uppercase `realClient` and all "realclients" bellow
</blockquote></details>

Yeah, good catch! Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/601)*

**Pull request merged**
