### PR TITLE
Support passing MTU through CloudInit

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/558)

### CODE REVIEW

**Comment by jellonek** [comment]
Ready to review, all tests are again green.

**Comment by ivan4th** [comment]
Reviewed 3 of 23 files at r1.
Review status: 3 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/libvirttools/cloudinit.go, line 162 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/558#-L3U2KKejgKC0Hm8iywl:-L3U2KKfEryTpgcDG2QP:bcdyyci) ([raw file](https://github.com/mirantis/virtlet/blob/6241584f0a9c43551e45bc4500fc15d38a749c4b/pkg/libvirttools/cloudinit.go#L162)):*
> ```Go
> 		subnets, curGateways := g.getSubnetsAndGatewaysForNthInterface(i, cniResult)
> 		gateways = append(gateways, curGateways...)
> 		mtu, err := mtuForParticularMac(iface.Mac, g.config.ContainerSideNetwork.Interfaces)
> ```

maybe `mtuForMacAddress`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/558)*

**Comment by jellonek** [comment]
Review status: 2 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/cloudinit.go, line 162 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/558#-L3U2KKejgKC0Hm8iywl:-L3XQgeMzPTF5FItUB27:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/6241584f0a9c43551e45bc4500fc15d38a749c4b/pkg/libvirttools/cloudinit.go#L162)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe `mtuForMacAddress`?
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 726 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/558#-L3U3HQSJyF1U1pykf9a:-L3XQh9ZrElcu8Vn3IT_:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/6241584f0a9c43551e45bc4500fc15d38a749c4b/pkg/nettools/nettools.go#L726)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`wrong CNI configuration: no interfaces defined: %s`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/558)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 19 of 23 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/558#-:-L3bh5OSKsBRHHNmXAGW:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Reviewed 21 of 23 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/558#-:-L3c3bDboYa0Jbwytxfe:bnfp4nl)*

**Pull request merged**
