### PR TITLE
Fix issues in diskimage package pointed by linter

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/599)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/599#-:-L6w_ty5NX8BjBVYPeF6:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/diskimage/diskimage_linux.go, line 40 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/599#-L6waDjhLf8b5tXJjctP:-L6waDjhLf8b5tXJjctQ:bgurmrx) ([raw file](https://github.com/mirantis/virtlet/blob/7bded8e16072da1d52e0c5bf3fd56d8c866ed58b/pkg/diskimage/diskimage_linux.go#L40)):*
> ```Go
> 
> // FormatDisk given a path will partition the image with MBR partition table
> // creating a single partition, then formatting it to ext4 filesystem.
> ```

FormatDisk partitions the specified image file by writing an MBR  with a single partition and then formatting that partition as an ext4 filesystem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/599)*

**Comment by jellonek** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/diskimage/diskimage_linux.go, line 40 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/599#-L6waDjhLf8b5tXJjctP:-L6whSUQs63Bdfrx6C8n:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7bded8e16072da1d52e0c5bf3fd56d8c866ed58b/pkg/diskimage/diskimage_linux.go#L40)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

FormatDisk partitions the specified image file by writing an MBR  with a single partition and then formatting that partition as an ext4 filesystem.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/599)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/599#-:-L6wi6n3R32pEraBbbTP:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/599)*

**Pull request merged**
