### PR TITLE
libvirttools: Pass network configuration through cloud-init

### PR DESCRIPTION
**Pull request by jellonek**
Network configuration prepared according to http://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html#network-config-v1
Can not be verified by cirros image (it simply do not uses nocloud network configuration).
Works best with CNI plugins which returns new type or [Result](https://github.com/containernetworking/cni/blob/master/SPEC.md#parameters) which contains list of interfaces (with their mac addresses).
Should work well with plugins returning multiple network addresses, even if we don't support yet that from interfaces passing level (vmwrapper passes only single interface) so it's ready for future.
Needs more testing in any way, manual, unittests, but probably using our own cirros image/ubuntu image.

TODO:
- [x] update tests
- [x] fix "legacy" interface

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/412)

### CODE REVIEW

**Comment by jellonek** [comment]
After adding fix in tapmanager - works also quite well with old style cni plugins, including that which we have in default dind setup.

**Comment by ivan4th** [comment]
BTW are there any docs on how to work with this? Maybe `docs/networking.md` needs to be updated?

---

Review status: 0 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[pkg/libvirttools/cloudinit.go, line 57 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku46qzzsMIucb77S0BY:-Ku46qzzsMIucb77S0BZ:b-i0me93) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/libvirttools/cloudinit.go#L57)):*
> ```Go
> 	return &CloudInitGenerator{
> 		config: config, podSandboxInfo: podSandboxInfo,
> 		volumeMap: volumeMap, isoDir: isoDir,
> ```

I think this should be made line-per-key

---

*[pkg/libvirttools/cloudinit.go, line 122 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku46x6MInS53vsCpqtn:-Ku46x6MInS53vsCpqto:bxg3kch) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/libvirttools/cloudinit.go#L122)):*
> ```Go
> 	if cniResult == nil {
> 		// That can only happen in integration tests where prepared
> 		// sandbox is quite dummy.
> ```

// This can only happen during integration tests where a dummy sandbox is used

---

*[pkg/libvirttools/cloudinit.go, line 171 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku47uAICW_--aOnn122:-Ku47uAICW_--aOnn123:bwx58j5) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/libvirttools/cloudinit.go#L171)):*
> ```Go
> 	// Cloud Init requires dns settings on subnet level (yeah, i know...)
> 	// while we have one same setting for each address from CNI, so as workaround
> 	// we are adding it to first subnet configuration if it's not dhcp
> ```

// Cloud Init requires dns settings on the subnet level (yeah, I know...) while we get just one setting for all the IP configurations from CNI, so as a workaround we're adding it to the first subnet configuration

---

*[pkg/libvirttools/cloudinit.go, line 179 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku47hcnSFFx7grni7mq:-Ku47hcovv6a8DqvcNM-:b-vlxk71) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/libvirttools/cloudinit.go#L179)):*
> ```Go
> 			subnets[0]["dns_search"] = cniResult.DNS.Search
> 		}
> 	}
> ```

I think this can be done in the loop above. Just do it for currently built subnet if `len(subnets) == 0`

---

*[pkg/libvirttools/cloudinit.go, line 181 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku49gnMbpDnxScglgcQ:-Ku49gnMbpDnxScglgcR:b-1ksk0e) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/libvirttools/cloudinit.go#L181)):*
> ```Go
> 	}
> 
> 	// TODO: parse cniResult.Routes and add them to correct subnet configuration
> ```

This is a serious limitation that needs to be documented...

---

*[pkg/tapmanager/tapfdsource.go, line 213 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku48qeu0KcttNtCahP0:-Ku48qeu0KcttNtCahP1:bfz21hb) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/tapmanager/tapfdsource.go#L213)):*
> ```Go
> func fixNetConfigForOldCNIPlugins(netConfig *cnicurrent.Result, csn *nettools.ContainerSideNetwork) {
> 	// If there is no info about interfaces, we can assume that this is
> 	// old style cni plugin, which operates on single interface, so there
> ```

which supports just one interface

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/412#-:-Ku49qwM2_MBrmIhdsXQ:b-ch32xv)*

**Comment by jellonek** [comment]
Review status: 0 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/libvirttools/cloudinit.go, line 57 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku46qzzsMIucb77S0BY:-KuKGDkdbioh9tJ5w9p9:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/libvirttools/cloudinit.go#L57)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I think this should be made line-per-key
</blockquote></details>

Done.

---

*[pkg/libvirttools/cloudinit.go, line 122 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku46x6MInS53vsCpqtn:-KuKGGerA9eFGEStP9BM:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/libvirttools/cloudinit.go#L122)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

// This can only happen during integration tests where a dummy sandbox is used
</blockquote></details>

Done.

---

*[pkg/libvirttools/cloudinit.go, line 171 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku47uAICW_--aOnn122:-KuKGHPKbdG24q2ntub7:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/libvirttools/cloudinit.go#L171)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

// Cloud Init requires dns settings on the subnet level (yeah, I know...) while we get just one setting for all the IP configurations from CNI, so as a workaround we're adding it to the first subnet configuration
</blockquote></details>

Done.

---

*[pkg/libvirttools/cloudinit.go, line 179 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku47hcnSFFx7grni7mq:-KuKGIpMiOSuraqj7Du3:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/libvirttools/cloudinit.go#L179)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I think this can be done in the loop above. Just do it for currently built subnet if `len(subnets) == 0`
</blockquote></details>

Done.

---

*[pkg/libvirttools/cloudinit.go, line 181 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku49gnMbpDnxScglgcQ:-KuKGJK6HIu8k-2CCijZ:bdw6so) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/libvirttools/cloudinit.go#L181)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

This is a serious limitation that needs to be documented...
</blockquote></details>

Will update the docs, also will try to do that better yet in same PR.

---

*[pkg/tapmanager/tapfdsource.go, line 213 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/412#-Ku48qeu0KcttNtCahP0:-KuKGXsQ9ZgtqhJS3Sle:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/0ece3e8240f715cfa604ccdb71f7f4562631b448/pkg/tapmanager/tapfdsource.go#L213)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

which supports just one interface
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/412)*

**Comment by ivan4th** [comment]
Reviewed 16 of 18 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/networking.md, line 52 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/412#-KuTgX7UcwIafnhcSIh2:-KuTgX7UcwIafnhcSIh3:b-qqyd1) ([raw file](https://github.com/mirantis/virtlet/blob/502d4695ac4c8f0d4cb293c0bb9413e0db297113/docs/networking.md#L52)):*
> ```Markdown
>    (see below for more details)
> 1. `tapmanager` returns to Virtlet prepared network configuration
>    which is then added to Cloud-Init data source
> ```

`tapmanager` returns network configuration info which is used by Virtlet to set up Cloud-Init network config

---

*[pkg/libvirttools/cloudinit_test.go, line 387 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/412#-KuTiVL_GEUliuurQJul:-KuTiVL_GEUliuurQJum:bw43gbn) ([raw file](https://github.com/mirantis/virtlet/blob/502d4695ac4c8f0d4cb293c0bb9413e0db297113/pkg/libvirttools/cloudinit_test.go#L387)):*
> ```Go
> 	if !reflect.DeepEqual(m, map[string]interface{}{
> 		"meta-data":      "{\"instance-id\":\"foo.default\",\"local-hostname\":\"foo\"}",
> 		"network-config": "version: 1\nconfig:\n- mac_address: \"00:11:22:33:44:55\"\n  name: cni0\n  subnets:\n  - address: 1.1.1.1/8\n    dns_nameservers:\n    - 1.2.3.4\n    dns_search:\n    - some\n    - search\n    gateway: 1.2.3.4\n    type: static\n  type: physical\n",
> ```

I think this check should be done via Golden master mechanism in a followup PR (ok for now though).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/412)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/412#-:-KuTmgxghWE2ZKou28z-:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 16 of 18 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/412#-:-KuU-H0xMbzu2r9p_I67:bnfp4nl)*

**Pull request merged**
