### PR TITLE
libvirttools: Add test for rootfs removal

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/363)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/libvirttools/virtualization_test.go, line 198 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/363#-KoJ5c5Ld9oq2inyT0nZ:-KoJ5c5MCufeKjjeJfLO:b-xtqnh4) ([raw file](https://github.com/mirantis/virtlet/blob/eca5c5c15ab3bef53ee6e85a39e1c7dacbd5ff0f/pkg/libvirttools/virtualization_test.go#L198)):*
> ```Go
> }
> 
> func (ct *containerTester) verifyContainerRootfsExistence(container *kubeapi.Container) bool {
> ```

`verifyContainerRootfsExists`

---

*[pkg/libvirttools/virtualization_test.go, line 205 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/363#-KoJ5llmXNWMGWcRptMV:-KoJ5llmXNWMGWcRptMW:b7ufttv) ([raw file](https://github.com/mirantis/virtlet/blob/eca5c5c15ab3bef53ee6e85a39e1c7dacbd5ff0f/pkg/libvirttools/virtualization_test.go#L205)):*
> ```Go
> 	// TODO: this is third place where rootfs volume name is calculated
> 	// so there should be a func which will do it in consistent way there,
> 	// in root_volumesource.go and in virtualization.go
> ```

I don't think we need a func that's shared between tests and the actual code for this. Having fully independent check in the tests is more bulletproof

---

*[pkg/libvirttools/virtualization_test.go, line 246 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/363#-KoJ6DpCpcM1LqSD2p6F:-KoJ6DpCpcM1LqSD2p6G:b-7xv3s7) ([raw file](https://github.com/mirantis/virtlet/blob/eca5c5c15ab3bef53ee6e85a39e1c7dacbd5ff0f/pkg/libvirttools/virtualization_test.go#L246)):*
> ```Go
> 	if container.Annotations["foo"] != "bar" {
> 		t.Errorf("Bad container annotation value: %q instead of %q", containers[0].Annotations["foo"], "bar")
> 	}
> ```

nice change! :+1: 

---

*[pkg/libvirttools/virtualization_test.go, line 286 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/363#-KoJ63kSg1CQVGweuEmI:-KoJ63kSg1CQVGweuEmJ:bm38w79) ([raw file](https://github.com/mirantis/virtlet/blob/eca5c5c15ab3bef53ee6e85a39e1c7dacbd5ff0f/pkg/libvirttools/virtualization_test.go#L286)):*
> ```Go
> 
> 	if ct.verifyContainerRootfsExistence(container) {
> 		t.Errorf("Unexpected remaining rootfs for container %#v", container)
> ```

Maybe "rootfs volume was not deleted for the container: %#v" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/363)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/libvirttools/virtualization_test.go, line 198 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/363#-KoJ5c5Ld9oq2inyT0nZ:-KoJBtPOZJBRoIUKT4cQ:bbh7oix) ([raw file](https://github.com/mirantis/virtlet/blob/eca5c5c15ab3bef53ee6e85a39e1c7dacbd5ff0f/pkg/libvirttools/virtualization_test.go#L198)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`verifyContainerRootfsExists`
</blockquote></details>

thx, spent some time on that how to name this func, but your version is better :)

---

*[pkg/libvirttools/virtualization_test.go, line 205 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/363#-KoJ5llmXNWMGWcRptMV:-KoJC3F-vcweL04bmfgJ:bqa7h1t) ([raw file](https://github.com/mirantis/virtlet/blob/eca5c5c15ab3bef53ee6e85a39e1c7dacbd5ff0f/pkg/libvirttools/virtualization_test.go#L205)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I don't think we need a func that's shared between tests and the actual code for this. Having fully independent check in the tests is more bulletproof
</blockquote></details>

Yeah, using that in tests is a minor thing, but imo in both other places this should be done by single mechanism.

---

*[pkg/libvirttools/virtualization_test.go, line 286 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/363#-KoJ63kSg1CQVGweuEmI:-KoJCMpisSrxeVdOwkua:bh9y1fh) ([raw file](https://github.com/mirantis/virtlet/blob/eca5c5c15ab3bef53ee6e85a39e1c7dacbd5ff0f/pkg/libvirttools/virtualization_test.go#L286)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Maybe "rootfs volume was not deleted for the container: %#v" ?
</blockquote></details>

Ok. Will do this change tomorrow morning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/363)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/libvirttools/virtualization_test.go, line 198 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/363#-KoJ5c5Ld9oq2inyT0nZ:-KoLugdCfoQBRU3k-HYt:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eca5c5c15ab3bef53ee6e85a39e1c7dacbd5ff0f/pkg/libvirttools/virtualization_test.go#L198)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

thx, spent some time on that how to name this func, but your version is better :)
</blockquote></details>

Done.

---

*[pkg/libvirttools/virtualization_test.go, line 286 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/363#-KoJ63kSg1CQVGweuEmI:-KoLui2rBnNuxZSXrYWc:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eca5c5c15ab3bef53ee6e85a39e1c7dacbd5ff0f/pkg/libvirttools/virtualization_test.go#L286)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Ok. Will do this change tomorrow morning.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/363)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/363#-:-KoSr5cw262UY1wkzhUH:bnfp4nl)*

**Pull request merged**
