### PR TITLE
New e2e test suite in golang

### PR DESCRIPTION
**Pull request by istalker2**
New e2e test suite in golang

* Pure golang
* Framework that allows remote execution of commands and other
  operations on DinD k8s node (i.e. what `docker exec` does),
  k8s pods (like `kubectl exec`) and created VMs (like vmssh.sh) without
  executing external apps
* ginkgo test framework drop-in replacement that extends the framework
  with ability to have BeforeAll/AfterAll methods that do setup/teardown
  for current context as a workaround for
  https://github.com/onsi/ginkgo/issues/70
* e2e suite is compiled into a standalone binary that has no system
  dependencies and can be run from outside of the cluster with
  virtlet deployed
* tests are performed in a temporary namespace that is deleted
  afterwards

Also, noticeably decrease project build time for subsequent builds
by adding `-i` flag to `go build`

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/390)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/e2e/framework/common.go, line 53 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/390#-Ks2hqEFuwsFpUZ-gP5-:-Ks2hqEFuwsFpUZ-gP50:bs4z4b4) ([raw file](https://github.com/mirantis/virtlet/blob/ae27d2dfe2640ceed90212434a3e15ba8ed610da/tests/e2e/framework/common.go#L53)):*
> ```Go
> 	if stderr != "" {
> 		return "", fmt.Errorf("stderr has errors: %s", stderr)
> 	}
> ```

If `stderr` output is collected after verifying that exit code is equal to zero - we can loose valuable (for debugging) error output. Looks like reverse order (test for stderr output, then for exit code) can be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/390)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/e2e/basic_test.go, line 76 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsA84FlausvbPewBZ9V:-KsA84FlausvbPewBZ9W:b-x9kayy) ([raw file](https://github.com/mirantis/virtlet/blob/ae27d2dfe2640ceed90212434a3e15ba8ed610da/tests/e2e/basic_test.go#L76)):*
> ```Go
> 		})
> 
> 		It("Check network interface", func(done Done) {
> ```

maybe tests should be renamed a bit to make the output more meaningful? It("...") means "verify that it ..." (does something). So if we're testing that foobar must be able to read a file, we should write `Context("foobar", func () { ... It ("should be able to read a file", ...`. See basic Ginkgo example here for instance: https://onsi.github.io/ginkgo/

---

*[tests/e2e/framework/common.go, line 65 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsA92pacu7BYZLhe39w:-KsA92pacu7BYZLhe39x:b-m9nh19) ([raw file](https://github.com/mirantis/virtlet/blob/ae27d2dfe2640ceed90212434a3e15ba8ed610da/tests/e2e/framework/common.go#L65)):*
> ```Go
> }
> 
> func waitState(f func() error, wait, poll time.Duration, waitFailure bool) error {
> ```

`waitForState` maybe? or just `waitFor` ?

---

*[tests/e2e/framework/common.go, line 93 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsA9QaVOGuPrg_YD3XP:-KsA9QaVOGuPrg_YD3XQ:bvlxz5n) ([raw file](https://github.com/mirantis/virtlet/blob/ae27d2dfe2640ceed90212434a3e15ba8ed610da/tests/e2e/framework/common.go#L93)):*
> ```Go
> }
> 
> func waitConsistentState(f func() error, timing ...time.Duration) error {
> ```

`waitForConsistentState`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/390)*

**Comment by istalker2** [comment]
A lot of changes from previous WiP-level PR. All shell e2e tests were migrated

**Comment by ivan4th** [comment]
Review status: 4 of 22 files reviewed at latest revision, 9 unresolved discussions.

---

*[tests/e2e/basic_test.go, line 59 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsOxSEA0ypNVPPghOX-:-KsOxSEA0ypNVPPghOX0:b8mouwd) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/basic_test.go#L59)):*
> ```Go
> 		scheduleWaitSSH(&vm, &ssh)
> 
> 		It("Should have default route", func() {
> ```

sorry for nitpicking, but perhaps the casing should be consistent (there's "Should" in some places and "should" in others -- with the latter perhaps being more suited for Ginkgo output)

---

*[tests/e2e/basic_test.go, line 137 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsOxtxWWnGlKnwzUAps:-KsOxtxWWnGlKnwzUApt:b63vui3) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/basic_test.go#L137)):*
> ```Go
> 					`cat "/var/log/virtlet/vms/%s/%s" | \
> 					grep "login as 'cirros' user. default password: 'cubswin:)'. use 'sudo' for root." | \
> 					wc -l`, sandboxID, filename))).To(Equal("1"))
> ```

Wouldn't it be a bit cleaner to just grab the content of the log file and use `strings.Count()` on it?

---

*[tests/e2e/basic_test.go, line 168 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsOyKXSR_z9Ld_40_ec:-KsOyKXSR_z9Ld_40_ed:b-dip2jy) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/basic_test.go#L168)):*
> ```Go
> 
> 		do(framework.ExecSimple(executor, "apt", "update"))
> 		do(framework.ExecSimple(executor, "apt", "install", "-y", "vncsnapshot"))
> ```

I think we should just install this `vncsnapshot` in `Dockerfile.build`, no need to do it during the test.

---

*[tests/e2e/ceph_test.go, line 227 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsOzi21FVl6zvy3K1w6:-KsOzi21FVl6zvy3K1w7:b-3dhlvk) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/ceph_test.go#L227)):*
> ```Go
> 		// Add rbd pool and volume
> 		`ceph osd pool create libvirt-pool 8 8`,
> 		`apt-get update && apt-get install -y qemu-utils 2> /dev/null`,
> ```

please add `qemu-utils` to `Dockerfile.build` instead of installing it during e2e (yes, it was using apt-get in e2e script before, but that's a hack)

---

*[tests/e2e/common.go, line 91 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsOyjn1Kz2-MVyY9Cqz:-KsOyjn1Kz2-MVyY9Cr-:bidhngq) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/common.go#L91)):*
> ```Go
> }
> 
> func do(value interface{}, extra ...interface{}) interface{} {
> ```

It would be nice to add a comment here describing what this func does.

---

*[tests/e2e/framework/controller.go, line 31 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsP0uNJHMlAyykRQXwt:-KsP0uNJHMlAyykRQXwu:b-gw7t88) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/framework/controller.go#L31)):*
> ```Go
> 	"k8s.io/client-go/tools/clientcmd"
> 
> 	// register standard k28 types
> ```

s/k28/k8s/

---

*[tests/e2e/ginkgo-ext/matchers.go, line 24 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsP-hUJG9uBa-QWWQY-:-KsP-hUJG9uBa-QWWQY0:br5opjw) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/ginkgo-ext/matchers.go#L24)):*
> ```Go
> 
> type anythingMatcher struct {
> }
> ```

empty structs usually are written as `type anythingMatcher struct {}` (single line)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/390)*

**Comment by istalker2** [comment]
Review status: 4 of 22 files reviewed at latest revision, 9 unresolved discussions.

---

*[tests/e2e/basic_test.go, line 168 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsOyKXSR_z9Ld_40_ec:-KsQZ7EONBAygJitFLsO:b-bqu8yz) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/basic_test.go#L168)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I think we should just install this `vncsnapshot` in `Dockerfile.build`, no need to do it during the test.
</blockquote></details>

here and above: probably you meant Dockerfile because Dockerfile.build because vncsnapshot need to be present in virtlet pod and not in the build container

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/390)*

**Comment by istalker2** [comment]
Review status: 4 of 22 files reviewed at latest revision, 9 unresolved discussions.

---

*[tests/e2e/ceph_test.go, line 227 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsOzi21FVl6zvy3K1w6:-KsS0A-WMLrJl9IeK7jv:bqs5l8l) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/ceph_test.go#L227)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

please add `qemu-utils` to `Dockerfile.build` instead of installing it during e2e (yes, it was using apt-get in e2e script before, but that's a hack)
</blockquote></details>

`quemu-img` is run in ceph container, which is based on `ceph/demo` image, which is not ours. So adding `qemu-utils` to it would mean to maintain our own derived docker image for the ceph just for this test. I don't think it worth it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/390)*

**Comment by istalker2** [comment]
PTAL

**Comment by istalker2** [comment]
CI is going to fail until we merge #396 because now e2e relies on vncsnapshot to be present in virtlet pod, but CI uses virtlet image from docker hub rather than build it from this commit. Thus changes to Dockerfile must be merged first

**Comment by pigmej** [comment]
> but CI uses virtlet image from docker hub rather than build it from this commit.  

That shouldn't be the case, if it is then it's probably broken because: https://github.com/Mirantis/virtlet/pull/386

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 3 of 15 files at r1, 7 of 19 files at r2, 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[tests/e2e/basic_test.go, line 168 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsOyKXSR_z9Ld_40_ec:-KsiD_B7c2UiEWqM3azB:b-68m2bv) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/basic_test.go#L168)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

here and above: probably you meant Dockerfile because Dockerfile.build because vncsnapshot need to be present in virtlet pod and not in the build container
</blockquote></details>

you're right, thanks.

---

*[tests/e2e/ceph_test.go, line 227 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsOzi21FVl6zvy3K1w6:-KsiDeXs_rHSJPc_U3bf:b-y7eihm) ([raw file](https://github.com/mirantis/virtlet/blob/d27269d5507e87ec4b185a306a6626481ec44772/tests/e2e/ceph_test.go#L227)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

`quemu-img` is run in ceph container, which is based on `ceph/demo` image, which is not ours. So adding `qemu-utils` to it would mean to maintain our own derived docker image for the ceph just for this test. I don't think it worth it
</blockquote></details>

ok then, sorry for misunderstanding, let's keep it as-is for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/390#-:-KsiDy1oc7vRc8eIpmDk:bnfp4nl)*

**Comment by jellonek** [comment]
With minor comment - :lgtm: 

---

Reviewed 7 of 19 files at r2, 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tests/e2e/ceph_test.go, line 226 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsiHcRKwMnuJnjdunf6:-KsiHcRKwMnuJnjdunf7:b-hzg562) ([raw file](https://github.com/mirantis/virtlet/blob/07bba083e72038973269db32cf1bf14df121ec7c/tests/e2e/ceph_test.go#L226)):*
> ```Go
> 	commands := []string{
> 		// Adjust ceph configs
> 		`echo -e "rbd default features = 1\nrbd default format = 2" >> /etc/ceph/ceph.conf`,
> ```

Usage of echo there to add something to file looks strange there. I know that this is simply the same what was in shell script, but later in time we can replace that with call to https://golang.org/pkg/io/ioutil/#WriteFile - for now i'm ok with current version. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/390#-:-KsiZMH9mQVfac3xQ29O:b9fm2io)*

**Comment by istalker2** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[tests/e2e/ceph_test.go, line 226 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsiHcRKwMnuJnjdunf6:-KsizjnXYNYQYn7nuv7-:bwbfxjx) ([raw file](https://github.com/mirantis/virtlet/blob/07bba083e72038973269db32cf1bf14df121ec7c/tests/e2e/ceph_test.go#L226)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Usage of echo there to add something to file looks strange there. I know that this is simply the same what was in shell script, but later in time we can replace that with call to https://golang.org/pkg/io/ioutil/#WriteFile - for now i'm ok with current version. 
</blockquote></details>

`echo` is executed in docker container, not on the host. How WriteFile can help here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/390)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[tests/e2e/ceph_test.go, line 226 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/390#-KsiHcRKwMnuJnjdunf6:-Ksj9UwuO5FMGgKDyAma:b-hldymc) ([raw file](https://github.com/mirantis/virtlet/blob/07bba083e72038973269db32cf1bf14df121ec7c/tests/e2e/ceph_test.go#L226)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

`echo` is executed in docker container, not on the host. How WriteFile can help here?
</blockquote></details>

Point taken.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/390)*

**Pull request merged**
