### PR TITLE
Added doc describing image handling.

### LINKED ISSUE #251: Add image handling description
Describe in separate doc the way image handling is implemented for virtlet, supported options, like imagePolicy and recently added VIRTLET_DOWNLOAD_PROTOCOL var.

### PR DESCRIPTION
**Pull request by vefimova**
Fixes #251

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/268)

### CODE REVIEW

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/images.md, line 6 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEV1GrdEpiPWdVU1ST:-KjEV1GrdEpiPWdVU1SU:b-fkedq3) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L6)):*
> ```Markdown
> 
> ## Options:
> - ImagePullSecrets - not supported currently
> ```

`ImagePullSecrets` - please enclose all names in doc in backticks, so also `PullImage`, `ImagePullPolicy`, `kubeapi.PullImageRequest`, and so on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268)*

**Comment by jellonek** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268)*

**Comment by vefimova** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/images.md, line 6 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEV1GrdEpiPWdVU1ST:-KjEYcsbjOVuD-fobA9I:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L6)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

`ImagePullSecrets` - please enclose all names in doc in backticks, so also `PullImage`, `ImagePullPolicy`, `kubeapi.PullImageRequest`, and so on.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268)*

**Comment by ivan4th** [comment]
Review status: 1 of 2 files reviewed at latest revision, 12 unresolved discussions.

---

*[docs/images.md, line 3 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEVMSeFHlOAqo1D7U2:-KjEVMSeFHlOAqo1D7U3:b-qh8zhv) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L3)):*
> ```Markdown
> # Image Handling
> 
> Virtlet supports qcow2 format images for VM boot images.
> ```

Maybe "Virtlet supports VM boot images in QCOW2 format" ?

---

*[docs/images.md, line 7 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEW6NYt389SeOBFpuw:-KjEW6NYt389SeOBFpux:bjozct) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L7)):*
> ```Markdown
> ## Options:
> - ImagePullSecrets - not supported currently
> - Protocol to use to download the image. By default `https` is used. To set other change `VIRTLET_DOWNLOAD_PROTOCOL` env var in `deploy/virtlet-ds.yaml`.
> ```

download the images ...
In order to use `http`, set `VIRTLET_DOWNLOAD_PROTOCOL` env var value to `http` in `deploy/virtlet-ds.yaml`.
`deploy/virtlet-ds-dev.yaml` defaults to using `http` currently.

---

*[docs/images.md, line 9 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEWYtDnHbXnZFtI8Xy:-KjEWYtDnHbXnZFtI8Xz:b7r6qa7) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L9)):*
> ```Markdown
> - Protocol to use to download the image. By default `https` is used. To set other change `VIRTLET_DOWNLOAD_PROTOCOL` env var in `deploy/virtlet-ds.yaml`.
> 
> ## Example of definition:
> ```

Sample definition or "An example of container definition"

---

*[docs/images.md, line 14 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEWhDuGFDfCGmAsrVp:-KjEWhDuGFDfCGmAsrVq:b-h1cry4) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L14)):*
> ```Markdown
>   containers:
>     - name: test-vm
>       image: download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
> ```

This will not work with CRI proxy, need `virtlet/` prefix

---

*[docs/images.md, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEWmOKeb0L6PnjAM2_:-KjEWmOKeb0L6PnjAM2a:b-nyitmn) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L17)):*
> ```Markdown
> ```
> 
> **Note**, that to pass apiserver pod's definition validation, you need to specify url without `scheme://`.
> ```

**Note**: you need to specify url without the `scheme://` part

(it's not just validation, it's also how Virtlet handles the images, right?)

---

*[docs/images.md, line 21 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEX9VhHdajfxUGj-iW:-KjEX9VhHdajfxUGj-iX:b-lafji9) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L21)):*
> ```Markdown
> 
> ## Image handling Workflow:
> 1. Kubelet sends PullImage gRPC request to virtlet
> ```

it's better to use consistent casing, perhaps `Virtlet` is better than `virtlet`

---

*[docs/images.md, line 22 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEXE79AM8jy0Lvy3Jg:-KjEXE7AY5X40Eqis5gx:bqy1ymk) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L22)):*
> ```Markdown
> ## Image handling Workflow:
> 1. Kubelet sends PullImage gRPC request to virtlet
> (Note, that as ImagePullPolicy value in not included within kubeapi.PullImageRequest to CRI runtime, it's up to kubelet basing on ImagePullPolicy whether to send PullImage gRPC request. So PullImage will be sent in two cases: ImagePullPolicy=PullAlways OR PullIfNotPreset).
> ```

Note that `PullImage` request can be skipped by kubelet unless the pod has `imagePullPolicy: PullAlways` or `imagePullPolicy: PullIfNotPreset` and the image is not pulled yet.

---

*[docs/images.md, line 23 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEYxjW6YkdQP8-DviF:-KjEYxjW6YkdQP8-DviG:ba7q5wa) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L23)):*
> ```Markdown
> 1. Kubelet sends PullImage gRPC request to virtlet
> (Note, that as ImagePullPolicy value in not included within kubeapi.PullImageRequest to CRI runtime, it's up to kubelet basing on ImagePullPolicy whether to send PullImage gRPC request. So PullImage will be sent in two cases: ImagePullPolicy=PullAlways OR PullIfNotPreset).
> 1. Virtlet uses image url fragment after last slash as image name to look up though the list of existent images on the host.
> ```

Virtlet uses image url fragment after last slash as internal image name that it looks up in the list of existing images on the host

---

*[docs/images.md, line 24 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEZFOURPJawra7SIql:-KjEZFOURPJawra7SIqm:bo4vk6x) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L24)):*
> ```Markdown
> (Note, that as ImagePullPolicy value in not included within kubeapi.PullImageRequest to CRI runtime, it's up to kubelet basing on ImagePullPolicy whether to send PullImage gRPC request. So PullImage will be sent in two cases: ImagePullPolicy=PullAlways OR PullIfNotPreset).
> 1. Virtlet uses image url fragment after last slash as image name to look up though the list of existent images on the host.
> 1. In case if there's no image with such name in the list, the image will be downloaded using specified url prepended with `scheme://`. And after that Virtlet creates libvirt volume in "**default**" libvirt pool under  `/var/lib/libvirt/images` and uploads image content to it.
> ```

remove "And"

... `default` libvirt pool
... copies the image content to it

---

*[docs/images.md, line 25 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEZVUJpzOXfan_z2ET:-KjEZVUJpzOXfan_z2EU:btkki92) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L25)):*
> ```Markdown
> 1. Virtlet uses image url fragment after last slash as image name to look up though the list of existent images on the host.
> 1. In case if there's no image with such name in the list, the image will be downloaded using specified url prepended with `scheme://`. And after that Virtlet creates libvirt volume in "**default**" libvirt pool under  `/var/lib/libvirt/images` and uploads image content to it.
> 1. In case if there's an entry with such name in list, just send succesfull response to kubelet.
> ```

PullImage call just return success. 

---

*[docs/images.md, line 27 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEZwkX5tcdueqZknPU:-KjEZwkX5tcdueqZknPV:bt94nfg) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L27)):*
> ```Markdown
> 1. In case if there's an entry with such name in list, just send succesfull response to kubelet.
> 
> **Note**, that to safe disk space and be able to reuse already existent guest OS volumes Virtlet creates separate volume which uses original one as backing store.
> ```

In order to save disk space and to be able to reuse existing guest OS Volumes creates separate volume which uses the original one as backing store.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268)*

**Comment by jellonek** [comment]
Review status: 1 of 2 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[docs/images.md, line 3 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEVMSeFHlOAqo1D7U2:-KjEdM3sofwhJk245U-b:boinf4b) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L3)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Maybe "Virtlet supports VM boot images in QCOW2 format" ?
</blockquote></details>

Or at last "... supports qcow2 images format ...". BTW. "boot" in this line seems to be unnecessary addition. More common name is "VM images".

---

*[docs/images.md, line 14 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEWhDuGFDfCGmAsrVp:-KjEeGbM5Wg64fa4xzWH:b-r3bwwe) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L14)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

This will not work with CRI proxy, need `virtlet/` prefix
</blockquote></details>

It's not virtlet requirement, but preferred virtlet deploy mode requirement, which uses criproxy. So this deserves for wider explanation with link to point in criproxy.md - now this info is described in a bit scattered in this doc, in `-connect` explanation, and later in image name explanation - maybe this also should be described in separate point to which this doc could link?
WDYT?

---

*[docs/images.md, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEWmOKeb0L6PnjAM2_:-KjEfjmDBgocs0wM51te:bgo7666) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L17)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

**Note**: you need to specify url without the `scheme://` part

(it's not just validation, it's also how Virtlet handles the images, right?)
</blockquote></details>

Yes, we don't test for any prefix like scheme - we are adding one basing on configuration (which defaults to `https://`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268)*

**Comment by vefimova** [comment]
Review status: 1 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/images.md, line 3 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEVMSeFHlOAqo1D7U2:-KjEo57qkSqyGt8yGLwD:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L3)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Or at last "... supports qcow2 images format ...". BTW. "boot" in this line seems to be unnecessary addition. More common name is "VM images".
</blockquote></details>

Done.

---

*[docs/images.md, line 7 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEW6NYt389SeOBFpuw:-KjEo5r56EdB1wnnfPPo:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L7)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

download the images ...
In order to use `http`, set `VIRTLET_DOWNLOAD_PROTOCOL` env var value to `http` in `deploy/virtlet-ds.yaml`.
`deploy/virtlet-ds-dev.yaml` defaults to using `http` currently.
</blockquote></details>

Done.

---

*[docs/images.md, line 9 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEWYtDnHbXnZFtI8Xy:-KjEnFhbE84ni-1_oLCE:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L9)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Sample definition or "An example of container definition"
</blockquote></details>

Done.

---

*[docs/images.md, line 14 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEWhDuGFDfCGmAsrVp:-KjEoTCs_t_N8WoaMamI:bhlqf7l) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L14)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

It's not virtlet requirement, but preferred virtlet deploy mode requirement, which uses criproxy. So this deserves for wider explanation with link to point in criproxy.md - now this info is described in a bit scattered in this doc, in `-connect` explanation, and later in image name explanation - maybe this also should be described in separate point to which this doc could link?
WDYT?
</blockquote></details>

Added note re virtlet/ prefix in case of criproxy.

---

*[docs/images.md, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEWmOKeb0L6PnjAM2_:-KjEou7aqm6joL4x_2OH:b-hr2s6d) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L17)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Yes, we don't test for any prefix like scheme - we are adding one basing on configuration (which defaults to `https://`).
</blockquote></details>

Yes, we don't, but kubelet does, and expects to have container image name there, so that's why Michal done it without setting schema:// for url. If you set it you'll receive from kubelet:
```
Failed to apply default image tag "http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img": couldn't parse image reference "http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img": invalid reference format
```
But anyway I removed this mention to not overcomplicate the description.

---

*[docs/images.md, line 21 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEX9VhHdajfxUGj-iW:-KjErrc6qtwQLkRW-p97:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L21)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

it's better to use consistent casing, perhaps `Virtlet` is better than `virtlet`
</blockquote></details>

Done.

---

*[docs/images.md, line 22 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEXE79AM8jy0Lvy3Jg:-KjEt79KujvrLKv5daB_:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L22)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Note that `PullImage` request can be skipped by kubelet unless the pod has `imagePullPolicy: PullAlways` or `imagePullPolicy: PullIfNotPreset` and the image is not pulled yet.
</blockquote></details>

Done.

---

*[docs/images.md, line 23 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEYxjW6YkdQP8-DviF:-KjEt7R_Jom0NMxspA88:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L23)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Virtlet uses image url fragment after last slash as internal image name that it looks up in the list of existing images on the host
</blockquote></details>

Done.

---

*[docs/images.md, line 24 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEZFOURPJawra7SIql:-KjEthoD-0UbPEa1opWL:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L24)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

remove "And"

... `default` libvirt pool
... copies the image content to it
</blockquote></details>

Done.

---

*[docs/images.md, line 25 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEZVUJpzOXfan_z2ET:-KjEthQaDFhtY-ICVxQq:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L25)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

PullImage call just return success. 
</blockquote></details>

Done.

---

*[docs/images.md, line 27 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEZwkX5tcdueqZknPU:-KjEuAaMQKPL2QNazdX4:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L27)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

In order to save disk space and to be able to reuse existing guest OS Volumes creates separate volume which uses the original one as backing store.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/images.md, line 3 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEVMSeFHlOAqo1D7U2:-KjHw76smfA8TjfwZwo5:bjpqpgv) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L3)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

IMO this should be: "Virtlet supports QCOW2 images format." or "... QCOW2 format for VM images".

---

*[docs/images.md, line 25 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEZVUJpzOXfan_z2ET:-KjHwuIffxSckGf9Ulas:bl6bq8r) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L25)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Double "." at the end.

---

*[docs/images.md, line 27 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEZwkX5tcdueqZknPU:-KjHwyFI-rdX0EPKDeMZ:boai9d2) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L27)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please replace "," with ":" in bolded part, and remove "that" at the beginning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268)*

**Comment by vefimova** [comment]
Review status: 1 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/images.md, line 3 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEVMSeFHlOAqo1D7U2:-KjHy045shccQEJP-QCe:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L3)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

IMO this should be: "Virtlet supports QCOW2 images format." or "... QCOW2 format for VM images".
</blockquote></details>

Done.

---

*[docs/images.md, line 25 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEZVUJpzOXfan_z2ET:-KjHy6dDn-332kLtAEIC:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L25)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Double "." at the end.
</blockquote></details>

Done.

---

*[docs/images.md, line 27 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/268#-KjEZwkX5tcdueqZknPU:-KjHyMKpWjI4mUEAMuhB:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/395f7090b42b8886d9db07ae0e87cc63aef97363/docs/images.md#L27)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

please replace "," with ":" in bolded part, and remove "that" at the beginning.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268#-:-KjHz3la67F4QJrTtbnd:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268#-:-KjIq7fRVEQNxq8VS0jw:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/268)*

**Pull request merged**
