### PR TITLE
Contributing guidelines and k8s incubation template.

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/215)

### CODE REVIEW

**Comment by nhlfr** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CONTRIBUTING.md, line 27 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/215#-Kf7OWZaYH4PgUvi2hNB:-Kf7OWZaYH4PgUvi2hNC:bq8n3gc) ([raw file](https://github.com/mirantis/virtlet/blob/7fd721d879181ede24091cafe808379eddd3af7c/CONTRIBUTING.md#L27)):*
> ```Markdown
> ### Adding dependencies
> 
> If your patch depends on new packages, add that package with [`godep`](https://github.com/tools/godep). Follow the [instructions to add a dependency](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#godep-and-dependency-management).
> ```

s/godep/glide

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/215)*

**Comment by jellonek** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CONTRIBUTING.md, line 27 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/215#-Kf7OWZaYH4PgUvi2hNB:-Kf7TzaVQlnUQUhCXtOT:b-8fx2u7) ([raw file](https://github.com/mirantis/virtlet/blob/7fd721d879181ede24091cafe808379eddd3af7c/CONTRIBUTING.md#L27)):*
<details><summary><i>Previously, nhlfr (Michal Rostecki) wrote…</i></summary><blockquote>

s/godep/glide
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/215)*

**Comment by jellonek** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[CONTRIBUTING.md, line 27 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/215#-Kf7OWZaYH4PgUvi2hNB:-Kf7VAQL5nMmeC4Q1nvT:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7fd721d879181ede24091cafe808379eddd3af7c/CONTRIBUTING.md#L27)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/215)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/215#-:-Kf7ZjKUIMzoOlyu3hLV:bnfp4nl)*

**Comment by nhlfr** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/215#-:-Kf7Zq35sD8TaKsnpA7w:bnfp4nl)*

**Pull request merged**
