### PR TITLE
Fix issues found by go vet

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/589)

### CODE REVIEW

**Comment by ivan4th** [comment]
Great work, thanks @jell!

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/589#-:-L6RFDkq98JX10e9N8Kn:b-ozgmyo)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/589#-:-L6RFHeBCSD_FVxYeQhi:bnfp4nl)*

**Comment by ivan4th** [comment]
Made a typo in Reviewable comment and can't fix it ;( But ok

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/589#-:-L6RFhZy1UYj2dopNEun:b-knti4l)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/589#-:-L6RGto-0759HwUNM5gR:bnfp4nl)*

**Pull request merged**
