### PR TITLE
volumes: Raw devices support

### LINKED ISSUE #252: If we pass wrong value in volume description - error is not handled correctly
We should return with error in https://github.com/Mirantis/virtlet/blob/3ad8dd642bf5a9d3e33bec290de7820fb8a0b587/pkg/libvirttools/storage_pool.go#L282

Fixing this in PR for raw devices support.

### PR DESCRIPTION
**Pull request by jellonek**
---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/256)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/volumes.md, line 103 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiZRtx4e00uEY6F80KF:-KiZRtx4e00uEY6F80KG:b-yz9u21) ([raw file](https://github.com/mirantis/virtlet/blob/4d7ef00d22e545df8b56fbfee28237ddc39d9d34/docs/volumes.md#L103)):*
> ```Markdown
>           }
>         }
>       }
> ```

affinity has now non-alpha syntax, this one will not work, see `cirros-vm.yaml` as an example

---

*[docs/volumes.md, line 269 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiZS2vZgIMgcJpod3kz:-KiZS2vZgIMgcJpod3l-:b-8gd39s) ([raw file](https://github.com/mirantis/virtlet/blob/4d7ef00d22e545df8b56fbfee28237ddc39d9d34/docs/volumes.md#L269)):*
> ```Markdown
>           }
>         }
>       }
> ```

same about affinity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256)*

**Comment by jellonek** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/volumes.md, line 103 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiZRtx4e00uEY6F80KF:-KiZV9QGjFkYKw_BmgMp:bb7f2mf) ([raw file](https://github.com/mirantis/virtlet/blob/4d7ef00d22e545df8b56fbfee28237ddc39d9d34/docs/volumes.md#L103)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

affinity has now non-alpha syntax, this one will not work, see `cirros-vm.yaml` as an example
</blockquote></details>

done

---

*[docs/volumes.md, line 269 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiZS2vZgIMgcJpod3kz:-KiZV6i_f5hXA4mrVzY_:bb7f2mf) ([raw file](https://github.com/mirantis/virtlet/blob/4d7ef00d22e545df8b56fbfee28237ddc39d9d34/docs/volumes.md#L269)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

same about affinity
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256)*

**Comment by ivan4th** [comment]
BTW can you add some pod yaml in examples and try it to make sure it works?

---

Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/volumes.md, line 250 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_NEkKQJhG-a6JQRSz:-Ki_NEkKQJhG-a6JQRT-:b-cfpx60) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/docs/volumes.md#L250)):*
> ```Markdown
> 
> As always, boot image is exposed to the guest OS under **vda** device.
> According to this definition here will be exposed to VM single raw device `/dev/loop0`.
> ```

This pod definition exposes a single raw device to the VM (`/dev/loop0`)

---

*[docs/volumes.md, line 259 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_NV2dJtf1GMyPm3uF:-Ki_NV2dJtf1GMyPm3uG:b-11lu7t) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/docs/volumes.md#L259)):*
> ```Markdown
> When not set, it defaults to `loop*`.
> 
> Easiest method to pass this parameter to `virtlet` is to use [configmap](https://kubernetes.io/docs/tasks/configure-pod-container/configmap) to contain a key/value pair (e.x. `devices.raw=loop*,mapper/vm_pool-*`), which then can be used in `deploy/virtlet_ds.yaml` after setting:
> ```

The easiest method of passing

---

*[pkg/libvirttools/storage_pool.go, line 285 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_Od4Aubh3UmYmkqha:-Ki_Od4BNfasB3NYbIvQ:bs0w0jj) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L285)):*
> ```Go
> }
> 
> // PrepareVolumesToBeAttached returns list of xml definitions for dom xml of created or raw volumes
> ```

returns a list

---

*[pkg/libvirttools/storage_pool.go, line 286 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_OeM7rg7uyJZUPcor:-Ki_OeM7rg7uyJZUPcos:bcf80ab) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L286)):*
> ```Go
> 
> // PrepareVolumesToBeAttached returns list of xml definitions for dom xml of created or raw volumes
> // letterInd contains information about how many drive letters are already used by flex volumes
> ```

letterInd contains the number of drive letters already used by flexvolumes

---

*[tests/integration/raw_devices_test.go, line 113 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_MOqwWU2PQ16IqXdo:-Ki_MOqwWU2PQ16IqXdp:bchjvzp) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/tests/integration/raw_devices_test.go#L113)):*
> ```Go
> }
> 
> func fromShell(format string, a ...interface{}) string {
> ```

perhaps we need some utils package for such funcs? We have stuff like this in several places across our code. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256#-:-Ki_N-spIw493G8_DIxD:b-ux76g3)*

**Comment by vefimova** [comment]
Review status: 0 of 8 files reviewed at latest revision, 13 unresolved discussions.

---

*[docs/volumes.md, line 251 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_4dYlo58k4sPHtKaG:-Ki_4dYlo58k4sPHtKaH:b-q5i76k) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/docs/volumes.md#L251)):*
> ```Markdown
> As always, boot image is exposed to the guest OS under **vda** device.
> According to this definition here will be exposed to VM single raw device `/dev/loop0`.
> As devices/volumes are exposed in the alphabet order starting from `b`, `vol1` will be visible on VM as `vdb`.
> ```

Pls, remove this note as it can be not the case, see #3 in "Caveats and Limitations" section.

---

*[pkg/libvirttools/storage_pool.go, line 54 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_CwK3utxh58NdFQNv:-Ki_CwK3utxh58NdFQNw:b-c1153u) ([raw file](https://github.com/mirantis/virtlet/blob/8007b0c7b1dcede54e4f57bcff0d766e1983e31e/pkg/libvirttools/storage_pool.go#L54)):*
> ```Go
> 		Format:       "qcow2",
> 		Capacity:     defaultCapacity,
> 		CapacityUnit: defaultCapacityUnit,
> ```

Pls, add setting  defaultCapacity and defaultCapacityUnit in case if they were not set for "qcow2" format case.

---

*[pkg/libvirttools/storage_pool.go, line 62 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_DCQh2cgD0a7S4Erm:-Ki_DCQh2cgD0a7S4Ern:b-wb7421) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L62)):*
> ```Go
> 	if err == nil && volWithDefaults.Name == "" {
> 		return fmt.Errorf("Validation failed for volumes definition within pod's annotations: volume name is mandatory.")
> 	}
> ```

Pls, add validation check for Path value, expect to not set in case of "qcow2" and set in case of "raw" and starts from "/dev".

---

*[pkg/libvirttools/storage_pool.go, line 308 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_CLE_ERT6ZQaqdiDc:-Ki_CLEap24AnP_9UWWo:bgcno9a) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L308)):*
> ```Go
> 		switch virtletVol.Format {
> 		case "qcow2":
> 			vol, err := s.CreateVolume(volName, defaultCapacity, defaultCapacityUnit)
> ```

Actually, there's a bug here, we need to use virtletVol.Capacity and virtletVol.CapacityUnit as args to CreateVolume func.

---

*[pkg/libvirttools/storage_pool.go, line 356 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_HSK4LDjKVKikrp5S:-Ki_HSK4LDjKVKikrp5T:bnwguks) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L356)):*
> ```Go
> 		}
> 	}
> 	return fmt.Errorf("device '%s' not whitelisted on this virtlet node", path)
> ```

We should check whether device exists on the node before that verdict, or to call  verifyRawDeviceAccess which supposed to return error in such case.

---

*[tests/integration/raw_devices_test.go, line 84 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_Nyg_cs0qniB64MxC:-Ki_NygaRaHNJRgM6yjH:b2y6gcs) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/tests/integration/raw_devices_test.go#L84)):*
> ```Go
> 	}
> 
> 	ct.waitForContainerRunning(container.ContainerId, container.Name)
> ```

Add here calling "virsh domblklist" to get the list of disks attached to vm and check loop dev is there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256)*

**Comment by vefimova** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256)*

**Comment by vefimova** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[pkg/libvirttools/storage_pool.go, line 356 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_HSK4LDjKVKikrp5S:-Ki_QVDal5ynd1An2hTU:bvlf2uj) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L356)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

We should check whether device exists on the node before that verdict, or to call  verifyRawDeviceAccess which supposed to return error in such case.
</blockquote></details>

Meant to call verifyRawDeviceAccess before isRawDeviceOnWhitelist

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256)*

**Comment by jellonek** [comment]
Doable. Will add.

---

Review status: 5 of 8 files reviewed at latest revision, 14 unresolved discussions.

---

*[docs/volumes.md, line 250 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_NEkKQJhG-a6JQRSz:-Ki_TaHT8lDGt4TDE4Ej:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/docs/volumes.md#L250)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

This pod definition exposes a single raw device to the VM (`/dev/loop0`)
</blockquote></details>

Done.

---

*[docs/volumes.md, line 251 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_4dYlo58k4sPHtKaG:-Ki_SBUbYYFUbu3KnHWb:b-nbutag) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/docs/volumes.md#L251)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Pls, remove this note as it can be not the case, see #3 in "Caveats and Limitations" section.
</blockquote></details>

Hmmm... So this should be also removed from `Ephemeral Local Storage` section? It's copied from it.
With this example pod definition (like in that Ephemeral one) I can not find how this could be not the case.

---

*[docs/volumes.md, line 259 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_NV2dJtf1GMyPm3uF:-Ki_TZ4SZOsvFY0XQ8su:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/docs/volumes.md#L259)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

The easiest method of passing
</blockquote></details>

Done.

---

*[pkg/libvirttools/storage_pool.go, line 54 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_CwK3utxh58NdFQNv:-Ki_WOaKVXYNUyBE2JVG:b7ify8g) ([raw file](https://github.com/mirantis/virtlet/blob/8007b0c7b1dcede54e4f57bcff0d766e1983e31e/pkg/libvirttools/storage_pool.go#L54)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Pls, add setting  defaultCapacity and defaultCapacityUnit in case if they were not set for "qcow2" format case.
</blockquote></details>

Hmmm... Added test for format and then filling defaults for `qcow2`.

---

*[pkg/libvirttools/storage_pool.go, line 62 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_DCQh2cgD0a7S4Erm:-Ki_UOOsJ65VyUyySISz:b-qn0o9c) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L62)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Pls, add validation check for Path value, expect to not set in case of "qcow2" and set in case of "raw" and starts from "/dev".
</blockquote></details>

Imo better would be to have a separate func for validation, instead of mixing this with unmarshaling.
So I added separate func for that, to which i'm also moving validation of name. I'm calling it at after unmarshal, to separate syntax error from logical error.

---

*[pkg/libvirttools/storage_pool.go, line 285 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_Od4Aubh3UmYmkqha:-Ki_UtjSMVzsHQwRrK6X:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L285)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

returns a list
</blockquote></details>

Done.

---

*[pkg/libvirttools/storage_pool.go, line 286 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_OeM7rg7uyJZUPcor:-Ki_V87Mro9S6kSRIi4p:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L286)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

letterInd contains the number of drive letters already used by flexvolumes
</blockquote></details>

Done.

---

*[pkg/libvirttools/storage_pool.go, line 308 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_CLE_ERT6ZQaqdiDc:-Ki_VJE8UkizAxVGu52G:bh638eh) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L308)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Actually, there's a bug here, we need to use virtletVol.Capacity and virtletVol.CapacityUnit as args to CreateVolume func.
</blockquote></details>

Ok. Fixed there.

---

*[pkg/libvirttools/storage_pool.go, line 356 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_HSK4LDjKVKikrp5S:-Ki_VvtFp1HVdjgYBIFC:b-w1wayx) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/pkg/libvirttools/storage_pool.go#L356)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Meant to call verifyRawDeviceAccess before isRawDeviceOnWhitelist
</blockquote></details>

Why in this order? It's already done (in opposite order, firstly i'm verifying whitelist, then access) in "raw" case.
Anyway, moved access test to validation after unmarshal - so it will be called before whitelist verification. 

---

*[tests/integration/raw_devices_test.go, line 84 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_Nyg_cs0qniB64MxC:-Ki_eBRPVuaGe4j0FTLG:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/tests/integration/raw_devices_test.go#L84)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Add here calling "virsh domblklist" to get the list of disks attached to vm and check loop dev is there.
</blockquote></details>

Done.

---

*[tests/integration/raw_devices_test.go, line 113 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Ki_MOqwWU2PQ16IqXdo:-Ki_RAXlo-GAFh99CnD8:b-afwfjx) ([raw file](https://github.com/mirantis/virtlet/blob/abd43c4f367ddd24bb852ccb6bf44cc837a323f1/tests/integration/raw_devices_test.go#L113)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

perhaps we need some utils package for such funcs? We have stuff like this in several places across our code. 
</blockquote></details>

Yes, this deserves for follow up. It's similar to verifyUsingShell - which also could be extracted there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256#-:-Ki_RkhngL54Oeuhefdo:b-wwg57l)*

**Comment by ivan4th** [comment]
Review status: 5 of 8 files reviewed at latest revision, 18 unresolved discussions.

---

*[docs/volumes.md, line 103 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaG8tqcmGLgosA1FkK:-KiaG8tqcmGLgosA1FkL:byuucqx) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/docs/volumes.md#L103)):*
> ```Markdown
> According to this definition will be created VM-POD with VM with 2 equal volumes, attached, which can be found in "volumes" pool under `<domain-uuid>-vol1` and `<domain-uuid>-vol2`
> Boot image is exposed to the guest OS under **vda** device.
> Additional volume disks are exposed on typical linux system in the alphabet order starting from b, so vol1 will be vdb and vol2 - vdc, but please reffer to third of caveats listed on the top of this document.
> ```

On a typical linux system the additional volume disks are assigned to `/dev/vdX` devices in an alphabetical order, so `vol1` will be `/dev/vdb` and `vol2` will be `/dev/vdc`,
but please refer to caveat #3 at the beginning of this document

---

*[pkg/libvirttools/storage_pool.go, line 94 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaHCTOba8wdFdBPo47:-KiaHCTPrDaFcCf-lvFP:b-ajz1bf) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/pkg/libvirttools/storage_pool.go#L94)):*
> ```Go
> 	case "raw":
> 		if vol.Capacity != 0 {
> 			return fmt.Errorf("raw volume should not have set Capacity, but it have it equal to: %d", vol.Capacity)
> ```

remove 'set'

---

*[tests/integration/raw_devices_test.go, line 88 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaI2KaQNu3uxZfrFDd:-KiaI2KaQNu3uxZfrFDe:blan0ne) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/tests/integration/raw_devices_test.go#L88)):*
> ```Go
> 	// check for loop in container dom
> 	cmd := fmt.Sprintf("virsh domblklist %s | grep '/dev/loop' | wc -l", container.ContainerId)
> 	verifyUsingShell(t, cmd, "how many there's attached loop devices", "1")
> ```

"the number of block devices attached"

---

*[tests/integration/raw_devices_test.go, line 111 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaHsectNgwvAoK8kfq:-KiaHsectNgwvAoK8kfr:b26fasz) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/tests/integration/raw_devices_test.go#L111)):*
> ```Go
> 	for counter := 0; counter < tempFileSizeInKB; counter++ {
> 		if _, err := file.Write(zeros); err != nil {
> 			log.Fatalf("Error during filling temporary file: %v", err)
> ```

Error writing temporary file: %v

(can write 'filling' too but IMO that's not very necessary...)

---

*[tests/integration/raw_devices_test.go, line 122 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaHmVu5lfOc0tYBApB:-KiaHmVu5lfOc0tYBApC:bbo1xlv) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/tests/integration/raw_devices_test.go#L122)):*
> ```Go
> 	out, err := exec.Command("bash", "-c", command).Output()
> 	if err != nil {
> 		log.Fatalf("Error during execution of command '%s': %v", command, err)
> ```

Error executing command %q: %v

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[pkg/libvirttools/storage_pool.go, line 90 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Kia0Qz_ggHA2mjPujSk:-Kia0QzamTMChuzKKeU-:b-ekcgad) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/pkg/libvirttools/storage_pool.go#L90)):*
> ```Go
> 	case "qcow2":
> 		if vol.Path != "" {
> 			return fmt.Errorf("qcow2 volume should not have Path but it have it set to: %s", vol.Path)
> ```

it "has" it set to, and for two Errorf messages below as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256#-:-KiaJ0x3LRE19lHPqyqr:bnfp4nl)*

**Comment by jellonek** [comment]
Review status: 5 of 8 files reviewed at latest revision, 19 unresolved discussions.

---

*[docs/volumes.md, line 103 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaG8tqcmGLgosA1FkK:-KiaVoYekhAZgcSgSW1M:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/docs/volumes.md#L103)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

On a typical linux system the additional volume disks are assigned to `/dev/vdX` devices in an alphabetical order, so `vol1` will be `/dev/vdb` and `vol2` will be `/dev/vdc`,
but please refer to caveat #3 at the beginning of this document
</blockquote></details>

Done.

---

*[pkg/libvirttools/storage_pool.go, line 90 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-Kia0Qz_ggHA2mjPujSk:-KiaVqpHDNxI_vI6ifsg:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/pkg/libvirttools/storage_pool.go#L90)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

it "has" it set to, and for two Errorf messages below as well
</blockquote></details>

Done.

---

*[pkg/libvirttools/storage_pool.go, line 94 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaHCTOba8wdFdBPo47:-KiaVsNe41v0G7RMh2hu:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/pkg/libvirttools/storage_pool.go#L94)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

remove 'set'
</blockquote></details>

Done.

---

*[tests/integration/raw_devices_test.go, line 88 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaI2KaQNu3uxZfrFDd:-KiaVuQk9n4C0-rjVfpi:bgebjo) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/tests/integration/raw_devices_test.go#L88)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

"the number of block devices attached"
</blockquote></details>

Done in a bit other way - grep looks exactly for loop devices.

---

*[tests/integration/raw_devices_test.go, line 111 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaHsectNgwvAoK8kfq:-KiaW5ZuxiM34oRkK9GC:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/tests/integration/raw_devices_test.go#L111)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Error writing temporary file: %v

(can write 'filling' too but IMO that's not very necessary...)
</blockquote></details>

Done.

---

*[tests/integration/raw_devices_test.go, line 122 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaHmVu5lfOc0tYBApB:-KiaW8D-67ci1PxZitPJ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/tests/integration/raw_devices_test.go#L122)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Error executing command %q: %v
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256)*

**Comment by ivan4th** [comment]
Review status: 5 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[tests/integration/raw_devices_test.go, line 88 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KiaI2KaQNu3uxZfrFDd:-KiaXSJag_5wEOVdNTzq:b-hgamnh) ([raw file](https://github.com/mirantis/virtlet/blob/1a7c26e41b7723e5ab8b369889c0afac34600fab/tests/integration/raw_devices_test.go#L88)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done in a bit other way - grep looks exactly for loop devices.
</blockquote></details>

sorry, it was a typo ('block')

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256)*

**Comment by ivan4th** [comment]
Review status: 5 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/libvirttools/storage_pool.go, line 371 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KicSsAGSNHIrnYOjC1Y:-KicSsAHMmRo9EyjHQpD:b4wr1k3) ([raw file](https://github.com/mirantis/virtlet/blob/6c192d4f874155142d77e7bb3b769c823a8043d5/pkg/libvirttools/storage_pool.go#L371)):*
> ```Go
> 			volXML = fmt.Sprintf(volXMLTemplate, path, virtDev)
> 
> 		case "raw":
> ```

maybe we should use `rawDevice` type here to make it clean that must be a block device and not a `raw` image? Because as of now it leaves such an impression being in the same switch statement with `qcow2`.

---

*[pkg/libvirttools/storage_pool.go, line 375 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KicTCgvy6a83MtjlBjW:-KicTCgw89AsGs0u3Juu:b-inn9d1) ([raw file](https://github.com/mirantis/virtlet/blob/6c192d4f874155142d77e7bb3b769c823a8043d5/pkg/libvirttools/storage_pool.go#L375)):*
> ```Go
> 				return nil, err
> 			}
> 			volXML = generateRawDeviceXML(virtletVol.Path, virtDev)
> ```

In this part of code we have severe confusion between `<volume>` and `<disk>` XMLs. Should probably fix it here & above in `qcow2` part?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256)*

**Comment by jellonek** [comment]
Review status: 3 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/libvirttools/storage_pool.go, line 371 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KicSsAGSNHIrnYOjC1Y:-Kid8CFjMCJmum-LCi68:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/6c192d4f874155142d77e7bb3b769c823a8043d5/pkg/libvirttools/storage_pool.go#L371)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe we should use `rawDevice` type here to make it clean that must be a block device and not a `raw` image? Because as of now it leaves such an impression being in the same switch statement with `qcow2`.
</blockquote></details>

Done.

---

*[pkg/libvirttools/storage_pool.go, line 375 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/256#-KicTCgvy6a83MtjlBjW:-KidDTowq8Ht7O3Zxnrp:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/6c192d4f874155142d77e7bb3b769c823a8043d5/pkg/libvirttools/storage_pool.go#L375)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

In this part of code we have severe confusion between `<volume>` and `<disk>` XMLs. Should probably fix it here & above in `qcow2` part?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 3 of 9 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/256#-:-KidDz1Y1oMWdB2M_44u:bnfp4nl)*

**Pull request merged**
