### PR TITLE
Improve deploy method with SR-IOV enabled

### PR DESCRIPTION
**Pull request by jellonek**
This PR contains update in docs for SR-IOV as also for already merged multiple interfaces support.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/534)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/vmwrapper/vmwrapper.go, line 113 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/534#-L0jShLVPkVI5CCtHDRB:-L0jShLVPkVI5CCtHDRC:b6vvri0) ([raw file](https://github.com/mirantis/virtlet/blob/cff50b8d6c256a1e7088a338851976705b302d98/cmd/vmwrapper/vmwrapper.go#L113)):*
> ```Go
> 
> 	// permanently drop privs if SR-IOV support is not enabled
> 	if (getenv("VMWRAPPER_SRIOV_SUPPORT") == NULL) {
> ```

I'd name this env var `VMWRAPPER_KEEP_PRIVS` as vmwrapper doesn't do anything directly SRIOV-related (or am I wrong?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/534)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/vmwrapper/vmwrapper.go, line 113 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/534#-L0jShLVPkVI5CCtHDRB:-L0jU3zj6Wa4ShFY26qz:b-f7vmiw) ([raw file](https://github.com/mirantis/virtlet/blob/cff50b8d6c256a1e7088a338851976705b302d98/cmd/vmwrapper/vmwrapper.go#L113)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'd name this env var `VMWRAPPER_KEEP_PRIVS` as vmwrapper doesn't do anything directly SRIOV-related (or am I wrong?)
</blockquote></details>

You are right, actually it does not do anything special (all things are done on tapmanager level). Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/534)*

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/networking.md, line 51 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/534#-L0jcAeGSn8buVNUshgs:-L0jcAeGSn8buVNUshgt:b-ak8mlc) ([raw file](https://github.com/mirantis/virtlet/blob/bd1f26c49e364eb4a7bb31d344b3482c89798f0b/docs/networking.md#L51)):*
> ```Markdown
> namespace. The special case is SR-IOV plugin which puts into pod network
> namespace a [Virtual Function](https://en.wikipedia.org/wiki/Single-root_input/output_virtualization)
> from host master device.
> ```

A special case is SR-IOV plugin which puts a [Virtual Function](https://en.wikipedia.org/wiki/Single-root_input/output_virtualization) into the pod network namespace.

---

*[docs/networking.md, line 63 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/534#-L0jq2XWaium7MT1yTla:-L0jq2XWaium7MT1yTlb:bxvq251) ([raw file](https://github.com/mirantis/virtlet/blob/bd1f26c49e364eb4a7bb31d344b3482c89798f0b/docs/networking.md#L63)):*
> ```Markdown
>    the was used by `tapmanager` to set up the network.
> 1. `vmwrapper` uses the key to ask `tapmanager` to send it the file
>    descriptors for the tap interfaces or description of SR-IOV VFs
> ```

or the description

---

*[docs/networking.md, line 107 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/534#-L0jp8fD6xeiiX8KBzhP:-L0jp8fD6xeiiX8KBzhQ:b-fhbwqx) ([raw file](https://github.com/mirantis/virtlet/blob/bd1f26c49e364eb4a7bb31d344b3482c89798f0b/docs/networking.md#L107)):*
> ```Markdown
> [virtlet-ds.yaml](../deploy/virtlet-ds.yaml) daemon set definition this option
> can be added to `virtlet` environment by setting `sriov_support=true` in
> `virtlet-config` config map.
> ```

[SR-IOV](https://github.com/hustcat/sriov-cni) CNI plugin requires running
qemu emulator with full root privileges, so it needs to be manually enabled during Virtlet deployment by setting `VIRTLET_SRIOV_SUPPORT` environment variable to a non-empty value for the `virtlet` container. In case if standard `deploy/virtlet-ds.yaml` is used, this can be done by setting`sriov_support=true` in `virtlet-config` ConfigMap.

---

*[docs/networking.md, line 110 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/534#-L0jpmYC9Tp7nCvL6Jfm:-L0jpmYC9Tp7nCvL6Jfn:bmj6zct) ([raw file](https://github.com/mirantis/virtlet/blob/bd1f26c49e364eb4a7bb31d344b3482c89798f0b/docs/networking.md#L110)):*
> ```Markdown
> 
> **NOTE:** Virtlet doesn't support `hostNetwork` pod setting because it
> cannot be impelemnted for VM in a meaningful way.
> ```

implemented (old typo but let's fix it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/534)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/534#-:-L0nNFi0wcucLKUihuFx:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/534#-:-L0nNjfSGVRubgftFpqg:bnfp4nl)*

**Pull request merged**
