### PR TITLE
Fix error handling in kubeclient used by tools

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/616)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/616#-:-L76LIsh-6uAdy4Usnhr:bnfp4nl)*

**Comment by lukaszo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/tools/kubeclient.go, line 358 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/616#-L79PCptR_DrKtDC-PDo:-L79PCptR_DrKtDC-PDp:b-6klzx2) ([raw file](https://github.com/mirantis/virtlet/blob/300100785ed96d0e110637f2aab6a940cfab8838/pkg/tools/kubeclient.go#L358)):*
> ```Go
> 		}
> 	}
> 	if err != nil {
> ```

why not in previous if?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/616)*

**Comment by lukaszo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/tools/kubeclient.go, line 358 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/616#-L79PCptR_DrKtDC-PDo:-L79PZ70zE8ckCYhRA0n:blx2k7v) ([raw file](https://github.com/mirantis/virtlet/blob/300100785ed96d0e110637f2aab6a940cfab8838/pkg/tools/kubeclient.go#L358)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

why not in previous if?
</blockquote></details>

actually why is it even needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/616)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/tools/kubeclient.go, line 358 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/616#-L79PCptR_DrKtDC-PDo:-L79PQk_dsc4DmjybTqQ:b-69qoht) ([raw file](https://github.com/mirantis/virtlet/blob/300100785ed96d0e110637f2aab6a940cfab8838/pkg/tools/kubeclient.go#L358)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

actually why is it even needed?
</blockquote></details>

Hmmm... Frankly speaking adding that to else in previous if would be probably cleaner. I just used the construct from https://github.com/Mirantis/virtlet/blob/07bba083e72038973269db32cf1bf14df121ec7c/tests/e2e/framework/pod_interface.go#L174

It's needed because we have a special case for successfully run commands which would return an exit code. It's treated by use not as an error and so we are transforming it in previous if to simple int.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/616)*

**Comment by lukaszo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/tools/kubeclient.go, line 358 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/616#-L79PCptR_DrKtDC-PDo:-L79Qj0SK3nRug2DtzGw:bxszptc) ([raw file](https://github.com/mirantis/virtlet/blob/300100785ed96d0e110637f2aab6a940cfab8838/pkg/tools/kubeclient.go#L358)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... Frankly speaking adding that to else in previous if would be probably cleaner. I just used the construct from https://github.com/Mirantis/virtlet/blob/07bba083e72038973269db32cf1bf14df121ec7c/tests/e2e/framework/pod_interface.go#L174

It's needed because we have a special case for successfully run commands which would return an exit code. It's treated by use not as an error and so we are transforming it in previous if to simple int.
</blockquote></details>

looks strange but ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/616)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/616#-:-L79QqXRTOsDkSAzRu_r:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/616#-:-L79SG85x9xo12JrlOww:bnfp4nl)*

**Comment by ivan4th** [comment]
I think it would be better to be consistent with Go conventions of exit code handling and return an error of specific type with the exit code inside it. We can use smth like https://github.com/kubernetes/client-go/blob/master/util/exec/exec.go#L31 although I'd prefer not to use it directly. See also: https://golang.org/pkg/os/exec/#ExitError (it has more info than we need, thus our own error type would be better)

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/616#-:-L7UPe_O-El7dZdldREa:b-v60uoz)*

**Comment by jellonek** [comment]
I think that adding new type adds new overhead. I would like to stick to proposed by Stan form there, and if you still would prefer to modify that (to be consistent, imo we also should have the same code in utils and in e2e framework) imo we should also modify an interface in e2e to be consistent with os.exec what could also eliminate the need for https://github.com/Mirantis/virtlet/blob/e5e5360fc41861c037a5aea916d4e726a31a9bcd/tests/e2e/framework/localcmd_interface.go

Also if we should do this change IMO we should stick to standard https://golang.org/pkg/os/exec/#ExitError instead of providing new type.

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/616#-:-L7Z3YVLLdeMVe1Oik-3:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/616#-:-L7ZIad0oYWwzd4guVwW:bnfp4nl)*

**Pull request merged**
