### PR TITLE
images: Fix metadata shredding

### PR DESCRIPTION
**Pull request by jellonek**
Closes: #101

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/104)

### CODE REVIEW

**Comment by nhlfr** [comment]
I wonder whether we shouldn't change a logic in `image.c`. The main cause of this error, as you are aware, is calling `GetLastError()` when image exists. So IMO we should return some other int than `-1` when image exists and handle that properly in Go codebase (i.e. do `GetLastError` only on `-1` result).

We will probably need to define these result ints in `image.h`.

**Comment by pigmej** [comment]
@jellonek rebase please?

**Comment by jellonek** [comment]
Done. Also updated logging, now uses `V(2)` as in rest of virtlet.

**Comment by jellonek** [comment]
Hmmm... This maybe be already resolved by #107 - i'll test this.

**Comment by jellonek** [comment]
Tested, after merging Michals #107 it's no longer needed.

**Pull request closed without merging**
