### PR TITLE
Passing environment variables

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/294)

### CODE REVIEW

**Comment by pigmej** [comment]
So point 1 can / should be implemented first, it doesn't need deeper explanation etc.

About 2 and 3. I'd go with "whatever defined in POD overrides /etc/environment", we may add a switch that will disable this behavior and it will merge POD defined items with /etc/environment. But as a default, I'd go with overriding.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[docs/design-proposals/environment-variables.md, line 10 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3OItAI1nptIflX-Ue:-Kl3OItBk4bn_UqMxGPD:b-14yez7) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L10)):*
> wtrite
typo :)

---

*[docs/design-proposals/environment-variables.md, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3PjfyKco9L6usBrmq:-Kl3PjfyKco9L6usBrmr:bh72vn3) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L35)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>
> ```bash
> TMPFILE=/tmp/env_$$
> cp /etc/environment ${TMPFILE}
> cat /etc/cloud/environment | while read line ; do
>   VARIABLE="$(echo $line | sed s/=.*//)"
>   if ! egrep -q "^${VARIABLE}=" /etc/environment ; then
>     echo "$line" >>${TMPFILE}
>   fi
> done
> mv ${TMPFILE} /etc/environment
```
</details>



I'm not sure if I like that script :)
```


---

*[docs/design-proposals/environment-variables.md, line 45 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3QkVItZy4Qfm1XEU1:-Kl3QkVJha169hSPad0c:bxyzzlf) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L45)):*
> `VirtletForcePodEnvironment: true` 

I'd go with opposite direction, enable by default (like in containers) and disable by option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/294#-:-Kl3NnpxS6jQ8gPi6A9F:brvz8cx)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/design-proposals/environment-variables.md, line 10 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3OItAI1nptIflX-Ue:-Kl3V76O7Btfit0oNypv:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L10)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> wtrite
typo :)
</blockquote></details>

Done.

---

*[docs/design-proposals/environment-variables.md, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3PjfyKco9L6usBrmq:-Kl3V9XDoQtzgkOq4lRA:b-jnu5q6) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L35)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> ```bash
> TMPFILE=/tmp/env_$$
> cp /etc/environment ${TMPFILE}
> cat /etc/cloud/environment | while read line ; do
>   VARIABLE="$(echo $line | sed s/=.*//)"
>   if ! egrep -q "^${VARIABLE}=" /etc/environment ; then
>     echo "$line" >>${TMPFILE}
>   fi
> done
> mv ${TMPFILE} /etc/environment
> ```


I'm not sure if I like that script :)
</blockquote></details>

It's only an example. Real implementation could do that in other way.

---

*[docs/design-proposals/environment-variables.md, line 45 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3QkVItZy4Qfm1XEU1:-Kl3VGAWhMSgKax0POf-:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L45)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> `VirtletForcePodEnvironment: true` 

I'd go with opposite direction, enable by default (like in containers) and disable by option.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/294)*

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[docs/design-proposals/environment-variables.md, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3PjfyKco9L6usBrmq:-Kl3ZD_qPiKIyDmYOTMm:bmr5ng) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L35)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

It's only an example. Real implementation could do that in other way.
</blockquote></details>

It's probably worth pointing out that Virtlet can make VMs execute the script using `bootcmd` section of `user-data` (it can be actually embedded there)
It can also be done using `runcmd` but perhaps `bootcmd` is better because the file will be modified early in the boot process.

---

*[docs/design-proposals/environment-variables.md, line 1 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIE4_-heVCtTy9ITii:-KlIE4_-heVCtTy9ITij:bow5h3m) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L1)):*
> ```Markdown
> # Environment variables passing to VM
> ```

Passing environment variables to VM

---

*[docs/design-proposals/environment-variables.md, line 4 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIE8eeejPLwXNckIif:-KlIE8eeejPLwXNckIig:bvguwy0) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L4)):*
> ```Markdown
> 
> Passing of environment variables set in pod definition, to VM created from this
> definition is based on [cloud-init](cloud-init-data-generation.md) support.
> ```

Virtlet uses [cloud-init](cloud-init-data-generation.md) mechanism to pass the environment variables from pod definition to the VM.

---

*[docs/design-proposals/environment-variables.md, line 6 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIEyFTeLC4ano7yfTV:-KlIEyFTeLC4ano7yfTW:b-kqnxwu) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L6)):*
> ```Markdown
> definition is based on [cloud-init](cloud-init-data-generation.md) support.
> 
> ## Virtlet aware images
> ```

Virtlet-aware

---

*[docs/design-proposals/environment-variables.md, line 13 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIGDOaOsmoiuXRtF2A:-KlIGDOaOsmoiuXRtF2B:b-znjbw) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L13)):*
> ```Markdown
> create file (e.g. under location `/etc/cloud/environment`) in standard shell
> script format (list of `KEY=value` pairs, one per line) which then can be sourced
> by any user shell script.
> ```

I'd write this section like this (it's not exactly shell script format -- /etc/environment file doesn't support expansion and this one also doesn't):
Virtlet uses `write_files` cloud-init module (`write_files` key in `user_data`) to write the pod-defined environment variables into `/etc/cloud/environment` using the same `KEY=value` format as used by `/etc/environment`. If the image was prepared specifically for Virtlet it can then utilize this file to load these values.

---

*[docs/design-proposals/environment-variables.md, line 18 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIHpZeR1bZcpbtp3DA:-KlIHpZeR1bZcpbtp3DB:b-aahlb0) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L18)):*
> ```Markdown
> 
> The common way to set system wide list of environment variables is to add them
> to `/etc/environment` - file used by many linux distributions at this time.
> ```

Most Linux distributions use `/etc/environment` file to store the system-wide list of environment variables.

---

*[docs/design-proposals/environment-variables.md, line 22 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIIPkgbmcZeJv8M122:-KlIIPkgbmcZeJv8M123:b-jyp2qb) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L22)):*
> ```Markdown
> feature Virtlet can provide a script, which then will merge the content
> of `/etc/environment` adding new lines from `/etc/cloud/environment` and setting
> existing variables to values from the last file.
> ```

See below concerning `bootcmd` approach

---

*[docs/design-proposals/environment-variables.md, line 24 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIINexO7JBxUxs_ckc:-KlIINexO7JBxUxs_ckd:bkbzd85) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L24)):*
> ```Markdown
> existing variables to values from the last file.
> 
> This could be done by extending above script:
> ```

by extending the following script:

---

*[docs/design-proposals/environment-variables.md, line 39 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIIYimOZZ-mLlAfkze:-KlIIYimOZZ-mLlAfkzf:bcabm1o) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L39)):*
> ```Markdown
> That way we keep support for original content of system environment file, with
> a method to overwrite theirs values and add new variables basing on content of
> pod definition.
> ```

This way one can combine the content of `/etc/environment` and `/etc/cloud/environment` with values from the latter taking precedence.

---

*[docs/design-proposals/environment-variables.md, line 41 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIJ9A1RzRaQjgZK9VW:-KlIJ9A1RzRaQjgZK9VX:b-w2pp3d) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L41)):*
> ```Markdown
> pod definition.
> 
> ## Forcing keeping original system environment values
> ```

BTW I thought what's the use case for this construct? You specify some vars in pod definition explicitly, knowing what kind of image you use, and then you tell Virtlet to forget about some of them. That's not something you can do with containers in k8s... Do we really need it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/294)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions.

---

*[docs/design-proposals/environment-variables.md, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3PjfyKco9L6usBrmq:-KlIlhqwtPx0LgC-VbgQ:b-49n4lq) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L35)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

It's probably worth pointing out that Virtlet can make VMs execute the script using `bootcmd` section of `user-data` (it can be actually embedded there)
It can also be done using `runcmd` but perhaps `bootcmd` is better because the file will be modified early in the boot process.
</blockquote></details>

Done. Chosen `bootcmd` - will verify in time of implementation if `runcmd` would be better suited.

---

*[docs/design-proposals/environment-variables.md, line 1 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIE4_-heVCtTy9ITii:-KlIkODUJjHVWMkdhaXw:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L1)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Passing environment variables to VM
</blockquote></details>

Done.

---

*[docs/design-proposals/environment-variables.md, line 4 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIE8eeejPLwXNckIif:-KlIkQLPiKo-A51MgmZA:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L4)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Virtlet uses [cloud-init](cloud-init-data-generation.md) mechanism to pass the environment variables from pod definition to the VM.
</blockquote></details>

Done.

---

*[docs/design-proposals/environment-variables.md, line 6 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIEyFTeLC4ano7yfTV:-KlIkR516-pbR9MAfL74:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L6)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Virtlet-aware
</blockquote></details>

Done.

---

*[docs/design-proposals/environment-variables.md, line 13 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIGDOaOsmoiuXRtF2A:-KlIkwxmSw3se9pog7SO:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L13)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'd write this section like this (it's not exactly shell script format -- /etc/environment file doesn't support expansion and this one also doesn't):
Virtlet uses `write_files` cloud-init module (`write_files` key in `user_data`) to write the pod-defined environment variables into `/etc/cloud/environment` using the same `KEY=value` format as used by `/etc/environment`. If the image was prepared specifically for Virtlet it can then utilize this file to load these values.

</blockquote></details>

Done.

---

*[docs/design-proposals/environment-variables.md, line 18 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIHpZeR1bZcpbtp3DA:-KlIldZuolqRA-5i3PSR:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L18)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Most Linux distributions use `/etc/environment` file to store the system-wide list of environment variables.
</blockquote></details>

Done.

---

*[docs/design-proposals/environment-variables.md, line 22 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIIPkgbmcZeJv8M122:-KlIle-mqp-b0E7ZWXVk:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L22)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

See below concerning `bootcmd` approach
</blockquote></details>

Done.

---

*[docs/design-proposals/environment-variables.md, line 24 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIINexO7JBxUxs_ckc:-KlIlet18zoja3e-fxFN:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L24)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

by extending the following script:
</blockquote></details>

Done.

---

*[docs/design-proposals/environment-variables.md, line 41 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIJ9A1RzRaQjgZK9VW:-KlIm0UKkU92Qd7XWANN:b-tdn6gu) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L41)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

BTW I thought what's the use case for this construct? You specify some vars in pod definition explicitly, knowing what kind of image you use, and then you tell Virtlet to forget about some of them. That's not something you can do with containers in k8s... Do we really need it?
</blockquote></details>

VMs are quite different from containers, so we have application level env variables and system level env variables. It would be nice to have a possibility to switch by option if system variables should be overwritten, or not - when app can use directly `/etc/cloud/environment`, so rest of system will not be affected by changes in system wide env file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/294)*

**Comment by pigmej** [comment]
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions.

---

*[docs/design-proposals/environment-variables.md, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3PjfyKco9L6usBrmq:-KlJ-6VabJ0ikr23GWND:bz8kv0f) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L35)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done. Chosen `bootcmd` - will verify in time of implementation if `runcmd` would be better suited.
</blockquote></details>

Anyway, can't we just merge all files without filtering? That filtering seems to me a bit "overcomplicated". And it makes the description of it also bit more "magical". Is there any reason why we can't merge all files in some defined order?

---

*[docs/design-proposals/environment-variables.md, line 41 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIJ9A1RzRaQjgZK9VW:-KlIzngxDl3xK7sKrY4W:buel4c7) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L41)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

VMs are quite different from containers, so we have application level env variables and system level env variables. It would be nice to have a possibility to switch by option if system variables should be overwritten, or not - when app can use directly `/etc/cloud/environment`, so rest of system will not be affected by changes in system wide env file.
</blockquote></details>

I'd treat it as a goodie, that's why I asked for changing default behaviour. Then we can leave that part not implemented, and implement it when it will be really needed. (use case needed)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/294)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions.

---

*[docs/design-proposals/environment-variables.md, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3PjfyKco9L6usBrmq:-KlOiRoLfCcaL0f7nmr4:b-l68br8) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L35)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

Anyway, can't we just merge all files without filtering? That filtering seems to me a bit "overcomplicated". And it makes the description of it also bit more "magical". Is there any reason why we can't merge all files in some defined order?
</blockquote></details>

O_O - this does exactly what you are asking for. This is simple merge and idk what do you mean by "filtering".

---

*[docs/design-proposals/environment-variables.md, line 39 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIIYimOZZ-mLlAfkze:-KlOi8PkcJYK1fkD1mAm:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L39)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

This way one can combine the content of `/etc/environment` and `/etc/cloud/environment` with values from the latter taking precedence.
</blockquote></details>

Done.

---

*[docs/design-proposals/environment-variables.md, line 41 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/294#-KlIJ9A1RzRaQjgZK9VW:-KlOhrsdPix2QCghskhc:b-71kw2m) ([raw file](https://github.com/mirantis/virtlet/blob/86a3fbc6dff3de4fca8e722837dd4301eace9652/docs/design-proposals/environment-variables.md#L41)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

I'd treat it as a goodie, that's why I asked for changing default behaviour. Then we can leave that part not implemented, and implement it when it will be really needed. (use case needed)
</blockquote></details>

Planned as described.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/294)*

**Comment by pigmej** [comment]
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions.

---

*[docs/design-proposals/environment-variables.md, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/294#-Kl3PjfyKco9L6usBrmq:-KlQjKYhUKqvCEnvCLOO:bzflzpn) ([raw file](https://github.com/mirantis/virtlet/blob/e0f806200a335c454da5d1e201cfe63b9ca73995/docs/design-proposals/environment-variables.md#L35)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

O_O - this does exactly what you are asking for. This is simple merge and idk what do you mean by "filtering".
</blockquote></details>

Handling duplicates etc. I'd go just copy whole content etc. Simpler, less logic etc. But yeah it's probably implementation detail only.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/294)*

**Comment by pigmej** [comment]
:lgtm: can be polished later / during implementation phase.

---

Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/294#-:-KlQk2gfea7AskkTs2IV:b-kr9esn)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/294#-:-KlR9PlXg0U1BMyznm5l:bnfp4nl)*

**Pull request merged**
