### PR TITLE
Don't use mount propagation when run on k8s 1.7

### PR DESCRIPTION
**Pull request by lukaszo**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/577)

### CODE REVIEW

**Comment by ivan4th** [comment]
Can we also do this in demo.sh?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/577#-:-L5JKYZSpbvUPkN3QLuq:b-riu5zj)*

**Comment by ivan4th** [comment]
Taking back my comment. The demo uses 1.8 all the time

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/577#-:-L5JNFFzsTXviUqcLZVI:b-hkai7v)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/577#-:-L5JNNylrKyIavntpe_B:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/577#-:-L5JNUjk8LTbWeHLE1nn:bnfp4nl)*

**Pull request merged**
