### PR TITLE
support building virtlet with myself vendor or "glide install"

### PR DESCRIPTION
**Pull request by volume-ji**
I want to build Mirantis/virtlet:latest with myself vendor other than "glide install" because it looks like downloading many useless package. So I submit this pr.

two point:
  1. delete a filter about local vendor
  2. add code logic to adapt myself vendor or "glide install" by environment "VIRTLET_SKIP_VENDOR"

dear @jellonek , do you agree with me?

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/829)

### CODE REVIEW

**Comment by volume-ji** [comment]
./sig test

**Comment by jellonek** [comment]
Still branch is not building on CI.

**Comment by jellonek** [comment]
You need to rebase on top of master to fix the current issue with building tests on CI.

**Comment by jellonek** [comment]
Ping.

**Comment by volume-ji** [comment]
rebase to new version

**Pull request merged**
