### PR TITLE
loglevel don't work

### LINKED ISSUE #731: There are plenty of useless info in virtlet log.
The ListContainers and ListPodSandbox info in log is useless.
It is more serious when there are many active pods. 
We should mask the QUERY info related to ListContainers and ListPodSandbox.

```
{"log":"filter:\n","stream":"stderr","time":"2018-07-31T01:47:21.62724036Z"}
{"log":"  state:\n","stream":"stderr","time":"2018-07-31T01:47:21.627247948Z"}
{"log":"    state: 1\n","stream":"stderr","time":"2018-07-31T01:47:21.627254817Z"}
{"log":"I0731 01:47:21.627438   16706 grpc.go:117] LEAVE: /runtime.v1alpha2.RuntimeService/ListContainers()\n","stream":"stderr","time":"2018-07-31T01:47:21.627485131Z"}
{"log":"{}\n","stream":"stderr","time":"2018-07-31T01:47:21.627500642Z"}
{"log":"I0731 01:47:21.630957   16706 grpc.go:108] ENTER: /runtime.v1alpha2.RuntimeService/ListPodSandbox():\n","stream":"stderr","time":"2018-07-31T01:47:21.631028224Z"}
{"log":"filter:\n","stream":"stderr","time":"2018-07-31T01:47:21.631053002Z"}
{"log":"  state: {}\n","stream":"stderr","time":"2018-07-31T01:47:21.631061146Z"}
{"log":"I0731 01:47:21.631015   16706 grpc.go:117] LEAVE: /runtime.v1alpha2.RuntimeService/ListPodSandbox()\n","stream":"stderr","time":"2018-07-31T01:47:21.631093453Z"}
{"log":"{}\n","stream":"stderr","time":"2018-07-31T01:47:21.631105845Z"}
{"log":"I0731 01:47:21.633625   16706 grpc.go:108] ENTER: /runtime.v1alpha2.RuntimeService/ListContainers():\n","stream":"stderr","time":"2018-07-31T01:47:21.633742902Z"}
{"log":"filter:\n","stream":"stderr","time":"2018-07-31T01:47:21.633766565Z"}
{"log":"  state:\n","stream":"stderr","time":"2018-07-31T01:47:21.633774304Z"}
{"log":"    state: 1\n","stream":"stderr","time":"2018-07-31T01:47:21.633783764Z"}
{"log":"I0731 01:47:21.633898   16706 grpc.go:117] LEAVE: /runtime.v1alpha2.RuntimeService/ListContainers()\n","stream":"stderr","time":"2018-07-31T01:47:21.633957653Z"}
{"log":"{}\n","stream":"stderr","time":"2018-07-31T01:47:21.633973099Z"}


```

### PR DESCRIPTION
**Pull request by yanxuean**
fix #731
The 731 is evil
Signed-off-by: yanxuean <yan.xuean@zte.com.cn>

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/738)

### CODE REVIEW

**Comment by yanxuean** [comment]
@jellonek PTAL

**Comment by yanxuean** [comment]
```
[cloud@cloud-test2:/var/lib/virtlet]$ ps -ef | grep virtlet
root      1025     1  0 Aug10 ?        00:00:02 /root/virtlet/images/http-server
root      7985     1  0 Aug10 ?        00:33:08 /root/virtlet/bin/criproxy -v 3 -logtostderr -connect /var/run/dockershim.sock,virtlet.cloud:/run/virtlet.sock -listen /run/criproxy.sock
root     14422 14404  0 16:55 ?        00:00:01 /usr/local/bin/virtlet --v 4
cloud    16089 12313  0 17:00 pts/0    00:00:00 grep --color=auto virtlet
```

```
[root@cloud-test1:~/virtlet/yaml/yan]$ kubectl logs virtlet-glrth -c virtlet -n kube-system
I0814 08:50:32.001786   12534 interface.go:360] Looking for default routes with IPv4 addresses
I0814 08:50:32.002029   12534 interface.go:365] Default route transits interface "ens3"
I0814 08:50:32.005800   12534 interface.go:174] Interface ens3 is up
I0814 08:50:32.005953   12534 interface.go:222] Interface "ens3" has 2 addresses :[192.168.122.196/24 fe80::5054:ff:fefa:a2eb/64].
I0814 08:50:32.006036   12534 interface.go:189] Checking addr  192.168.122.196/24.
I0814 08:50:32.006061   12534 interface.go:196] IP found 192.168.122.196
I0814 08:50:32.006087   12534 interface.go:228] Found valid IPv4 address 192.168.122.196 for interface "ens3".
I0814 08:50:32.006096   12534 interface.go:371] Found active IP 192.168.122.196
I0814 08:50:32.007562   12534 listener.go:66] UnixSocket Listener started
W0814 08:50:32.010140   12534 image.go:326] listing images: skipping image link "myimage%vsegw_paas_717.qcow2": stat "/var/lib/virtlet/images/data/8961703db3d575476e9b593996860d43ecf521608c3f9e015ce7efce8cbab948": stat /var/lib/virtlet/images/data/8961703db3d575476e9b593996860d43ecf521608c3f9e015ce7efce8cbab948: no such file or directory
I0814 08:50:32.010278   12534 manager.go:147] Starting server on socket /run/virtlet.sock
2018/08/14 08:50:32 transport: http2Server.HandleStreams failed to receive the preface from client: read unix /run/virtlet.sock->@: read: connection reset by peer
I0814 08:50:32.026359   12534 grpc.go:108] ENTER: /runtime.v1alpha2.RuntimeService/Version():
{}
I0814 08:50:32.026678   12534 grpc.go:117] LEAVE: /runtime.v1alpha2.RuntimeService/Version()
runtime_api_version: 0.1.0
runtime_name: virtlet
runtime_version: 0.1.0
version: 0.1.0
W0814 08:50:34.027123   12534 image.go:326] listing images: skipping image link "myimage%vsegw_paas_717.qcow2": stat "/var/lib/virtlet/images/data/8961703db3d575476e9b593996860d43ecf521608c3f9e015ce7efce8cbab948": stat /var/lib/virtlet/images/data/8961703db3d575476e9b593996860d43ecf521608c3f9e015ce7efce8cbab948: no such file or directory
I0814 08:50:36.797794   12534 grpc.go:108] ENTER: /runtime.v1alpha2.ImageService/ImageFsInfo():
{}
I0814 08:50:36.797859   12534 grpc.go:115] FAIL: /runtime.v1alpha2.ImageService/ImageFsInfo(): ImageFsInfo() not implemented
2018/08/14 08:50:37 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
I0814 08:50:46.801168   12534 grpc.go:108] ENTER: /runtime.v1alpha2.ImageService/ImageFsInfo():
{}
I0814 08:50:46.801244   12534 grpc.go:115] FAIL: /runtime.v1alpha2.ImageService/ImageFsInfo(): ImageFsInfo() not implemented
2018/08/14 08:50:47 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
I0814 08:50:56.804109   12534 grpc.go:108] ENTER: /runtime.v1alpha2.ImageService/ImageFsInfo():
{}
I0814 08:50:56.804174   12534 grpc.go:115] FAIL: /runtime.v1alpha2.ImageService/ImageFsInfo(): ImageFsInfo() not implemented
2018/08/14 08:50:57 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
[root@cloud-test1:~/virtlet/yaml/yan]$ kubectl logs virtlet-glrth -c virtlet -n kube-system
I0814 08:50:32.001786   12534 interface.go:360] Looking for default routes with IPv4 addresses
I0814 08:50:32.002029   12534 interface.go:365] Default route transits interface "ens3"
I0814 08:50:32.005800   12534 interface.go:174] Interface ens3 is up
I0814 08:50:32.005953   12534 interface.go:222] Interface "ens3" has 2 addresses :[192.168.122.196/24 fe80::5054:ff:fefa:a2eb/64].
I0814 08:50:32.006036   12534 interface.go:189] Checking addr  192.168.122.196/24.
I0814 08:50:32.006061   12534 interface.go:196] IP found 192.168.122.196
I0814 08:50:32.006087   12534 interface.go:228] Found valid IPv4 address 192.168.122.196 for interface "ens3".
I0814 08:50:32.006096   12534 interface.go:371] Found active IP 192.168.122.196
I0814 08:50:32.007562   12534 listener.go:66] UnixSocket Listener started
W0814 08:50:32.010140   12534 image.go:326] listing images: skipping image link "myimage%vsegw_paas_717.qcow2": stat "/var/lib/virtlet/images/data/8961703db3d575476e9b593996860d43ecf521608c3f9e015ce7efce8cbab948": stat /var/lib/virtlet/images/data/8961703db3d575476e9b593996860d43ecf521608c3f9e015ce7efce8cbab948: no such file or directory
I0814 08:50:32.010278   12534 manager.go:147] Starting server on socket /run/virtlet.sock
2018/08/14 08:50:32 transport: http2Server.HandleStreams failed to receive the preface from client: read unix /run/virtlet.sock->@: read: connection reset by peer
I0814 08:50:32.026359   12534 grpc.go:108] ENTER: /runtime.v1alpha2.RuntimeService/Version():
{}
I0814 08:50:32.026678   12534 grpc.go:117] LEAVE: /runtime.v1alpha2.RuntimeService/Version()
runtime_api_version: 0.1.0
runtime_name: virtlet
runtime_version: 0.1.0
version: 0.1.0
W0814 08:50:34.027123   12534 image.go:326] listing images: skipping image link "myimage%vsegw_paas_717.qcow2": stat "/var/lib/virtlet/images/data/8961703db3d575476e9b593996860d43ecf521608c3f9e015ce7efce8cbab948": stat /var/lib/virtlet/images/data/8961703db3d575476e9b593996860d43ecf521608c3f9e015ce7efce8cbab948: no such file or directory
I0814 08:50:36.797794   12534 grpc.go:108] ENTER: /runtime.v1alpha2.ImageService/ImageFsInfo():
{}
I0814 08:50:36.797859   12534 grpc.go:115] FAIL: /runtime.v1alpha2.ImageService/ImageFsInfo(): ImageFsInfo() not implemented
2018/08/14 08:50:37 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
I0814 08:50:46.801168   12534 grpc.go:108] ENTER: /runtime.v1alpha2.ImageService/ImageFsInfo():
{}
I0814 08:50:46.801244   12534 grpc.go:115] FAIL: /runtime.v1alpha2.ImageService/ImageFsInfo(): ImageFsInfo() not implemented
2018/08/14 08:50:47 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
I0814 08:50:56.804109   12534 grpc.go:108] ENTER: /runtime.v1alpha2.ImageService/ImageFsInfo():
{}
I0814 08:50:56.804174   12534 grpc.go:115] FAIL: /runtime.v1alpha2.ImageService/ImageFsInfo(): ImageFsInfo() not implemented
2018/08/14 08:50:57 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
W0814 08:51:04.035985   12534 image.go:326] listing images: skipping image link "myimage%vsegw_paas_717.qcow2": stat "/var/lib/virtlet/images/data/8961703db3d575476e9b593996860d43ecf521608c3f9e015ce7efce8cbab948": stat /var/lib/virtlet/images/data/8961703db3d575476e9b593996860d43ecf521608c3f9e015ce7efce8cbab948: no such file or directory
I0814 08:51:06.806553   12534 grpc.go:108] ENTER: /runtime.v1alpha2.ImageService/ImageFsInfo():
{}
I0814 08:51:06.806641   12534 grpc.go:115] FAIL: /runtime.v1alpha2.ImageService/ImageFsInfo(): ImageFsInfo() not implemented
2018/08/14 08:51:07 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
[root@cloud-test1:~/virtlet/yaml/yan]$

```

**Comment by jellonek** [comment]
Can you rebase your PR on top of master? I would like to process it quickly.

**Pull request merged**
