### PR TITLE
Add qcow2 flexvolume test

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/566)

### CODE REVIEW

**Comment by lukaszo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/qcow2_flexvolume_test.go, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/566#-L4aXQePAnNTZnKG9Mcq:-L4aXQePAnNTZnKG9Mcr:b-exbzkd) ([raw file](https://github.com/mirantis/virtlet/blob/6816252da1863ba22dcfb8c23e6785d56c719bd9/pkg/libvirttools/qcow2_flexvolume_test.go#L42)):*
> ```Go
> 		return "", err
> 	}
> 	tempfile.Close()
> ```

Why not defer?

---

*[pkg/libvirttools/qcow2_flexvolume_test.go, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/566#-L4aYCiBlbiLmNEKkMw3:-L4aYCiBlbiLmNEKkMw4:buvv897) ([raw file](https://github.com/mirantis/virtlet/blob/6816252da1863ba22dcfb8c23e6785d56c719bd9/pkg/libvirttools/qcow2_flexvolume_test.go#L50)):*
> ```Go
> 	v := qcow2Volume{
> 		volumeBase: volumeBase{
> 			&VMConfig{DomainUUID: testUuid},
> ```

Where testUuid does come from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/566)*

**Comment by jellonek** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/qcow2_flexvolume_test.go, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/566#-L4aXQePAnNTZnKG9Mcq:-L4aZtGUJzRaN8QXHCHB:b-o8nn58) ([raw file](https://github.com/mirantis/virtlet/blob/6816252da1863ba22dcfb8c23e6785d56c719bd9/pkg/libvirttools/qcow2_flexvolume_test.go#L42)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

Why not defer?
</blockquote></details>

It would be pointless - I wan't to close this file explicitly in this place, not at the end of the func.

---

*[pkg/libvirttools/qcow2_flexvolume_test.go, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/566#-L4aYCiBlbiLmNEKkMw3:-L4a_2O5gpzrB7kUG6rZ:bw78sn1) ([raw file](https://github.com/mirantis/virtlet/blob/6816252da1863ba22dcfb8c23e6785d56c719bd9/pkg/libvirttools/qcow2_flexvolume_test.go#L50)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

Where testUuid does come from?
</blockquote></details>

It's declared in other test file in the same package - `root_volumesource_test.go`.
Whole this file replicates what is done on same level for root volume source.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/566)*

**Comment by lukaszo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/qcow2_flexvolume_test.go, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/566#-L4aXQePAnNTZnKG9Mcq:-L4aa0owOa-OPng2q-Uo:b-7han37) ([raw file](https://github.com/mirantis/virtlet/blob/6816252da1863ba22dcfb8c23e6785d56c719bd9/pkg/libvirttools/qcow2_flexvolume_test.go#L42)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

It would be pointless - I wan't to close this file explicitly in this place, not at the end of the func.
</blockquote></details>

but in the case of the error it will not be closed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/566)*

**Comment by jellonek** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/qcow2_flexvolume_test.go, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/566#-L4aXQePAnNTZnKG9Mcq:-L4abMB8MAB2DBhPzvcC:b-6u9935) ([raw file](https://github.com/mirantis/virtlet/blob/6816252da1863ba22dcfb8c23e6785d56c719bd9/pkg/libvirttools/qcow2_flexvolume_test.go#L42)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

but in the case of the error it will not be closed
</blockquote></details>

Hmmm... You are correct. Will move that up to the upper if.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/566)*

**Comment by jellonek** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/libvirttools/qcow2_flexvolume_test.go, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/566#-L4aXQePAnNTZnKG9Mcq:-L4abt8wOVcSnUCvadCy:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/6816252da1863ba22dcfb8c23e6785d56c719bd9/pkg/libvirttools/qcow2_flexvolume_test.go#L42)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... You are correct. Will move that up to the upper if.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/566)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/566#-:-L4acY_KCC1HBt_P0Ti5:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/566#-:-L4acjjchP9Zb6eIcizT:bnfp4nl)*

**Pull request merged**
