### PR TITLE
Environment variables support

### PR DESCRIPTION
**Pull request by jellonek**
Implementation of first part of https://github.com/Mirantis/virtlet/blob/master/docs/design-proposals/environment-variables.md#virtlet-aware-images

- [x] code
- [x] docs

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/305)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/libvirttools/virtualization.go, line 360 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/305#-KlyEqSoDuxdd6jRGl3b:-KlyEqSoDuxdd6jRGl3c:b-fickcr) ([raw file](https://github.com/mirantis/virtlet/blob/b74f9fe59ee4cbc55d9b79caecaece538f44f2c1/pkg/libvirttools/virtualization.go#L360)):*
> ```Go
> }
> 
> func getEnvVarsFileData(keyVals []*kubeapi.KeyValue) string {
> ```

I think this is cloud-init-related detail, so it should probably go to `cloud_init.go`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305)*

**Comment by vefimova** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/environment-variables.md, line 8 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/305#-Kly072EHKwTFHE_cZz2:-Kly072EHKwTFHE_cZz3:bqdnntq) ([raw file](https://github.com/mirantis/virtlet/blob/b74f9fe59ee4cbc55d9b79caecaece538f44f2c1/docs/environment-variables.md#L8)):*
> in standard in linux systems world `/etc/environment` file.
Mayb be just 'in standard linux `/etc/environment` file.'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/environment-variables.md, line 8 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/305#-Kly072EHKwTFHE_cZz2:-KlyGOiErODQVArsiPEI:btjuz50) ([raw file](https://github.com/mirantis/virtlet/blob/b74f9fe59ee4cbc55d9b79caecaece538f44f2c1/docs/environment-variables.md#L8)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

> in standard in linux systems world `/etc/environment` file.
Mayb be just 'in standard linux `/etc/environment` file.'
</blockquote></details>

Ack. Will fix that.

---

*[pkg/libvirttools/virtualization.go, line 360 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/305#-KlyEqSoDuxdd6jRGl3b:-KlyG22_g0ljjIfJ5lgq:b-ajvwtu) ([raw file](https://github.com/mirantis/virtlet/blob/b74f9fe59ee4cbc55d9b79caecaece538f44f2c1/pkg/libvirttools/virtualization.go#L360)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I think this is cloud-init-related detail, so it should probably go to `cloud_init.go`
</blockquote></details>

Didn't wanted to have in `cloud_init.go` any thing operating on `kubeapi`, that's why this func does that there, instead of doing that in this other file. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305)*

**Comment by vefimova** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305#-:-KlyIzHXIGVnvFGjixqx:bnfp4nl)*

**Comment by vefimova** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/environment-variables.md, line 5 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/305#-KlydSAKJG8YcPSYEJz4:-KlydSAKJG8YcPSYEJz5:b5aenbe) ([raw file](https://github.com/mirantis/virtlet/blob/a36c8a5b24376f2e7c061add49b381719f29b374/docs/environment-variables.md#L5)):*
> ```Markdown
> Virtlet supports passing environment variables to VM by using
> [cloud-init](http://cloudinit.readthedocs.io/en/latest/index.html).
> Variables set in container part of pod definition, along with several other
> ```

The environment variables set for the container the pod definition

---

*[docs/environment-variables.md, line 8 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/305#-Klyck90-twB3e1MpzS5:-Klyck90-twB3e1MpzS6:b-pswo0m) ([raw file](https://github.com/mirantis/virtlet/blob/a36c8a5b24376f2e7c061add49b381719f29b374/docs/environment-variables.md#L8)):*
> ```Markdown
> predefined by kubernetes environment, are written to `/etc/cloud/environment`
> file. It can be sourced/used by any Virtlet aware application. Format of this
> file is the same as in standard in linux `/etc/environment` file.
> ```

... file which can be sourced/used by applications running in the VM. The format of this file...

I'd refrain from introducing the term "Virtlet aware application" as it's a bit too serious-sounding for an app that uses just one hardcoded path. Also non-Virtlet-aware images can be tweaked with cloud-init  to make use of this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/libvirttools/virtualization.go, line 360 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/305#-KlyEqSoDuxdd6jRGl3b:-KlydqHleQ2Psirlt33L:b-ooiq40) ([raw file](https://github.com/mirantis/virtlet/blob/b74f9fe59ee4cbc55d9b79caecaece538f44f2c1/pkg/libvirttools/virtualization.go#L360)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Didn't wanted to have in `cloud_init.go` any thing operating on `kubeapi`, that's why this func does that there, instead of doing that in this other file. 
</blockquote></details>

Ok will update this part myself in my PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/environment-variables.md, line 5 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/305#-KlydSAKJG8YcPSYEJz4:-KlyeJWI_bkaINl7LmPQ:bb6sh2i) ([raw file](https://github.com/mirantis/virtlet/blob/a36c8a5b24376f2e7c061add49b381719f29b374/docs/environment-variables.md#L5)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

The environment variables set for the container the pod definition
</blockquote></details>

Ack.

---

*[docs/environment-variables.md, line 8 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/305#-Klyck90-twB3e1MpzS5:-KlyeKOpYOTarjDANsj2:bsw7723) ([raw file](https://github.com/mirantis/virtlet/blob/a36c8a5b24376f2e7c061add49b381719f29b374/docs/environment-variables.md#L8)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

... file which can be sourced/used by applications running in the VM. The format of this file...

I'd refrain from introducing the term "Virtlet aware application" as it's a bit too serious-sounding for an app that uses just one hardcoded path. Also non-Virtlet-aware images can be tweaked with cloud-init  to make use of this file.
</blockquote></details>

Ok. Will change this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305)*

**Comment by vefimova** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 441 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/305#-KlywapubOmJNqKqe6VC:-KlywapubOmJNqKqe6VD:b-mtw1kk) ([raw file](https://github.com/mirantis/virtlet/blob/e63a99e3f5e83f84216e798bca2d1298f0f686da/pkg/libvirttools/virtualization.go#L441)):*
> ```Go
> 			in.PodSandboxId, config.Image.Image, cloneName, config.Labels,
> 			config.Annotations, nocloudFile, v.timeFunc)
> 		if err != nil {
> ```

The thing is that err value will be set at time of declaring funcion and hence will be nil even if there will be failure later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305)*

**Comment by jellonek** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 441 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/305#-KlywapubOmJNqKqe6VC:-KlyzsRUvXj1eGi7vI7q:b8o163z) ([raw file](https://github.com/mirantis/virtlet/blob/e63a99e3f5e83f84216e798bca2d1298f0f686da/pkg/libvirttools/virtualization.go#L441)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

The thing is that err value will be set at time of declaring funcion and hence will be nil even if there will be failure later.
</blockquote></details>

Not exactly. Code in defered func will be called for every `return` after this definition, and will operate on `err` variable from this func scope, so on value at the time of exiting this func.
This is why integration tests which are covering that passed in https://travis-ci.org/Mirantis/virtlet/builds/240104500

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305)*

**Comment by vefimova** [comment]
:lgtm:

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305#-:-Klz06cLGAYkSjIJnX98:bnfp4nl)*

**Comment by vefimova** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/305#-:-KlzebdDGhnxv0-k2LiV:bnfp4nl)*

**Pull request merged**
