### PR TITLE
dhcp: Base for dhcp server

### PR DESCRIPTION
**Pull request by jellonek**
- [x] base skeleton for serving 2 protocols on 2 different connection types
- [x] grpc on unix socket server for configuration providing/modifying/removal
- [x] skeleton for dhcp server
- [x] passing real data from configuration as options (ip/routes, hardcoded dns entries read from host?)

With this points fulfilled we will have possibility to add support for dhcp into calico branch.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/110)

### CODE REVIEW

**Comment by jellonek** [comment]
https://github.com/Mirantis/virtlet/pull/110/files#diff-98e28311e3529c25828c931b46319afaR45 - this was chosen as a simple way to store/restore internal metadata. Also traversing through list is suboptimal, but for now - we don't need any extreme performance.

When this will be too slow - we will be able to change saving/updating/restoring metadata in hashmap, internally in simple map, externally - in e.x. redis or something similar.
This is not added now due to unnecessary complication and no need for greater performance for this moment.

**Comment by nhlfr** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/dhcp/README.md, line 5 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/110#-KWCiMULjKL_PfMu-i6G:-KWCiMULjKL_PfMu-i6H:b-ydlv44) ([raw file](https://github.com/mirantis/virtlet/blob/7736852f13b273e7099bcd5661c7d18149228264/pkg/dhcp/README.md#L5)):*
> ```Markdown
> 
> ```sh
>   protoc --go_out=plugins=grpc:. configuration.proto
> ```

Why two spaces at the beginning?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/110)*

**Comment by jellonek** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/dhcp/README.md, line 5 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/110#-KWCiMULjKL_PfMu-i6G:-KWCq7pW88VTktZSCzHa:bf26jc) ([raw file](https://github.com/mirantis/virtlet/blob/7736852f13b273e7099bcd5661c7d18149228264/pkg/dhcp/README.md#L5)):*
<details><summary><i>Previously, nhlfr (Michal Rostecki) wrote…</i></summary>
> Why two spaces at the beginning?
</details>
Good catch. Just habit. Will fix this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/110)*

**Comment by jellonek** [comment]
For now, there is no passing any dns values - should be rethinked.

**Comment by ivan4th** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dhcpserver/dhcp-server.go, line 45 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/110#-KWcWSjLcyF2eijoV4dP:-KWcWSjLcyF2eijoV4dQ:b-m6hlvt) ([raw file](https://github.com/mirantis/virtlet/blob/232c29dfb0ed78cc308fdf53826bf615dabea473/cmd/dhcpserver/dhcp-server.go#L45)):*
> ```Go
> 		os.Exit(1)
> 	}
> 	glog.Infof("Starting server on socket %s", *socketPath)
> ```

`glog.V(1)` maybe?

---

*[pkg/dhcp/server/dhcp_server.go, line 35 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/110#-KWcXXSUjwo7CLhQTWeG:-KWcXXSUjwo7CLhQTWeH:b-nnai9h) ([raw file](https://github.com/mirantis/virtlet/blob/232c29dfb0ed78cc308fdf53826bf615dabea473/pkg/dhcp/server/dhcp_server.go#L35)):*
> ```Go
> )
> 
> type dHCPServer struct {
> ```

somewhat strange casing, maybe `dhcpServer` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/110)*

**Comment by jellonek** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dhcpserver/dhcp-server.go, line 45 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/110#-KWcWSjLcyF2eijoV4dP:-KWc_rOJkHS6xWBE02IA:b-f06h8g) ([raw file](https://github.com/mirantis/virtlet/blob/232c29dfb0ed78cc308fdf53826bf615dabea473/cmd/dhcpserver/dhcp-server.go#L45)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> `glog.V(1)` maybe?
</details>
Yes, good catch.

---

*[pkg/dhcp/server/dhcp_server.go, line 35 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/110#-KWcXXSUjwo7CLhQTWeG:-KWc_zxx411LuCGCfLar:b-wmjwer) ([raw file](https://github.com/mirantis/virtlet/blob/232c29dfb0ed78cc308fdf53826bf615dabea473/pkg/dhcp/server/dhcp_server.go#L35)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary>
> somewhat strange casing, maybe `dhcpServer` ?
</details>
Specific shortcuts in golang should be named in upcase, like DNS, DHCP, IP, ID, but i tried to not export this from package and this is why it have so ugly name. I think that your proposal is much better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/110)*

**Comment by ivan4th** [comment]
LGTM, but we need tests for that, and not just integration tests.

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/110#-:-KXFlGFH3PSsDnz6Y6_O:b5n2v6q)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/110#-:-KXFlQuGi7l24AhZNiMd:bnfp4nl)*

**Pull request merged**
