### PR TITLE
Added resource management doc

### PR DESCRIPTION
**Pull request by vefimova**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/299)

### CODE REVIEW

**Comment by jellonek** [comment]
Whole file has space as first column - looks like something non intentional.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/resource_managment.md, line 4 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KlsnWiUhRy7HOWcWENO:-KlsnWiUhRy7HOWcWENP:b-owu0i5) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L4)):*
> ```Markdown
>  ## Resource monitoring on node
>  All data about current resource usage are collected by cadvisor, so when VM is started in Virtlet container (it's not using a separate container for VM) - cadvisor will return only resources used by `vmwrapper`, which uses this container only during pod start/cleanup
>   (networking setup/teardown). This means that scheduler has info that virtlet controlled pods do not use any RAM/cpu when there are no limits set in pod definition.
> ```

additional space at the beginning of line?

---

*[docs/resource_managment.md, line 10 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KlsmZMWxqPQvkVEZ6Ew:-KlsmZMWxqPQvkVEZ6Ex:b-50hjx8) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L10)):*
> ```Markdown
>  1. `shares` - relative value of cpu time assigned, not recommended for using in production as it's hard to predict actual performance as it highly depends on neighbours groups.
>  1. `CFS CPU bandwidth control` - period and quota - hard limits.
>  `Parent_Period/Quota >= Child_1_Period/Quota + ..+ Child_N_Period/Quota`,
> ```

inconsistent spaces around `..`

---

*[docs/resource_managment.md, line 24 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KlsnGqNrDjpeSJ0PLh4:-KlsnGqNrDjpeSJ0PLh5:b2mw1v3) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L24)):*
> ```Markdown
>  rchives/libvir-list/2015-June/msg00923.html).
>  1. `emulator_period` and `emulator_quota` - for emulator threads => for each VM we have extra consuming by qemu threads and the amount is currently unlimited. At the same time benchmarking can show that on unlimited domains, qemu threads depending on type of operatio
>  n (disk or networking I/O) can consume from ~40% to ~80% from overall guest VM physical CPU usage.
> ```

Line broken in middle of word.

---

*[docs/resource_managment.md, line 31 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-Klsn3-F1miADX77HvOM:-Klsn3-F1miADX77HvON:b2mw1v3) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L31)):*
> ```Markdown
>  #### CPU overcommit
>  It's outlined that linux scheduler doesn't perform well in case of CPU overcommitment and if it's not caused real need (like having multi-core VM to perform build/compile, running application inside that can effectively utilize multiple cores and was designed for par
>  allel processing) and widely recommended to use one vCPU per VM otherwise you can expect performance degradation.
> ```

Line broken in middle of word.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/299#-:-KlsnN0dE0yygYv_Y5Ig:b-u1dox4)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[docs/resource_managment.md, line 21 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-Klsp7VprZTdmByaMDKb:-Klsp7VprZTdmByaMDKc:bic1rjp) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L21)):*
> ```Markdown
>  ### Libvirt CPU allocation:
>  1. `shares` is set per each vCPU.
>  1. `period` and `quota` are set per each vCPU =>  comparing to containers resources consumed by VM with current settings will be greater in numvCPUs times per VM then per container. (More details re reasons of libvirt per-vCPU cgroup approach https://www.redhat.com/a
> ```

"=> with current settings resources consumed by VM will be greater (comparing to containers) by numvCPU times per container."
this seems to be better, but i'm not sure if this was what author had in mind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/299)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[docs/resource_managment.md, line 14 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmB_olzImXKQdJRlte_:-KmB_olzImXKQdJRltea:b-wn8typ) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L14)):*
> ```Markdown
> 
>  ### K8s CPU allocation:
>  1. `shares` set per container.
> ```

are set per container

---

*[docs/resource_managment.md, line 25 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBa4UW2rc78QlVwZ89:-KmBa4UW2rc78QlVwZ8A:b-y807f7) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L25)):*
> ```Markdown
>  1. `emulator_period` and `emulator_quota` - for emulator threads => for each VM we have extra consuming by qemu threads and the amount is currently unlimited. At the same time benchmarking can show that on unlimited domains, qemu threads depending on type of operatio
>  n (disk or networking I/O) can consume from ~40% to ~80% from overall guest VM physical CPU usage.
>  1. vCPUs per VM - commonly recommended to have 1 set (see details in section **"CPU overcommit"** below).
> ```

it's commonly recommended to have vCPU count set to 1

---

*[docs/resource_managment.md, line 30 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBaw6fd8mOM8tMgDnl:-KmBaw6fd8mOM8tMgDnm:bim3bij) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L30)):*
> ```Markdown
> 
>  #### CPU overcommit
>  It's outlined that linux scheduler doesn't perform well in case of CPU overcommitment and if it's not caused real need (like having multi-core VM to perform build/compile, running application inside that can effectively utilize multiple cores and was designed for par
> ```

outlined where? any links? maybe the link below this paragraph? (need to make this clear)

---

*[docs/resource_managment.md, line 40 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBbBIdHBZBsJy_cq8m:-KmBbBIdHBZBsJy_cq8n:bzi6oit) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L40)):*
> ```Markdown
>  ### Virtlet CPU resources management
>  1. By default, all VMs are created with 1 vCPU.
>  To change vCPU number for VM-Pod you have to add annotation `VirtletVCPUCount `with desired number, see [examples/cirros-vm.yaml](../examples/cirros-vm.yaml).
> ```

`VirtletVCPUCount` -- misplaced apostrophe.

---

*[docs/resource_managment.md, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBbG-xuN6-70DYtEYN:-KmBbG-xuN6-70DYtEYO:b-31405c) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L41)):*
> ```Markdown
>  1. By default, all VMs are created with 1 vCPU.
>  To change vCPU number for VM-Pod you have to add annotation `VirtletVCPUCount `with desired number, see [examples/cirros-vm.yaml](../examples/cirros-vm.yaml).
>  1. Taking into account **2** in **"Libvirt CPU Allocation"** Virtlet divides equally assinged cpu resource limit among VM's vCPU threads.
> ```

Due to p.2 in **"Libvirt CPU Allocation"**, Virtlet spreads the assigned CPU resource limit equally among VM's vCPU threads.

---

*[docs/resource_managment.md, line 46 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBlU1Iw-MWKU-rg_a3:-KmBlU1J3C-9jnUXPkYY:b4tqveu) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L46)):*
> ```Markdown
>  ### K8s memory allocation
>  Omitting memory setting, i.e. passed value 0, leads to unlimited memory usage for container
>  doesn't support container memory swap, when using docker container is created with --memory-swappiness=0 (see more https://github.com/kubernetes/kubernetes/issues/7294).
> ```

"Setting memory limit to 0 or omitting it means there's no memory limit for the container."

As of the swap, having swap on k8s nodes in unsupported. It may work but such a cluster is considered to be misconfigured basically and only good for testing. This may be acceptable for some DIND/local-cluster setup but not for a real cluster.

---

*[docs/resource_managment.md, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBmSiQYH8eZevLpxFm:-KmBmSiQYH8eZevLpxFn:bqs2vsp) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L50)):*
> ```Markdown
>  ### [Libvirt memory allocation](http://libvirt.org/formatdomain.html#elementsMemoryAllocation)
>  1. `memory` - allocated RAM memory at VM boot.
>  1. `memtune=>hard_limit` - cgroup memory limit on all domain including qemu itself usage. However, it's claimed that such limit should be set accurately.
> ```

cgroup memory limit on all domains which includes the memory used by qemu processes. "However, it's claimed that such limit should be set accurately."  -- what's claiming this and what does it mean, "accurately"?

---

*[docs/resource_managment.md, line 54 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBmv7YPv9Eh4eXfx9e:-KmBmv7YPv9Eh4eXfx9f:b-gc1hex) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L54)):*
> Overcommit memory to a ~150% of physical RAM.

What does this mean? It's done always, triggered by some setting, it's max or recommended value?

Re swap, one should not use swap on k8s nodes in the production setting.

---

*[docs/resource_managment.md, line 59 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBnE3w1z9fQ0VMganT:-KmBnE3xoD-ctkhiRmzL:bat2l37) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L59)):*
> ```Markdown
> 
>  ### Virtlet Memory resources management
>  1. By default, each VM is assugned to 1GB of RAM. To set other value you need set resource memory limit for container, see [examples/cirros-vm.yaml](../examples/cirros-vm.yaml).
> ```

each VM is assigned 1GB or RAM (note the typo in 'assigned')

---

*[docs/resource_managment.md, line 60 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBnLrhhqQrpddrV45T:-KmBnLrhhqQrpddrV45U:bkslflf) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L60)):*
> ```Markdown
>  ### Virtlet Memory resources management
>  1. By default, each VM is assugned to 1GB of RAM. To set other value you need set resource memory limit for container, see [examples/cirros-vm.yaml](../examples/cirros-vm.yaml).
>  2. Virtlet generate domain's xml with setting "memoryBacking"=>locked to prevent swapping out domain's pages.
> ```

Virtlet generates domain XML with memoryBacking=locked setting

---

*[docs/resource_managment.md, line 62 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBnSGCj0bqIPGCNQFy:-KmBnSGCj0bqIPGCNQFz:b21gmg9) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L62)):*
> ```Markdown
>  2. Virtlet generate domain's xml with setting "memoryBacking"=>locked to prevent swapping out domain's pages.
> 
>  ## Summary of planned action items:
> ```

of the action items

---

*[docs/resource_managment.md, line 65 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBng2tTw0dzXHL3Sd3:-KmBng2tTw0dzXHL3Sd4:b79fk2w) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L65)):*
> ```Markdown
>  1. Implement [CRI container stats methods](https://github.com/kubernetes/kubernetes/issues/27097) for Virtlet.
> 
>  1. According to **2** and **3** in **"Libvirt CPU Allocation"** we need to elaborate some rule of setting CFS CPU bandwidth limits spreaded among qemu and vcpu threads, thus k8s scheduler could have right assumptions on allocated resources on the node.
> ```

we need to invent some rule of setting CFS CPU bandwidth limit spread among QEMU and vCPU threads, so as to make k8s scheduler have right assumptions about the resources allocated on the node

---

*[docs/resource_managment.md, line 67 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBo1QsjmZWLkc2njy5:-KmBo1QsjmZWLkc2njy6:birhysx) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L67)):*
> ```Markdown
>  1. According to **2** and **3** in **"Libvirt CPU Allocation"** we need to elaborate some rule of setting CFS CPU bandwidth limits spreaded among qemu and vcpu threads, thus k8s scheduler could have right assumptions on allocated resources on the node.
> 
>  1. Research on how to set up memory [hard limits](http://libvirt.org/formatdomain.html#elementsMemoryTuning) for VM-pod.
> ```

Research how to configure the hard limits on memory for VM pods

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/299)*

**Comment by vefimova** [comment]
Review status: 0 of 1 files reviewed at latest revision, 22 unresolved discussions.

---

*[docs/resource_managment.md, line 2 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KlslzLLfVwhoQP44enH:-KmbmM635pL3WN_coXrU:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L2)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

on the node
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 4 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-Klsm9ilgJW45SaH9Tzf:-KmbvqSjYb8jW4udVAp1:b-itp894) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L4)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

everywhere: cAdvisor

All the data ... inside the Virtlet container ...

also -- qemu/kvm processes run inside the Virtlet container too, not just `vmwrapper`. So perhaps this can be put as all the resource usage being lumped together and ascribed to Virtlet pod.
</blockquote></details>

rephrased, pls check

---

*[docs/resource_managment.md, line 4 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KlsnWiUhRy7HOWcWENO:-Kmbvz427J6828m00qlj:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L4)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

additional space at the beginning of line?
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 8 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-Klsn7lRweFbanuZxR47:-Kmbw8SgcnNp2h48PMWj:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L8)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

the actual performance which highly depends on the neighboring cgroups
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 10 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KlsmZMWxqPQvkVEZ6Ew:-KmbwEGwSUoZQXgZ8GBU:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L10)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

inconsistent spaces around `..`
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 14 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmB_olzImXKQdJRlte_:-KmbwXDdTlEDCQuYriqB:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L14)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

are set per container
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 21 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-Klsp7VprZTdmByaMDKb:-KmbwhqoU5VtH7_ctVmD:b-itp894) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L21)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

"=> with current settings resources consumed by VM will be greater (comparing to containers) by numvCPU times per container."
this seems to be better, but i'm not sure if this was what author had in mind.
</blockquote></details>

rephrased, pls check

---

*[docs/resource_managment.md, line 22 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KlsnZy3S1eobPgmN16S:-KmbwkHxVhrqR7CTtoyt:b-itp894) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L22)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

can't understand this frankly ...
</blockquote></details>

rephrased, pls check

---

*[docs/resource_managment.md, line 24 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KlsnGqNrDjpeSJ0PLh4:-Kmc-9p4-h-JL1BwHztg:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L24)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Line broken in middle of word.
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 25 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBa4UW2rc78QlVwZ89:-Kmc-LF4DchCauFSu1jy:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L25)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

it's commonly recommended to have vCPU count set to 1
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 30 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBaw6fd8mOM8tMgDnl:-Kmc-YwHXRuRuE2eZMqG:b84cdfy) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L30)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

outlined where? any links? maybe the link below this paragraph? (need to make this clear)
</blockquote></details>

yep, below link contains more details. As this is all one paragraph summarizing the main aspects, I put it at the end of it.

---

*[docs/resource_managment.md, line 31 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-Klsn3-F1miADX77HvOM:-Kmc-RkBzQUfZfLpxJ6F:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L31)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Line broken in middle of word.
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 40 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBbBIdHBZBsJy_cq8m:-Kmc06UfK912og-Ts_Gl:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L40)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`VirtletVCPUCount` -- misplaced apostrophe.
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBbG-xuN6-70DYtEYN:-Kmc0SAONEGjrNH1HUSP:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L41)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Due to p.2 in **"Libvirt CPU Allocation"**, Virtlet spreads the assigned CPU resource limit equally among VM's vCPU threads.
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 46 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBlU1Iw-MWKU-rg_a3:-Kmc72QZH2wDlNvmlvA3:b-iz19yg) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L46)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

"Setting memory limit to 0 or omitting it means there's no memory limit for the container."

As of the swap, having swap on k8s nodes in unsupported. It may work but such a cluster is considered to be misconfigured basically and only good for testing. This may be acceptable for some DIND/local-cluster setup but not for a real cluster.
</blockquote></details>

fixed, pls check.

---

*[docs/resource_managment.md, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBmSiQYH8eZevLpxFm:-Kmc18x2uRv-e4tqQZ5A:bsg0mn1) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L50)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

cgroup memory limit on all domains which includes the memory used by qemu processes. "However, it's claimed that such limit should be set accurately."  -- what's claiming this and what does it mean, "accurately"?
</blockquote></details>

fixed, added link

---

*[docs/resource_managment.md, line 54 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBmv7YPv9Eh4eXfx9e:-Kmc35pq5NZV6LN1FlMe:bj3el32) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L54)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

> Overcommit memory to a ~150% of physical RAM.

What does this mean? It's done always, triggered by some setting, it's max or recommended value?

Re swap, one should not use swap on k8s nodes in the production setting.
</blockquote></details>

yes, re swap and k8s, but this paragraph regards to memory overcommit considerations in common case.
rephrased to make it clearer.
More details are in the link below.

---

*[docs/resource_managment.md, line 59 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBnE3w1z9fQ0VMganT:-Kmc2I1LTaWzZqgPRm5d:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L59)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

each VM is assigned 1GB or RAM (note the typo in 'assigned')
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 60 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBnLrhhqQrpddrV45T:-Kmc2Cw2TR0uHA0rJ4u-:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L60)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Virtlet generates domain XML with memoryBacking=locked setting
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 62 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBnSGCj0bqIPGCNQFy:-Kmc2M894W09dw2WqygH:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L62)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

of the action items
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 65 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBng2tTw0dzXHL3Sd3:-Kmc2sg8jX-EzRhqPOj9:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L65)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

we need to invent some rule of setting CFS CPU bandwidth limit spread among QEMU and vCPU threads, so as to make k8s scheduler have right assumptions about the resources allocated on the node
</blockquote></details>

Done.

---

*[docs/resource_managment.md, line 67 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmBo1QsjmZWLkc2njy5:-Kmc2tHpHEvvdrm4BQvZ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L67)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Research how to configure the hard limits on memory for VM pods
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/299)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 23 unresolved discussions.

---

*[docs/resource_managment.md, line 51 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmfD7s1S2I0FJ51sfZR:-KmfD7s1S2I0FJ51sfZS:bxcimwb) ([raw file](https://github.com/mirantis/virtlet/blob/d9f8da997cdfc72c000184b1a6abda6170e8bbab/docs/resource_managment.md#L51)):*
> ```Markdown
> 
> #### Memory overcommit
> Overcommit memory value can reach ~150% of physycal RAM amount. This relies on assumtion that most processes do not access 100% of their allocated memory all the time. So you can grant guest VMs more RAM than actually is available on the host. However, this strongly depends on memory swap size available on the node and workloads of VMs memory consumptions.
> ```

s/physycal/physical/ 
s/assumtion/assumption/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/299)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 23 unresolved discussions.

---

*[docs/resource_managment.md, line 21 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-Klsp7VprZTdmByaMDKb:-Kmf9_MBI2X697Uzws5v:bnhh6wy) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L21)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

rephrased, pls check
</blockquote></details>

"consumption" is a wrong word here b/c it's actually the limit, the VM can consume much less CPU than that. I'd say ... so actual CPU quota is `quota` value from the domain definition times the number of vCPUs.

---

*[docs/resource_managment.md, line 22 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KlsnZy3S1eobPgmN16S:-KmfB_Yl6lRPnfrLZgSg:b-3j7gex) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L22)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

rephrased, pls check
</blockquote></details>

`emulator_period` and `emulator_quota` denote the limits for emulator activities not tied to vCPUs. Benchmarks show that these activities may measure up to 40-80% of overall physical CPU usage by QEMU/KVM process running the guest VM. At this time Virtlet doesn't support setting these values, but there are plans to fix this in future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/299)*

**Comment by vefimova** [comment]
Review status: 0 of 1 files reviewed at latest revision, 23 unresolved discussions.

---

*[docs/resource_managment.md, line 21 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-Klsp7VprZTdmByaMDKb:-KmfV0WH-WM2ihxKFloN:b78ueax) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L21)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

"consumption" is a wrong word here b/c it's actually the limit, the VM can consume much less CPU than that. I'd say ... so actual CPU quota is `quota` value from the domain definition times the number of vCPUs.
</blockquote></details>

thx, fixed

---

*[docs/resource_managment.md, line 22 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KlsnZy3S1eobPgmN16S:-KmfTbhfynb2ycXjyvDS:bc7hacc) ([raw file](https://github.com/mirantis/virtlet/blob/7ebb0fff663cfee9e3c09a49229f282daeb9cce2/docs/resource_managment.md#L22)):*
Thx, fixed.

> At this time Virtlet doesn't support setting these values, but there are plans to fix this in future.
- added this to `Virtlet CPU resource management` section

---

*[docs/resource_managment.md, line 51 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/299#-KmfD7s1S2I0FJ51sfZR:-KmfNcZrVBY_UO7LoAPr:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d9f8da997cdfc72c000184b1a6abda6170e8bbab/docs/resource_managment.md#L51)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

s/physycal/physical/ 
s/assumtion/assumption/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/299)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 23 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/299#-:-Kmf_RYhq3rzsf5fx88t:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/299#-:-KmfbR94GZqnyrG7B51l:bnfp4nl)*

**Pull request merged**
