### PR TITLE
metadata: Refactor boltdb storage

### PR DESCRIPTION
**Pull request by jellonek**
Added new interface for metadata accessing so now all libvirt based
methods can be unittested without real usage of boltdb.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/205)

### CODE REVIEW

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/205#-:-Kd5WlA-PkwhgsqCqm9t:bnfp4nl)*

**Comment by pigmej** [comment]
Looks ok but @ivan4th pls verify ;-)

---

Reviewed 7 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/205#-:-Kd5YT5ib4RS-4iVpx5E:bjughq1)*

**Comment by ivan4th** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/metadata/store.go, line 54 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/205#-Kd60ia1AeA9YEwj_c8U:-Kd60ia1AeA9YEwj_c8V:bvcb3rs) ([raw file](https://github.com/mirantis/virtlet/blob/074ae87c40a6d14079cb4e18488e0ef3da4df636/pkg/metadata/store.go#L54)):*
> ```Go
> 	GetPodNetworkConfigurationAsBytes(podId string) ([]byte, error)
> 
> 	// containers - virtualization
> ```

I think this is probably ok, but virtualization is a bit broader concept, maybe just "containers (VMs)" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/205)*

**Comment by jellonek** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/metadata/store.go, line 54 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/205#-Kd60ia1AeA9YEwj_c8U:-Kd61iisbS52l5e-kTJ3:bume7ka) ([raw file](https://github.com/mirantis/virtlet/blob/074ae87c40a6d14079cb4e18488e0ef3da4df636/pkg/metadata/store.go#L54)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I think this is probably ok, but virtualization is a bit broader concept, maybe just "containers (VMs)" ?
</blockquote></details>

This closely follows naming convention which we have in libvirttools package. I added `containers` there because it's more close to what actually it covers.
I thing that in near future we should s/virtualization/containers/ in these package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/205)*

**Comment by ivan4th** [comment]
What about splitting MetadataStore into ImageMetadataStore, SandboxMetadataStore and ContainerMetadata store? Then you can make MetadataStore interface inherit these 3. In places where just some aspects of the store are needed you may use one of the 3 subtypes (e.g. VirtualizationTool uses just container methods or do I miss something?) Maybe also we'll be able to split ImageManager from VirtletManager later and it will use only ImageMetadataStore. Later this will also make unit testing a bit easier.

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/205#-:-Kd61TOx-8MlXIZvkkuv:brga1k7)*

**Comment by jellonek** [comment]
I was thinking about this few days ago (and also started from that point) but leaved this for future.
Hmmm... Will rethink this now and probably will implement this.

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/205#-:-Kd62frxnK9mVdnq-5KO:b-g0e3na)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/205#-:-Kd66wzUAN2SCICWEyGn:bnfp4nl)*

**Pull request merged**
