### PR TITLE
Add multiple interface support to fdserver

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/490)

### CODE REVIEW

**Comment by ivan4th** [comment]
Reviewed 12 of 14 files at r1.
Review status: 7 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 169 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXkjQZgQY5DMm1gLHE:-KyXkjQZgQY5DMm1gLHF:bwcsxc8) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/cmd/vmwrapper/vmwrapper.go#L169)):*
> ```Go
> 
> 			var hwAddrs []net.HardwareAddr
> 			if err := json.Unmarshal(marshaledHwAddrs, &hwAddrs); err != nil {
> ```

I'm a bit unsure, but isn't JSON marshalling a bit of overkill there? We're dealing with Ethernet mac addrs only there, right? So just split the slice into 6-byte parts. Or, if for some reason we need other types of hardware addrs or you have some other reason for complex marshalling, encoding/gob maybe a bit better choice (fdserver protocol uses binary frames anyway)

---

*[pkg/nettools/nettools.go, line 304 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXoQkgiqgQnTRFEYi4:-KyXoQkgiqgQnTRFEYi5:bugitjs) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L304)):*
> ```Go
> // FindVeth locates single veth link in list of provided links.
> // There must be exactly one veth interface in the list.
> func FindVeth(links []netlink.Link) ([]netlink.Link, error) {
> ```

I'd say that making this function return a slice is a bit misleading. I understand that reverting the change will make the code that uses `FindVeth()` a bit bulkier, but maybe it would be more clean?

---

*[pkg/nettools/nettools.go, line 333 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXo2pY61pTsqIonq8S:-KyXo2pY61pTsqIonq8T:b-ih20oo) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L333)):*
> ```Go
> // If there is provided a list of interfaces in CNI Result, it sets output list
> // in the same order. If CNI Result lacks this list, there must be exactly one
> // veth interface in the namespace.
> ```

GetContainerInterfaces locates veth network links in the current network namespace.
If info is not nil and contains a non-empty list of network interfaces, the resulting slice will contain a link for each entry in that list. If info is nil or has no interfaces listed, the current network namespace must contain exactly one veth network link.

---

*[pkg/nettools/nettools.go, line 506 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXprMMM2E0LPpiyPWe:-KyXprMMM2E0LPpiyPWf:b-97yur9) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L506)):*
> ```Go
> 	// Result contains CNI result object describing the network settings
> 	Result *cnicurrent.Result
> 	// TapFiles contains a list of open File objects pointing to Tap
> ```

tap (lowercase) is perhaps better

---

*[pkg/nettools/nettools.go, line 510 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXpfQmBV5tLwI4L6LI:-KyXpfQmBV5tLwI4L6LJ:bcdy5pl) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L510)):*
> ```Go
> 	TapFiles []*os.File
> 	// HardwareAddrs stores a list of original hardware addresses of
> 	// a CNI veth interfaces
> ```

HardwareAddrs contains a list of original hardware addresses of CNI-created veth links

---

*[pkg/nettools/nettools.go, line 537 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXq84uRuiL7yP0TEPj:-KyXq84uRuiL7yP0TEPk:b-5aldfx) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L537)):*
> ```Go
> 			dnsInfo = info.DNS
> 		}
> 		info, err = ExtractLinkInfo(contVeths[0])
> ```

I think it may be better to be a bit more paranoid here and make sure `contVeths` has exactly one item.

---

*[pkg/nettools/nettools.go, line 657 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXqNf6GYBOhLKqnfSy:-KyXqNf6GYBOhLKqnfSz:b5hzy2p) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L657)):*
> ```Go
> func ConfigureLink(link netlink.Link, linkNo int, info *cnicurrent.Result) error {
> 	if len(info.IPs) < linkNo+1 {
> 		return fmt.Errorf("cni result has %d addresses but expected at last %d", len(info.IPs), linkNo+1)
> ```

at least

---

*[pkg/nettools/nettools_test.go, line 453 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXrAPIbvTy9V1TByba:-KyXrAPIbvTy9V1TBybb:b-ig0nmd) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools_test.go#L453)):*
> ```Go
> 	if err != nil {
> 		log.Panicf("AddrList() failed: %v", err)
> 	}
> ```

Is it possible to add a test case for multiple interfaces in the container-side network?

---

*[pkg/tapmanager/fdserver.go, line 470 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXrKWwu_vYXQrEj8kB:-KyXrKWwu_vYXQrEj8kC:b-nuz2o9) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/tapmanager/fdserver.go#L470)):*
> ```Go
> }
> 
> // GetFDs requests a file descriptors from the FDServer. It returns a
> ```

requests file descriptors

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/490)*

**Comment by ivan4th** [comment]
Review status: 7 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 169 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXkjQZgQY5DMm1gLHE:-KyXtOOBFldnE-OqiiSw:b3cffqd) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/cmd/vmwrapper/vmwrapper.go#L169)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'm a bit unsure, but isn't JSON marshalling a bit of overkill there? We're dealing with Ethernet mac addrs only there, right? So just split the slice into 6-byte parts. Or, if for some reason we need other types of hardware addrs or you have some other reason for complex marshalling, encoding/gob maybe a bit better choice (fdserver protocol uses binary frames anyway)
</blockquote></details>

Ok, I see that in other PRs you replace simple addr list with some more complex struct. I'm not insisting that you use gob... It would be a bit more consistent with the binary nature of the protocol, but not critical of course.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/490)*

**Comment by jellonek** [comment]
Review status: 7 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 169 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXkjQZgQY5DMm1gLHE:-Ky_CQ29cGwKe18M8wwl:b-i4tywv) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/cmd/vmwrapper/vmwrapper.go#L169)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Ok, I see that in other PRs you replace simple addr list with some more complex struct. I'm not insisting that you use gob... It would be a bit more consistent with the binary nature of the protocol, but not critical of course.
</blockquote></details>

I'm fine with gob there. Will replace json to it today.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/490)*

**Comment by jellonek** [comment]
Review status: 6 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 169 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXkjQZgQY5DMm1gLHE:-KypL0c8wXdplfGswaug:bto6j15) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/cmd/vmwrapper/vmwrapper.go#L169)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

I'm fine with gob there. Will replace json to it today.
</blockquote></details>

As I mentioned that in #497 - i'll keep there  json encoding as changing that to gob would introduce new encoder to code and would complicate it a bit (with negative impact on readability).

---

*[pkg/nettools/nettools.go, line 304 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXoQkgiqgQnTRFEYi4:-KypLQ2SJAODyKKuSV8B:b-jniev4) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L304)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'd say that making this function return a slice is a bit misleading. I understand that reverting the change will make the code that uses `FindVeth()` a bit bulkier, but maybe it would be more clean?
</blockquote></details>

That's precise - as in original form it was more clean - i reverted that there.

---

*[pkg/nettools/nettools.go, line 333 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXo2pY61pTsqIonq8S:-KypLbXy4OKGtmjiCVn8:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L333)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

GetContainerInterfaces locates veth network links in the current network namespace.
If info is not nil and contains a non-empty list of network interfaces, the resulting slice will contain a link for each entry in that list. If info is nil or has no interfaces listed, the current network namespace must contain exactly one veth network link.
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 506 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXprMMM2E0LPpiyPWe:-KypLdMcaDuWTmu8i8H4:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L506)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

tap (lowercase) is perhaps better
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 510 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXpfQmBV5tLwI4L6LI:-KypLivYwEiq_5WVWUOE:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L510)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

HardwareAddrs contains a list of original hardware addresses of CNI-created veth links
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 537 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXq84uRuiL7yP0TEPj:-KypLkS2_1UpGCuKThDG:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L537)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I think it may be better to be a bit more paranoid here and make sure `contVeths` has exactly one item.
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 657 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXqNf6GYBOhLKqnfSy:-KypLmZTfRIPMY0R8nwT:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools.go#L657)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

at least
</blockquote></details>

Done.

---

*[pkg/nettools/nettools_test.go, line 453 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXrAPIbvTy9V1TByba:-KypLno_FBghCqMjBH7a:b-tnzsym) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/nettools/nettools_test.go#L453)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Is it possible to add a test case for multiple interfaces in the container-side network?
</blockquote></details>

Will add a followup task for that.

---

*[pkg/tapmanager/fdserver.go, line 470 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/490#-KyXrKWwu_vYXQrEj8kB:-KypLtU9VMbFmqpmQAyp:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5c7dba58ea04eb056ab29a8451e865d84b16f446/pkg/tapmanager/fdserver.go#L470)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

requests file descriptors
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/490)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 2 of 14 files at r1, 3 of 3 files at r2.
Review status: 9 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/490#-:-KyukxO0Be_eNrwFg7hW:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 11 of 14 files at r1, 3 of 3 files at r2.
Review status: 9 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/490#-:-KyusX4lnqVkPS-FEZEv:bnfp4nl)*

**Pull request merged**
