### PR TITLE
Use dind-cluster-v1.8.sh to run the k8s v1.8 cluster.

### PR DESCRIPTION
**Pull request by warmchang**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/552)

### CODE REVIEW

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/552#-:-L2_Yap7k16OS4U8pNg2:bnfp4nl)*

**Comment by ivan4th** [comment]
Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/552#-:-L2_YeDUOm9s49yIcn1O:b-ucfknh)*

**Comment by warmchang** [comment]
OMG, reply so quickly. 👍

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/552#-:-L2_bvAxpFqc4CQy0k_U:bnfp4nl)*

**Pull request merged**
