### PR TITLE
Provide correct network teardown

### PR DESCRIPTION
**Pull request by jellonek**
This provides teardown procedure needed to correct usage of CNI plugin
DEL command, which expects configuration matching that, which it leaved
acter calling ADD command.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/192)

### CODE REVIEW

**Comment by ivan4th** [comment]
May need several small changes in comments, LGTM other than that.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[pkg/nettools/nettools.go, line 285 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/192#-KbjQLwIZUVG15ewjcK4:-KbjQLwJVJ0w1g29A5IO:b-ismlfi) ([raw file](https://github.com/mirantis/virtlet/blob/2459ab6466fc9b69444f660d4da2c7dff6085ab6/pkg/nettools/nettools.go#L285)):*
> ```Go
> }
> 
> func operateOnEbtables(interfaceName, command string) error {
> ```

Maybe use a bit more conventional name like updateEbtables() ? (not critical though)

---

*[pkg/nettools/nettools.go, line 363 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/192#-KbjSL4B3O_pKX_Uk5NC:-KbjSL4B3O_pKX_Uk5ND:b-zf8vww) ([raw file](https://github.com/mirantis/virtlet/blob/2459ab6466fc9b69444f660d4da2c7dff6085ab6/pkg/nettools/nettools.go#L363)):*
> ```Go
> }
> 
> // TeardownBridge removes links from bridge and turns it down
> ```

maybe a bit better 'and sets it down'

---

*[pkg/nettools/nettools.go, line 374 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/192#-KbjSTtTXtVVy5I7WfvB:-KbjSTtTXtVVy5I7WfvC:b-7nmz6t) ([raw file](https://github.com/mirantis/virtlet/blob/2459ab6466fc9b69444f660d4da2c7dff6085ab6/pkg/nettools/nettools.go#L374)):*
> ```Go
> }
> 
> // ConfigureLink adds ip address and routes link basing on data in info.
> ```

adds IP address and routes for the link based on info.

---

*[pkg/nettools/nettools.go, line 398 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/192#-KbjRDzGAwWNq3YPdzmM:-KbjRDzGAwWNq3YPdzmN:b-5dytk1) ([raw file](https://github.com/mirantis/virtlet/blob/2459ab6466fc9b69444f660d4da2c7dff6085ab6/pkg/nettools/nettools.go#L398)):*
> ```Go
> // It does it by calling tear down funcs in opposite direction to that from
> // SetupContainerSideNetwork. At the end - network configuration in container
> // namespace should match situation from before SetupContainerSideNetwork call.
> ```

probably a bit better this way:

It does so by invoking teardown sequence which removes ebtables rules, links
and addresses in an order opposite to that of their creation in SetupContainerSideNetwork.
The end result is the same network configuration in the container network namespace
as it was before SetupContainerSideNetwork() call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/192#-:-KbjSgCBjGXsoo3y4H6x:b4i4jfp)*

**Comment by jellonek** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/nettools/nettools.go, line 285 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/192#-KbjQLwIZUVG15ewjcK4:-KbjUIC3jNWoBUgeq07g:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2459ab6466fc9b69444f660d4da2c7dff6085ab6/pkg/nettools/nettools.go#L285)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Maybe use a bit more conventional name like updateEbtables() ? (not critical though)
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 363 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/192#-KbjSL4B3O_pKX_Uk5NC:-KbjUIre_smS4qjA1eNQ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2459ab6466fc9b69444f660d4da2c7dff6085ab6/pkg/nettools/nettools.go#L363)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe a bit better 'and sets it down'
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 374 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/192#-KbjSTtTXtVVy5I7WfvB:-KbjUJVfl7DV5qteWGdB:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2459ab6466fc9b69444f660d4da2c7dff6085ab6/pkg/nettools/nettools.go#L374)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

adds IP address and routes for the link based on info.
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 398 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/192#-KbjRDzGAwWNq3YPdzmM:-KbjUKUmrG6t7OM_K5vL:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2459ab6466fc9b69444f660d4da2c7dff6085ab6/pkg/nettools/nettools.go#L398)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

probably a bit better this way:

It does so by invoking teardown sequence which removes ebtables rules, links
and addresses in an order opposite to that of their creation in SetupContainerSideNetwork.
The end result is the same network configuration in the container network namespace
as it was before SetupContainerSideNetwork() call.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/192)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/192#-:-KbjcAge7mk0KSCGnzz9:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/192#-:-KbjcSaPRWmipEeOiXNE:bnfp4nl)*

**Pull request merged**
