### PR TITLE
Update Virtlet for Kubernetes 1.7

### PR DESCRIPTION
**Pull request by ivan4th**
- [X] update to Go 1.8
- [X] update CNI-related code
- [X] make Virtlet compatible with CRI 1.7
- [X] make CRI proxy compatible with CRI 1.7
- [X] create separate binary for docker-shim
- [X] do basic manual test with k8s 1.7
- [x] update bundled CNI
- [x] fix unit/integration tests
- [x] fix e2e tests
- [x] fix CRI proxy bootstrap
- [x] recheck real CNI support
- [x] verify demo
- [x] ensure CI is stable
- [x] update docs, including "real cluster" instructions

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/360)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 48 of 52 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 33 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/360#-KqXH-x-Lvg0wKtnved5:-KqXH-x0KjOdGqj3CqjG:b-f84wmi) ([raw file](https://github.com/mirantis/virtlet/blob/a090332875c1035dcc71023f1ed6f483a7c5e657/cmd/vmwrapper/vmwrapper.go#L33)):*
> ```Go
> 
> 	"github.com/containernetworking/cni/pkg/ns"
> 	"github.com/containernetworking/cni/pkg/types/current"
> ```

Please add there an alias, e.g. `cnitypes`.

---

*[docs/criproxy.md, line 150 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/360#-KqXHqe7zrKUNWKDf4pe:-KqXHqe7zrKUNWKDf4pf:b-mcqif3) ([raw file](https://github.com/mirantis/virtlet/blob/a090332875c1035dcc71023f1ed6f483a7c5e657/docs/criproxy.md#L150)):*
> ```Markdown
>    stores kubelet command line together with other info (node name and
>    docker endpoint) as `/etc/criproxy/node.conf`.
> 6. DaemonSet's init container starts invokes `criproxy` binary in
> ```

Wrong numeration - 6 is repeated.

---

*[pkg/dhcp/config.go, line 23 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/360#-KqXJ5myYPzqwT4Hir9X:-KqXJ5myYPzqwT4Hir9Y:b-8nysjz) ([raw file](https://github.com/mirantis/virtlet/blob/a090332875c1035dcc71023f1ed6f483a7c5e657/pkg/dhcp/config.go#L23)):*
> ```Go
> 	"net"
> 
> 	"github.com/containernetworking/cni/pkg/types/current"
> ```

Please add an alias with name: `cnitypes`.

---

*[pkg/dhcp/server.go, line 29 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/360#-KqXJDcmwKjqty5Sg4mV:-KqXJDcmwKjqty5Sg4mW:bk7lbt5) ([raw file](https://github.com/mirantis/virtlet/blob/a090332875c1035dcc71023f1ed6f483a7c5e657/pkg/dhcp/server.go#L29)):*
> ```Go
> 	"strings"
> 
> 	"github.com/containernetworking/cni/pkg/types/current"
> ```

Same as in other files.

---

*[pkg/nettools/nettools.go, line 49 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/360#-KqXJmq0wrIrDooLMVYP:-KqXJmq0wrIrDooLMVYQ:bk7lbt5) ([raw file](https://github.com/mirantis/virtlet/blob/a090332875c1035dcc71023f1ed6f483a7c5e657/pkg/nettools/nettools.go#L49)):*
> ```Go
> 	"github.com/containernetworking/cni/pkg/ns"
> 	"github.com/containernetworking/cni/pkg/types"
> 	"github.com/containernetworking/cni/pkg/types/current"
> ```

Same as in other files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/360)*

**Comment by ivan4th** [comment]
Review status: 48 of 58 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 33 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/360#-KqXH-x-Lvg0wKtnved5:-KqXPhBAVAtpJCv0mcnH:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a090332875c1035dcc71023f1ed6f483a7c5e657/cmd/vmwrapper/vmwrapper.go#L33)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Please add there an alias, e.g. `cnitypes`.
</blockquote></details>

Done.

---

*[docs/criproxy.md, line 150 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/360#-KqXHqe7zrKUNWKDf4pe:-KqXQAW8GUw5Ftint6Zc:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a090332875c1035dcc71023f1ed6f483a7c5e657/docs/criproxy.md#L150)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Wrong numeration - 6 is repeated.
</blockquote></details>

Done.

---

*[pkg/dhcp/config.go, line 23 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/360#-KqXJ5myYPzqwT4Hir9X:-KqXPFpuiaWqTTAK6LLE:b-jqz4mt) ([raw file](https://github.com/mirantis/virtlet/blob/a090332875c1035dcc71023f1ed6f483a7c5e657/pkg/dhcp/config.go#L23)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Please add an alias with name: `cnitypes`.
</blockquote></details>

Sometimes we import `types` and sometimes `types/current`, so I added alias 'cnicurrent'

---

*[pkg/dhcp/server.go, line 29 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/360#-KqXJDcmwKjqty5Sg4mV:-KqXPeLyqwoDVAAHi_V7:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a090332875c1035dcc71023f1ed6f483a7c5e657/pkg/dhcp/server.go#L29)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Same as in other files.
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 49 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/360#-KqXJmq0wrIrDooLMVYP:-KqXPfloci591iWv1aEW:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a090332875c1035dcc71023f1ed6f483a7c5e657/pkg/nettools/nettools.go#L49)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Same as in other files.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/360)*

**Comment by jellonek** [comment]
Plain `types` is used only in tests, and `Result` is type from cni package, but yeah - what we have now :lgtm:

---

Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/360#-:-KqXTUEwjobgqclLWkCH:b-m6xq7k)*

**Comment by istalker2** [comment]
:lgtm:

---

Reviewed 39 of 52 files at r1, 9 of 10 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/360#-:-Kq_a7lUmoLstUqsPtXZ:bnfp4nl)*

**Pull request merged**
