### PR TITLE
Revamp Virtlet image management

### PR DESCRIPTION
**Pull request by ivan4th**
- [X] Use backing files for root volumes
- [X] Use plain files and symlinks for image management
- [X] Use built-in webserver for images in the integration tests
- [X] Add cirros image to the build container
- [X] Use bigger buffer for image download
- [X] Report qcow2 file size as the image size to kubelet
- [X] Make image CRI function return docker-like info (use digests)
- [x] Fix CRI Proxy Image Id bug (bad prefixing)
- [x] Add image GC
- [x] Extra manual testing (redownloading images, big images)
- [x] Update docs

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/556)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 43 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/image/download.go, line 36 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L38Vp--RNAMt2NU1N1k:-L38Vp--RNAMt2NU1N1l:bhyhbym) ([raw file](https://github.com/mirantis/virtlet/blob/5c25561011fa936b5d4e2ea9258c1f662cfb14ab/pkg/image/download.go#L36)):*
> const (
> 	copyBufferSize = 1024 * 1024 * 1024

I think it's way to big. 1GB sounds ridiculous high.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/556)*

**Comment by ivan4th** [comment]
Review status: 0 of 43 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/image/download.go, line 36 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L38Vp--RNAMt2NU1N1k:-L38W55MQv85jvSr7m7p:b-ctcfe9) ([raw file](https://github.com/mirantis/virtlet/blob/5c25561011fa936b5d4e2ea9258c1f662cfb14ab/pkg/image/download.go#L36)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> const (
> 	copyBufferSize = 1024 * 1024 * 1024

I think it's way to big. 1GB sounds ridiculous high.
</blockquote></details>

Oops thanks for spotting this one, I meant 1024 * 1024 but overdid it :) Will fix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/556)*

**Comment by pigmej** [comment]
Review status: 0 of 43 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/image/download.go, line 36 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L38Vp--RNAMt2NU1N1k:-L38WFHaVbSfZRU1R7zq:b-7m42hk) ([raw file](https://github.com/mirantis/virtlet/blob/5c25561011fa936b5d4e2ea9258c1f662cfb14ab/pkg/image/download.go#L36)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Oops thanks for spotting this one, I meant 1024 * 1024 but overdid it :) Will fix
</blockquote></details>

np :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/556)*

**Comment by ivan4th** [comment]
CRI proxy fix: https://github.com/Mirantis/criproxy/pull/13

**Comment by ivan4th** [comment]
Extra manual testing done, including working with huge Windows image.
This was done on a node with CirrOS, Ubuntu and Windows pods:
```
root@kube-node-1:/# qemu-img info /var/lib/virtlet/volumes/virtlet_root_15b5864b-8f0e-5559-6953-f7a90793a29a
image: /var/lib/virtlet/volumes/virtlet_root_15b5864b-8f0e-5559-6953-f7a90793a29a
file format: qcow2
virtual size: 12G (13096714240 bytes)
disk size: 490M
cluster_size: 65536
backing file: /var/lib/virtlet/images/data/bbfe05983790dcdc00616b4e404b02723c8adaf4405ad651f492f56b90b000c7
backing file format: qcow2
Format specific information:
    compat: 0.10
    refcount bits: 16
root@kube-node-1:/# ls -lhR /var/lib/virtlet/images/
/var/lib/virtlet/images/:
total 8.0K
drwxr-xr-x 2 root root 4.0K Jan 24 14:10 data
drwxr-xr-x 2 root root 4.0K Jan 24 14:10 links

/var/lib/virtlet/images/data:
total 12G
-rw------- 1 libvirt-qemu kvm 277M Jan 24 13:25 28c13089574f3c90705d09fc703242d361b8d694b70887d67626a23ba3bbdb81
-rw------- 1 libvirt-qemu kvm  13M Jan 24 13:40 a8dd75ecffd4cdd96072d60c2237b448e0c8b2bc94d57f10fdbc8c481d9005b8
-rw------- 1 libvirt-qemu kvm  12G Jan 24 14:08 bbfe05983790dcdc00616b4e404b02723c8adaf4405ad651f492f56b90b000c7

/var/lib/virtlet/images/links:
total 12K
lrwxrwxrwx 1 root root 72 Jan 24 13:40 cirros -> ../data/a8dd75ecffd4cdd96072d60c2237b448e0c8b2bc94d57f10fdbc8c481d9005b8
lrwxrwxrwx 1 root root 72 Jan 24 13:25 cloud-images.ubuntu.com%xenial%current%xenial-server-cloudimg-amd64-disk1.img -> ../data/28c13089574f3c90705d09fc703242d361b8d694b70887d67626a23ba3bbdb81
lrwxrwxrwx 1 root root 72 Jan 24 14:10 win -> ../data/bbfe05983790dcdc00616b4e404b02723c8adaf4405ad651f492f56b90b000c7```

**Comment by jellonek** [comment]
Reviewed 27 of 44 files at r1, 1 of 1 files at r2, 13 of 17 files at r3, 11 of 11 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[docs/images.md, line 9 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cigw-oiQ8zcmbWgTD:-L3cigw-oiQ8zcmbWgTE:b-x09bdi) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/docs/images.md#L9)):*
> ```Markdown
> - protocol to use to download the image. By default `https` is
>   used. In order to use `http` set `VIRTLET_DOWNLOAD_PROTOCOL` env var
>   to `http` for virtlet container. `<scheme>://` below denotes
> ```

... for virtlet container. In case of using default deploy method, this can be set in `virtlet-config` config map (defined by [virtlet-ds.yaml(../deploy/virtlet-ds.yaml)) under the name `download_protocol`. `<scheme>://` below ...

---

*[docs/images.md, line 10 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cjvh1fP_Cs4WYFmfb:-L3cjvh1fP_Cs4WYFmfc:b-msb2x3) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/docs/images.md#L10)):*
> ```Markdown
>   used. In order to use `http` set `VIRTLET_DOWNLOAD_PROTOCOL` env var
>   to `http` for virtlet container. `<scheme>://` below denotes
>   the selected protocol
> ```

Missing dot at the end.

---

*[docs/images.md, line 51 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3chYKiiUjJ0c98CEQe:-L3chYKjkdTy1XVGlywL:b5kaekc) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/docs/images.md#L51)):*
> ```Markdown
> 
> The image store performs GC upon Virtlet startup, which consists of
> removing any part_* files and those files in data/ which have no
> ```

`part_*`, `data/` - they should be enclosed with `

---

*[docs/volumes.md, line 103 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3chj20f9OAjoiP6hgH:-L3chj20f9OAjoiP6hgI:b-1lg8jl) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/docs/volumes.md#L103)):*
> ```Markdown
> All ephemeral volumes created by request as well as VM root volumes
> are stored in the local libvirt storage pool "**volumes**" which is
> located at `/var/lib/virtlet/volumes`.
> ```

Hmmm... Path for images is configurable - but this one is hardcoded. IDK if that's what we want.

---

*[pkg/image/image.go, line 93 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cl9WUvbOjREQgI6wt:-L3cl9WUvbOjREQgI6wu:b-q7pq8o) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/pkg/image/image.go#L93)):*
> ```Go
> 
> // ImageFileStore implements ImageStore
> // The images are stored like this:
> ```

This wole section looks like unexpected paste from doc, or at last undesired repetition - better would be to point from there to docs, to have a single place for any future changes.

---

*[pkg/image/image.go, line 198 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cmAtKI7SHWR9z1tBw:-L3cmAtKI7SHWR9z1tBx:b-mf9ite) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/pkg/image/image.go#L198)):*
> ```Go
> 	}
> 	for _, imgSpec := range imgList {
> 		if d := getHexDigest(imgSpec); d != "" {
> ```

This is the only place where I found execution of `getHexDigest` (maybe I simply didn't catch others) so maybe it would be better to return boolean value from it - that would eliminate several underlying data to string conversions and this one `if`.

---

*[pkg/manager/manager.go, line 102 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cnhhF2tdzX1_zGPn8:-L3cnhhF2tdzX1_zGPn9:bt9ja64) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/pkg/manager/manager.go#L102)):*
> ```Go
> 
> 	if err := imageStore.GC(); err != nil {
> 		glog.Warningf("error during the image GC: %v", err)
> ```

This message should be capitalized.

---

*[pkg/metadata/sandboxes.go, line 97 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3co56U-dC4QQD7nJlK:-L3co56U-dC4QQD7nJlL:b-rhoef9) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/pkg/metadata/sandboxes.go#L97)):*
> ```Go
> func (b *boltClient) ListPodSandboxes(filter *kubeapi.PodSandboxFilter) ([]PodSandboxMetadata, error) {
> 	var result []PodSandboxMetadata
> 	prefix := []byte("sandboxes/")
> ```

What is the reason to move this variable to outer scope?

---

*[pkg/metadata/sandboxes.go, line 101 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3coOSsWjJOh7YxKMUB:-L3coOSsWjJOh7YxKMUC:bb6mt9b) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/pkg/metadata/sandboxes.go#L101)):*
> ```Go
> 		c := tx.Cursor()
> 		for k, _ := c.Seek(prefix); k != nil && bytes.HasPrefix(k, prefix); k, _ = c.Next() {
> 			psm := podSandboxMeta{client: b, id: string(k[len(prefix):])}
> ```

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/556)*

**Comment by ivan4th** [comment]
Review status: 46 of 52 files reviewed at latest revision, 10 unresolved discussions.

---

*[docs/images.md, line 9 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cigw-oiQ8zcmbWgTD:-L3nbYVvUjb87atLxIUc:b-aakl12) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/docs/images.md#L9)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

... for virtlet container. In case of using default deploy method, this can be set in `virtlet-config` config map (defined by [virtlet-ds.yaml(../deploy/virtlet-ds.yaml)) under the name `download_protocol`. `<scheme>://` below ...
</blockquote></details>

Fixed, although with slightly different wording.

---

*[docs/images.md, line 10 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cjvh1fP_Cs4WYFmfb:-L3nbY4u8rmrKDaRfXTg:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/docs/images.md#L10)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Missing dot at the end.
</blockquote></details>

Done.

---

*[docs/images.md, line 51 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3chYKiiUjJ0c98CEQe:-L3nbeyjfwazcrWC3M1R:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/docs/images.md#L51)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

`part_*`, `data/` - they should be enclosed with `
</blockquote></details>

Done.

---

*[docs/volumes.md, line 103 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3chj20f9OAjoiP6hgH:-L3nbgISiJtXpC-xs_Tp:bff9pfa) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/docs/volumes.md#L103)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... Path for images is configurable - but this one is hardcoded. IDK if that's what we want.
</blockquote></details>

I just didn't change this (although I've removed an unused storage pool in one of the latest commits). We can fix this separately but I'm not sure it's worth it, as I'm not sure heavily customized Virtlet deployments is something we want or need to support.

---

*[pkg/image/download.go, line 36 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L38Vp--RNAMt2NU1N1k:-L3nc-yEqxnzIBdfjqon:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5c25561011fa936b5d4e2ea9258c1f662cfb14ab/pkg/image/download.go#L36)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

np :)
</blockquote></details>

Done.

---

*[pkg/image/image.go, line 93 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cl9WUvbOjREQgI6wt:-L3nc2EeJcRRSCF5CkAE:b-rwkbf4) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/pkg/image/image.go#L93)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This wole section looks like unexpected paste from doc, or at last undesired repetition - better would be to point from there to docs, to have a single place for any future changes.
</blockquote></details>

It was vice versa, I wrote it here before copying it to the docs. But ok, let's just indeed point to the docs.

---

*[pkg/image/image.go, line 198 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cmAtKI7SHWR9z1tBw:-L3ncBTYRMvDAzTZC520:b-5rth2j) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/pkg/image/image.go#L198)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This is the only place where I found execution of `getHexDigest` (maybe I simply didn't catch others) so maybe it would be better to return boolean value from it - that would eliminate several underlying data to string conversions and this one `if`.
</blockquote></details>

`d` string is used below as a map key, so just bool value is not appropriate here.

---

*[pkg/manager/manager.go, line 102 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cnhhF2tdzX1_zGPn8:-L3ncNyVEw8sUvMfkAm0:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/pkg/manager/manager.go#L102)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This message should be capitalized.
</blockquote></details>

Done.

---

*[pkg/metadata/sandboxes.go, line 97 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3co56U-dC4QQD7nJlK:-L3ncPOocp6SDMEMlgub:b5qpby6) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/pkg/metadata/sandboxes.go#L97)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

What is the reason to move this variable to outer scope?
</blockquote></details>

Well, actually I think it's better to make it global var (const would be even better, but there's no such thing as `[]byte` const). So I did that and also added some helper funcs to form the keys.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/556)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/image/image.go, line 198 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/556#-L3cmAtKI7SHWR9z1tBw:-L3nzeOwnNRCaHEd4Bob:b536b98) ([raw file](https://github.com/mirantis/virtlet/blob/aa42ceb18e0fe8cf467c73b403464a65d67bf74a/pkg/image/image.go#L198)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`d` string is used below as a map key, so just bool value is not appropriate here.
</blockquote></details>

Right. Facepalm on my side.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/556#-:-L3o-HrCrcwzDiydgP6i:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/556#-:-L41-puWkaJvaQ19t43m:bnfp4nl)*

**Pull request merged**
