### PR TITLE
deploy: Fix mounting /var/lib/libvirt from host

### LINKED ISSUE #222: Fix mounting /var/lib/libvirt into Virtlet container
See here: https://github.com/Mirantis/virtlet/blob/e3222d372a8fd9fc620a00edc6d36c084c500771/deploy/virtlet-ds.yaml#L107

### PR DESCRIPTION
**Pull request by jellonek**
closes #222

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/267)

### CODE REVIEW

**Comment by jellonek** [comment]
There are no tests for this on CI.
Manual tests on dind require building image locally, sending it to `kube-node-1`, and then starting it by `start-dind` command of `./build/cmd.sh` (preceded by `build`, `copy` and `copy-dind`).
This should allow to use host `/var/lib/libvirt` in virtlet container, so also keeping it's images store during virtlet daemonset or even node restarts.

**Comment by ivan4th** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[image_skel/start.sh, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/267#-KifIr87a3wALDiuIazg:-KifIr87a3wALDiuIazh:b7gw6lg) ([raw file](https://github.com/mirantis/virtlet/blob/14a312327ee2037af1b5e6e861776823803dd80a/image_skel/start.sh#L42)):*
> ```Shell
> # Removal of the socket below helps but not always.
> 
> if [[ -f /var/lib/libvirt/qemu ]]; then
> ```

`[[ -f /var/lib/libvirt/qemu ]]` is basically never true (should use `-e` and perhaps only do this if /var/lib/qemu is not a mount point) There's chance this hack may not be necessary with `/var/lib/libvirt/qemu` being mounted from host in daemonsets, but this may break integration tests. (For me the hack doesn't affect Travis but w/o it integration tests were breaking on some test machines)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/267)*

**Comment by ivan4th** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[image_skel/start.sh, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/267#-KifIr87a3wALDiuIazg:-KifK4Tk_XQ1PqBeaISm:bs4zg6p) ([raw file](https://github.com/mirantis/virtlet/blob/14a312327ee2037af1b5e6e861776823803dd80a/image_skel/start.sh#L42)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`[[ -f /var/lib/libvirt/qemu ]]` is basically never true (should use `-e` and perhaps only do this if /var/lib/qemu is not a mount point) There's chance this hack may not be necessary with `/var/lib/libvirt/qemu` being mounted from host in daemonsets, but this may break integration tests. (For me the hack doesn't affect Travis but w/o it integration tests were breaking on some test machines)
</blockquote></details>

(can test for the mountpoint using `mountpoint` command)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/267)*

**Comment by jellonek** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[image_skel/start.sh, line 42 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/267#-KifIr87a3wALDiuIazg:-Kif_et0Z7cj1qFmAxx_:bew9x6h) ([raw file](https://github.com/mirantis/virtlet/blob/14a312327ee2037af1b5e6e861776823803dd80a/image_skel/start.sh#L42)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

(can test for the mountpoint using `mountpoint` command)
</blockquote></details>

It's imo necessary because we have dual situation - there can be `/var/lib/libvirt` with potentially started vm on qemu on host - so there is a possibility that this socket will be there, so hack with`mv` will be useful, and second - there was no `/var/lib/libvirt` on host - so i'm making it empty in `prepare-node.sh`, so this `mv` will fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/267)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/267#-:-Kio2kE5-V2_J8gDc6vP:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/267)*

**Pull request merged**
