### PR TITLE
Update the docs to use kubectl attach

### PR DESCRIPTION
**Pull request by lukaszo**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/526)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/real-cluster.md, line 88 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/526#-L099jo0QinPZw_hjEqq:-L099jo0QinPZw_hjEqr:b-b5m29z) ([raw file](https://github.com/mirantis/virtlet/blob/7dc59916b05b9bc58067b52b57cef57585304ed1/deploy/real-cluster.md#L88)):*
> ```Markdown
> $ kubectl attach -it cirros-vm
> Connected to domain 411c70b0-1df3-46be-4838-c85474a1b44a-cirros-vm
> Escape character is ^]
> ```

Above message is incorrect. Now we have:
`If you don't see a command prompt, try pressing enter.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/526)*

**Comment by lukaszo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/real-cluster.md, line 88 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/526#-L099jo0QinPZw_hjEqq:-L09RnwT6jIhhDFnQdrZ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7dc59916b05b9bc58067b52b57cef57585304ed1/deploy/real-cluster.md#L88)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Above message is incorrect. Now we have:
`If you don't see a command prompt, try pressing enter.`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/526)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/real-cluster.md, line 65 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/526#-L09SfiFbk4jhOv7I62t:-L09SfiFbk4jhOv7I62u:b8y0myq) ([raw file](https://github.com/mirantis/virtlet/blob/91f01b9407fad01296ca1809cd71b8f19ad41193/deploy/real-cluster.md#L65)):*
> ```Markdown
> Both utilities need `kubectl` to be configured to access your cluster.
> 
> `virsh.sh` can be used to access a VM console. `virsh.sh` currently assumes
> ```

Hmmm... Seems that this also needs an update.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/526)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/526#-:-L09cDPMGRyxBhoIcTKc:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/526#-:-L0EC3hwik21c5ZPwFkK:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/526#-:-L0EJtiR6uu1XbXRRIGQ:bnfp4nl)*

**Pull request merged**
