### PR TITLE
Fix routes sent by dhcp

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/560)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/network/vm_network_test.go, line 459 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/560#-L40wLGPgnSNazlOuG0-:-L40wLGPgnSNazlOuG00:by8ttd7) ([raw file](https://github.com/mirantis/virtlet/blob/8f83f22c62bbeaeaa19696410c14db6b5506cb49/tests/network/vm_network_test.go#L459)):*
> ```Go
> 					"new_subnet_mask='255.255.255.0'",
> 					"tap1: offered 10.2.90.5 from 169.254.254.2",
> 				},
> ```

Why remove this entry completely? It should remain there, just remove the routes from it. If you remove the entry, dhcp test will not be done for tap1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/560)*

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/network/vm_network_test.go, line 459 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/560#-L40wLGPgnSNazlOuG0-:-L40y1uh8ueNF0brRufE:b-aqgq1v) ([raw file](https://github.com/mirantis/virtlet/blob/8f83f22c62bbeaeaa19696410c14db6b5506cb49/tests/network/vm_network_test.go#L459)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Why remove this entry completely? It should remain there, just remove the routes from it. If you remove the entry, dhcp test will not be done for tap1
</blockquote></details>

Yep, that was wrong - fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/560)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/560#-:-L40yIwCopi2q1Orl4ZM:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/560#-:-L40ymB68DQgnvHG766i:bnfp4nl)*

**Pull request merged**
