### PR TITLE
Simple startup of Virtlet

### LINKED ISSUE #207: Single-command startup of Virtlet demo setup
The command should use kubeadm-dind-cluster to create a cluster and then set up Virtlet on it.

### PR DESCRIPTION
**Pull request by ivan4th**
- [x] fix DNS handling in Virtlet DaemonSet - stop tying it to image-service
- [x] rename `contrib/deploy` -> `deploy`
- [x] update examples directory (move `image-*.yaml` and `cirros-vm.yaml` from `deploy` there)
- [x] add script that starts kubeadm-dind-cluster, deploys Virtlet on it and starts a sample VM
- [x] update README.md - add instructions on single-command startup and slightly more manual startup method based on kubeadm-dind-cluster (i.e. the same thing but "the hard way")
- [x] gain initial feedback on how well the script works
- [x] update file URLs in demo script to use `master` branch

Fixes #207

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/217)

### CODE REVIEW

**Comment by pigmej** [comment]
@ivan4th I think demo.sh should support `--help` option.

**Comment by jellonek** [comment]
Why? It does not use any parameters, or i'm missing something?

**Comment by pigmej** [comment]
Because you may want to use --help just to check maybe it accepts some, and instead it will start executing stuff.

`--help` could return short description + info how to exit how to clean etc.

**Comment by jellonek** [comment]
Seems legit, but also documenting this in place where script is mentioned in docs should be enough IMO.
The best would be to add such info in both places, in docs and in script.

**Comment by pigmej** [comment]
yeah docs are must have :)

**Comment by jellonek** [comment]
:lgtm_strong: with one question and one suggestion.

---

Reviewed 16 of 22 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/demo.sh, line 143 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/217#-KfhhrY6sssEalFZqf9p:-KfhhrY6sssEalFZqf9q:bcko2fe) ([raw file](https://github.com/mirantis/virtlet/blob/75cea5d6f052f4dbda1c1062743dd6c5e663496f/deploy/demo.sh#L143)):*
> ```Shell
>   echo >&2
>   echo "[1] https://github.com/Mirantis/virtlet" >&2
>   echo "[2] https://github.com/Mirantis/kubeadm-dind-cluster" >&2
> ```

All this lines could be changed to:
```
cat <<__EOF__ >&2
Usage: ...
...
...
__EOF__

This would probably look cleaner a bit without using echo & redirection on each line.
Also instead of checking "--help" or "-h" - i would like to show this info if number of parameters is not equal to zero, what would cover mentioned parameters like any other misused. WDYT?
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/217#-:-KfhiyY09RXgU4XRcRVb:bf3afam)*

**Comment by jellonek** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 23 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/217#-Kfppdt7-zpFYgcsL9SA:-Kfppdt7-zpFYgcsL9SB:bphtk36) ([raw file](https://github.com/mirantis/virtlet/blob/1d4f06bda906085dd7d3543f2fe6d091762ea151/README.md#L23)):*
> ```Markdown
> You can also give Virtlet a quick try using our demo script (requires Docker 1.12+):
> ```
> wget https://cdn.rawgit.com/Mirantis/virtlet/ivan4th/master/deploy/demo.sh
> ```

Last thing - remove ivan4th in branch name and we can merge this IMO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/217)*

**Comment by ivan4th** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 23 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/217#-Kfppdt7-zpFYgcsL9SA:-KfpqZ5m1IP_NFaHcqYi:b-x3bh92) ([raw file](https://github.com/mirantis/virtlet/blob/1d4f06bda906085dd7d3543f2fe6d091762ea151/README.md#L23)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Last thing - remove ivan4th in branch name and we can merge this IMO.
</blockquote></details>

Fixed, also switched to raw.githubusercontent.com

---

*[deploy/demo.sh, line 143 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/217#-KfhhrY6sssEalFZqf9p:-Kfpqc4F3rngmuxeuUmp:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/75cea5d6f052f4dbda1c1062743dd6c5e663496f/deploy/demo.sh#L143)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

All this lines could be changed to:
```
cat <<__EOF__ >&2
Usage: ...
...
...
__EOF__

This would probably look cleaner a bit without using echo & redirection on each line.
Also instead of checking "--help" or "-h" - i would like to show this info if number of parameters is not equal to zero, what would cover mentioned parameters like any other misused. WDYT?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/217)*
<!-- Sent from Reviewable.io -->

**Comment by jellonek** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/217)*

**Pull request merged**
