### PR TITLE
Added VIRTLET_DEMO_BRANCH

### PR DESCRIPTION
**Pull request by pigmej**
Use VIRTLET_DEMO_BRANCH to select branch in demo.sh
Use VIRTLET_DEMO_RELEASE to select virtlet release in demo.sh

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/443)

### CODE REVIEW

**Comment by ivan4th** [comment]
You also need to update `.circleci/config.yml` and `test.sh` (or, the latter can be actually removed I think, it was used for Travis)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/443#-:-KvD-yqN1T_5svCB8lur:b-tcwvnl)*

**Comment by pigmej** [comment]
Yeah sorry, updated.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/443#-:-KvD2-zvfLFX_zhsLUjt:b3q24gs)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/443#-:-KvD3tm-LMAWo0xaptVR:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/demo.sh, line 266 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/443#-KvTA5p3xc8LzaCbM6rR:-KvTA5p3xc8LzaCbM6rS:bwnm0hn) ([raw file](https://github.com/mirantis/virtlet/blob/520a66daf9e296b86ab59765ad10bce05dfefa38/deploy/demo.sh#L266)):*
> ```Shell
>       virtlet_docker_tag="latest"
>       ds_location="${BASE_LOCATION}/deploy/virtlet-ds.yaml"
>       replace_image_in_ds=1
> ```

`ds_location` and `replace_image_in_ds` are set to the same value in both branches of this `if`, maybe set them above `if`?

---

*[deploy/demo.sh, line 312 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/443#-KvTASnkzL2tfAYjrlmC:-KvTASnkzL2tfAYjrlmD:bp7hugu) ([raw file](https://github.com/mirantis/virtlet/blob/520a66daf9e296b86ab59765ad10bce05dfefa38/deploy/demo.sh#L312)):*
> ```Shell
>   if [[ "${replace_image_in_ds}" == 1 ]]; then
>     demo::step "Deploying Virtlet DaemonSet from ${ds_location} and will set correct ${virtlet_docker_tag}"
>     curl --silent "${ds_location}" | sed "s/image: mirantis\/virtlet/image: mirantis\/virtlet:${virtlet_docker_tag}/g" | "${kubectl}" create -f -
> ```

you can use e.g. `sed s@...@...@g` so as to avoid escaping slashes (I don't insist though, some may think slashes are prettier)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/443)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/443#-:-KvTHWxXOfj4wWZjXTxj:bnfp4nl)*

**Comment by istalker2** [comment]
:lgtm:, but needs rebase

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/443#-:-KvaIDyPlG7RWjRm19YF:b-b46vdh)*

**Comment by istalker2** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/443#-:-KvaWfjW4r7rNlnVj2R3:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/443#-:-KvaZCgWumWr77l6gS5P:bnfp4nl)*

**Pull request merged**
