### PR TITLE
Add virtletctl version

### PR DESCRIPTION
**Pull request by ivan4th**
- [x] implement virtletctl version
- [x] make sure it works with Virtlet release mechanism

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/658)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/658#-:-LAJ-t514xByRMFBZk2p:bnfp4nl)*

**Comment by jellonek** [comment]
Reviewed 9 of 38 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cmd/virtlet/virtlet.go, line 180 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/658#-LAIzVhR77aEbQj2vaMy:-LAIzVhR77aEbQj2vaMz:b-40xfjw) ([raw file](https://github.com/mirantis/virtlet/blob/88258e128caf0b22cb6d580de49638bffaf421c2/cmd/virtlet/virtlet.go#L180)):*
> ```Go
> 	flag.Parse()
> 	if *displayVersion {
> 		printVersion()
> ```

Imo `os.Exit` should be called from main, not from above func, but I'm fine with that also...

---

*[pkg/tools/version.go, line 91 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/658#-LAJ0BAI0aXNEfa5-MB4:-LAJ0BAI0aXNEfa5-MB5:bnb9wb8) ([raw file](https://github.com/mirantis/virtlet/blob/88258e128caf0b22cb6d580de49638bffaf421c2/pkg/tools/version.go#L91)):*
> ```Go
> 			continue
> 		case exitCode != 0:
> 			errors = append(errors, fmt.Sprintf("node %q: error getting version from Virtlet pod %q: %v", nodeName, podName, err))
> ```

There should be probably shown `exitCode` as `err` is equal in this case to `nil`.
If it should have the same body it should be probably denoted as `case err != nil, exitCode != 0:`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/658)*

**Comment by ivan4th** [comment]
Review status: 36 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/virtlet/virtlet.go, line 180 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/658#-LAIzVhR77aEbQj2vaMy:-LAMdQ_JCNYD4ti_6GoN:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/88258e128caf0b22cb6d580de49638bffaf421c2/cmd/virtlet/virtlet.go#L180)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Imo `os.Exit` should be called from main, not from above func, but I'm fine with that also...
</blockquote></details>

Done.

---

*[pkg/tools/version.go, line 91 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/658#-LAJ0BAI0aXNEfa5-MB4:-LAMdOYO22UXhXZ6G9ND:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/88258e128caf0b22cb6d580de49638bffaf421c2/pkg/tools/version.go#L91)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

There should be probably shown `exitCode` as `err` is equal in this case to `nil`.
If it should have the same body it should be probably denoted as `case err != nil, exitCode != 0:`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/658)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 37 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/658#-:-LAMxrdd-v9rpMS0jCaI:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/658#-:-LAMyZN5DG52S49nMLkw:bnfp4nl)*

**Pull request merged**
