### PR TITLE
Fixed go import paths

### PR DESCRIPTION
**Pull request by vefimova**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/11)

### CODE REVIEW

**Comment by nhlfr** [comment]
Umm...

```
$ git remote add victoria git@github.com:vefimova/virtlet.git
$ git fetch -t victoria
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), done.
From github.com:vefimova/virtlet
 * [new branch]      fixed_imports -> victoria/fixed_imports
 * [new branch]      master     -> victoria/master
$ git checkout fixed_imports 
Branch fixed_imports set up to track remote branch fixed_imports from victoria.
Switched to a new branch 'fixed_imports'
$ ./autogen.sh 
configure.ac:4: installing './compile'
configure.ac:2: installing './install-sh'
configure.ac:2: installing './missing'
parallel-tests: installing './test-driver'
pkg/libvirttools/Makefile.am: installing './depcomp'
 nhlfr@nhlfr-pc  ~/gopath/src/github.com/Mirantis/virtlet   fixed_imports  ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for glib... yes
checking for libvirt... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating pkg/download/Makefile
config.status: creating pkg/etcdtools/Makefile
config.status: creating pkg/libvirttools/Makefile
config.status: creating pkg/manager/Makefile
config.status: creating pkg/sandbox/Makefile
config.status: executing depfiles commands
$ make
Making all in pkg/download
make[1]: Entering directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/pkg/download'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/pkg/download'
Making all in pkg/etcdtools
make[1]: Entering directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/pkg/etcdtools'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/pkg/etcdtools'
Making all in pkg/libvirttools
make[1]: Entering directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/pkg/libvirttools'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/pkg/libvirttools'
Making all in pkg/manager
make[1]: Entering directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/pkg/manager'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/pkg/manager'
Making all in pkg/sandbox
make[1]: Entering directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/pkg/sandbox'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/pkg/sandbox'
make[1]: Entering directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/nhlfr/gopath/src/github.com/Mirantis/virtlet'
go build -o ./virtlet ./cmd/virtlet
cmd/virtlet/virtlet.go:23:2: cannot find package "Mirantis/virtlet/pkg/manager" in any of:
	/home/nhlfr/gopath/src/github.com/Mirantis/virtlet/vendor/Mirantis/virtlet/pkg/manager (vendor tree)
	/home/nhlfr/go/src/Mirantis/virtlet/pkg/manager (from $GOROOT)
	/home/nhlfr/gopath/src/Mirantis/virtlet/pkg/manager (from $GOPATH)
Makefile:768: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by nhlfr** [comment]
Also, what's wrong with using `github.com`?

**Comment by jellonek** [comment]
If we want to drop "github.com" prefix, we should also drop "Mirantis" from this prefix and then add app project root dir into GOPATH.

**Comment by vefimova** [comment]
Yeah, well, it's not so major, but it's just the case of setting up project to be built from sources. In this case it's not obviouse, as for me, I created only Mirantis dir additionally in GOPATH/src on a hunch.

**Comment by jellonek** [comment]
So maybe it would be better to describe how to develop/contribute into virtlet?
@nhlfr wdyt?

**Comment by nhlfr** [comment]
I described building process in #12 - due to C codebase and unit test (which will probably become even bigger), I think that autotools is the way to go.

We may also prepare docs for contributing and adding things to configure.ac, Makefile.am etc. Maybe tomorrow.

**Comment by nhlfr** [comment]
However, we may continue work on this PR and get rid of the whole `github.com/Mirantis/virtlet` prefix, like rkt did. @vefimova do you agree?

**Comment by vefimova** [comment]
yes, I'll do it.

**Comment by vefimova** [comment]
@jellonek @nhlfr 
I doubt that it's possible to get rid of the whole prefix. At least, in a valid way. We still need to have some root dir for the project at GOPATH/src, in our case GOPATH/src/virtlet. As otherwise if you specifi GOPATH to project root dir, go will look other sources with adding "src".
However it's possible to use relative paths, it's discouraged and doesn't seem right thing:
`go build -o ./virtlet ./cmd/virtlet
package ./cmd/virtlet
        imports ../../pkg/manager
        imports ../../pkg/etcdtools
        imports ../../vendor/github.com/coreos/etcd/client: must be imported as github.com/coreos/etcd/client
package ./cmd/virtlet
        imports ../../vendor/github.com/golang/glog: must be imported as github.com/golang/glog
`

So I suppose I'll turn this PR out to chenges in docs, regarding GOPATH setting and that's all. WDYT?

**Comment by jellonek** [comment]
LGTM!

**Pull request merged**
