### PR TITLE
e2e: Change ImagePullPolicy

### PR DESCRIPTION
**Pull request by jellonek**
Set correct ImagePullPolicy for e2e tests.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/430)

### CODE REVIEW

**Comment by jellonek** [comment]
Rebased on top of #432 because of tests.

**Comment by jellonek** [comment]
Please do not merge - will rebase it on top of the master branch after PR with vnc disabling will be merged to it.

**Comment by jellonek** [comment]
Rebase already done. So we will have additional run of tests ;)

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/430#-:-Kv3Du713Q_QSjY4uMj4:bnfp4nl)*

**Comment by pigmej** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/430)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/430#-:-Kv3EHqR2KRs9rM--3JS:bnfp4nl)*

**Pull request merged**
