### PR TITLE
Redownload dind cluster script if it exists to be sure it is up to date

### PR DESCRIPTION
**Pull request by vefimova**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/243)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/demo.sh, line 43 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhEuVuBwIsUQehGsN-0:-KhEuVuBwIsUQehGsN-1:bh0vj5a) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L43)):*
> ```Shell
>     demo::step "Will now clear existent dind-cluster-v1.5.sh to be sure it is up to date"
>     demo::ask-before-continuing
>     rm ${dind_script}
> ```

Hmmm... IMO better would be to have there an option to skip this `rm`, as someone could prefer to use already tested ver, instead of looking for lottery, hoping that newer one is really better ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/demo.sh, line 43 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhEuVuBwIsUQehGsN-0:-KhEvcTSxrQAr7cFwutY:b5mtl7k) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L43)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... IMO better would be to have there an option to skip this `rm`, as someone could prefer to use already tested ver, instead of looking for lottery, hoping that newer one is really better ;)
</blockquote></details>

I think we shouldn't remove it  at all, these scripts are going to stabilize someday, therefore we will *not* need to update them for quite long time. Or at least there should be possibility to preserve existing one as @jellonek suggests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by vefimova** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/demo.sh, line 43 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhEuVuBwIsUQehGsN-0:-KhMcvQI0Ldi3B3eqN0M:b-qxd292) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L43)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

I think we shouldn't remove it  at all, these scripts are going to stabilize someday, therefore we will *not* need to update them for quite long time. Or at least there should be possibility to preserve existing one as @jellonek suggests
</blockquote></details>

Well, as we always update dind image only warning about that, not updating scripts as well can cause issues, like with introducing https://github.com/Mirantis/kubeadm-dind-cluster/search?utf8=%E2%9C%93&q=CNI_PLUGIN&type=  new var CNI_PLUGIN lately which will be unset otherwise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/demo.sh, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhMxP5fPppEgW56KUmN:-KhMxP5fPppEgW56KUmO:b-efzt45) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L41)):*
> ```Shell
> function demo::get-dind-cluster {
>   if [[ -f ${dind_script} ]]; then
>     demo::step "Will now clear existent dind-cluster-v1.5.sh to be sure it is up to date"
> ```

"Will now update ${dind_script} script to the latest version" 

---

*[deploy/demo.sh, line 43 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhEuVuBwIsUQehGsN-0:-KhMxbS4X38bbZ6Vz82H:b-it84ou) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L43)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Well, as we always update dind image only warning about that, not updating scripts as well can cause issues, like with introducing https://github.com/Mirantis/kubeadm-dind-cluster/search?utf8=%E2%9C%93&q=CNI_PLUGIN&type=  new var CNI_PLUGIN lately which will be unset otherwise.
</blockquote></details>

rm "${dind_script}"

(quote the var)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by vefimova** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/demo.sh, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhMxP5fPppEgW56KUmN:-KhWyRe1WvgEy8rBYcN6:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L41)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

"Will now update ${dind_script} script to the latest version" 
</blockquote></details>

Done.

---

*[deploy/demo.sh, line 43 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhEuVuBwIsUQehGsN-0:-KhWyRM2PqZVre385Bss:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L43)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

rm "${dind_script}"

(quote the var)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by jellonek** [comment]
:lgtm: but still IMO we should an option to skip this `rm`. Up to now we have a possibility to use old/tested ver or dind script. This is changed there and does not provide any option to keep old-safe behavior.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243#-:-KhWz2AUnVJC0qy0FeGK:b-r7zf24)*

**Comment by vefimova** [comment]
updated, ptal

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy/demo.sh, line 69 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KnK2bXNtT9PJYBg-jp_:-KnK2bXNtT9PJYBg-jpa:b-rlq39o) ([raw file](https://github.com/mirantis/virtlet/blob/b8cd413085326e714d91e434a22b67bc3563cc88/deploy/demo.sh#L69)):*
> ```Shell
>     demo::step "Found existent ${dind_script}, it can be not up to date"
>     if [[ ! ${NONINTERACTIVE} ]]; then
>         demo::ask-user "Do you want to reload ${dind_script} ?" download
> ```

"redownload", instead of "reload"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by vefimova** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy/demo.sh, line 69 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KnK2bXNtT9PJYBg-jp_:-KnLeGLTJD7DUBcEeU0x:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/b8cd413085326e714d91e434a22b67bc3563cc88/deploy/demo.sh#L69)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

"redownload", instead of "reload"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243#-:-KnZEhT6rU1xPugTg_Mh:bnfp4nl)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/demo.sh, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhMxP5fPppEgW56KUmN:-KnZK3A5Zx6G1xm4wnGE:b2d66d6) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L41)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Where it's done? I don't see it still says that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by vefimova** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/demo.sh, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhMxP5fPppEgW56KUmN:-KncmedXZ-EtTFIgiz2r:b2plxa1) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L41)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

Where it's done? I don't see it still says that.
</blockquote></details>

Well, actually this comment was valid to previous version of patch, so I don't think it's still valid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by vefimova** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/demo.sh, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhMxP5fPppEgW56KUmN:-Knee2F2HUxzgiZOXbS3:b-34yyua) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L41)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Well, actually this comment was valid to previous version of patch, so I don't think it's still valid.
</blockquote></details>

now done :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243#-:-KnehdmTQdYRZbLd0K2r:bnfp4nl)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/demo.sh, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhMxP5fPppEgW56KUmN:-Knej6_mehxGeA71IPGJ:b7g1qfy) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L41)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

now done :)
</blockquote></details>

In fact do we really need this message? Because then we're asking if redownload. Also it's bit missleading.

Though I'm not blocking merge just wondering (we can also fix it later)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy/demo.sh, line 74 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KnfCQyBcGYfmpl6esBG:-KnfCQyCbbbbDfHpHhhJ:b135its) ([raw file](https://github.com/mirantis/virtlet/blob/8358667b7de84be8ad85c9767813fe290d9bb902/deploy/demo.sh#L74)):*
> ```Shell
>         fi
>     else
>        demo::step "Will now clear existent ${dind_script}"
> ```

existing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by vefimova** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy/demo.sh, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KhMxP5fPppEgW56KUmN:-KnfKJjcNOmFg0bvJfjB:b-ikoerf) ([raw file](https://github.com/mirantis/virtlet/blob/844152acc5d845ea8839b1ab2ee1f55c64fba8e7/deploy/demo.sh#L41)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

In fact do we really need this message? Because then we're asking if redownload. Also it's bit missleading.

Though I'm not blocking merge just wondering (we can also fix it later)
</blockquote></details>

Maybe re-phrase it as "Better to update...."

---

*[deploy/demo.sh, line 74 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/243#-KnfCQyBcGYfmpl6esBG:-KnfK4LNmG6K0CiWvcMo:b4lmwgo) ([raw file](https://github.com/mirantis/virtlet/blob/8358667b7de84be8ad85c9767813fe290d9bb902/deploy/demo.sh#L74)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

existing
</blockquote></details>

thx, sorry, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243#-:-KniV2rbVd0Zg0dcsE-C:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/243#-:-KniVOTR3qufTVVp_jpL:bnfp4nl)*

**Pull request merged**
