### PR TITLE
Better CNI handling

### LINKED ISSUE #284: Pass extra args to CNI
Need to pass extra arguments to CNI that include `K8S_POD_NAMESPACE`, `K8S_POD_NAME`, `K8S_POD_INFRA_CONTAINER_ID` like kubelet does: https://github.com/kubernetes/kubernetes/blob/v1.6.2/pkg/kubelet/network/cni/cni.go#L289-L294

This is needed by some of CNI implementations we're working with.

### PR DESCRIPTION
**Pull request by ivan4th**
- Mimic the kubelet behavior in passing extra CNI args
- Move hwaddr from CNI veth to the VM
- Ignore CNI-provided json config if it has no routes (i.e. no default gw) and extract it from netns instead. This makes Virtlet support Weave.

Fixes #284

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/291)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/291#-:-KktP8p1wXO_4ECao4KE:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/291#-:-Kl7v08bnbWeRiWKXpeZ:bnfp4nl)*

**Comment by vefimova** [comment]
one small nit

---

Reviewed 4 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 34 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/291#-KlPiwrDPFJWlH9AWBr4:-KlPiwrDPFJWlH9AWBr5:b-ofqx1f) ([raw file](https://github.com/mirantis/virtlet/blob/567d8c366819e4916983411f04524f7c11e92ced/README.md#L34)):*
> ```Markdown
> ```
> 
> By default, CNI bridge plugin is used for cluster networking. I's also possible to override this with `flannel` or `weave` plugin, e.g.:
> ```

s/I's/It's/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/291#-:-KlPnEVFRvA3ff2nz22O:bg94zfl)*

**Comment by ivan4th** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 34 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/291#-KlPiwrDPFJWlH9AWBr4:-KlPrHhs5w9Zqb-PWbgG:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/567d8c366819e4916983411f04524f7c11e92ced/README.md#L34)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

s/I's/It's/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/291)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/291#-:-KlPrW5Dr5kZ1FWLaOZq:bnfp4nl)*

**Pull request merged**
