### PR TITLE
ConfigDrive support + fix on dns search

### PR DESCRIPTION
**Pull request by jellonek**
TODO:
 - [x] update integration test for ConfigDrive
 - [x] update docs

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/553)

### CODE REVIEW

**Comment by jellonek** [comment]
Ok. It's ready to review.

**Comment by ivan4th** [comment]
Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/cloud-init-data-generation.md, line 20 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/553#-L2uKSA9WLKbDd_D6HXS:-L2uKSA9WLKbDd_D6HXT:b-58yry2) ([raw file](https://github.com/mirantis/virtlet/blob/d45ab03a5e156736fcf43cf24c000655e718f7c2/docs/cloud-init-data-generation.md#L20)):*
> ```Markdown
> ConfigDrive. Which one should be used is controlled by annotation
> `VirtletCloudInitImageType`. It accepts as values `nocloud`, `configdrive` and
> defaults to `nocloud` when annotation is not set.
> ```

Virtlet supports two types of Cloud-init ISO9660-based datasources, NoCloud and
ConfigDrive. The user may choose an appropriate one using
`VirtletCloudInitImageType` annotation, which can have either `nocloud` or `configdrive` as its value. 
When there's no `VirtletCloudInitImageType` annotation, Virtlet defaults to `nocloud`.

---

*[docs/cloud-init-data-generation.md, line 160 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/553#-L2uL0hmslsIoiyQmQt1:-L2uL0hmslsIoiyQmQt2:bafllhg) ([raw file](https://github.com/mirantis/virtlet/blob/d45ab03a5e156736fcf43cf24c000655e718f7c2/docs/cloud-init-data-generation.md#L160)):*
> ```Markdown
> 
> In case of Config Drive this JSON has duplicated `instance-id` as `uuid` and
> `local-hostname` as `hostname`.
> ```

In case of ConfigDrive, this JSON has `instance-id` repeated as `uuid` and `local-hostname` repeated as `hostname`.

---

*[pkg/libvirttools/cloudinit_test.go, line 99 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/553#-L2uIcQwPXOKKUXGnio-:-L2uIcQwPXOKKUXGnio0:ba8vn3w) ([raw file](https://github.com/mirantis/virtlet/blob/421e727ae284549bae492d9be92cb29db79fd59e/pkg/libvirttools/cloudinit_test.go#L99)):*
> ```Go
> 		expectedNetworkConfig map[string]interface{}
> 		expectedUserDataStr   string
> 	}{
> ```

Is it possible to add a configdrive test case(s) here ? It shouldn't be hard

---

*[pkg/libvirttools/cloudinit_test.go, line 364 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/553#-L2uK6Kvo93CG-eUM-aS:-L2uK6Kvo93CG-eUM-aT:bz2bx02) ([raw file](https://github.com/mirantis/virtlet/blob/d45ab03a5e156736fcf43cf24c000655e718f7c2/pkg/libvirttools/cloudinit_test.go#L364)):*
> ```Go
> 		},
> 		{
> 			name: "pod with network config",
> ```

These test cases need to be implemented for "configdrive", too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/553)*

**Comment by jellonek** [comment]
Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/cloud-init-data-generation.md, line 20 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/553#-L2uKSA9WLKbDd_D6HXS:-L2uTZe1R9OzE5xcujKA:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d45ab03a5e156736fcf43cf24c000655e718f7c2/docs/cloud-init-data-generation.md#L20)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Virtlet supports two types of Cloud-init ISO9660-based datasources, NoCloud and
ConfigDrive. The user may choose an appropriate one using
`VirtletCloudInitImageType` annotation, which can have either `nocloud` or `configdrive` as its value. 
When there's no `VirtletCloudInitImageType` annotation, Virtlet defaults to `nocloud`.

</blockquote></details>

Done.

---

*[docs/cloud-init-data-generation.md, line 160 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/553#-L2uL0hmslsIoiyQmQt1:-L2uT_BiW22UUbAQI092:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d45ab03a5e156736fcf43cf24c000655e718f7c2/docs/cloud-init-data-generation.md#L160)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

In case of ConfigDrive, this JSON has `instance-id` repeated as `uuid` and `local-hostname` repeated as `hostname`.
</blockquote></details>

Done.

---

*[pkg/libvirttools/cloudinit_test.go, line 99 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/553#-L2uIcQwPXOKKUXGnio-:-L2uTaX8kvKMNmPiwpbm:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/421e727ae284549bae492d9be92cb29db79fd59e/pkg/libvirttools/cloudinit_test.go#L99)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Is it possible to add a configdrive test case(s) here ? It shouldn't be hard
</blockquote></details>

Done.

---

*[pkg/libvirttools/cloudinit_test.go, line 364 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/553#-L2uK6Kvo93CG-eUM-aS:-L2uTc5hO3hb7Qmv5uhw:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d45ab03a5e156736fcf43cf24c000655e718f7c2/pkg/libvirttools/cloudinit_test.go#L364)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

These test cases need to be implemented for "configdrive", too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/553)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/553#-:-L32K5LOs9g-ItEH8tsp:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 22 of 24 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/553#-:-L32VeFvffjvxF14M_W9:bnfp4nl)*

**Comment by jellonek** [comment]
Rebased on top of master. Please wait for tests and rereview.

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 21 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/553#-:-L32gLWhFm7tj7u7iYNQ:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/553#-:-L32nP0bOcKAG8dBG8c7:bnfp4nl)*

**Pull request merged**
