### PR TITLE
Support mounting virtlet flexvolumes using volumeMounts

### LINKED ISSUE #287: Support mounting virtlet flexvolumes using volumeMounts
This is Stage 3 of Virtlet [cloud-init data generation proposal](https://github.com/Mirantis/virtlet/blob/master/docs/design-proposals/cloud-init-data-generation.md). It depends on #286 

Virtlet should generate cloud-init user-data that mounts virtlet flexvolumes into the VM.
E.g. the following should cause the corresponding volumes to be mounted under
`/var/lib/docker`, `/var/lib/postgresql` and `/cephdata`:

```yaml
  containers:
  - name: ubuntu-vm
    image: virtlet/cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
    volumeMounts:

    # mount the qcow2 volume under /var/lib/docker
    - name: extra
      mountPath: /var/lib/docker

    # mount a raw device under /var/lib/postgresql
    - name: raw
      mountPath: /var/lib/postgresql

    # mount a ceph volume under /cephdata
    - name: ceph
      mountPath: /cephdata

  volumes:
  - name: extra
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: qcow2
        capacity: 2048MiB
  - name: raw
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: raw
        path: /dev/mapper/somevg
  - name: ceph
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: ceph
        monitor: 10.0.0.1:6789
        user: libvirt
        secret: ....
        volume: rbd-test-image
        pool: libvirt-pool
```

This is done by generating the following `mounts` section in `user-data`:
```yaml
#cloud-config
mounts:
- [ /dev/vdc1, /var/lib/docker ]
- [ /dev/vdd, /var/lib/postgresql ]
- [ /dev/vde, /cephdata ]
```

### PR DESCRIPTION
**Pull request by ivan4th**
- [x] use `virtio-scsi` for disks by default to  get more predictable disk ordering
- [x] support mounting flexvolumes into VM via cloud-init
- [x] update docs

Fixes #287

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/317)

### CODE REVIEW

**Comment by jellonek** [comment]
```
# github.com/Mirantis/virtlet/tests/integration
./container_test.go:73: not enough arguments in call to flexvolume.NewFlexVolumeDriver
```
So not only a docs need update :)

**Comment by jellonek** [comment]
Reviewed 38 of 38 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/volumes.md, line 13 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/317#-Kma8z4F-RnS3WfLCFRt:-Kma8z4F-RnS3WfLCFRu:bqutzhg) ([raw file](https://github.com/mirantis/virtlet/blob/c43be40e340b038e87abb86a5b07addd56747629/docs/volumes.md#L13)):*
> ```Markdown
>   annotations:
>     kubernetes.io/target-runtime: virtlet
>     VirtletDiskDriver: virtio
> ```

That is quite strange - both drivers are using `virtio` as transport, so there IMO should be `blk` and `scsi` acceptable.

---

*[docs/volumes.md, line 70 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/317#-KmaA2plTg6gHV99vFvg:-KmaA2plTg6gHV99vFvh:b-ukv1pd) ([raw file](https://github.com/mirantis/virtlet/blob/c43be40e340b038e87abb86a5b07addd56747629/docs/volumes.md#L70)):*
> ```Markdown
> 
> 3. The attached disks are visible by the OS inside VM as hard disk
>    devices `/dev/sdb`, `/dev/sdc` and so on (`/dev/sdb`, `/dev/sdc`
> ```

This should be `vdb`, `vdc` in parentheses, for blk.

---

*[docs/volumes.md, line 140 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/317#-KmaAdjLnfOgUX_rdaGx:-KmaAdjLnfOgUX_rdaGy:b-v7sdp) ([raw file](https://github.com/mirantis/virtlet/blob/c43be40e340b038e87abb86a5b07addd56747629/docs/volumes.md#L140)):*
> ```Markdown
> According to this definition will be created VM-POD with VM with 2
> equal volumes, attached, which can be found in "volumes" pool under
> `<domain-uuid>-vol1` and `<domain-uuid>-vol2` A clone of boot image is
> ```

Missing dot before "A clone".

---

*[docs/volumes.md, line 294 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/317#-KmaBTU3jZWXuZWTz_C-:-KmaBTU3jZWXuZWTz_C0:bo51dfn) ([raw file](https://github.com/mirantis/virtlet/blob/c43be40e340b038e87abb86a5b07addd56747629/docs/volumes.md#L294)):*
> ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/317)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/volumes.md, line 13 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/317#-Kma8z4F-RnS3WfLCFRt:-KmaC-a9VOhL_FzVgBuM:bo224tg) ([raw file](https://github.com/mirantis/virtlet/blob/c43be40e340b038e87abb86a5b07addd56747629/docs/volumes.md#L13)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

That is quite strange - both drivers are using `virtio` as transport, so there IMO should be `blk` and `scsi` acceptable.
</blockquote></details>

I used the values employed by libvirt in 'target' spec of the disk.

---

*[docs/volumes.md, line 70 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/317#-KmaA2plTg6gHV99vFvg:-KmaC73n6k_yOoL8F9NT:bvr1g4p) ([raw file](https://github.com/mirantis/virtlet/blob/c43be40e340b038e87abb86a5b07addd56747629/docs/volumes.md#L70)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This should be `vdb`, `vdc` in parentheses, for blk.
</blockquote></details>

Thanks, will fix

---

*[docs/volumes.md, line 140 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/317#-KmaAdjLnfOgUX_rdaGx:-KmaC9EQ2xvK3LoNX_ZM:bhy9q7g) ([raw file](https://github.com/mirantis/virtlet/blob/c43be40e340b038e87abb86a5b07addd56747629/docs/volumes.md#L140)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Missing dot before "A clone".
</blockquote></details>

Will fix

---

*[docs/volumes.md, line 294 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/317#-KmaBTU3jZWXuZWTz_C-:-KmaCCrsg-pi-Q6xNVGm:bb7hl18) ([raw file](https://github.com/mirantis/virtlet/blob/c43be40e340b038e87abb86a5b07addd56747629/docs/volumes.md#L294)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

> ...
</blockquote></details>

hmm?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/317)*

**Comment by jellonek** [comment]
Review status: 39 of 40 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/volumes.md, line 294 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/317#-KmaBTU3jZWXuZWTz_C-:-Kmao7pVW9RAAlcdnZLv:b-3ottmm) ([raw file](https://github.com/mirantis/virtlet/blob/c43be40e340b038e87abb86a5b07addd56747629/docs/volumes.md#L294)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

hmm?
</blockquote></details>

Sorry - misclick.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/317)*

**Comment by ivan4th** [comment]
Review status: 39 of 40 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/volumes.md, line 13 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/317#-Kma8z4F-RnS3WfLCFRt:-Kmb71eipwBS--GF1hNz:b-qq1gwu) ([raw file](https://github.com/mirantis/virtlet/blob/c43be40e340b038e87abb86a5b07addd56747629/docs/volumes.md#L13)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I used the values employed by libvirt in 'target' spec of the disk.
</blockquote></details>

Updated the description, now it lists the possible values and tells why these values were chosen.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/317)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/317#-:-KmbCLBxPDFVk2ETHsbL:bnfp4nl)*

**Comment by vefimova** [comment]
Reviewed 38 of 38 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/volumes.md, line 294 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/317#-KmbHbdZnO-0kh7_3kbm:-KmbHbdZnO-0kh7_3kbn:b6iq3zd) ([raw file](https://github.com/mirantis/virtlet/blob/b6c9f5fa4b735e67d34153e3b8d5ec0cdfcdaeaa/docs/volumes.md#L294)):*
> ```Markdown
> ### Mounting the volumes into the VMs
> 
> In case if the guest OS supports proper `#cloud-config` format of
> ```

Probably it's worth to mention, what happen otherwise?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/317)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/volumes.md, line 294 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/317#-KmbHbdZnO-0kh7_3kbm:-KmbMR9-v4Wq-7EgBT7i:b-z21vq7) ([raw file](https://github.com/mirantis/virtlet/blob/b6c9f5fa4b735e67d34153e3b8d5ec0cdfcdaeaa/docs/volumes.md#L294)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Probably it's worth to mention, what happen otherwise?
</blockquote></details>

Well... Actually it kind of obvious, in that case, it's not possible to mount the volumes (unrecognized user-data file is not handled). As of availability of volumes that aren't mounted,  this part I didn't change this behavior (although was going to initially) and it's already described above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/317)*

**Comment by vefimova** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/317#-:-KmbR0FU6jPizGJqqY2d:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/317#-:-KmbSbPsoHZHjYJSvsnK:bnfp4nl)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/317#-:-KmbTftL-lHSzml5rIkx:bnfp4nl)*

**Pull request merged**
