### PR TITLE
Disable VNC

### PR DESCRIPTION
**Pull request by jellonek**
... because of causing sig-segv inside of libvirt.

Libvirt fails on vnc/spice port allocation what leads to failure in starting VMs and even libvirt crash.
Upstream libvirt bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863266

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/432)

### CODE REVIEW

**Comment by istalker2** [comment]
I'd prefer a solution that fixes vnc rather than removes the support for it. Can't we allocate ports manually? Also, why leave it commented? There is always git history for that

**Comment by jellonek** [comment]
Look around on this section of file - we have such comments repeating.
It's temporary fix until we find a proper solution.
Btw. this support was used only in e2e tests, it was even not documented.

**Comment by pigmej** [comment]
:lgtm:

I agree with that solution, adding control over ports may be separate solution, but for now this one is ok.

---

Reviewed 2 of 2 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/432#-:-Kusi1PoTgUdmwpuRQEd:b-wmskmo)*

**Comment by ivan4th** [comment]
The primary reason for this is libvirt vnc port allocation problem. It would be better to mention it in comments instead of a bit vague "libvirt failure". Also you may mention libvirt crash after libvirt error due to the port allocation problem in the descriptive part of the commit message.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/432#-:-KussBhCbWn3MnBGzI8p:b-6oywbg)*

**Comment by jellonek** [comment]
Updated commit message and PR description according to Ivan's comment.

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/432#-:-KuxZe44R12uFrA6dbD_:bnfp4nl)*

**Pull request merged**
