### PR TITLE
Image name translation with YAML configs

### PR DESCRIPTION
**Pull request by istalker2**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/409)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[deploy/images.yaml, line 4 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KtpsveBUyMcFtEKy4r4:-KtpsveBUyMcFtEKy4r5:b-o5lsel) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/deploy/images.yaml#L4)):*
> ```YAML
>   - name: cirros/0.3.5
>     url: https://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
> ```

Unnecessary empty line. Minor thing.

---

*[pkg/imagetranslation/translator.go, line 132 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ktpv7PdvrONi1j9_qBD:-Ktpv7PdvrONi1j9_qBE:b-64gpfx) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L132)):*
> ```Go
> 	}
> 
> 	glog.Info("Loading image name translations from ", config.Name())
> ```

Please log that on specific log level. `V(2)` seems to be optimal.

---

*[pkg/imagetranslation/translator.go, line 137 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KtpvpP9Ufa7hqOWn_Q8:-KtpvpP9Ufa7hqOWn_Q9:bqa43bx) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L137)):*
> ```Go
> 
> 	t.lock.Lock()
> 	defer t.lock.Unlock()
> ```

Manually unlocking after next line seems to be better, because glog can provide unnecessary delay there, e.g. on syncing file to disk. https://groups.google.com/forum/#!topic/golang-nuts/86Aavuin4eI for reference.

---

*[pkg/imagetranslation/translator.go, line 159 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ktpzk5ZvHEc9Y4OfNiU:-Ktpzk5ZvHEc9Y4OfNiV:bci66sb) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L159)):*
> ```Go
> 		err := t.load(config)
> 		if err != nil {
> 			glog.Warning("Error loading image translation config: ", err)
> ```

When we will have user available source - that can be abused to overgrown virtlet log.

---

*[pkg/imagetranslation/translator.go, line 169 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KtpzY__3F_tvbNaclGP:-KtpzY__3F_tvbNaclGQ:btw6i81) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L169)):*
> ```Go
> 		defer t.lock.Unlock()
> 		for name := range unusedNames {
> 			glog.Warning("Deleting image translation config ", name)
> ```

Why this is warning and not simple info? For sure verbosity level there should be adjusted.

---

*[pkg/imagetranslation/translator.go, line 202 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KtpxNrNEqag7Lt9Ku8D:-KtpxNrNEqag7Lt9Ku8E:b38hli6) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L202)):*
> ```Go
> 			re, err := regexp.Compile(r.Regex)
> 			if err != nil {
> 				glog.Warning("Invalid regexp in image translation config: ", r.Regex)
> ```

With broken data provided by some user controlled source that can spam a bit logs of virtlet, what is not so usable for end user. That can be even used in malicious way to overgrown virtlet logs, when e.g. virtlet is supposed to be quite, when started with `-v 0`.
The simple idea is to move that to different verbosity level, e.g. 2, or even 3 - because at the end the real validation of data correctness should be done on different level - a only supported tool to manipulate this type of configuration.
Same applies to other calls of `glog.Warning` in this file.

---

*[pkg/libvirttools/image.go, line 38 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ktq-1kSC_KsR36kCx26:-Ktq-1kSC_KsR36kCx27:b6euj54) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/libvirttools/image.go#L38)):*
> ```Go
> const (
> 	imageTranslationConfigsDirectory     = "/etc/virtlet/images"
> 	imageTranslationConfigsPollFrequency = time.Second * 3
> ```

I don't like the idea to hardcode this value there. If content of this directory has to be dynamically modifiable the time should be probably smaller. If it will be provided as not modifiable data, there is no reason to reread it's content at all. It seems to me that this value should be set per data source, or at last as cmdline provided value.

---

*[pkg/libvirttools/image.go, line 99 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KtpuHFBW9Svogk2xUfw:-KtpuHFBW9Svogk2xUfx:bk1i9ak) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/libvirttools/image.go#L99)):*
> ```Go
> 	if endpoint.Url == "" {
> 		endpoint = imagetranslation.Endpoint{Url: imageName}
> 		glog.Infof("Using URL %q without translation", imageName)
> ```

Please leave this info on `V(3)` verbosity level.
Same for below call to `glog.Infof`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[pkg/imagetranslation/translator.go, line 92 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku45j2UR24X1CJyIDxL:-Ku45j2UR24X1CJyIDxM:bhgfa7l) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L92)):*
> ```Go
> 		return tr, err
> 	}
> 	err = yaml.Unmarshal(data, &tr)
> ```

It would be nice to include filename in the unmarshalling error message.

---

*[pkg/imagetranslation/translator.go, line 159 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ktpzk5ZvHEc9Y4OfNiU:-Ku43NTOm4NRGy2YoRWf:b-md0i0y) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L159)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

When we will have user available source - that can be abused to overgrown virtlet log.
</blockquote></details>

@jellonek I think having always-visible message here is still important.

---

*[pkg/imagetranslation/translator.go, line 239 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku44xpUGoIsUWYpU5AL:-Ku44xpUGoIsUWYpU5AM:b-714gxd) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L239)):*
> ```Go
> func (t *ImageNameTranslator) StopBackgroundUpdates() {
> 	if t.stopBackgroundUpdates != nil {
> 		t.stopBackgroundUpdates <- struct{}{}
> ```

Why not just close the channel here? It'll work just fine for waking up `select`

---

*[pkg/imagetranslation/translator.go, line 248 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku45BJTofQLzEYYAybR:-Ku45BJTofQLzEYYAybS:bf0yjsy) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L248)):*
> ```Go
> 		configSource: source,
> 		translations: map[string]*ImageTranslation{},
> 		AllowRegexp:  env == "1" || env == "TRUE" || env == "YES",
> ```

For other env var settings like `VIRTLET_DISABLE_KVM` we have any non-empty value meaning true. We need to either fix it in all places or update this part to make it consistent with the rest of Virtlet.

---

*[pkg/utils/download.go, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku44ScirMc2m5RPm6qF:-Ku44ScirMc2m5RPm6qG:bchdh6r) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/utils/download.go#L50)):*
> ```Go
> }
> 
> func (d *defaultDownloader) DownloadFile(endpoint imagetranslation.Endpoint) (string, error) {
> ```

What's the advantage here of passing `imagetranslation.Endpoint` here? We're adding `pkg/utils` -> `pkg/imagetranslation` dependency here with no apparent gains ... `pkg/utils` is supposed to be "leaf" package with no deps inside virtlet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by istalker2** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[pkg/imagetranslation/translator.go, line 159 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ktpzk5ZvHEc9Y4OfNiU:-KuJ1bBHjRutmkweqsMD:b4a1l6u) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L159)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

@jellonek I think having always-visible message here is still important.
</blockquote></details>

The next commit will change how configs are accessed and there won't be background updates anymore. Thus there won't be too many error messages anyway

---

*[pkg/imagetranslation/translator.go, line 248 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku45BJTofQLzEYYAybR:-KuJ20ivJZNSqJR3waiy:bd3i8e8) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L248)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

For other env var settings like `VIRTLET_DISABLE_KVM` we have any non-empty value meaning true. We need to either fix it in all places or update this part to make it consistent with the rest of Virtlet.
</blockquote></details>

I can fix it later in a separate commit for other places. I don't find logical `SOME_FLAG=0` to work exactly like `SOME_FLAG=1` because both 1 and 0 are non-empty values

---

*[pkg/libvirttools/image.go, line 38 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ktq-1kSC_KsR36kCx26:-KuJ2OGrjQuIPLjhR1A9:bww6bm7) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/libvirttools/image.go#L38)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

I don't like the idea to hardcode this value there. If content of this directory has to be dynamically modifiable the time should be probably smaller. If it will be provided as not modifiable data, there is no reason to reread it's content at all. It seems to me that this value should be set per data source, or at last as cmdline provided value.
</blockquote></details>

This will turn into CLI flag in next commit

---

*[pkg/libvirttools/image.go, line 99 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KtpuHFBW9Svogk2xUfw:-KuJ2W0EkoKTNLD93XM3:b-dgmvzk) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/libvirttools/image.go#L99)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Please leave this info on `V(3)` verbosity level.
Same for below call to `glog.Infof`.
</blockquote></details>

I think that this particular message is very important for debugging since it shows what is the real image location that is going to be used. Considering there is just 1 such message per VM I think it deserves to be in the log even on basic log level

---

*[pkg/utils/download.go, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku44ScirMc2m5RPm6qF:-KuJ3-1AZTXnXg2x8hmX:b-libp8x) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/utils/download.go#L50)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

What's the advantage here of passing `imagetranslation.Endpoint` here? We're adding `pkg/utils` -> `pkg/imagetranslation` dependency here with no apparent gains ... `pkg/utils` is supposed to be "leaf" package with no deps inside virtlet
</blockquote></details>

`Eendpoint` is just a data structure. Currently, it only contains Url, but in the near future, it's going to contain other endpoint-related things like TLS and HTTP parameters.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[pkg/libvirttools/image.go, line 38 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ktq-1kSC_KsR36kCx26:-KuJ47ewPSg--Yug4hq5:bb6mt9b) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/libvirttools/image.go#L38)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

This will turn into CLI flag in next commit
</blockquote></details>

:+1:

---

*[pkg/libvirttools/image.go, line 99 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KtpuHFBW9Svogk2xUfw:-KuJ3rcaqR983nmH9lhs:b3h00mw) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/libvirttools/image.go#L99)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

I think that this particular message is very important for debugging since it shows what is the real image location that is going to be used. Considering there is just 1 such message per VM I think it deserves to be in the log even on basic log level
</blockquote></details>

Exactly - it's for debugging purpose and only for it, so it should land on the same level as other debugging info which we are producing - and in our case it's `V(3)`.
Even if  looks "small enough" it should not land in output if no one is debugging anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks broke.

---

*[examples/cirros-vm.yaml, line 41 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KuJC8zOKOddgidyzGX0:-KuJC8zOKOddgidyzGX1:b-g5t97o) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/examples/cirros-vm.yaml#L41)):*
> virtlet/cirros/0.3.5

We merged prs that are using our "custom" cirros, can you adjust examples to that?

---

*[pkg/utils/download.go, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku44ScirMc2m5RPm6qF:-KuJCRyPxtnhiod2weYg:bllwaeb) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/utils/download.go#L50)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

`Eendpoint` is just a data structure. Currently, it only contains Url, but in the near future, it's going to contain other endpoint-related things like TLS and HTTP parameters.  
</blockquote></details>

:+1: for Stan idea about TLS options etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by istalker2** [comment]
Comments that left without an answer are no longer relevant after the last commit

---

Review status: 3 of 23 files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409#-:-KuJaSoRXegq2X_UVamO:b-xc6gcj)*

**Comment by ivan4th** [comment]
Review status: 3 of 23 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[pkg/imagetranslation/translator.go, line 248 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku45BJTofQLzEYYAybR:-KuJbiQobtmVuK53t6LD:b-ebp458) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L248)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

I can fix it later in a separate commit for other places. I don't find logical `SOME_FLAG=0` to work exactly like `SOME_FLAG=1` because both 1 and 0 are non-empty values
</blockquote></details>

Well maybe keep it consistent with other places for this PR and then update everywhere in the next one? Because inconsistency is the worst ...

---

*[pkg/utils/download.go, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku44ScirMc2m5RPm6qF:-KuJbxkF4FAObNH5ZIn3:brw3daq) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/utils/download.go#L50)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

:+1: for Stan idea about TLS options etc.
</blockquote></details>

Then maybe keep utils package leaf and move the struct here? Because `pkg/utils` really are a bottom layer and they have no business depending on `pkg/imagetranslations`. They know nothing about image translations...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by jellonek** [comment]
Reviewed 22 of 22 files at r2, 15 of 17 files at r3.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[pkg/imagetranslation/file_source.go, line 61 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KuQ9HneozBqs-HCekeO:-KuQ9HneozBqs-HCekeP:b-b58ka0) ([raw file](https://github.com/mirantis/virtlet/blob/d61477fdcf73cf6bca8b01122271b6a5dbb9751c/pkg/imagetranslation/file_source.go#L61)):*
> ```Go
> }
> 
> // Name implements TranslationConfig Config
> ```

s/Config/Name/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by ivan4th** [comment]
Request for a followup: e2e test for image translation.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[deploy/images.yaml, line 4 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KtpsveBUyMcFtEKy4r4:-KuQSzzYlYOIWzwfAgb-:bvo3i04) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/deploy/images.yaml#L4)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Unnecessary empty line. Minor thing.
</blockquote></details>

It would be nice to provide some CRD example, too.

---

*[pkg/imagetranslation/file_source.go, line 71 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KuQSDjxICnqkYdIOFx8:-KuQSDjyZwtC1jCmNeFu:bpi343e) ([raw file](https://github.com/mirantis/virtlet/blob/d61477fdcf73cf6bca8b01122271b6a5dbb9751c/pkg/imagetranslation/file_source.go#L71)):*
> ```Go
> 	var tr ImageTranslation
> 	if err != nil {
> 		return tr, err
> ```

Please include the config path in the error message

---

*[pkg/imagetranslation/file_source.go, line 73 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KuQNAfcksSIFvGmYR3e:-KuQNAfdqmDHH9R-CjDW:bpi343e) ([raw file](https://github.com/mirantis/virtlet/blob/d61477fdcf73cf6bca8b01122271b6a5dbb9751c/pkg/imagetranslation/file_source.go#L73)):*
> ```Go
> 		return tr, err
> 	}
> 	err = yaml.Unmarshal(data, &tr)
> ```

Please include the config path in the error message

---

*[pkg/imagetranslation/translator.go, line 92 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku45j2UR24X1CJyIDxL:-KuQN3JYj2YtRG9WNrSo:b-1236si) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L92)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

It would be nice to include filename in the unmarshalling error message.
</blockquote></details>

the relevant part of code has moved, will re-add the comment there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409#-:-KuQMpgpBWH3P9zR6fG0:b-hniwnz)*

**Comment by istalker2** [comment]
Review status: 20 of 27 files reviewed at latest revision, 15 unresolved discussions.

---

*[pkg/imagetranslation/translator.go, line 92 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku45j2UR24X1CJyIDxL:-KuTJV0sycPn_hfAreFK:b9ql9ml) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L92)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

the relevant part of code has moved, will re-add the comment there.
</blockquote></details>

it's already included in a different place: when this error is trapped, it is logged with config.Name() that would be a file name in this case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by istalker2** [comment]
Review status: 20 of 27 files reviewed at latest revision, 14 unresolved discussions.

---

*[deploy/images.yaml, line 4 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KtpsveBUyMcFtEKy4r4:-KuTJvsqOrtLj6wrTVKh:b-cscrxd) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/deploy/images.yaml#L4)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

It would be nice to provide some CRD example, too.
</blockquote></details>

CRD example is in the doc and another one in e2e

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by ivan4th** [comment]
Reviewed 7 of 22 files at r2, 12 of 17 files at r3, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/imagetranslation/file_source.go, line 71 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KuQSDjxICnqkYdIOFx8:-KuTOkgmu83nbuqEmft6:b-gc7tvb) ([raw file](https://github.com/mirantis/virtlet/blob/d61477fdcf73cf6bca8b01122271b6a5dbb9751c/pkg/imagetranslation/file_source.go#L71)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Please include the config path in the error message
</blockquote></details>

Ok, I see, it's fixed in another place

---

*[pkg/imagetranslation/file_source.go, line 73 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KuQNAfcksSIFvGmYR3e:-KuTOqG5so2J0nhVSmku:b-uve4pg) ([raw file](https://github.com/mirantis/virtlet/blob/d61477fdcf73cf6bca8b01122271b6a5dbb9751c/pkg/imagetranslation/file_source.go#L73)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Please include the config path in the error message
</blockquote></details>

As above, ok, it's fixed in another place

---

*[pkg/imagetranslation/translator.go, line 239 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/409#-Ku44xpUGoIsUWYpU5AL:-KuTPLJXZqesIhoXHe1I:b-yag4x0) ([raw file](https://github.com/mirantis/virtlet/blob/7b0e6d15b25f6c16d5c780dbfe7ade2cd149537a/pkg/imagetranslation/translator.go#L239)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Why not just close the channel here? It'll work just fine for waking up `select`
</blockquote></details>

as far as I understand that part of code was removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by jellonek** [comment]
Almost perfect :)

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[docs/image-name-translation.md, line 8 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KuTS60GZnCa339tWMnx:-KuTS60GZnCa339tWMny:b7ly7a8) ([raw file](https://github.com/mirantis/virtlet/blob/53074cb7167fbf03683eaf9961f7d58b44d8dcbc/docs/image-name-translation.md#L8)):*
> ```Markdown
> * Colon cannot appear in the name. Thus the URL cannot include scheme part (`http://` or `https://`). As a consequence
>   it becomes impossible use images that have scheme that differs from configured default.
> * For the same reasons it is impossible to use URLs that include queries, authentication credentials, anchors or port number.
> ```

http protocol does not support anchors, it's part of html.

---

*[docs/image-name-translation.md, line 11 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KuTSOmG281Pv2UVMuSA:-KuTSOmHHB-XUWjHOsE9:b-244hsy) ([raw file](https://github.com/mirantis/virtlet/blob/53074cb7167fbf03683eaf9961f7d58b44d8dcbc/docs/image-name-translation.md#L11)):*
> ```Markdown
> * The URL must be all low-case which works well for the domain part, but may not be acceptable for the path part.
> 
> To overcome these limitations, virtlet provides a mechanism for image name translation.
> ```

Please use upper case for `Virtlet` name in whole file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409#-:-KuTT7aItzzdNs2W2oF8:bkgkgy7)*

**Comment by istalker2** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[docs/image-name-translation.md, line 8 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KuTS60GZnCa339tWMnx:-KuTW1gTla19zO0kcQBY:b-l828sz) ([raw file](https://github.com/mirantis/virtlet/blob/53074cb7167fbf03683eaf9961f7d58b44d8dcbc/docs/image-name-translation.md#L8)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

http protocol does not support anchors, it's part of html.
</blockquote></details>

anchor (#something) is a part of URL spec. HTML just using it. And HTTP doesn't care of any parts of URL after domain name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/image-name-translation.md, line 8 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/409#-KuTS60GZnCa339tWMnx:-KuTaxiGgO5-kRSfhG7F:b-btjhgb) ([raw file](https://github.com/mirantis/virtlet/blob/53074cb7167fbf03683eaf9961f7d58b44d8dcbc/docs/image-name-translation.md#L8)):*
<details><summary><i>Previously, istalker2 (Stan Lagun) wrote…</i></summary><blockquote>

anchor (#something) is a part of URL spec. HTML just using it. And HTTP doesn't care of any parts of URL after domain name
</blockquote></details>

Ok. See that it's removed after we agreed in chat.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409#-:-KuTcS1jb708IW4WkMAb:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/409#-:-KuTpR5N0-zzSkoAihir:bnfp4nl)*

**Pull request merged**
