### PR TITLE
check result of ContainerMetadata.Retrieve

### PR DESCRIPTION
**Pull request by yanxuean**
Signed-off-by: yanxuean <yan.xuean@zte.com.cn>

ref #621 

/cc @jellonek

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/626)

### CODE REVIEW

**Comment by yanxuean** [comment]
@jellonek   PTAL

**Comment by jellonek** [comment]
Small nits but rest is perfect.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/metadata/containers.go, line 188 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/626#-L7YklWvB76wy6LfUXYC:-L7YklWvB76wy6LfUXYD:b4fxzi5) ([raw file](https://github.com/mirantis/virtlet/blob/c9fbba968f971ec1cc0c74353a67fad1a18d46e3/pkg/metadata/containers.go#L188)):*
> ```Go
> 				}
> 				if ci == nil {
> 					return fmt.Errorf("containerInfo of container %s is not find in Virtlet metadata store", containerMeta.GetID())
> ```

Please change the message to "containerInfo for container %q not found in Virtlet metadata store".

---

*[pkg/metadata/containers_test.go, line 39 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/626#-L7YlJVlljp5Olxn1eB6:-L7YlJVlljp5Olxn1eB7:b4fxzi5) ([raw file](https://github.com/mirantis/virtlet/blob/c9fbba968f971ec1cc0c74353a67fad1a18d46e3/pkg/metadata/containers_test.go#L39)):*
> ```Go
> 		}
> 		if containerInfo == nil {
> 			t.Fatal(fmt.Errorf("containerInfo of container %s is not find in Virtlet metadata store", container.ContainerId))
> ```

Please change the message to "containerInfo for container %q not found in Virtlet metadata store".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/626#-:-L7YlLCVLhHIZcq6XL0c:b-epnnf2)*

**Comment by yanxuean** [comment]
done
@jellonek PTAL

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/626#-:-L7ZgBzuIq3n0oXczjVs:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/626#-:-L8-XQG9gHLoG7SqUNeB:bnfp4nl)*

**Pull request merged**
