### PR TITLE
Fix standard container labels

### LINKED ISSUE #295: Container name label not reported to Kubernetes
When user invokes `kubectl logs <container>`, Kubernetes searches for logs in file with the following name:
```go
func buildContainerLogsPath(containerName string, restartCount int) string {
	return fmt.Sprintf("%s_%d.log", containerName, restartCount)
}
```
where `containerName` is obtained like this:
```go
containerName := labels["io.kubernetes.container.name"]
```
What bothers me is that filename for Virtlet-powered "containers" appears to always be:
```
_0.log
```
meaning that Kubernetes is missing `io.kubernetes.container.name` label. For cirros example one would actually expect to see log file named as `cirros-vm_0.log`. Is there perhaps some step missing on Virtlet side during container creation that prevents Kubernetes from getting the container name?

Could it perhaps be that container name is intentionally suppressed to emphasize that Virtlet does not work with containers but with Pods only?

### Debugging
I've checked what labels are passed to [`CreateContainer`](https://github.com/Mirantis/virtlet/blob/master/pkg/libvirttools/virtualization.go#L302) function and container name appears to be there since value of `in.Config.Labels[types.KubernetesContainerNameLabel]` is:
```
[map[io.kubernetes.pod.name:cirros-vm io.kubernetes.pod.namespace:default io.kubernetes.pod.uid:22f85076-4216-11e7-b534-02420ac00002 io.kubernetes.container.name:cirros-vm]]
```

### PR DESCRIPTION
**Pull request by ivan4th**
This also fixes the naming of pod log files.
Fixes #295

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/313)

### CODE REVIEW

**Comment by miha-plesko** [comment]
*[pkg/libvirttools/virtualization.go, line 346 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/313#-Km5cgp3mrGxBuZrFa5n:-Km5cYNTQqaJ-3Tv3OAO:b-o2ikrv) ([raw file](https://github.com/mirantis/virtlet/blob/c402d924c3087e3ec2d0d06229cc10fb28d08a0d/pkg/libvirttools/virtualization.go#L346)):*
>  addSerialDevicesToDomain

Perhaps consider using constants from kubernetes package: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/types/labels.go#L19-L24. In case they update them as some point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/313)*

**Comment by jellonek** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/libvirttools/virtualization.go, line 346 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/313#-Km5cgp3mrGxBuZrFa5n:-Km5ogQPNNhALrC2I7gu:bb6mt9b) ([raw file](https://github.com/mirantis/virtlet/blob/c402d924c3087e3ec2d0d06229cc10fb28d08a0d/pkg/libvirttools/virtualization.go#L346)):*
<details><summary><i>Previously, miha-plesko (Miha Pleško) wrote…</i></summary><blockquote>

>  addSerialDevicesToDomain

Perhaps consider using constants from kubernetes package: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/types/labels.go#L19-L24. In case they update them as some point.

</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/313)*

**Comment by miha-plesko** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/virtlet/313#-Km5ryiKX23yv-dmv1jG:-Km5ryiLPY3iSeBgi7G0:byg4kh5) (no related file):*
I like your changes @ivan4th ! I've tested in my local environment and both the log name for cirros gets changed to `cirros-vm_0.log` and the `kubectl logs cirros-vm` works meaning that labels are accepted by kubernetes when container is created.

I'm fine if we merge this once you apply the comment below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/313)*

**Comment by ivan4th** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/virtualization.go, line 346 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/313#-Km5cgp3mrGxBuZrFa5n:-Kn2fofKpoLBbLLplMS5:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/c402d924c3087e3ec2d0d06229cc10fb28d08a0d/pkg/libvirttools/virtualization.go#L346)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/313)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/313#-:-Kn3oE-xkFSmK-ZzvOxa:bnfp4nl)*

**Comment by miha-plesko** [comment]
@ivan4th I think you need to adjust [e2e test](https://github.com/Mirantis/virtlet/blob/master/tests/e2e/e2e.sh#L125) before merging i.e. replace regex comparison with json comparison there. Other than that looks good to me as well.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/313#-:-Kn4IegJJyGQrhG5cuzV:b-j8b9y8)*

**Comment by ivan4th** [comment]
@miha-plesko it's already fixed there: https://github.com/Mirantis/virtlet/pull/311/files#diff-47f80368b6c6dddd7a87165379f5345aL123 (already merged)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/313#-:-Kn4_gUXoRfWgOLb8May:b-865pjj)*

**Comment by miha-plesko** [comment]
Somehow I think the Travis was red when I wrote you this an hour ago. I see it green now and yes, the regex should work so everything good. :lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/313#-:-Kn4eMKfEJulTj36lZaf:b-cg12f9)*

**Pull request merged**
