### PR TITLE
Fix CRI proxy verbosity

### PR DESCRIPTION
**Pull request by ivan4th**
The logs were eating all the disk space.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/325)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/README.md, line 82 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/325#-KmkomvBSPG8QSd0p5mq:-KmkomvBSPG8QSd0p5mr:b-jsmhmx) ([raw file](https://github.com/mirantis/virtlet/blob/f2ef83a8fffdba667404073d727295187df86228/deploy/README.md#L82)):*
> ```Markdown
> ```
> 
> `-v` option of `criproxy` controls the verbosity here (3 means dumping
> ```

So there should be also description what means 2nd level and why first level is skipped.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/325)*

**Comment by vefimova** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/325#-:-Kmkr6jKPbhgEbwOO9BZ:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/README.md, line 82 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/325#-KmkomvBSPG8QSd0p5mq:-Kmkv0z3I594IiEL7rhc:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f2ef83a8fffdba667404073d727295187df86228/deploy/README.md#L82)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

So there should be also description what means 2nd level and why first level is skipped.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/325)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/README.md, line 83 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/325#-KmkvXoGT_mBk6UzK4Uz:-KmkvXoGT_mBk6UzK4V-:b2l5jcv) ([raw file](https://github.com/mirantis/virtlet/blob/f28d6b09c8fc7fb30b729458b5a138c937fdbe1b/deploy/README.md#L83)):*
> ```Markdown
> 
> `-v` option of `criproxy` controls the verbosity here (0-1 means some
> very basic logging during startup and displaying serious errors, 2
> ```

"2 adds to them CRI request errors to be logged and 3 adds to previously noted messages dumps of actual ..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/325)*

**Comment by ivan4th** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/README.md, line 83 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/325#-KmkvXoGT_mBk6UzK4Uz:-KmkwoqaUdDpqL_rfVSe:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f28d6b09c8fc7fb30b729458b5a138c937fdbe1b/deploy/README.md#L83)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

"2 adds to them CRI request errors to be logged and 3 adds to previously noted messages dumps of actual ..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/325)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/325#-:-Kmkx0o5weXBUQWAnGlk:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/325#-:-KmkxXtXpPVpt2Rx9ZmY:bnfp4nl)*

**Pull request merged**
