### PR TITLE
Fixed Virlet crash during domains listing in case of external domain existence.

### LINKED ISSUE #280: Fix virtlet crashing on domains listing in case of defined domains existence not registered in bolt
Bug was caught due to overlay affect of subsequent running integration tests and not fully cleaned env after failing tests:

```
I0518 14:30:15.316399   14216 manager.go:375] ListContainers: (*runtime.ListContainersRequest)(0xc420074550)({
 Filter: (*runtime.ContainerFilter)(<nil>)
})
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5e9c56]

goroutine 37 [running]:
panic(0xa53b80, 0xc4200120c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/Mirantis/virtlet/pkg/libvirttools.(*VirtualizationTool).getContainer(0xc42015a8c0, 0xc420074568, 0x3, 0x4, 0x0)
        /go/src/github.com/Mirantis/virtlet/pkg/libvirttools/virtualization.go:603 +0xb6
github.com/Mirantis/virtlet/pkg/libvirttools.(*VirtualizationTool).ListContainers(0xc42015a8c0, 0x0, 0x12, 0xc42004b9c0, 0x1, 0x1, 0xc4201c0101)
        /go/src/github.com/Mirantis/virtlet/pkg/libvirttools/virtualization.go:698 +0x16c
github.com/Mirantis/virtlet/pkg/manager.(*VirtletManager).ListContainers(0xc42015a980, 0x7f8966676160, 0xc4200dbc20, 0xc420074550, 0x0, 0xc42003fac8, 0x553858)
        /go/src/github.com/Mirantis/virtlet/pkg/manager/manager.go:376 +0x2ab
github.com/Mirantis/virtlet/vendor/k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/runtime._RuntimeService_ListContainers_Handler(0xadf8a0, 0xc42015a980, 0x7f8966676160, 0xc4200dbc20, 0xc420085900, 0x0, 0x0, 0x0, 0x30, 0x0)
        /go/src/github.com/Mirantis/virtlet/vendor/k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2462 +0x27d
github.com/Mirantis/virtlet/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420186a00, 0x104c360, 0xc420016480, 0xc420127ef0, 0xc4201a3170, 0x103b790, 0xc4200dbbf0, 0x0, 0x0)
        /go/src/github.com/Mirantis/virtlet/vendor/google.golang.org/grpc/server.go:608 +0xc50
github.com/Mirantis/virtlet/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420186a00, 0x104c360, 0xc420016480, 0xc420127ef0, 0xc4200dbbf0)
        /go/src/github.com/Mirantis/virtlet/vendor/google.golang.org/grpc/server.go:766 +0x6b0
github.com/Mirantis/virtlet/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4201c2680, 0xc420186a00, 0x104c360, 0xc420016480, 0xc420127ef0)
        /go/src/github.com/Mirantis/virtlet/vendor/google.golang.org/grpc/server.go:419 +0xab
created by github.com/Mirantis/virtlet/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/Mirantis/virtlet/vendor/google.golang.org/grpc/server.go:420 +0xa3
2017/05/18 14:30:15 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2017/05/18 14:30:15 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /tmp/virtlet.sock: connect: connection refused"; Reconnecting to {"/tmp/virtlet.sock" <nil>}
--- FAIL: TestContainerStatuses (53.16s)
        container_test.go:114: Container created: "03ce3d01-dc9c-4e10-5afa-42e710ceccc9"
        container_test.go:132: Listing containers failure: rpc error: code = 13 desc = transport is closing
```

After failing volume test on ContainerCreate stage (https://travis-ci.org/Mirantis/virtlet/builds/233420469#L6529) defined domain remains in libvirt which causes virtlet crashing in subsequent test runs on list func with nil or only labels set filter each time (https://travis-ci.org/Mirantis/virtlet/builds/233420469#L8087)

ToDo:
- fix test cleanups
- fix virtlet listing func to just ignore and put warning log when it faces to "unknown" domains.

### PR DESCRIPTION
**Pull request by vefimova**
Fixes #280

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/302)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/bolttools/virtualization.go, line 178 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/302#-KlV9Vln_stiMAKWXupq:-KlV9Vln_stiMAKWXupr:b-gnhqxj) ([raw file](https://github.com/mirantis/virtlet/blob/ddd778271a309e63156362e0eb0d6f3703745337/pkg/bolttools/virtualization.go#L178)):*
> ```Go
> 			// 1. Container info removed, but sandbox still exists
> 			// 2. There's externally defined domain in libvirt daemon
> 			//    using `virsh`or libvirt api, not registered in bolt
> ```

Missing space after `virsh`.
Btw. this should be invalid situation - there should be no libvirt domains registered in virtlet container and in same time unknown to virtlet.
So I suggest there to at last send an info to logs that could be such unusual situation.

---

*[pkg/libvirttools/virtualization.go, line 679 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/302#-KlVA9q483H55XGb6p5V:-KlVA9q483H55XGb6p5W:b-w20b01) ([raw file](https://github.com/mirantis/virtlet/blob/ddd778271a309e63156362e0eb0d6f3703745337/pkg/libvirttools/virtualization.go#L679)):*
> ```Go
> 			if containerInfo == nil {
> 				// There's no such container - looks like it's already removed or has been defined externally, but still is mentioned in sandbox
> 				return nil, fmt.Errorf("Container metadata not found, but it's still mentioned in sandbox %s", filter.PodSandboxId)
> ```

Is this error message still correct?

---

*[tests/integration/utils.go, line 68 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/302#-KlVAK3T7eayguRt4K0k:-KlVAK3T7eayguRt4K0l:b-urycq7) ([raw file](https://github.com/mirantis/virtlet/blob/ddd778271a309e63156362e0eb0d6f3703745337/tests/integration/utils.go#L68)):*
> ```Go
> 	domainXML, err := domain.Marshal()
> 	if err != nil {
> 		log.Panicf("XML marashaling: %v", err)
> ```

Typo in `marashaling`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/302)*

**Comment by vefimova** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/bolttools/virtualization.go, line 178 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/302#-KlV9Vln_stiMAKWXupq:-KlVBM4G4C9b0-lI8D-f:byos51x) ([raw file](https://github.com/mirantis/virtlet/blob/ddd778271a309e63156362e0eb0d6f3703745337/pkg/bolttools/virtualization.go#L178)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Missing space after `virsh`.
Btw. this should be invalid situation - there should be no libvirt domains registered in virtlet container and in same time unknown to virtlet.
So I suggest there to at last send an info to logs that could be such unusual situation.
</blockquote></details>

well, yes and no, for example docker runtime can work with defined externally containers, it just ignores them. Also, I think, you would agree that at least virtlet must not crash in such situation. But yeah, let's add logging that virtlet found "unknown" domain.

---

*[pkg/libvirttools/virtualization.go, line 679 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/302#-KlVA9q483H55XGb6p5V:-KlVAvbT1z2bzIo9ytLf:b-fgd8uk) ([raw file](https://github.com/mirantis/virtlet/blob/ddd778271a309e63156362e0eb0d6f3703745337/pkg/libvirttools/virtualization.go#L679)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Is this error message still correct?
</blockquote></details>

oops, will remove changing of this comment, this can't happen, if domain has been defined externally.

---

*[tests/integration/utils.go, line 68 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/302#-KlVAK3T7eayguRt4K0k:-KlVBDZMlEPaJSXQEtWD:bldeoic) ([raw file](https://github.com/mirantis/virtlet/blob/ddd778271a309e63156362e0eb0d6f3703745337/tests/integration/utils.go#L68)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Typo in `marashaling`.
</blockquote></details>

thx, will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/302)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/bolttools/virtualization.go, line 178 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/302#-KlV9Vln_stiMAKWXupq:-KlVCYbaEOQFf1KiDckM:b-rodudp) ([raw file](https://github.com/mirantis/virtlet/blob/ddd778271a309e63156362e0eb0d6f3703745337/pkg/bolttools/virtualization.go#L178)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

well, yes and no, for example docker runtime can work with defined externally containers, it just ignores them. Also, I think, you would agree that at least virtlet must not crash in such situation. But yeah, let's add logging that virtlet found "unknown" domain.
</blockquote></details>

Yeah, without any doubt virtlet should not crash in such situation. I'm only saying that this should be logged as warning, probably even on V(0) level.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/302)*

**Comment by vefimova** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/bolttools/virtualization.go, line 178 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/302#-KlV9Vln_stiMAKWXupq:-KlVUYCK5_fCuFOb9nBB:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ddd778271a309e63156362e0eb0d6f3703745337/pkg/bolttools/virtualization.go#L178)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Yeah, without any doubt virtlet should not crash in such situation. I'm only saying that this should be logged as warning, probably even on V(0) level.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/302)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/302#-:-KlVd8OmNXiQIiWPPSAP:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/302#-:-KlVsQKXeTaUFtwgGTZ_:bnfp4nl)*

**Pull request merged**
