### PR TITLE
Proper tests (and fixes) for GC

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/388)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/libvirttools/gc_test.go, line 63 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVwxs3j7h9aFY5Rx2z:-KrVwxs411JM4PV8ReBy:b-j3j1uh) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L63)):*
> ```Go
> 
> 	// this should remove all domains (including other than virlet defined)
> 	// with exception of last listed in randomUUIDs slice
> ```

with an exception of the last one in randomUUIDs slice

---

*[pkg/libvirttools/gc_test.go, line 70 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVx7F3oAA85Z836PpD:-KrVx7F3oAA85Z836PpE:buy14qb) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L70)):*
> ```Go
> 
> 	if domains, _ := ct.domainConn.ListDomains(); len(domains) != 1 {
> 		t.Errorf("After calling removeOrphanDomains expected single remaining domain, ListDomains() returned %d of them", len(domains))
> ```

Expected a single domain to remain after removeOrphanDomains(), but ListDomains() returned %d domains

---

*[pkg/libvirttools/gc_test.go, line 105 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVxfaJ1_FiwAJBoMsw:-KrVxfaJ1_FiwAJBoMsx:b-5whcwd) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L105)):*
> ```Go
> 
> 	// this should remove only root volumes for two first elements of randomUUIDs slice
> 	// keeping intact other
> ```

this should remove only root volumes corresponding to the first two elements of randomUUIDs slice, keeping others

---

*[pkg/libvirttools/gc_test.go, line 147 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVy23reTyprBCEsdyf:-KrVy23reTyprBCEsdyg:bmtg166) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L147)):*
> ```Go
> 
> 	// this should remove only qcow2 volumes for two first elements of randomUUIDs slice
> 	// keeping intact other
> ```

this should remove only ephemeral (??? that's correct, right?) qcow2 volumes corresponding to the first two elements of randomUUIDs slice, keeping others

---

*[pkg/libvirttools/gc_test.go, line 154 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVzQ02tq0zA8eg31-Q:-KrVzQ02tq0zA8eg31-R:b4tobjg) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L154)):*
> ```Go
> 
> 	if volumes, _ := pool.ListAllVolumes(); len(volumes) != 2 {
> 		t.Errorf("Expected two remaining volumes, ListAllVolumes() returned %d of them", len(volumes))
> ```

Expected 2 volumes to remain, but ListAllVolumes() returned %d volumes

---

*[pkg/libvirttools/gc_test.go, line 173 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVzJbX_ehLrMDdzNOb:-KrVzJbX_ehLrMDdzNOc:bihkac2) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L173)):*
> ```Go
> 		fname := filepath.Join(directory, "nocloud-"+uuid+".iso")
> 		if file, err := os.Create(fname); err != nil {
> 			t.Fatalf("Cannot create fake iso with name '%s': %v", fname, err)
> ```

'%s' -> %q

---

*[pkg/libvirttools/gc_test.go, line 180 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVzM680J2oobfbw7vQ:-KrVzM6955vexiDSioC7:bihkac2) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L180)):*
> ```Go
> 	fname := filepath.Join(directory, "some other.iso")
> 	if file, err := os.Create(fname); err != nil {
> 		t.Fatalf("Cannot create fake iso with name '%s': %v", fname, err)
> ```

'%s' -> %q

---

*[pkg/libvirttools/gc_test.go, line 194 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVyMLyAnBX_sgNMDqa:-KrVyMLyAnBX_sgNMDqb:b5nn8ks) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L194)):*
> ```Go
> 
> 	// this should remove olny nocloud iso file for first element of randomUUIDs slice
> 	// keeping intact rest of files
> ```

this should remove only nocloud iso file corresponding to the first element of randomUUIDs slice, keeping other files

---

*[pkg/libvirttools/gc_test.go, line 202 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVzDBjZz5CdfuTiVUR:-KrVzDBjZz5CdfuTiVUS:b-c8odtz) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L202)):*
> ```Go
> 	postCallFileNames, err := filepath.Glob(filepath.Join(directory, "*"))
> 	if err != nil {
> 		t.Fatalf("Error globbing names in temporary directory: %v", err)
> ```

in the temporary directory

---

*[pkg/libvirttools/gc_test.go, line 207 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVyhvb9wS9j6qm8gBN:-KrVyhvb9wS9j6qm8gBO:bpunjgd) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L207)):*
> ```Go
> 	diff := difference(preCallFileNames, postCallFileNames)
> 	if len(diff) != 1 {
> 		t.Fatalf("Expected that removeOrphanNoCloudImages will remove single file, but it removed: %d", len(diff))
> ```

Expected removeOrphanNoCloudImages to remove a single file, but it removed %d files

---

*[pkg/libvirttools/gc_test.go, line 212 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVz32lol67Sz-5L3QA:-KrVz32lol67Sz-5L3QB:b-et0v3r) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L212)):*
> ```Go
> 	expectedPath := filepath.Join(directory, "nocloud-"+randomUUIDs[0]+".iso")
> 	if diff[0] != expectedPath {
> 		t.Fatalf("Expected that removeOrphanNoCloudImages will remove only '%s' file, but there is missing: %q", expectedPath, diff[0])
> ```

Expected removeOrphanNoCloudImages to remove only %q, but it also removed %q

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/388)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/libvirttools/gc_test.go, line 63 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVwxs3j7h9aFY5Rx2z:-KrW6svMdxUoiNQ4bryb:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L63)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

with an exception of the last one in randomUUIDs slice
</blockquote></details>

Done.

---

*[pkg/libvirttools/gc_test.go, line 70 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVx7F3oAA85Z836PpD:-KrW6wW6ocr_w8cZNjHf:b-if5jyl) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L70)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Expected a single domain to remain after removeOrphanDomains(), but ListDomains() returned %d domains
</blockquote></details>

Used other wording, closer to rest of similar messages.

---

*[pkg/libvirttools/gc_test.go, line 105 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVxfaJ1_FiwAJBoMsw:-KrW718_72CnQPhzQuOv:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L105)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

this should remove only root volumes corresponding to the first two elements of randomUUIDs slice, keeping others
</blockquote></details>

Done.

---

*[pkg/libvirttools/gc_test.go, line 147 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVy23reTyprBCEsdyf:-KrW71Zw1qiHlljbna9y:b-lkd50o) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L147)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

this should remove only ephemeral (??? that's correct, right?) qcow2 volumes corresponding to the first two elements of randomUUIDs slice, keeping others
</blockquote></details>

That's correct. Done.

---

*[pkg/libvirttools/gc_test.go, line 154 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVzQ02tq0zA8eg31-Q:-KrW7LxZI0rJTyKQLJtq:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L154)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Expected 2 volumes to remain, but ListAllVolumes() returned %d volumes
</blockquote></details>

Done.

---

*[pkg/libvirttools/gc_test.go, line 173 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVzJbX_ehLrMDdzNOb:-KrW7MYQ_L_TLDR5yG0H:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L173)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

'%s' -> %q
</blockquote></details>

Done.

---

*[pkg/libvirttools/gc_test.go, line 180 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVzM680J2oobfbw7vQ:-KrW7MwBfYj1eDBmS2gG:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L180)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

'%s' -> %q
</blockquote></details>

Done.

---

*[pkg/libvirttools/gc_test.go, line 194 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVyMLyAnBX_sgNMDqa:-KrW7O4YzpzdWmx2k5IQ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L194)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

this should remove only nocloud iso file corresponding to the first element of randomUUIDs slice, keeping other files
</blockquote></details>

Done.

---

*[pkg/libvirttools/gc_test.go, line 202 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVzDBjZz5CdfuTiVUR:-KrW7p_hpjUdXPDurEJs:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L202)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

in the temporary directory
</blockquote></details>

Done.

---

*[pkg/libvirttools/gc_test.go, line 207 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVyhvb9wS9j6qm8gBN:-KrW7sP3sPPKLozCuTfy:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L207)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Expected removeOrphanNoCloudImages to remove a single file, but it removed %d files
</blockquote></details>

Done.

---

*[pkg/libvirttools/gc_test.go, line 212 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/388#-KrVz32lol67Sz-5L3QA:-KrW7w_RHvo7xmtDVvdq:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/82f7e1d72bae78d1f7178fc8977fab35673ff5db/pkg/libvirttools/gc_test.go#L212)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Expected removeOrphanNoCloudImages to remove only %q, but it also removed %q
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/388)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/388#-:-KrWZjyeap_d8pqh4LBO:bnfp4nl)*

**Comment by istalker2** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/388#-:-KrYD6TIkU9-UBYdJjEh:bnfp4nl)*

**Pull request merged**
