### PR TITLE
Add support for kubectl port-forward

### PR DESCRIPTION
**Pull request by lukaszo**
---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/472)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[.circleci/config.yml, line 165 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/472#-KwfmGFDyAVRosDpcPMm:-KwfmGFDyAVRosDpcPMn:b45h7df) ([raw file](https://github.com/mirantis/virtlet/blob/f5c68b38ea0ebf176d2a726bb0a996ea8202c569/.circleci/config.yml#L165)):*
> ```YAML
>       name: install kubectl
>       command: |
>         curl -L https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o /bin/kubectl
> ```

shouldn't we pin to the same version as in glide? Right now we're fetching 1.8 right?

---

*[images/Dockerfile.build-base, line 55 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/472#-KwfmRNxzZIPKnTVvdg4:-KwfmRNxzZIPKnTVvdg5:bmsmkvo) ([raw file](https://github.com/mirantis/virtlet/blob/f5c68b38ea0ebf176d2a726bb0a996ea8202c569/images/Dockerfile.build-base#L55)):*
> ```
> 
> # Install kubectl
> RUN curl -L https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o /bin/kubectl
> ```

same question as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/472)*

**Comment by lukaszo** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[.circleci/config.yml, line 165 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/472#-KwfmGFDyAVRosDpcPMm:-KwfpAX5QcgxuAoZ2IR7:b-y0gtu5) ([raw file](https://github.com/mirantis/virtlet/blob/f5c68b38ea0ebf176d2a726bb0a996ea8202c569/.circleci/config.yml#L165)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

shouldn't we pin to the same version as in glide? Right now we're fetching 1.8 right?
</blockquote></details>

I'm assuming that the newest kubectl should be working with older clusters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/472)*

**Comment by ivan4th** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[.circleci/config.yml, line 165 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/472#-KwfmGFDyAVRosDpcPMm:-KwiVFqHAzTrF9U0Gsip:bqrqsiu) ([raw file](https://github.com/mirantis/virtlet/blob/f5c68b38ea0ebf176d2a726bb0a996ea8202c569/.circleci/config.yml#L165)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

I'm assuming that the newest kubectl should be working with older clusters.
</blockquote></details>

IMO it would be better to 1) use specific version of kubectl 2) add sha1sum check like this: `echo "XXXXXXXXXXXXXXX... /usr/local/bin/kubectl" | sha1sum -c`

---

*[images/Dockerfile.build-base, line 55 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/472#-KwfmRNxzZIPKnTVvdg4:-KwiVWT0Y4_SOlD69U1R:by3cgnq) ([raw file](https://github.com/mirantis/virtlet/blob/f5c68b38ea0ebf176d2a726bb0a996ea8202c569/images/Dockerfile.build-base#L55)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

same question as above
</blockquote></details>

same as above, IMO need fixed version + kubectl sha1sum check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/472)*

**Comment by lukaszo** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[.circleci/config.yml, line 165 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/472#-KwfmGFDyAVRosDpcPMm:-Kwj6LpdC_QLOYY3XD8R:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f5c68b38ea0ebf176d2a726bb0a996ea8202c569/.circleci/config.yml#L165)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

IMO it would be better to 1) use specific version of kubectl 2) add sha1sum check like this: `echo "XXXXXXXXXXXXXXX... /usr/local/bin/kubectl" | sha1sum -c`
</blockquote></details>

Done.

---

*[images/Dockerfile.build-base, line 55 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/472#-KwfmRNxzZIPKnTVvdg4:-Kwj6N-nFI5UkULm-its:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f5c68b38ea0ebf176d2a726bb0a996ea8202c569/images/Dockerfile.build-base#L55)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

same as above, IMO need fixed version + kubectl sha1sum check
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/472)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 10 of 13 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/472#-:-Kwj6zcszw7rvbwTKocZ:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 10 of 13 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/472#-:-Kwj9GRGFs14JDZrctXx:bnfp4nl)*

**Pull request merged**
