### PR TITLE
VNC subcommand in virtletctl

### PR DESCRIPTION
**Pull request by jellonek**
This command needs to be rebased on top of master after merging #598 on which it depends.

Todo:
 - [x] docs,
 - [x] test output of command and created port forwarding.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/613)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/tools/vnc.go, line 40 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z3k3IPZzD5OWtJPYY:-L7Z3k3IPZzD5OWtJPYZ:bs05upx) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L40)):*
> ```Go
> )
> 
> // vncCommand gives an access to VNC console of VM pod.
> ```

// vncCommand provides access to the VNC console of a VM pod

---

*[pkg/tools/vnc.go, line 47 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z3vEe7FmiaLR1uIb1:-L7Z3vEe7FmiaLR1uIb2:b-lj83em) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L47)):*
> ```Go
> }
> 
> // NewVNCCmd returns a cobra.Command that gives an access to VNC console of VM pod.
> ```

... that provides access to the VNC console of a VM pod

---

*[pkg/tools/vnc.go, line 52 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z45JVFJZS7cd91Zt9:-L7Z45JWgPwFEVb3EH4Z:b4zw7oq) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L52)):*
> ```Go
> 	cmd := &cobra.Command{
> 		Use:   "vnc pod [port]",
> 		Short: "Provide an access to a VM pod VNC console",
> ```

Provide access to the VNC console of a VM pod

---

*[pkg/tools/vnc.go, line 57 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z499aZDQXL-SjPD-l:-L7Z499aZDQXL-SjPD-m:b-khjv4s) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L57)):*
> ```Go
> 			provided port forwarding for VNC will try to use that one.
> 			Otherwise the kernel will chose a random one which will
> 			be displayed as a part of command output.
> ```

I'd put it this way:

This command forwards a local port to the VNC port used by the specified VM pod. If no local port number is provided, a random available port is picked instead. The port number is displayed after the forwarding is set up, after which the commands enters an endless loop until it's interrupted with Ctrl-C.

---

*[pkg/tools/vnc.go, line 107 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z603fqrV4IiajjmWh:-L7Z603fqrV4IiajjmWi:bozbn3h) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L107)):*
> ```Go
> 	switch {
> 	case len(parts) != 3:
> 		return fmt.Errorf("virsh returned %q, while expected to return something like %q", buffer.String(), "vnc://127.0.0.1:0")
> ```

while expected to return a value of a form ...

---

*[pkg/tools/vnc.go, line 109 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5xhe58IcVv9FSLW_:-L7Z5xhe58IcVv9FSLWa:b-uzwjq4) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L109)):*
> ```Go
> 		return fmt.Errorf("virsh returned %q, while expected to return something like %q", buffer.String(), "vnc://127.0.0.1:0")
> 	case parts[0] != vncProtocolName:
> 		return fmt.Errorf("virsh returned %q as a display protocol while expected one was %q", parts[0], vncProtocolName)
> ```

instea of expected %q

---

*[pkg/tools/vnc.go, line 111 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5vqaga34Vj6LnOh0:-L7Z5vqaga34Vj6LnOh1:b6ygkmm) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L111)):*
> ```Go
> 		return fmt.Errorf("virsh returned %q as a display protocol while expected one was %q", parts[0], vncProtocolName)
> 	case parts[1][:2] != "//":
> 		return fmt.Errorf("virsh returned %q after first ':' while expected was %q", parts[1][:2], "//")
> ```

instead of expected %q

---

*[pkg/tools/vnc.go, line 113 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5sye0uG5Ihgczzte:-L7Z5sye0uG5Ihgczztf:b6ygkmm) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L113)):*
> ```Go
> 		return fmt.Errorf("virsh returned %q after first ':' while expected was %q", parts[1][:2], "//")
> 	case parts[1][2:] != expectedHost:
> 		return fmt.Errorf("virsh returned %q as a display host while expected one was %q", parts[1], expectedHost)
> ```

instead of expected %q

---

*[pkg/tools/vnc.go, line 116 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5A8XQaFkoaIMRxYP:-L7Z5A8XQaFkoaIMRxYQ:bg88p4u) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L116)):*
> ```Go
> 	}
> 
> 	displayPortOffset, err := strconv.Atoi(parts[2])
> ```

I think it's called "display number" not "display port offset" in VNC.

---

*[pkg/tools/vnc.go, line 117 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5F1GDJ0lzyi9ukJm:-L7Z5F1GDJ0lzyi9ukJn:b-v4d4jc) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L117)):*
> ```Go
> 
> 	displayPortOffset, err := strconv.Atoi(parts[2])
> 	if err != nil || displayPortOffset < 0 || displayPortOffset > maximalDisplayPortOffset {
> ```

besides "display port offset" -> "display number" remark above, s/maximal/max/

---

*[pkg/tools/vnc.go, line 118 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z4yRnmpkLW8bDJaeG:-L7Z4yRnmpkLW8bDJaeH:basxuc5) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L118)):*
> ```Go
> 	displayPortOffset, err := strconv.Atoi(parts[2])
> 	if err != nil || displayPortOffset < 0 || displayPortOffset > maximalDisplayPortOffset {
> 		return fmt.Errorf("virsh returned %q as a display port offset while expected one was a non negative integer less than %d", parts[2], maximalDisplayPortOffset)
> ```

virsh returned %a a a display number which is expected to be in range 0 .. %d

---

*[pkg/tools/vnc.go, line 132 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5fNNVAHkoyklLboc:-L7Z5fNOgpwK3sgfilXX:b-v8mn1z) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L132)):*
> ```Go
> 
> 	fmt.Printf("VNC console for pod %q is available on local port %d\n", v.podName, pf.LocalPort)
> 	fmt.Printf("Press ctrl-c (or send a terminate singal) to finish that.\n")
> ```

Press Ctrl-C or kill the process to stop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/613)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/tools/vnc.go, line 40 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z3k3IPZzD5OWtJPYY:-L7ZCpNXJ4T4gpPTbUzJ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L40)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

// vncCommand provides access to the VNC console of a VM pod
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 47 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z3vEe7FmiaLR1uIb1:-L7ZChE9Lj_1Dwi5z01Z:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L47)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

... that provides access to the VNC console of a VM pod
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 52 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z45JVFJZS7cd91Zt9:-L7ZCosXzGuIaYKBQxiI:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L52)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Provide access to the VNC console of a VM pod
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 57 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z499aZDQXL-SjPD-l:-L7ZCq0l20oBNbYvzUrp:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L57)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'd put it this way:

This command forwards a local port to the VNC port used by the specified VM pod. If no local port number is provided, a random available port is picked instead. The port number is displayed after the forwarding is set up, after which the commands enters an endless loop until it's interrupted with Ctrl-C.
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 107 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z603fqrV4IiajjmWh:-L7ZCrG0WN9ZS_vI1gNK:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L107)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

while expected to return a value of a form ...
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 109 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5xhe58IcVv9FSLW_:-L7ZCrqIkGtqsT928bvs:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L109)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

instea of expected %q
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 111 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5vqaga34Vj6LnOh0:-L7ZCzdTVU08ju5FgjWM:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L111)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

instead of expected %q
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 113 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5sye0uG5Ihgczzte:-L7ZD-1zEatkOp10P1z8:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L113)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

instead of expected %q
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 116 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5A8XQaFkoaIMRxYP:-L7ZD13mQ-LyaRR5pJ2U:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L116)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I think it's called "display number" not "display port offset" in VNC.
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 117 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5F1GDJ0lzyi9ukJm:-L7ZD1hCPD7ldODXo9cX:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L117)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

besides "display port offset" -> "display number" remark above, s/maximal/max/
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 118 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z4yRnmpkLW8bDJaeG:-L7ZD2kVJlq_TN_0_DpW:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L118)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

virsh returned %a a a display number which is expected to be in range 0 .. %d
</blockquote></details>

Done.

---

*[pkg/tools/vnc.go, line 132 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7Z5fNNVAHkoyklLboc:-L7ZD4l-C-9qayg9BcAr:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/eb9518bbc954e8e95c65af674754e86fecbd7547/pkg/tools/vnc.go#L132)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Press Ctrl-C or kill the process to stop.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/613)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/613#-:-L7ZEGc16isVoxqnj9si:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/tools/vnc_test.go, line 72 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7ZGbA5Jd4EnyNBdw9D:-L7ZGbA5Jd4EnyNBdw9E:b-9mxnwv) ([raw file](https://github.com/mirantis/virtlet/blob/33aa3fe637c640e4a51028b3fb183ae42fe33dbd/pkg/tools/vnc_test.go#L72)):*
> ```Go
> 			switch err := cmd.Execute(); {
> 			case err != nil && tc.errSubstring == "":
> 				t.Errorf("virsh command returned an unexpected error: %v", err)
> ```

vnc command

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/613)*

**Comment by jellonek** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/tools/vnc_test.go, line 72 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/613#-L7ZGbA5Jd4EnyNBdw9D:-L7ZHf565tkILff6XCQ-:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/33aa3fe637c640e4a51028b3fb183ae42fe33dbd/pkg/tools/vnc_test.go#L72)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

vnc command
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/613)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/613#-:-L7ZHnVNaCbxUKRsXoW5:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/613#-:-L7kwU5EzVMLl5wHgYut:bnfp4nl)*

**Pull request merged**
