### PR TITLE
Improve logging and streamer docs

### PR DESCRIPTION
**Pull request by lukaszo**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/449)

### CODE REVIEW

**Comment by miha-plesko** [comment]
Hi @lukaszo, I hope you don't mind me quickly looking at this PR. We've noticed only now that you're changing the logging mechanism and got curious. I really like the unix socket approach that you've taken (and is mostly merged already anyway), because there is really no need for "raw files" to ever exist.

I have some minor comments on this PR, please take a look. Most notably, I'd appreciate an updated architecture image  for users to understand architecture better. Also, I'd split this PR into two parts: one part would be "Use ConfigMap to configure virtlet logging" and the other part would be "Document Stream listener", but that's just my opinion.

Looking forward to be testing when the new logging mechanism is delievered!

---

Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/devel/vm-logging.md, line 16 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kvf9DE-Ah1TPx5M1Bhz:-Kvf9DE00NonV6GwriSR:b-iykw7b) ([raw file](https://github.com/mirantis/virtlet/blob/a98f2967b13008be2f3fda3dde84c99bf647c202/docs/devel/vm-logging.md#L16)):*
> ```Markdown
> 
> ### Architecture
> Following image illustrates how logging is handled. There is one directory on host needed:
> ```

Please remove the sentence that's mentioning the "following image" since there is no image anymore. Alternatively, you could provide the updated image where you show how libvirt stdout is redirected to unix and how we're then consuming this stream.

---

*[docs/devel/vm-logging.md, line 26 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/449#-KvfACK9X36uX3qoz8No:-KvfACK9X36uX3qoz8Np:b-ewdf7p) ([raw file](https://github.com/mirantis/virtlet/blob/a98f2967b13008be2f3fda3dde84c99bf647c202/docs/devel/vm-logging.md#L26)):*
> ```Markdown
> by Kubernetes.
> 
> Provided that redirecting `stdout` and `stderr` to unix socket is turned on(DEFAULT)
> ```

The space is missing in front of "(DEFAULT)"

---

*[pkg/libvirttools/virtualization.go, line 283 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/449#-KvfAxt-lU6JTho04FC4:-KvfAxt-lU6JTho04FC5:b-xiifk9) ([raw file](https://github.com/mirantis/virtlet/blob/a98f2967b13008be2f3fda3dde84c99bf647c202/pkg/libvirttools/virtualization.go#L283)):*
> ```Go
> func loggingDisabled() bool {
> 	disabled := os.Getenv("VIRTLET_DISABLE_LOGGING")
> 	if disabled != "" {
> ```

I'd go with

```go
if disabled != "" && disabled != "false" {
```

to protect user from pulling her hair when she decides to set VIRTLET_DISABLE_LOGGING to `false` for some reason. That being said, it would be even better to provide generic auxilary function like `func getBoolFromEnv(name string) bool` where you handle persing the env properly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-KvfGewVFuPWhbBjn5nb:bjfzjoy)*

**Comment by lukaszo** [comment]
Hi @miha-plesko, thank you for your comments. I will split the PR into two commits. I will also try to draw something I hope it will be readable :)

---

Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/devel/vm-logging.md, line 16 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kvf9DE-Ah1TPx5M1Bhz:-KvgndYowMMLC6JRkKdh:bexfakh) ([raw file](https://github.com/mirantis/virtlet/blob/a98f2967b13008be2f3fda3dde84c99bf647c202/docs/devel/vm-logging.md#L16)):*
<details><summary><i>Previously, miha-plesko (Miha Pleško) wrote…</i></summary><blockquote>

Please remove the sentence that's mentioning the "following image" since there is no image anymore. Alternatively, you could provide the updated image where you show how libvirt stdout is redirected to unix and how we're then consuming this stream.
</blockquote></details>

I will add it in the next PR

---

*[docs/devel/vm-logging.md, line 26 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/449#-KvfACK9X36uX3qoz8No:-KvgnpBVnKoIFDC8weLa:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a98f2967b13008be2f3fda3dde84c99bf647c202/docs/devel/vm-logging.md#L26)):*
<details><summary><i>Previously, miha-plesko (Miha Pleško) wrote…</i></summary><blockquote>

The space is missing in front of "(DEFAULT)"
</blockquote></details>

Done.

---

*[pkg/libvirttools/virtualization.go, line 283 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/449#-KvfAxt-lU6JTho04FC4:-Kvgnr8Y1x5NDxY629ej:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a98f2967b13008be2f3fda3dde84c99bf647c202/pkg/libvirttools/virtualization.go#L283)):*
<details><summary><i>Previously, miha-plesko (Miha Pleško) wrote…</i></summary><blockquote>

I'd go with

```go
if disabled != "" && disabled != "false" {
```

to protect user from pulling her hair when she decides to set VIRTLET_DISABLE_LOGGING to `false` for some reason. That being said, it would be even better to provide generic auxilary function like `func getBoolFromEnv(name string) bool` where you handle persing the env properly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-KvfiwpGRFMqrAgEYvPY:b4hyp3b)*

**Comment by pigmej** [comment]
:lgtm: 

---

Reviewed 7 of 9 files at r1, 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-Kw0J7PZvlhzHoxLFBd2:bg7igkv)*

**Comment by ivan4th** [comment]
Reviewed 7 of 9 files at r1, 14 of 15 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/devel/vm-logging.md, line 54 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw5igULv1uzaonb315O:-Kw5hvDqwv8-KM_YsUe1:b-ig6sgd) ([raw file](https://github.com/mirantis/virtlet/blob/4e73f1ef6be7f79429bac60b9522d5c038746f89/docs/devel/vm-logging.md#L54)):*
> ```Markdown
> There is one limitation when redirecting logs to unix socket is enabled:
> 
> - Command `virsh console <vm>` no longer works since libvirt serial port type is 'unix' and not 'pty'.
> ```

Doesn't disabling the logging reenable the console?

---

*[pkg/stream/server.go, line 81 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw5iTOaAqwnuok3Dgvj:-Kw5iTOaAqwnuok3Dgvk:bhe47a4) ([raw file](https://github.com/mirantis/virtlet/blob/4e73f1ef6be7f79429bac60b9522d5c038746f89/pkg/stream/server.go#L81)):*
> ```Go
> }
> 
> // Stop stops all gorutines
> ```

goroutines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449)*

**Comment by lukaszo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/devel/vm-logging.md, line 54 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw5igULv1uzaonb315O:-Kw7RqzNxB9gLICWzVYv:brkpe45) ([raw file](https://github.com/mirantis/virtlet/blob/4e73f1ef6be7f79429bac60b9522d5c038746f89/docs/devel/vm-logging.md#L54)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Doesn't disabling the logging reenable the console?
</blockquote></details>

Yes, this is a limitation when logging is enabled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449)*

**Comment by lukaszo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/stream/server.go, line 81 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw5iTOaAqwnuok3Dgvj:-Kw7S-4GlNcdHnlW-99O:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4e73f1ef6be7f79429bac60b9522d5c038746f89/pkg/stream/server.go#L81)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

goroutines
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449)*

**Comment by ivan4th** [comment]
Review status: 21 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/devel/vm-logging.md, line 54 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw5igULv1uzaonb315O:-Kw9SSLyr9l6HkpszNnn:b-or1guj) ([raw file](https://github.com/mirantis/virtlet/blob/4e73f1ef6be7f79429bac60b9522d5c038746f89/docs/devel/vm-logging.md#L54)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

Yes, this is a limitation when logging is enabled
</blockquote></details>

Can we mention it here? In case someone needs to disable logging and still wants to see the console.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449)*

**Comment by jellonek** [comment]
This PR removes from docs info about logs location (`/var/log/vms/<sandboxId>/_<retry>.log`) replacing it with info about about streamer socket, without mention how it's used by streamer. 

---

Reviewed 6 of 9 files at r1, 15 of 15 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/devel/vm-logging.md, line 62 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw9TRzQPtzx_0nHnmaL:-Kw9TRzQPtzx_0nHnmaM:bd0w2m5) ([raw file](https://github.com/mirantis/virtlet/blob/de4d028da604a7a10717499bf07d88cd2b503d24/docs/devel/vm-logging.md#L62)):*
> ```Markdown
> 
> ### Limitations
> There are some limitations when redirecting logs into files is disabled:
> ```

... into unix socket?

---

*[docs/devel/vm-logging.md, line 65 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw9TalJovZcC8YnL6OW:-Kw9TalJovZcC8YnL6OX:bv2o9oo) ([raw file](https://github.com/mirantis/virtlet/blob/de4d028da604a7a10717499bf07d88cd2b503d24/docs/devel/vm-logging.md#L65)):*
> ```Markdown
> 
> - command `kubectl logs <MY-POD>` will not work
> - command `kubectl attach <MY-POD>` will not work as it uses the same unix socket connection
> ```

I don't quite understand that. Multiple parallel calls of this command will not work? It uses the same unix socket as what?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-Kw9RLVrppS7UxVS1dn9:b-rdp6m6)*

**Comment by lukaszo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/devel/vm-logging.md, line 65 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw9TalJovZcC8YnL6OW:-Kw9Vr8jzyYT71f1dpHs:b-jzr4v8) ([raw file](https://github.com/mirantis/virtlet/blob/de4d028da604a7a10717499bf07d88cd2b503d24/docs/devel/vm-logging.md#L65)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

I don't quite understand that. Multiple parallel calls of this command will not work? It uses the same unix socket as what?
</blockquote></details>

See the paragraph title: "Redirecting stdout and stderr into pty" This commands will not work when stdout is  redirected to pty

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/devel/vm-logging.md, line 65 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw9TalJovZcC8YnL6OW:-Kw9XSBoourD4Vrxfqcn:b-jfvfeh) ([raw file](https://github.com/mirantis/virtlet/blob/de4d028da604a7a10717499bf07d88cd2b503d24/docs/devel/vm-logging.md#L65)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

See the paragraph title: "Redirecting stdout and stderr into pty" This commands will not work when stdout is  redirected to pty
</blockquote></details>

Ok. So please change ```unix socket connection``` to ```mechanism as used with `kubectl logs` ``` or do not inform why (as in line above).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449)*

**Comment by miha-plesko** [comment]
Just an idea in my head, not sure if it's doable: when we were redirecting all the logs into the file, it was obvious that `virsh console` can no longer work, since it would need to communicate with VM thru that file, which is impossible. But having unix sockets implemented I'm wondering if it's perhaps possible to have both - the logging and the `virsh console`? I mean, sockets are bidirectional, aren't they? Theoretically, they could be sending input to the VM, aren't they?

As I said, this is just an idea, feel free to laugh :smile: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-Kw9_Mmz1h1gKms0SEOc:b-bktan1)*

**Comment by jellonek** [comment]
Lukasz already answered that (in response to Ivan's comment) - when console has other type than `pty` `virsh console` will not work (limitation on libvirt side). Just keep in mind that connection over unix socket only sends text data, but does not support sending pty control data (like terminal size change and so on). That would require an additional protocol (e.g. telnet) on top of this connection, instead of only sending plain data, but this requirement would  then stay on qemu/libvirt level also.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-Kw9axlQn_VEdX85xEUo:b-yloyt3)*

**Comment by ivan4th** [comment]
@miha-plesko actually there's not much use in `virsh console` now that there's `kubectl attach`. Or am I missing something?

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-Kw9cFASXSW-bc1BP4kn:b9pxz0g)*

**Comment by jellonek** [comment]
Btw. `virsh console` is our only internal/devel hack which will be inaccessible on "real deployment" by users, because it requires access to virtlet pod internals. The right way (and it's why Lukasz added that) is to use `kubectl attach`, which streaming server enables ;)

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-Kw9cjM1vDkzvCTry90v:b2tcr8w)*

**Comment by miha-plesko** [comment]
Ah, awesome - I didn't realize that there is `kubectl attach` available WHEN redirect to socket is turned on (RTFM :smile: ). That is, naturally, much better than `virsh console`. Thanks for the explanation.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-Kw9cf7Wg3Ha8L27tWF0:bqjsa4p)*

**Comment by miha-plesko** [comment]
@lukaszo I've added one more minor comment, but generally this PR looks great to me :lgtm: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/stream/server.go, line 29 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw9flPzN-xlcjQdGjPW:-Kw9flPzN-xlcjQdGjPX:b-yslg60) ([raw file](https://github.com/mirantis/virtlet/blob/de4d028da604a7a10717499bf07d88cd2b503d24/pkg/stream/server.go#L29)):*
> ```Go
> )
> 
> // Server implements streaming.Runtime
> ```

You could add following line just below Server struct to actually assert that it really does implement the interface:

```go
var _ streaming.Runtime= (*Server)(nil)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-Kw9gxPpL2z2HRhQufaF:b509ous)*

**Comment by lukaszo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/devel/vm-logging.md, line 54 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw5igULv1uzaonb315O:-KwCADPG_h3zOBOz9TEv:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4e73f1ef6be7f79429bac60b9522d5c038746f89/docs/devel/vm-logging.md#L54)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Can we mention it here? In case someone needs to disable logging and still wants to see the console.
</blockquote></details>

Done.

---

*[docs/devel/vm-logging.md, line 65 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw9TalJovZcC8YnL6OW:-KwCAP_7v6UJxoFzp6pE:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/de4d028da604a7a10717499bf07d88cd2b503d24/docs/devel/vm-logging.md#L65)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Ok. So please change ```unix socket connection``` to ```mechanism as used with `kubectl logs` ``` or do not inform why (as in line above).
</blockquote></details>

Done.

---

*[pkg/stream/server.go, line 29 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/449#-Kw9flPzN-xlcjQdGjPW:-KwCC9cJQE0SF6o4Ig90:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/de4d028da604a7a10717499bf07d88cd2b503d24/pkg/stream/server.go#L29)):*
<details><summary><i>Previously, miha-plesko (Miha Pleško) wrote…</i></summary><blockquote>

You could add following line just below Server struct to actually assert that it really does implement the interface:

```go
var _ streaming.Runtime= (*Server)(nil)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-KwChD0tFGJ-wSLmKyoD:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/449#-:-KwJe2T_SwAi-wt5Bm9v:bnfp4nl)*

**Pull request merged**
