### PR TITLE
Add e2e tests for virtletctl

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/636)

### CODE REVIEW

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/e2e/framework/localcmd_interface.go, line 36 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8-Lx7--dJVh3li9Idv:-L8-Lx70lKOXFubO8i2Y:b-30rs0p) ([raw file](https://github.com/mirantis/virtlet/blob/2cecd8f3c7b0795ab6127e3bb0ed216d01b88be7/tests/e2e/framework/localcmd_interface.go#L36)):*
> ```Go
> 			}
> 		}
> 		return 0, err
> ```

Ok. That change is quite silly. If it has to match the `Executor` interface in same way as in `docker_interface.go` or `ssh_interface.go` it should wait for cmd result, so it could simply call `cmd.Run` instead of `cmd.Start/cmd.Wait`.

Still changing this interface means breaking some tests (for sure port forwarding) which depends on not waiting for cmd finish.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/636)*

**Comment by ivan4th** [comment]
Review status: 0 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[tests/e2e/virtletctl_test.go, line 34 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CKIrkTNhh21cO7jXY:-L8CKIrkTNhh21cO7jXZ:bq0pweo) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L34)):*
> ```Go
> )
> 
> var _ = Describe("virtletctl tests", func() {
> ```

"virtletctl"

---

*[tests/e2e/virtletctl_test.go, line 35 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CKL38R9hAJjl7CPBI:-L8CKL38R9hAJjl7CPBJ:b-xq67fw) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L35)):*
> ```Go
> 
> var _ = Describe("virtletctl tests", func() {
> 	It("Should how usage", func(done Done) {
> ```

"Should display usage info on help subcommand"

---

*[tests/e2e/virtletctl_test.go, line 47 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CKReICiHwBemMeQxZ:-L8CKReICiHwBemMeQx_:b-4hl311) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L47)):*
> ```Go
> 	})
> 
> 	It("Should not fail during dump-metadata", func(done Done) {
> ```

Perhaps this test should check for some simple strings in metadata dump output? Maybe after starting a pod? "Should dump Virtlet metadata on dump-metadata subcommand"

---

*[tests/e2e/virtletctl_test.go, line 59 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CKgm364fMTAwewese:-L8CKgm4zBdEb1uqeYaW:b-brwj04) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L59)):*
> ```Go
> 	})
> 
> 	It("Should not fail during gendoc", func(done Done) {
> ```

perhaps this test should check for a substring in the generated files and should be named "Should generate documentation on gendoc subcommand"

---

*[tests/e2e/virtletctl_test.go, line 72 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CLFOqsH2R0gs4NfxO:-L8CLFOqsH2R0gs4NfxP:b3q5v47) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L72)):*
> ```Go
> 
> 	Context("Install subcommand", func() {
> 		It("Should not fail during install", func(done Done) {
> ```

"Should install itself as a kubectl plugin on install subcommand" This test is too disruptive, as in, it can damage user's environment if e2e runner is invoked directly. Probably we should mark it as such and take some measures so this test is only executed inside build container or if explicitly asked for? For example, it should maybe skip itself upon some env var like `VIRTLET_UNSAFE_E2E` (set it in `docker run` for the build container in `build/cmd.sh`)

---

*[tests/e2e/virtletctl_test.go, line 123 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CLvYplIIkv6OOnVYF:-L8CLvYplIIkv6OOnVYG:b-78lk7v) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L123)):*
> ```Go
> 			Expect(err).NotTo(HaveOccurred())
> 			Expect(os.Chmod(tempfileName, 0600)).NotTo(HaveOccurred())
> 		})
> ```

I guess several commands like `vnc`, `ssh` and `dump-metadata` can be grouped under one `Describe("pod commands", ...` with this BeforeAll/AfterAll and make use of this pod setup for their testing.

---

*[tests/e2e/virtletctl_test.go, line 131 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CMEuYsho0OMmrB7vv:-L8CMEuYsho0OMmrB7vw:b-nad7up) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L131)):*
> ```Go
> 		})
> 
> 		It("Should can call remote command with virtletctl ssh", func(done Done) {
> ```

"Should be able to access the pod via ssh using ssh subcommand"

---

*[tests/e2e/virtletctl_test.go, line 145 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CMYa7-BkpkAhbo-7B:-L8CMYa7-BkpkAhbo-7C:b-pzwm6j) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L145)):*
> ```Go
> 	})
> 
> 	It("Should not fail during virsh list", func(done Done) {
> ```

Again "Should list libvirt domains on list subcommand" and check for the presence of the pod in the list (there's some code to get domain id from pod name/id in `tests/e2e`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/636)*

**Comment by jellonek** [comment]
Review status: 0 of 17 files reviewed at latest revision, 8 unresolved discussions.

---

*[tests/e2e/virtletctl_test.go, line 47 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CKReICiHwBemMeQxZ:-L8X-TfM04U1DdtsQIyR:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L47)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

The one thing is to ensure that there was not error during whole procedure (copying file content from container, using it as boltdb, unmarshalling the data), and another would be validation of generated output. Perhaps this later could be added as conformance test?
</blockquote></details>

Done.

---

*[tests/e2e/virtletctl_test.go, line 59 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CKgm364fMTAwewese:-L8X1ZWxWrAyaGpdRXYQ:bks9cs3) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L59)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Same as above, that would require to add there a logic aware about which commands should have docs and maybe verification of generated doc format. Good candidate for conformance test.
</blockquote></details>

Added tests for substrings in main `virtletctl.md` file.

---

*[tests/e2e/virtletctl_test.go, line 72 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CLFOqsH2R0gs4NfxO:-L8X1O0RmRZ-W6Ap9g4T:bd68i4) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L72)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Does anybody run our e2e against  user's environment? That would leave tons of unfinished pods hidden in per run created namespaces (i was in this situation, that's why i wanted to have vm pods created in default namespace, to have them better noticeable).

Anyway - good idea with this possibility to skip, added that in the way as cloud init tests are skipped.
</blockquote></details>

Added in a way how cloud init tests are handled.

---

*[tests/e2e/virtletctl_test.go, line 145 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8CMYa7-BkpkAhbo-7B:-L8X3Ay3TFsaNSmBVdd7:b-jqr1nc) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L145)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Message updated. That part - Done.

As commented above - IMO validation of virsh command output for some added for this test pod is out of scope there and would only increase unnecessarily the test by 20-30sec.
It only verifies if virsh can be accessed and do anything on libvirt. If it could not do that - it would fail, what should be caught by this test. Maybe instead of calling virsh list i should use there virsh help for this purpose, maybe this purpose would be more clear?

But... As commented above - if single pod would be precreated for this test during BeforeSuite - overall cost of such validation would be minimal and so such conformance test could be also added.
Can do that, but hopefully in a followup.
</blockquote></details>

Instead of relying on `virsh list` I changed verification of `virsh` command to use `version` subcommand and it's expected substrings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/636)*

**Comment by ivan4th** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[.circleci/config.yml, line 182 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8Xey8H7LuFzha8mtWQ:-L8Xey8I5xViMka3Ozk7:b-dfjalr) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/.circleci/config.yml#L182)):*
> ```YAML
>         build/portforward.sh 8080&
>         mkdir -p ~/junit
>         _output/virtlet-e2e-tests -test.v -ginkgo.skip="\[Heavy\]" -junitOutput ~/junit/junit.xml -include-non-safe-tests=true
> ```

Please also add this option in `build/cmd.sh`, `build/cmd.sh` uses the build container so it's safe to run these tests there.

---

*[tests/e2e/common.go, line 37 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8Xe8CH3PH81BHu4Xlh:-L8Xe8CH3PH81BHu4Xli:b-vc6hij) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/common.go#L37)):*
> ```Go
> 	sshUser               = flag.String("sshuser", defaultSSHUser, "default SSH user for VMs")
> 	includeCloudInitTests = flag.Bool("include-cloud-init-tests", false, "include Cloud-Init tests")
> 	includeNonSafeTests   = flag.Bool("include-non-safe-tests", false, "include tests which can modify environment")
> ```

includeUnsafeTests
include-unsafe-tests
include tests that can be unsafe if they're run outside the build container

---

*[tests/e2e/common.go, line 151 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8XfXNM1mXD80ObRXii:-L8XfXNM1mXD80ObRXij:b-wo7mn3) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/common.go#L151)):*
> ```Go
> }
> 
> func includeNonSafe() {
> ```

includeUnsafe

---

*[tests/e2e/common.go, line 153 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8Xejfb8HEtFVuj3vcl:-L8Xejfb8HEtFVuj3vcm:b1v2zx8) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/common.go#L153)):*
> ```Go
> func includeNonSafe() {
> 	if !*includeNonSafeTests {
> 		Skip("Tests modifying cluster environment are not enabled")
> ```

Tests that are unsafe outside the build container are disabled

---

*[tests/e2e/virtletctl_test.go, line 47 at r2](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8CKReICiHwBemMeQxZ:-L8E1kNlC1LB2VnzkHbJ:bow46wr) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L47)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

The one thing is to ensure that there was not error during whole procedure (copying file content from container, using it as boltdb, unmarshalling the data), and another would be validation of generated output. Perhaps this later could be added as conformance test?
</blockquote></details>

well, I was speaking not about validation, but rather about at least some identifying strings present in the output, so as to make sure it doesn't just produce an empty file and does gather some info about pods.

---

*[tests/e2e/virtletctl_test.go, line 59 at r2](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8CKgm364fMTAwewese:-L8E1yrtLVa7FcMdJ9NO:b-atrf0e) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L59)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Same as above, that would require to add there a logic aware about which commands should have docs and maybe verification of generated doc format. Good candidate for conformance test.
</blockquote></details>

Well, just the same as above, I meant a simple func to check for e.g. just one word in the output, not any serious correctness checks.

---

*[tests/e2e/virtletctl_test.go, line 72 at r2](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8CLFOqsH2R0gs4NfxO:-L8E2DVPFMOz-GTAb7b2:b-u5kx4j) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L72)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Does anybody run our e2e against  user's environment? That would leave tons of unfinished pods hidden in per run created namespaces (i was in this situation, that's why i wanted to have vm pods created in default namespace, to have them better noticeable).

Anyway - good idea with this possibility to skip, added that in the way as cloud init tests are skipped.
</blockquote></details>

I sometimes build & execute e2e runner on MAC. This test being skipped by default would be highly welcome ...

---

*[tests/e2e/virtletctl_test.go, line 123 at r2](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8CLvYplIIkv6OOnVYF:-L8XbnGMCIfbxkiNX6VL:b-9rr4nq) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L123)):*
> Clearly vnc and ssh need them and could be grouped as you proposed, and even could reuse the same vm pod (so that could use BeforeSuite/AfterSuite instead of BeforeAll/AfterAll which are simply adding multiple BeforeEach afair). So when i'll be adding vnc test - will add this Describe.

Well my idea was using the same pod for all the checks incl. virsh / dump-metadata so you could look for pod-specific substrings in the output, but ok, let's keep it this way for now.

---

*[tests/e2e/virtletctl_test.go, line 117 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8XbDeS6pT17jN15nVf:-L8XbDeS6pT17jN15nVg:bkis7wl) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/virtletctl_test.go#L117)):*
> ```Go
> 			_, err = tempfile.Write([]byte(strippedKey))
> 			Expect(err).NotTo(HaveOccurred())
> 			Expect(os.Chmod(tempfileName, 0600)).NotTo(HaveOccurred())
> ```

Expect(os.Chmod(tempfileName, 0600)).To(Succeed())

---

*[tests/e2e/virtletctl_test.go, line 154 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8XfGnnDMLJ_OQnd4xW:-L8XfGnnDMLJ_OQnd4xX:b-jd7yez) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/virtletctl_test.go#L154)):*
> ```Go
> 	}, 60)
> })
> ```

Pls use `Context("[unsafe]", ...)` inside `Describe("virtletctl", ...)`.  Or just do the check inside `It(...)`

---

*[tests/e2e/virtletctl_test.go, line 160 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8Xfl1F58LNNJaY2iO5:-L8Xfl1F58LNNJaY2iO6:bqrvmvm) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/virtletctl_test.go#L160)):*
> ```Go
> 	})
> 
> 	Context("Should install itself as a kubectl plugin on install subcommand", func() {
> ```

Perhaps just `It("Should install itself as a kubectl plugin on install subcommand", ...)` You may then also check plugin yaml for a substring and make sure `_output/virtletctl` is copied to the proper location.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/636)*

**Comment by jellonek** [comment]
Review status: 0 of 19 files reviewed at latest revision, 8 unresolved discussions.

---

*[.circleci/config.yml, line 182 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8Xey8H7LuFzha8mtWQ:-L8XkNXE9YEQfMtOxvqp:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/.circleci/config.yml#L182)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Please also add this option in `build/cmd.sh`, `build/cmd.sh` uses the build container so it's safe to run these tests there.
</blockquote></details>

Done.

---

*[tests/e2e/common.go, line 37 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8Xe8CH3PH81BHu4Xlh:-L8Xl-dG6VkLAaNF_UyY:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/common.go#L37)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

includeUnsafeTests
include-unsafe-tests
include tests that can be unsafe if they're run outside the build container
</blockquote></details>

Done.

---

*[tests/e2e/common.go, line 151 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8XfXNM1mXD80ObRXii:-L8XlTHb2P9c3QxxjLj1:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/common.go#L151)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

includeUnsafe
</blockquote></details>

Done.

---

*[tests/e2e/common.go, line 153 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8Xejfb8HEtFVuj3vcl:-L8XlSpOASyJTSMLz4vl:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/common.go#L153)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Tests that are unsafe outside the build container are disabled
</blockquote></details>

Done.

---

*[tests/e2e/virtletctl_test.go, line 47 at r2](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8CKReICiHwBemMeQxZ:-L8Y1Zt25Oiuy2X7e4j5:b-hcin7i) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L47)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

well, I was speaking not about validation, but rather about at least some identifying strings present in the output, so as to make sure it doesn't just produce an empty file and does gather some info about pods.
</blockquote></details>

Added that.

---

*[tests/e2e/virtletctl_test.go, line 72 at r2](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8CLFOqsH2R0gs4NfxO:-L8Xlt-Q7I4yoaooxpWx:b-emnevj) ([raw file](https://github.com/mirantis/virtlet/blob/5fc3d26ba59b1c0a465290b6747645a1af8dd3d0/tests/e2e/virtletctl_test.go#L72)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I sometimes build & execute e2e runner on MAC. This test being skipped by default would be highly welcome ...
</blockquote></details>

Ok. Removed this test and we can rethink how to do it properly in a followup.

---

*[tests/e2e/virtletctl_test.go, line 117 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8XbDeS6pT17jN15nVf:-L8XmZP470eaVLrYu3LW:bctjna4) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/virtletctl_test.go#L117)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Expect(os.Chmod(tempfileName, 0600)).To(Succeed())
</blockquote></details>

Good catch. Found also other place where this will improve readability.

---

*[tests/e2e/virtletctl_test.go, line 154 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8XfGnnDMLJ_OQnd4xW:-L8XpvBiDLa64vi-X5Yc:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/virtletctl_test.go#L154)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Pls use `Context("[unsafe]", ...)` inside `Describe("virtletctl", ...)`.  Or just do the check inside `It(...)`
</blockquote></details>

Done.

---

*[tests/e2e/virtletctl_test.go, line 160 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8Xfl1F58LNNJaY2iO5:-L8XpvsT9UeqH2ZUoXgU:b-atfpcx) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/virtletctl_test.go#L160)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Perhaps just `It("Should install itself as a kubectl plugin on install subcommand", ...)` You may then also check plugin yaml for a substring and make sure `_output/virtletctl` is copied to the proper location.
</blockquote></details>

I see no point in validation of yaml content while kubectl will do that in the end of test. Similar with binary - if there would be copied any garbage - command `kubectl plugin virt help` will end with failure.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/636)*

**Comment by ivan4th** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/e2e/virtletctl_test.go, line 160 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/636#-L8Xfl1F58LNNJaY2iO5:-L8Y3LNWGE8MKYSi9kjg:b-8ua1sj) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/virtletctl_test.go#L160)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

I see no point in validation of yaml content while kubectl will do that in the end of test. Similar with binary - if there would be copied any garbage - command `kubectl plugin virt help` will end with failure.
</blockquote></details>

ok, didn't notice it was running the plugin. then it's ok. sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/636)*

**Comment by jellonek** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/e2e/virtletctl_test.go, line 154 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8XfGnnDMLJ_OQnd4xW:-L8Y623N-ijZaHeKWni0:b-r1me1p) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/virtletctl_test.go#L154)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done. This time in requested way :)

---

*[tests/e2e/virtletctl_test.go, line 160 at r3](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-L8Xfl1F58LNNJaY2iO5:-L8Y6-Q--VfD4uN3Ghci:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f675013639f895490225e3880125d5cf740ff046/tests/e2e/virtletctl_test.go#L160)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

ok, didn't notice it was running the plugin. then it's ok. sorry.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/636)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 14 of 17 files at r2, 4 of 5 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/636#-:-L8Y6SfS8We-C45nLyAE:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/636#-:-L8YlTyqwvIHtJqEqWMT:bnfp4nl)*

**Pull request merged**
