### PR TITLE
Use kubeadm-dind-cluster for e2e tests

### PR DESCRIPTION
**Pull request by ivan4th**
As a bonus, add VM network checking to the updated `expect` script.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/225)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[deploy/demo.sh, line 51 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/225#-KfwXNL2nKQ9pJDvwRXQ:-KfwXNL3bo86AFQDav5F:b-ivb1q4) ([raw file](https://github.com/mirantis/virtlet/blob/72eb10b99cd836167dfe07c439cba6a9a006450e/deploy/demo.sh#L51)):*
> ```Shell
> function demo::start-dind-cluster {
>   demo::step "Will now clear any kubeadm-dind-cluster data on the current Docker"
>   echo "VM console will be attached after Virtlet setup is complete, press Ctrl-] to detach." >&2
> ```

This message seems to be incorrect for non interactive test.

---

*[tests/e2e/e2e.sh, line 21 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/225#-KfwY-BXaNsHhIasdiHE:-KfwY-BXaNsHhIasdiHF:b-74t9nl) ([raw file](https://github.com/mirantis/virtlet/blob/72eb10b99cd836167dfe07c439cba6a9a006450e/tests/e2e/e2e.sh#L21)):*
> ```Shell
> set -o errtrace
> 
> if [ $(uname) = Darwin ]; then
> ```

Hmmm... Is there a possibility that this would work on OS X?
I know that libvirt can be installed on mac (e.x. using brew), but will it work with kubeadm-dind-cluster?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/225)*

**Comment by ivan4th** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/demo.sh, line 51 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/225#-KfwXNL2nKQ9pJDvwRXQ:-KfwrGo9FuT8Ck-yVVnr:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/72eb10b99cd836167dfe07c439cba6a9a006450e/deploy/demo.sh#L51)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This message seems to be incorrect for non interactive test.
</blockquote></details>

Done.

---

*[tests/e2e/e2e.sh, line 21 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/225#-KfwY-BXaNsHhIasdiHE:-KfwrHovqpT9ob9A-3zr:b5txsj) ([raw file](https://github.com/mirantis/virtlet/blob/72eb10b99cd836167dfe07c439cba6a9a006450e/tests/e2e/e2e.sh#L21)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... Is there a possibility that this would work on OS X?
I know that libvirt can be installed on mac (e.x. using brew), but will it work with kubeadm-dind-cluster?
</blockquote></details>

This scripts runs without problems on Mac. libvirt works inside docker (either inside Mac Docker's VM or on a remote docker engine) `virsh.sh` invokes virsh inside virtlet container.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/225)*

**Comment by jellonek** [comment]
:lgtm: but tests failed.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/225#-:-KfwzwVSTBKBcC_gHcuS:b-yqaan0)*

**Comment by pigmej** [comment]
@jellonek I restarted it because the error is bit strange `2017-03-23 20:31:04.901+0000: 33: error : virQEMUCapsParseHelpStr:1419 : internal error: QEMU / QMP failed: Could not access KVM kernel module: No such file or directory`

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/225#-:-Kfx2UM50KIHWJvcxvAP:b-qs3042)*

**Comment by jellonek** [comment]
So it's not strange because tests on travis require VIRTLET_DISABLE_KVM which was in dockercompose there https://github.com/Mirantis/virtlet/pull/225/files#diff-ab085fe24e590ec1acbd9b89bdf5522aL9 
So it should be added to travis variables and then passed to e2e script and so on.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/225#-:-Kfx2zLHPq7NhH3EoKpU:bn10rci)*

**Comment by ivan4th** [comment]
@pigmej @jellonek I don't quite understand why QEMU complains about KVM here. Actually in this case VIRTLET_DISABLE_KVM is passed, it's currently hardcoded in Virtlet DaemonSet definition https://github.com/Mirantis/virtlet/blob/76e4a04bd3e6bd78378f831ae4c50bb82d3c2aad/deploy/virtlet-ds.yaml#L121 Basically replacing it with optional autodetect is what #223 is about. Concerning the actual reason for the test failure, if you see libvirt log at the end, this usually means that 'make test' stage failed, and you need to scroll up a bit to see what test caused the failure. The failed build appears to be cleared after restart so I can no longer see the log, but usually it's flaky CRI proxy race test - made in issue for it https://github.com/Mirantis/virtlet/issues/226 (there's a link to a sample failure log there, too) I'll try to see whether it's possible to fix it really quickly or we can disable the test on Travis for the time being.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/225#-:-KfxAl7bcP4mO-AWLvdF:b-2w6wjt)*

**Comment by pigmej** [comment]
It's green now.... 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/225#-:-KfxPx7-J-cnPfAJSZkT:b7x29nv)*

**Pull request merged**
