### PR TITLE
Virtlet streamer

### PR DESCRIPTION
**Pull request by lukaszo**
Configure qemu to connect console to virtlet using unix sockets. Virtlet
will use stdout to save pod logs so `kubectl log <pod>` will work.

Use kubelete streaming server so `kubectl attach <pod>` will work.

This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/427)

### CODE REVIEW

**Comment by ivan4th** [comment]
Reviewed 1 of 41 files at r1.
Review status: 1 of 41 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/stream/utils_test.go, line 56 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/427#-KvYnDDMPVPN5wcJlSps:-KvYnDDMPVPN5wcJlSpt:bib81ix) ([raw file](https://github.com/mirantis/virtlet/blob/0d39af440d648ee8e467d8f5f31f7c7ed08cddb9/pkg/stream/utils_test.go#L56)):*
> ```Go
> }
> 
> func TestGerProcessEnvironment(t *testing.T) {
> ```

typo: TestGetProcessEnvironment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/427)*

**Comment by ivan4th** [comment]
Review status: 1 of 41 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/stream/streamer.go, line 73 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/427#-KvYp3E7BpjWxTOKYvXO:-KvYp3E7BpjWxTOKYvXP:b-4z30ga) ([raw file](https://github.com/mirantis/virtlet/blob/5e33e63f4573d17f318157d2703d795bd8fe7877/pkg/stream/streamer.go#L73)):*
> ```Go
> 	}()
> 
> 	err := (error)(nil)
> ```

maybe `var err error` is a bit simpler?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/427)*

**Comment by lukaszo** [comment]
Review status: 1 of 41 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/stream/streamer.go, line 73 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/427#-KvYp3E7BpjWxTOKYvXO:-KvYuZT9uvfn5OXQqt8z:bdrc7ue) ([raw file](https://github.com/mirantis/virtlet/blob/5e33e63f4573d17f318157d2703d795bd8fe7877/pkg/stream/streamer.go#L73)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe `var err error` is a bit simpler?
</blockquote></details>

heh, a bit :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/427)*

**Comment by lukaszo** [comment]
Review status: 1 of 41 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/stream/utils_test.go, line 56 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/427#-KvYnDDMPVPN5wcJlSps:-KvYw8y9PmckUrrVwSLv:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/0d39af440d648ee8e467d8f5f31f7c7ed08cddb9/pkg/stream/utils_test.go#L56)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

typo: TestGetProcessEnvironment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/427)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 34 of 41 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/427#-:-KvZ0E-v9G51GYQzwgOq:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 35 of 41 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/427#-:-KvaxRrgDVslX2KiMvON:bnfp4nl)*

**Pull request merged**
