### PR TITLE
libvirttools: Distinguish libvirt errors from the internal ones

### LINKED ISSUE #101: Metadata for images shredded on image redownload request
When we are starting vm from image which is not in store, we are downloading it, storing in bolt it's metadata then we are starting vm, but if for some reason this vm will not start, kubelet will resend request to start container and then we can notice that there is also request for redownload for image (maybe something is broken with ImagesList) which ends with shredding of information about image file location in bolt. This ends with broken domain xml for vm with empty value for image file path.

### PR DESCRIPTION
**Pull request by nhlfr**
Fixes #101

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/107)

### CODE REVIEW

**Comment by jellonek** [comment]
LGTM

**Comment by jellonek** [comment]
Little questions - rest seems to be quite good.

---

Reviewed 12 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/image.h, line 25 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/107#-KW7tJ-UMuBT9kioOq8G:-KW7tJ-UMuBT9kioOq8H:b-lf2gk7) ([raw file](https://github.com/mirantis/virtlet/blob/ac49a547810a4de157cacc3c64533f9c47d6139e/pkg/libvirttools/image.h#L25)):*
> ```objc
> 
> enum virtletImageErr {
> 	VIRTLET_IMAGE_OK = 0,
> ```

Is there any reason why we have 0 marked in each file under separate `VIRTLET_..._OK` alias name? You are not using these enums at return types, just simple ints.

---

*[pkg/libvirttools/image.h, line 27 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/107#-KW7ttVaJGHMkpNTGXBI:-KW7ttVaJGHMkpNTGXBJ:b-dw27vk) ([raw file](https://github.com/mirantis/virtlet/blob/ac49a547810a4de157cacc3c64533f9c47d6139e/pkg/libvirttools/image.h#L27)):*
> ```objc
> 	VIRTLET_IMAGE_OK = 0,
> 
> 	VIRTLET_IMAGE_ERR_SEND_STREAM = VIRTLET_IMAGE_ERR_BASE + 1,
> ```

Why you are starting from `..._BASE + 1` instead of simple `..._BASE`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/107#-:-KW7uRm6jS-2OXmQIL0h:b-9f51o9)*

**Comment by nhlfr** [comment]
Review status: 7 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/image.h, line 25 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/107#-KW7tJ-UMuBT9kioOq8G:-KW8LCia0KF6ZHz6qlFx:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ac49a547810a4de157cacc3c64533f9c47d6139e/pkg/libvirttools/image.h#L25)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary>
> Is there any reason why we have 0 marked in each file under separate `VIRTLET_..._OK` alias name? You are not using these enums at return types, just simple ints.
</details>
Done.

---

*[pkg/libvirttools/image.h, line 27 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/107#-KW7ttVaJGHMkpNTGXBI:-KW8LD6A7NneOUz6BvbV:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/ac49a547810a4de157cacc3c64533f9c47d6139e/pkg/libvirttools/image.h#L27)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary>
> Why you are starting from `..._BASE + 1` instead of simple `..._BASE`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/107)*

**Comment by jellonek** [comment]
:lgtm_strong: 

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/107#-:-KWCLiIrGDSal4SQZ9-5:b-uwkowd)*

**Comment by ivan4th** [comment]
Closing in favor of rebased copy (#119) - let's do CI checks

**Pull request closed without merging**
