### PR TITLE
Add Calico TapFDSource test cases

### PR DESCRIPTION
**Pull request by ivan4th**
A test case for just Calico and another one for Calico + 2nd CNI.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/576)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/network/fake_cni_test.go, line 268 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/576#-L5oFKm3xriN6_kML6AC:-L5oFKm3xriN6_kML6AD:bwyxy7d) ([raw file](https://github.com/mirantis/virtlet/blob/7d5df069ae5dd29b530fe66472d60e49962d4445/tests/network/fake_cni_test.go#L268)):*
> ```Go
> 		// if err := cni.DestroyNetNS(c.DummyPodId); err != nil {
> 		// 	log.Panicf("Error destroying dummy pod network ns: %v", err)
> 		// }
> ```

Commented code left in commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/576)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/576#-:-L5oUFbHBkI9Y94RQNBM:bnfp4nl)*

**Comment by jellonek** [comment]
still :lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/576#-:-L5sdyKWcTXUDbIa2mri:b-5fsfav)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/576#-:-L5sfOJ-m1puUFwfv_6m:bnfp4nl)*

**Pull request merged**
