### PR TITLE
Xml refactoring

### LINKED ISSUE #132: XML handling
We should stop rely on plain string templates for domain XML generation. Instead we should fill initial values in structs, operate on them and only once at the end generate from this XML, cutting down need to parse it at first.

So this is placeholder issue for future refactor.

### PR DESCRIPTION
**Pull request by vefimova**
- [x] moved to libvirt-go-xml package usage and get rid of internally defined domain structures
- [x] fixed bugs found in generated domain's xml definition during testing and added ability to specify cmdline env vars. Currently done by applying patch, it will be removed later after changes will be merged to upstream repo.
- [x] get rid of raw strings usage during forming domain's definition

Fixes #132 

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/279)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLmvRBS8xr9CiWkmSN:-KkLmvRBS8xr9CiWkmSO:b906rgn) (no related file):*
BTW when dealing with XML "dom" (DOM) means "Document Object Model" which may be a bit confusing. Maybe `domain` is better?

---

*[pkg/libvirttools/virtualization.go, line 90 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLmGwE2_oe6JBXFM3A:-KkLmGwE2_oe6JBXFM3B:b-5rwncl) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L90)):*
> ```Go
> }
> 
> func getDomain() *libvirtxml.Domain {
> ```

What's the reason for separating this func from `createDomain()`?

---

*[pkg/libvirttools/virtualization.go, line 109 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLm2WlJJUjVmRlA9MY:-KkLm2WlJJUjVmRlA9MZ:bbe07ws) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L109)):*
> ```Go
> 	dom.OnPoweroff = "destroy"
> 	dom.OnReboot = "restart"
> 	dom.OnCrash = "restart"
> ```

maybe including all of this inside `dom.Devices = &libvirtxml.DomainDeviceList{ ... }` would look a bit cleaner?

---

*[pkg/libvirttools/virtualization.go, line 145 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLmOTl2EHwwMZgaIqw:-KkLmOTl2EHwwMZgaIqx:b-cfp8c) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L145)):*
> ```Go
> 	cniConfigEscaped := buf.String()
> 
> 	dom.CMDLine = &libvirtxml.DomainCMDLine{Envs: []libvirtxml.QemuEnv{
> ```

`Envs:` would look better on the next line

---

*[pkg/libvirttools/virtualization.go, line 262 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLmc5S97Lgtu82y0Fi:-KkLmc5S97Lgtu82y0Fj:buhu80c) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L262)):*
> ```Go
> 		return "", err
> 	}
> 	domXML := strings.Replace(string(outArr[:]), "\"", "'", -1)
> ```

Why we need this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/279)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLmvRBS8xr9CiWkmSN:-KkLt6Qf0553JPihiqbF:b5nsl1c) (no related file):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

BTW when dealing with XML "dom" (DOM) means "Document Object Model" which may be a bit confusing. Maybe `domain` is better?
</blockquote></details>

:+1: for changing "dom" to "domain" in all places.

---

*[pkg/libvirttools/virtualization.go, line 109 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLm2WlJJUjVmRlA9MY:-KkLpyo44dM61ci-kswQ:b-6p1utb) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L109)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe including all of this inside `dom.Devices = &libvirtxml.DomainDeviceList{ ... }` would look a bit cleaner?
</blockquote></details>

Look's like all values can be set as:
```
domain = libvirtxml.Domain{
    Devices = libvirtxml.DomainDeviceList{
        ...
    },
    OS = ...,
    OnPoweroff = ...,
    ...
}```
```


---

*[pkg/libvirttools/virtualization.go, line 332 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLqq7SGmTlXmNL72eE:-KkLqq7SGmTlXmNL72eF:b-dhdput) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L332)):*
> ```Go
> 	domSettings.cniConfig = cniConfig
> 	domSettings.domainUUID, err = utils.NewUuid()
> 	if err != nil {
> ```

This whole block can be replaced with:
```
uuid, err := utils.NewUUid()
if err != nil {
    return "", err
}
settings := VirtletDomainSettings{
    netNSPath: netNSPath,
    cniConfig: cniConfig,
    domainUUID: uuid,
}```
If you don't want to have uuid variable accessible in rest of func, you can join first two lines, and set `settings` in else block, but this would require declaration of `var settings VirtletDomainSettings` which i tried to omit.
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/279)*

**Comment by vefimova** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLmvRBS8xr9CiWkmSN:-KkNFimEvwtD8BLPeo0o:b-ywciuz) (no related file):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

:+1: for changing "dom" to "domain" in all places.
</blockquote></details>

Fixed comments

---

*[pkg/libvirttools/virtualization.go, line 90 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLmGwE2_oe6JBXFM3A:-KkN676hU8OtksTRCdPS:bss4a2b) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L90)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

What's the reason for separating this func from `createDomain()`?
</blockquote></details>

Removed.

---

*[pkg/libvirttools/virtualization.go, line 109 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLm2WlJJUjVmRlA9MY:-KkN6HGCsbTwmlT43nW6:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L109)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Look's like all values can be set as:
```
domain = libvirtxml.Domain{
    Devices = libvirtxml.DomainDeviceList{
        ...
    },
    OS = ...,
    OnPoweroff = ...,
    ...
}```
</blockquote></details>

Done.

---

*[pkg/libvirttools/virtualization.go, line 145 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLmOTl2EHwwMZgaIqw:-KkNF_i7c0nLu013UgE5:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L145)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`Envs:` would look better on the next line
</blockquote></details>

Done.

---

*[pkg/libvirttools/virtualization.go, line 262 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLmc5S97Lgtu82y0Fi:-KkNFb2cUHDJo0EEStn1:ba3dfob) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L262)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Why we need this?
</blockquote></details>

Removed

---

*[pkg/libvirttools/virtualization.go, line 332 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/279#-KkLqq7SGmTlXmNL72eE:-KkNFYUH856ez2hFVHu1:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/258d21885e0ad36368f6bd1de5f298f9991f9163/pkg/libvirttools/virtualization.go#L332)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This whole block can be replaced with:
```
uuid, err := utils.NewUUid()
if err != nil {
    return "", err
}
settings := VirtletDomainSettings{
    netNSPath: netNSPath,
    cniConfig: cniConfig,
    domainUUID: uuid,
}```
If you don't want to have uuid variable accessible in rest of func, you can join first two lines, and set `settings` in else block, but this would require declaration of `var settings VirtletDomainSettings` which i tried to omit.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/279)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/279#-:-KkNUssKqNXfrkpDMGXH:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/279#-:-KkR9TtCt_ZVMxEgSFTR:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/279#-:-KkVSGjOzWQ3iP4A-YDt:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/279#-:-KkVjOWvXQm1vCi0pqBo:bnfp4nl)*

**Pull request merged**
