### PR TITLE
Add Verifier interface to tests/gm

### PR DESCRIPTION
**Pull request by ivan4th**
Make it possible to customize Golden Master comparison and data generation. The tests now support not just JSON-based output comparison but also text and YAML-based output comparison, too.

This is a spinoff from #598 to make it smaller. The idea is to use Golden Master to verify plugin.yaml generation. I thought to make the test output for all the commands initially and thus the need for this GM thing (verify by comparing yaml not json). The test output turned out to be much smaller in the end (although GM is still used), but this mechanism is important anyway because later we can use it quite easily to switch libvirttools test from comparing JSON representation of libvirt objects to comparing their "real" XML form.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/611)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/gm/data.go, line 53 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/611#-L6xJ7MqVvqtfmimcwKT:-L6xJ7MqVvqtfmimcwKU:bkk3err) ([raw file](https://github.com/mirantis/virtlet/blob/59bc1311ef722381a9709ad40f96daa9e4bf9397/tests/gm/data.go#L53)):*
> ```Go
> }
> 
> type textVerifier string
> ```

It would be nice to add there:
```
var _ Verifier = &textVerifier
```

---

*[tests/gm/data.go, line 69 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/611#-L6xJJHZoqK8sEUBjqlP:-L6xJJHZoqK8sEUBjqlQ:b2nreh6) ([raw file](https://github.com/mirantis/virtlet/blob/59bc1311ef722381a9709ad40f96daa9e4bf9397/tests/gm/data.go#L69)):*
> ```Go
> type jsonVerifier struct {
> 	data interface{}
> }
> ```

Same as above.

---

*[tests/gm/data.go, line 109 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/611#-L6xJTbSKeAOqZUdntI6:-L6xJTbSKeAOqZUdntI7:b2nreh6) ([raw file](https://github.com/mirantis/virtlet/blob/59bc1311ef722381a9709ad40f96daa9e4bf9397/tests/gm/data.go#L109)):*
> ```Go
> type YamlVerifier struct {
> 	data interface{}
> }
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/611)*

**Comment by ivan4th** [comment]
Review status: 17 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/gm/data.go, line 53 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/611#-L6xJ7MqVvqtfmimcwKT:-L71ljiGfn8RPir2lbLT:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/59bc1311ef722381a9709ad40f96daa9e4bf9397/tests/gm/data.go#L53)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

It would be nice to add there:
```
var _ Verifier = &textVerifier
```
</blockquote></details>

Done.

---

*[tests/gm/data.go, line 69 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/611#-L6xJJHZoqK8sEUBjqlP:-L71lkb55npl1zOFZdKi:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/59bc1311ef722381a9709ad40f96daa9e4bf9397/tests/gm/data.go#L69)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---

*[tests/gm/data.go, line 109 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/611#-L6xJTbSKeAOqZUdntI6:-L71llL996P6e6P0kGCP:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/59bc1311ef722381a9709ad40f96daa9e4bf9397/tests/gm/data.go#L109)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/611)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: 17 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/611#-:-L73qdmMJSzzrTlrZEj0:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 32 of 33 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/611#-:-L73wtv9S0NGcCtLXT0a:bnfp4nl)*

**Pull request merged**
