### PR TITLE
Removed travis.yml

### PR DESCRIPTION
**Pull request by pigmej**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/413)

### CODE REVIEW

**Comment by jellonek** [comment]
You forgot a badge in `README.md`.
-1!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/413#-:-Ku41tBtla20XwjBXyPp:b5awtls)*

**Comment by pigmej** [comment]
My fault, fixed :)

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/413#-:-Ku438gqqxtibGJJber2:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/413#-:-Ku46XdypeomeZ6ppbCQ:bnfp4nl)*

**Pull request merged**
