### PR TITLE
Changed codeclimate config to be version 2 compatible

### PR DESCRIPTION
**Pull request by pigmej**
[ci skip]

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/618)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.codeclimate.yml, line 39 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/618#-L79whgfGQr18lAs4_eD:-L79whgfGQr18lAs4_eE:bmtyvwf) ([raw file](https://github.com/mirantis/virtlet/blob/b8c0e8c89a6f4bed7fd6555149eca721d6e940c6/.codeclimate.yml#L39)):*
> ```YAML
> exclude_patterns:
>   - "vendor/"
>   - "pkg/diskimage/guestfs/guestfs.go"
> ```

Please add there also "tests/"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/618)*

**Comment by pigmej** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.codeclimate.yml, line 39 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/618#-L79whgfGQr18lAs4_eD:-L7Oi_RqkH6FvXPyqALU:br8ll8o) ([raw file](https://github.com/mirantis/virtlet/blob/b8c0e8c89a6f4bed7fd6555149eca721d6e940c6/.codeclimate.yml#L39)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Please add there also "tests/"
</blockquote></details>

Will not, let's try to have cc on tests ,too and let's exclude these files one by one if needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/618)*

**Comment by pigmej** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.codeclimate.yml, line 39 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/618#-L79whgfGQr18lAs4_eD:-L7Opn-j-1wo0HYiDqRQ:bkmpqc0) ([raw file](https://github.com/mirantis/virtlet/blob/b8c0e8c89a6f4bed7fd6555149eca721d6e940c6/.codeclimate.yml#L39)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

Will not, let's try to have cc on tests ,too and let's exclude these files one by one if needed.
</blockquote></details>

Ok added, because _tests are already excluded automatically

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/618)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/618#-:-L7Oq34W0MMf2z1Ilz-X:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/618#-:-L7UOfn6V1LFiIqWIxdl:bnfp4nl)*

**Pull request merged**
