### PR TITLE
Add virtletctl gen

### PR DESCRIPTION
**Pull request by ivan4th**
This PR includes a commit from #645 which needs to be merged first.

- [x] bump k8s libs to 1.9 so `MountPropagation` field can be set in k8s objects
- [x] embed `virtlet-ds.yaml` using bindata
- [x] check bindata consistency during `build/cmd.sh build`
- [x] implement `virtletctl gen` command
- [x] update `build/cmd.sh start-dind` to use `virtletctl gen`
- [x] embed image tag in virtletctl when doing release builds on CircleCI
- [x] update `demo.sh` to use `virtletctl` from `mirantis/virtlet` image (pass selected image tag to it using `--tag`)
- [x] remove `jq` from the build container
- [x] fix style issues
- [x] split the part that updates k8s libs into a separate PR
- [x] update docs
- [x] verify `build/cmd.sh release` which no longer includes yamls
- [x] verify `raw_devices` setting in virtlet config
- [x] verify `VIRTLET_DISABLE_KVM=1 build/cmd.sh start-dind`

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/642)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 43 of 44 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/networking.md, line 105 at r2](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-L99Xy7AAbzgOAyewq9i:-L9AIO377uUMZr4vOki8:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4d88ebdaf160dd3fb0714e9889ef6ac4ae41c9d9/docs/networking.md#L105)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

There was a typo - missing space after setting. So that should be "setting `sriov_...".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/642)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-:-L9AIi1KBGV8sc67uDyb:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-:-L9FOiXy8JJ3tuxIFvgR:bnfp4nl)*

**Comment by lukaszo** [comment]
Review status: 29 of 37 files reviewed at latest revision, all discussions resolved.

---

*[deploy/real-cluster.md, line 37 at r4](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-L9FSpw27sIR2X36oTtm:-L9FSpw27sIR2X36oTtn:b-b6qxno) ([raw file](https://github.com/mirantis/virtlet/blob/e81000955e41c1d87e9741dbe694bbe83e153037/deploy/real-cluster.md#L37)):*
> ```Markdown
> After that, you need to get `virtletctl` command line tool (replace `N.N.N` in the command below accordingly):
> ```
> curl -SL -o virtletctl https://github.com/Mirantis/virtlet/releases/download/vN.N.N/virtletctl
> ```

is it possible to have here `latest` version?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/642)*

**Comment by ivan4th** [comment]
Review status: 27 of 37 files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/real-cluster.md, line 37 at r4](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-L9FSpw27sIR2X36oTtm:-L9FXCv-4bVXAYtDfLjy:b-2i9590) ([raw file](https://github.com/mirantis/virtlet/blob/e81000955e41c1d87e9741dbe694bbe83e153037/deploy/real-cluster.md#L37)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

is it possible to have here `latest` version?
</blockquote></details>

Added the notes about it below.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/642)*

**Comment by lukaszo** [comment]
:lgtm:

---

Reviewed 5 of 31 files at r1, 21 of 31 files at r2, 1 of 1 files at r3, 8 of 9 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-:-L9FYkt0DPtXaBScVXWX:bnfp4nl)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/README.md, line 57 at r5](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-L9Fcu7hE-PP6wVOyYRx:-L9Fcu7hE-PP6wVOyYRy:bgbcm1c) ([raw file](https://github.com/mirantis/virtlet/blob/8196fff2029bfb64a3e6e8b978d16fb56664c829/deploy/README.md#L57)):*
> ```Markdown
> cp _output/virtletctl /usr/local/bin
> ```
> Another way is to use the latest released virtletctl with `--tag latest`, see below.
> ```

`virtletctl`

---

*[deploy/README.md, line 67 at r5](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-L9FcrpR1kCDEFDBsRcW:-L9FcrpR1kCDEFDBsRcX:bgbcm1c) ([raw file](https://github.com/mirantis/virtlet/blob/8196fff2029bfb64a3e6e8b978d16fb56664c829/deploy/README.md#L67)):*
> ```Markdown
> ```
> Note thought that it'll only work if the generated yaml didn't change between
> virtletctl version and the image tag you specified, so your mileage may vary.
> ```

`virtletctl`

---

*[deploy/real-cluster.md, line 44 at r5](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-L9Fcj0BCxb1djU18oOL:-L9Fcj0BCxb1djU18oOM:bgbcm1c) ([raw file](https://github.com/mirantis/virtlet/blob/8196fff2029bfb64a3e6e8b978d16fb56664c829/deploy/real-cluster.md#L44)):*
> ```Markdown
> ```
> 
> If you want to use the latest image, you can build virtletctl yourself from the source:
> ```

`virtletctl`

---

*[deploy/real-cluster.md, line 52 at r5](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-L9FcnjCAiicpjtJyupq:-L9FcnjCAiicpjtJyupr:bgbcm1c) ([raw file](https://github.com/mirantis/virtlet/blob/8196fff2029bfb64a3e6e8b978d16fb56664c829/deploy/real-cluster.md#L52)):*
> ```Markdown
> cp _output/virtletctl /usr/local/bin
> ```
> Another way is to use the latest released virtletctl with `--tag latest`, see below.
> ```

`virtletctl`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/642)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r4, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/642#-:-L9Feawi0AKJIUYNu_aI:bnfp4nl)*

**Pull request merged**
