### PR TITLE
dhcp: Add domain search to options if it's set

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/201)

### CODE REVIEW

**Comment by ivan4th** [comment]
Does dhcpcd -T output search list? If so it should be trivial to extend dhcp test to check this

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/201#-:-KcNtL6TDvsf_gNYeDGu:bfdhopx)*

**Comment by ivan4th** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/dhcp/server.go, line 289 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/201#-KeDVmCmLqLwdfDCQCjp:-KeDVmCmLqLwdfDCQCjq:b-dcerfe) ([raw file](https://github.com/mirantis/virtlet/blob/fc4920f2509f183352c1a925d3388cbfbbba57ea/pkg/dhcp/server.go#L289)):*
> ```Go
> 	first := true
> 	for _, domain := range domainList {
> 		if first != true {
> ```

Hmm `first != true` instead of `!first` is a bit clumsy... what about eliminating extra var?
```
for n, domain := range domainList {
        if n > 0 {
        ...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/201)*

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/dhcp/server.go, line 289 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/201#-KeDVmCmLqLwdfDCQCjp:-KeDXbbV6enRwZS-yjKE:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/fc4920f2509f183352c1a925d3388cbfbbba57ea/pkg/dhcp/server.go#L289)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Hmm `first != true` instead of `!first` is a bit clumsy... what about eliminating extra var?
```
for n, domain := range domainList {
        if n > 0 {
        ...
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/201)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/201#-:-KeDgSeLHgpgldd7jgAI:bnfp4nl)*

**Pull request merged**
