### PR TITLE
cni: Initial support for CNI

### PR DESCRIPTION
**Pull request by jellonek**
As in subject...

This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/130)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[contrib/images/cni/Dockerfile, line 12 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXuvXQP5JTh3g7iCjLX:-KXuvXQP5JTh3g7iCjLY:bkjtqb1) ([raw file](https://github.com/mirantis/virtlet/blob/117d4bad9791ac740f979703a35ae5698137f648/contrib/images/cni/Dockerfile#L12)):*
> ```Dockerfile
> VOLUME /opt/cni
> 
> CMD ["/start.sh"]
> ```

Maybe CMD ["sleep", "infinity"] would be enough here?

---

*[contrib/images/cni/prepare.sh, line 4 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXuvdk62bW2ZXMRG4_V:-KXuvdk62bW2ZXMRG4_W:b-6zim1b) ([raw file](https://github.com/mirantis/virtlet/blob/117d4bad9791ac740f979703a35ae5698137f648/contrib/images/cni/prepare.sh#L4)):*
> ```Shell
> 
> mkdir -p opt/cni/bin
> curl -L https://github.com/containernetworking/cni/releases/download/v0.3.0/cni-v0.3.0.tgz | tar zxC opt/cni/bin
> ```

Are relative paths intentional here?

---

*[contrib/images/cni/start.sh, line 5 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXuvgAMh19QPwHOWqi3:-KXuvgAMh19QPwHOWqi4:but3gw6) ([raw file](https://github.com/mirantis/virtlet/blob/117d4bad9791ac740f979703a35ae5698137f648/contrib/images/cni/start.sh#L5)):*
> ```Shell
> while : ; do
> 	sleep 5
> done
> ```

See above, maybe CMD ["sleep", "infinity"] would be enough for the image?

---

*[pkg/cni/ns.go, line 27 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXuvoZuCSqUDZyj-u3b:-KXuvoZuCSqUDZyj-u3c:bdicslq) ([raw file](https://github.com/mirantis/virtlet/blob/117d4bad9791ac740f979703a35ae5698137f648/pkg/cni/ns.go#L27)):*
> ```Go
> 	netnsBasePath = "/var/run/netns"
> )
> ```

Please add some comments why we have to use "ip netns" here (fd leakage if we use cni stuff, also possible problem with networking in virtlet process due to unix.Unshare() calls)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/130)*

**Comment by jellonek** [comment]
Review status: 0 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[contrib/images/cni/Dockerfile, line 12 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXuvXQP5JTh3g7iCjLX:-KXv27As3JHd8Se4ab1u:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/117d4bad9791ac740f979703a35ae5698137f648/contrib/images/cni/Dockerfile#L12)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Maybe CMD ["sleep", "infinity"] would be enough here?
</blockquote></details>

Done.

---

*[contrib/images/cni/prepare.sh, line 4 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXuvdk62bW2ZXMRG4_V:-KXv27fZs43n7toTeztc:bb77ufg) ([raw file](https://github.com/mirantis/virtlet/blob/117d4bad9791ac740f979703a35ae5698137f648/contrib/images/cni/prepare.sh#L4)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Are relative paths intentional here?
</blockquote></details>

Yes.

---

*[pkg/cni/ns.go, line 27 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXuvoZuCSqUDZyj-u3b:-KXv2FKBhGryPD_Holby:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/117d4bad9791ac740f979703a35ae5698137f648/pkg/cni/ns.go#L27)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Please add some comments why we have to use "ip netns" here (fd leakage if we use cni stuff, also possible problem with networking in virtlet process due to unix.Unshare() calls)
</blockquote></details>

Done.

---

*[contrib/images/cni/start.sh, line 5 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXuvgAMh19QPwHOWqi3:-KXv2GJY5vObAmkBkuUD:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/117d4bad9791ac740f979703a35ae5698137f648/contrib/images/cni/start.sh#L5)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

See above, maybe CMD ["sleep", "infinity"] would be enough for the image?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/130)*

**Comment by ivan4th** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cni/ns.go, line 24 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXv3InyQYvxaaYMYPAU:-KXv3InyQYvxaaYMYPAV:b-26l4jh) ([raw file](https://github.com/mirantis/virtlet/blob/85b3c2a306540d2718c875c0cd59c6c2b69bb5d8/pkg/cni/ns.go#L24)):*
> ```Go
> )
> 
> // we are using "ip netns" command instead od cni/pkg/ns because usage
> ```

typo (od)

---

*[pkg/cni/ns.go, line 25 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXv3KtpEXnPpOyYPAba:-KXv3KtpEXnPpOyYPAbb:banecyx) ([raw file](https://github.com/mirantis/virtlet/blob/85b3c2a306540d2718c875c0cd59c6c2b69bb5d8/pkg/cni/ns.go#L25)):*
> ```Go
> 
> // we are using "ip netns" command instead od cni/pkg/ns because usage
> // of later will lead to file descriptors leakages
> ```

file descriptor leakages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/130)*

**Comment by jellonek** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cni/ns.go, line 24 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXv3InyQYvxaaYMYPAU:-KXv6fbxTG8mgj2SKgpi:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/85b3c2a306540d2718c875c0cd59c6c2b69bb5d8/pkg/cni/ns.go#L24)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

typo (od)
</blockquote></details>

Done.

---

*[pkg/cni/ns.go, line 25 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/130#-KXv3KtpEXnPpOyYPAba:-KXv6cMY0ZXWWriWgSGb:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/85b3c2a306540d2718c875c0cd59c6c2b69bb5d8/pkg/cni/ns.go#L25)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

file descriptor leakages
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/130)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 16 of 20 files at r1, 2 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/130#-:-KXv8vZU_9S2Ei3ftWTr:bnfp4nl)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 16 of 20 files at r1, 2 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/130#-:-KXvDUL9YpcExZPX_x48:bnfp4nl)*

**Pull request merged**
