### PR TITLE
Fix demo, check for images.yaml before creating

### PR DESCRIPTION
**Pull request by pigmej**
Don't create `images.yaml` when not found. It fixes `demo.sh` with `0.8.2`.

Tested:
`./deploy/demo.sh` - deploys 0.8.2 (without `images.yaml`)
`VIRTLET_DEMO_RELEASE=master ./deploy/demo.sh` - deploys master (with `images.yaml`)

This can be removed after we make release with images.yaml

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/431)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/431#-:-KucnoZ4GKd3OYsSXyrQ:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/demo.sh, line 284 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/431#-Kuco3Bb8pWu-s2a5Fne:-Kuco3Bb8pWu-s2a5Fnf:b-3qnoya) ([raw file](https://github.com/mirantis/virtlet/blob/380ec1e84130f83ddf40f8972fa45a6e41c6d4a3/deploy/demo.sh#L284)):*
> ```Shell
>   # new functionality added post 0.8.2
>   # 'if' could be removed later
>   if [ -f "${BASE_LOCATION}/deploy/images.yaml" ]; then
> ```

please use bash-style `if [[ ... ]]` for the sake of consistency. note that for `[[ ... ]]` you don't need to quote `${BASE_LOCATION}/deploy/images.yaml` (there's a couple of `if [ ... ]` in demo.sh but we need to make it more consistent, not less consistent ...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/431)*

**Comment by pigmej** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/demo.sh, line 284 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/431#-Kuco3Bb8pWu-s2a5Fne:-KucpFkM5f-rJdXu0v6I:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/380ec1e84130f83ddf40f8972fa45a6e41c6d4a3/deploy/demo.sh#L284)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

please use bash-style `if [[ ... ]]` for the sake of consistency. note that for `[[ ... ]]` you don't need to quote `${BASE_LOCATION}/deploy/images.yaml` (there's a couple of `if [ ... ]` in demo.sh but we need to make it more consistent, not less consistent ...)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/431)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/431#-:-KucpfnyhRtk_nd7mN1G:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/431#-:-KudZhVr83fWIQs2TyRJ:bnfp4nl)*

**Comment by istalker2** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/431#-:-Kuh9UlsX7mY3I8LifG6:bnfp4nl)*

**Pull request merged**
