### PR TITLE
Add vCPU count spec

### PR DESCRIPTION
**Pull request by ivan4th**
- refactor annotation handling and metadataStore usage in `VirtualizationTool`
- add vCPU count spec via `VirtletVCPUCount` annotation
- default to 1 vCPU
- document pod options in `cirros-vm.yaml`

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/277)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/cirros-vm.yaml, line 6 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/277#-KkBQEUVq0OzaNu4BWeG:-KkBQEUVq0OzaNu4BWeH:bul026f) ([raw file](https://github.com/mirantis/virtlet/blob/5661bb186667255df546b915862c307118944b7a/examples/cirros-vm.yaml#L6)):*
> ```YAML
>   name: cirros-vm
>   annotations:
>     # This tells CRI Proxy that this Pod belongs to Virtlet runtime
> ```

"pod" - it should be lowercase - please refer to https://kubernetes.io/docs/concepts/workloads/pods/pod/
btw. we can have this probably in more places to fix. In below lines I see that you have this correct :)

---

*[pkg/libvirttools/annotations.go, line 100 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/277#-KkBR6s1k47soT7v54uj:-KkBR6s1k47soT7v54uk:bw8fft6) ([raw file](https://github.com/mirantis/virtlet/blob/5661bb186667255df546b915862c307118944b7a/pkg/libvirttools/annotations.go#L100)):*
> ```Go
> 	}
> 	if errs != nil {
> 		return fmt.Errorf("Bad virtlet annotations. Errors:\n%s", strings.Join(errs, "\n"))
> ```

Error message should be started with lower case.

---

*[pkg/libvirttools/annotations_test.go, line 147 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/277#-KkBT5EvSu5iFZkqfIqk:-KkBT5EvSu5iFZkqfIql:b-zgzm6u) ([raw file](https://github.com/mirantis/virtlet/blob/5661bb186667255df546b915862c307118944b7a/pkg/libvirttools/annotations_test.go#L147)):*
> ```Go
> 				"VirtletVolumes": `[{"Name": "rawVol", "Format": "rawDevice", "Path": "/tmp/foobar"}]`,
> 			},
> 		},
> ```

This list misses tests for negative capacity for volumes, or for unknown capacity units.
Hmmm... We do not validate them, maybe we should?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/277)*

**Comment by ivan4th** [comment]
Review status: 7 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/cirros-vm.yaml, line 6 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/277#-KkBQEUVq0OzaNu4BWeG:-KkBZrW6a2BPMHk4UDNd:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5661bb186667255df546b915862c307118944b7a/examples/cirros-vm.yaml#L6)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

"pod" - it should be lowercase - please refer to https://kubernetes.io/docs/concepts/workloads/pods/pod/
btw. we can have this probably in more places to fix. In below lines I see that you have this correct :)
</blockquote></details>

Done.

---

*[pkg/libvirttools/annotations.go, line 100 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/277#-KkBR6s1k47soT7v54uj:-KkBZtBpUfb9LuQ5s8h5:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5661bb186667255df546b915862c307118944b7a/pkg/libvirttools/annotations.go#L100)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Error message should be started with lower case.
</blockquote></details>

Done.

---

*[pkg/libvirttools/annotations_test.go, line 147 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/277#-KkBT5EvSu5iFZkqfIqk:-KkBZxCkDCSDnMJXPRxJ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/5661bb186667255df546b915862c307118944b7a/pkg/libvirttools/annotations_test.go#L147)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This list misses tests for negative capacity for volumes, or for unknown capacity units.
Hmmm... We do not validate them, maybe we should?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/277)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/277#-:-KkB_6JkAuVT9IfRKt1l:bnfp4nl)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 4 of 10 files at r1, 3 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/277#-:-KkBiW8r-8nQ4FQ0SxU2:bnfp4nl)*

**Pull request merged**
