### PR TITLE
Better handling of broken CNIs

### PR DESCRIPTION
**Pull request by ivan4th**
Fix IP & DNS config if it's not provided in CNI result

This concerns e.g. Weave but may affects other CNIs as well

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/510)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:
will add a note about that to multiple interfaces followup that this also should be covered in tests.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/510#-:-Kza0GZJxmbDtvBKaIat:b-l9csn2)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/510#-:-Kzi1hfdkb4w9SUcpdmo:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/510#-:-Kzi1o_OJONVfB5sbQmC:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/510#-:-Kzi3bYAlVuLb2V6p7I7:bnfp4nl)*

**Pull request merged**
