### PR TITLE
Add VLan support for sr-iov

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/674)

### CODE REVIEW

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/674#-:-LCc2d_X26eS2wJCqo67:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/674)*

**Comment by lukaszo** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/nettools/nettools.go, line 768 at r1](https://reviewable.io/reviews/mirantis/virtlet/674#-LCc9GUy1GigflJN-Sxd:-LCc9GUzCXsRPtdkt0UR:bb76mu4) ([raw file](https://github.com/mirantis/virtlet/blob/6fea820bff6d6c96c21faa198a2a00188a2f75f0/pkg/nettools/nettools.go#L768)):*
> ```Go
> 			}
> 
> 			var err error
> ```

Why?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/674)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/nettools/nettools.go, line 768 at r1](https://reviewable.io/reviews/mirantis/virtlet/674#-LCc9GUy1GigflJN-Sxd:-LCc9u9s3Uqdyb0kHSTD:b-5yci6i) ([raw file](https://github.com/mirantis/virtlet/blob/6fea820bff6d6c96c21faa198a2a00188a2f75f0/pkg/nettools/nettools.go#L768)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Good question. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/674)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/674#-:-LCcgnxU7TK16vwm30qw:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/674)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/674#-:-LCcgyuy-OrTPOYmdRxJ:bnfp4nl)*

**Pull request merged**
