### PR TITLE
docs: Add a short demo from asciinema

### PR DESCRIPTION
**Pull request by nhlfr**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/36)

### CODE REVIEW

**Comment by nebril** [comment]
Unfortunately, the asciinema recording is almost unviewable on smaller screens, mostly due to vertical orientation (I couldn't really follow it on my 13' laptop). Can you re-record it with smaller window size and in landscape orientation?

**Comment by jellonek** [comment]
Also in demo there is invalid command.

**Comment by pigmej** [comment]
+1 for @nebril

**Comment by ivan4th** [comment]
This one needs to be re-done, closing.

**Pull request closed without merging**
