### PR TITLE
Virtlet restart

### PR DESCRIPTION
**Pull request by lukaszo**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/596)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/manager/manager.go, line 194 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/596#-L89yMtyOfFJ-h8V22g3:-L89yMtzOhx2LJHV9LEX:b-rkggki) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L194)):*
> ```Go
> 			}, err
> 		}
> 		// FIXME sandbox exists but it's not ready. Should we delete it?
> ```

This can have a place only when tapmanager would fail somehow. IMO we should return there whatever state was retrieved from metadata store, so simply when `err == && sandboxInfo != nil`.
If sandbox is not ready - it will be later cleaned up after a proper call from kubelet.

---

*[pkg/manager/manager.go, line 397 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/596#-L8A-9KRqzluC7BNIJ4n:-L8A-9KSrwBJov9rrJl1:bka251d) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L397)):*
> ```Go
> 			glog.V(3).Infof("CreateContainer: there's already a container in the sandbox (id: %s)", container.GetID())
> 			response := &kubeapi.CreateContainerResponse{ContainerId: container.GetID()}
> 			return response, nil
> ```

In such case this for loops does not have a sense... It only hides if len(..) > 0, while it can be equal to 0 or 1.
We also probably should (probably not in this PR, as a followup) change ListPodContainers to RetrievePodContainer, as there can bo only one in our pod sandbox.

---

*[pkg/manager/manager.go, line 434 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/596#-L8A0h_WEHg61HuAtM6n:-L8A0h_XSTaY_Z6jTPhx:b-raycb5) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L434)):*
> ```Go
> 
> 	status, err := v.libvirtVirtualizationTool.ContainerStatus(in.ContainerId)
> 	if err == nil && status != nil && status.State == 1 {
> ```

Please use named constant instead of plain number.

---

*[pkg/manager/manager.go, line 435 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/596#-L8A0urkBwS2Fia52e89:-L8A0urkBwS2Fia52e8A:brh1k7o) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L435)):*
> ```Go
> 	status, err := v.libvirtVirtualizationTool.ContainerStatus(in.ContainerId)
> 	if err == nil && status != nil && status.State == 1 {
> 		glog.V(2).Infof("StartContainer: Container %s is already running %v", in.ContainerId, status)
> ```

... is already in state: %v

---

*[pkg/stream/listener.go, line 81 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/596#-L8A16iJ_cBbdh8NboVd:-L8A16iJ_cBbdh8NboVe:b-sbheqs) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/stream/listener.go#L81)):*
> ```Go
> 	// is recreated with root/root set as owner/group so changing user manualy
> 	// FIXME: Is it better way to do it?
> 	// 64055 libvirt uid
> ```

https://golang.org/pkg/os/user/#Lookup on constant name "libvirt" and in returned `User` there is `Uid` which needs to be passed through https://golang.org/pkg/strconv/#Atoi

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/596)*

**Comment by lukaszo** [comment]
Review status: 29 of 31 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/manager/manager.go, line 194 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/596#-L89yMtyOfFJ-h8V22g3:-L8CUlf6do8X03WJGdTN:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L194)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This can have a place only when tapmanager would fail somehow. IMO we should return there whatever state was retrieved from metadata store, so simply when `err == && sandboxInfo != nil`.
If sandbox is not ready - it will be later cleaned up after a proper call from kubelet.
</blockquote></details>

Done.

---

*[pkg/manager/manager.go, line 397 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/596#-L8A-9KRqzluC7BNIJ4n:-L8CHo8TUVfRQrL0SQ70:b38wvw8) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L397)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

In such case this for loops does not have a sense... It only hides if len(..) > 0, while it can be equal to 0 or 1.
We also probably should (probably not in this PR, as a followup) change ListPodContainers to RetrievePodContainer, as there can bo only one in our pod sandbox.
</blockquote></details>

I'm just reusing code from pkg/metadata/containers.go in ImagesInUse

---

*[pkg/manager/manager.go, line 434 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/596#-L8A0h_WEHg61HuAtM6n:-L8CLjbJLzbtAH7YIZIG:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L434)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Please use named constant instead of plain number.
</blockquote></details>

Done.

---

*[pkg/manager/manager.go, line 435 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/596#-L8A0urkBwS2Fia52e89:-L8CM0y_jFEWmSHcyEVC:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L435)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

... is already in state: %v
</blockquote></details>

Done.

---

*[pkg/stream/listener.go, line 81 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/596#-L8A16iJ_cBbdh8NboVd:-L8CGlUagZof4sZTCiyI:bdaek36) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/stream/listener.go#L81)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

https://golang.org/pkg/os/user/#Lookup on constant name "libvirt" and in returned `User` there is `Uid` which needs to be passed through https://golang.org/pkg/strconv/#Atoi
</blockquote></details>

good point

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/596)*

**Comment by jellonek** [comment]
Review status: 29 of 31 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/manager/manager.go, line 397 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/596#-L8A-9KRqzluC7BNIJ4n:-L8CvPkH7-2TchI5142A:b-4fv69e) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L397)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

I'm just reusing code from pkg/metadata/containers.go in ImagesInUse
</blockquote></details>

Ok. It can be there as is, will look on that later from readability point of view.

---

*[pkg/manager/manager.go, line 434 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/596#-L8A0h_WEHg61HuAtM6n:-L8CwrMc2UHwRedt75sc:b-jtgvak) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L434)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

YYY, i had in mind there usage of `kubeapi.ContainerState_CONTAINER_RUNNING`. ;)

---

*[pkg/stream/listener.go, line 81 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/596#-L8A16iJ_cBbdh8NboVd:-L8CxINL5nXVMLvqdlUH:bnx4eh1) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/stream/listener.go#L81)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

good point
</blockquote></details>

Perfect.
Almost - it will be working ok, but we need to keep in mind that content of `/etc/passwd` in both containers needs to be same (it's now), i mean in virtlet container and in libvirt container.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/596)*

**Comment by lukaszo** [comment]
Review status: 29 of 31 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/manager/manager.go, line 434 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/596#-L8A0h_WEHg61HuAtM6n:-L8CyEeb8E-R1RfRgBAc:b-bcs04t) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L434)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

YYY, i had in mind there usage of `kubeapi.ContainerState_CONTAINER_RUNNING`. ;)
</blockquote></details>

I didn't like that name :P

---

*[pkg/stream/listener.go, line 81 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/596#-L8A16iJ_cBbdh8NboVd:-L8CyLESTKqV048TW8EL:b1ltg69) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/stream/listener.go#L81)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Perfect.
Almost - it will be working ok, but we need to keep in mind that content of `/etc/passwd` in both containers needs to be same (it's now), i mean in virtlet container and in libvirt container.
</blockquote></details>

I know, I double checked it before making this change 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/596)*

**Comment by lukaszo** [comment]
Review status: 29 of 31 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/manager/manager.go, line 434 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/596#-L8A0h_WEHg61HuAtM6n:-L8HuF_wgLbUWZQVWj_x:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/da5dc4d4097aab14d4c73af17decd75f06062ec6/pkg/manager/manager.go#L434)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

I didn't like that name :P
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/596)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/596#-:-L8Hzz_OWiYKpbNTjiFh:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 29 of 31 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/596)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/596#-:-L8In1bEHcgMX-YcczOl:bnfp4nl)*

**Pull request merged**
