### PR TITLE
[docs] Add Virtlet Update notes section to docs

### PR DESCRIPTION
**Pull request by ologvinova**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/500)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/update-notes/Q4'17-10-18.md, line 13 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/500#-Kyv5ciQWsdiybw0uvvk:-Kyv5ciQWsdiybw0uvvl:by70jmg) ([raw file](https://github.com/mirantis/virtlet/blob/7b10f918cb6606134ddff02cd3691384f0db89e7/docs/update-notes/Q4'17-10-18.md#L13)):*
> ```Markdown
>   If the `key` part is omitted, `authorized_keys` is used.
> * Added a helper function to recursively merge arbitrary JSON-like
>   data.
> ```

Actually what's done is this:
* Implemented cloud-init user data [merge algorithm](http://cloudinit.readthedocs.io/en/latest/topics/merging.html)

---

*[docs/update-notes/Q4'17-10-18.md, line 14 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/500#-Kyv5XeZtWft-fCpXLe_:-Kyv5XeZtWft-fCpXLea:b8xt4iq) ([raw file](https://github.com/mirantis/virtlet/blob/7b10f918cb6606134ddff02cd3691384f0db89e7/docs/update-notes/Q4'17-10-18.md#L14)):*
> ```Markdown
> * Added a helper function to recursively merge arbitrary JSON-like
>   data.
> * Moved common Kubernetes-client related code to the `utils` package.
> ```

This is not really user-facing change... Should we list it here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/500)*

**Comment by ologvinova** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/update-notes/Q4'17-10-18.md, line 13 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/500#-Kyv5ciQWsdiybw0uvvk:-KyvBdmb1zqJaug6xySB:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7b10f918cb6606134ddff02cd3691384f0db89e7/docs/update-notes/Q4'17-10-18.md#L13)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Actually what's done is this:
* Implemented cloud-init user data [merge algorithm](http://cloudinit.readthedocs.io/en/latest/topics/merging.html)
</blockquote></details>

Done.

---

*[docs/update-notes/Q4'17-10-18.md, line 14 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/500#-Kyv5XeZtWft-fCpXLe_:-KyvBeaU4_PiNn7VRqM_:bss4a2b) ([raw file](https://github.com/mirantis/virtlet/blob/7b10f918cb6606134ddff02cd3691384f0db89e7/docs/update-notes/Q4'17-10-18.md#L14)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

This is not really user-facing change... Should we list it here?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/500)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/500#-:-KyvBsswmH0u5aqe7kVW:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/500#-:-KyvLvV49xTN4q-Yu203:bnfp4nl)*

**Pull request merged**
