### PR TITLE
storage: Remove snapshot by it's name

### LINKED ISSUE #135: Snapshot removal issue
```
virtlet_1       | libvirt: Storage Driver error : Storage volume not found: no storage vol with matching name '/var/lib/libvirt/images/snapshot_702d1086-12bf-4398-791c-843158379044'
virtlet_1       | E1209 15:10:55.016604       1 manager.go:329] Error when removing image snapshot with path '/var/lib/libvirt/images/snapshot_702d1086-12bf-4398-791c-843158379044': Storage volume not found: no storage vol with matching name '/var/lib/libvirt/images/snapshot_702d1086-12bf-4398-791c-843158379044'
```
While domain is created with:
```
<source file='/var/lib/virtlet/snapshot_702d1086-12bf-4398-791c-843158379044'></source>
```

### PR DESCRIPTION
**Pull request by jellonek**
Closes #135

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/158)

### CODE REVIEW

**Comment by jellonek** [comment]
Hold on, looks like this still does not work:
```
libvirt: Storage Driver error : Storage volume not found: no storage vol with matching name 'snapshot_75b458c3-c1bc-4880-458c-56951ba1a61f'
E1215 23:56:06.216713   29690 manager.go:334] Error when removing image snapshot with name 'snapshot_75b458c3-c1bc-4880-458c-56951ba1a61f': Storage volume not found: no storage vol with matching name 'snapshot_75b458c3-c1bc-4880-458c-56951ba1a61f'
```
while:
```
docker exec virtlet virsh vol-list volumes | grep 75b
 snapshot_75b458c3-c1bc-4880-458c-56951ba1a61f /var/lib/virtlet/snapshot_75b458c3-c1bc-4880-458c-56951ba1a61f
```

**Comment by vefimova** [comment]
The reason of failure is that the wrong pool pointer for images is used (from ImageTool) and we need to pass it pool ptr stored in VirtualizationTool for created volumes

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/158#-:-KZ71TAcLnMEg8U9Yk1J:bnkpeby)*

**Comment by vefimova** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/158)*

**Comment by jellonek** [comment]
Ough. Will fix this pointer!

**Comment by vefimova** [comment]
Very nice! :) :lgtm_strong: 

---

Review status: 4 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/158#-:-KZMD4CnRhhWPVoOwZDm:b-y8zn7m)*

**Pull request merged**
