### PR TITLE
Multiple interfaces support

### PR DESCRIPTION
**Pull request by jellonek**
This branch should work as before it with simple bridge or calico.
It includes code for multiple interfaces. It's prerequisite for sr-iov, which will be rebased on top of this..

It also contains small fixes for things found in tests and docstrings found in master.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/508)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 14 files reviewed at latest revision, 11 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 169 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTe6eCYlFs-38IxP52:-KzTe6eDMrDi7KPBEdak:btjpifd) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/cmd/vmwrapper/vmwrapper.go#L169)):*
> ```Go
> 			var descriptions []tapmanager.InterfaceDescription
> 			if err := json.Unmarshal(marshaledData, &descriptions); err != nil {
> 				glog.Errorf("Failed to unmarshal info about network interfaces: %v", err)
> ```

Failed to unmarshal network interface info

---

*[pkg/dhcp/server.go, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTeL2akd40wqV289fX:-KzTeL2akd40wqV289fY:b-vs7gwu) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/pkg/dhcp/server.go#L50)):*
> ```Go
> 
> func NewServer(config *cnicurrent.Result) (*Server, error) {
> 	return &Server{config: config}, nil
> ```

Does it really make sense to return `error` here at all? This func is only called directly (e.g. not via some func type var)

---

*[pkg/nettools/nettools.go, line 350 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTfZBrxOlTQ1RYD4QV:-KzTfZBsy0ajJYncGbYa:b5arvz1) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/pkg/nettools/nettools.go#L350)):*
> ```Go
> 
> 	var links []netlink.Link
> 	for _, iface := range info.Interfaces {
> ```

Please skip interfaces with `Sandbox == nil`, they don't belong to the container network namespace

---

*[pkg/nettools/nettools.go, line 521 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTiPCdLuAciP0QKfK_:-KzTiPCdLuAciP0QKfKa:b6w9a1c) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/pkg/nettools/nettools.go#L521)):*
> ```Go
> 	// Result contains CNI result object describing the network settings
> 	Result *cnicurrent.Result
> 	// NsPath to the container network namespace
> ```

NsPath specifies the path to the container network namespace

---

*[pkg/nettools/nettools.go, line 527 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTiJystOUv5F6dMgHI:-KzTiJystOUv5F6dMgHJ:b3hx9ev) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/pkg/nettools/nettools.go#L527)):*
> ```Go
> 	TapFiles []*os.File
> 	// HardwareAddrs contains a list of original hardware addresses of
> 	// a CNI-created veth links
> ```

of CNI-created veth links

---

*[tests/network/dhcp_test.go, line 136 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTi-AyQflBzWwDRUuy:-KzTi-AyQflBzWwDRUuz:b-sfs6l3) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/dhcp_test.go#L136)):*
> ```Go
> 		mac, _ := net.ParseMAC(clientMacAddress)
> 		if err = nettools.SetHardwareAddr(clientVeth, mac); err != nil {
> 			return fmt.Errorf("can not set test mac address on client interface: %v", err)
> ```

can't set MAC address on the client interface:

---

*[tests/network/utils_test.go, line 188 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTh-BTBJTqpvv-bo3I:-KzTh-BTBJTqpvv-bo3J:bilmnz1) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/utils_test.go#L188)):*
> ```Go
> 
> func (d *DhcpClient) Run(readyCh, stopCh chan struct{}) error {
> 	cmd := exec.Command("dhcpcd", "-T", "-t", "2")
> ```

maybe make a constant named dhcpcdTimeout (int)?

---

*[tests/network/utils_test.go, line 208 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTh4vL2Ip-qzfVJ2-j:-KzTh4vL2Ip-qzfVJ2-k:behgcpc) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/utils_test.go#L208)):*
> ```Go
> 	outStr := b.String()
> 	if err != nil {
> 		return fmt.Errorf("dhcpcd -T -t 2 failed: %v\nout:\n%s", err, outStr)
> ```

perhaps should just make `args := []string{"dhcpcd", "-T", "-t", strconv.Itoa(dhcpcdTimeout)}`, use it to construct the command (`exec.Command(args...)`) and also display it here: `return fmt.Errorf("%s failed: %v\nout\n:%s", strings.Join(args, " "), err, outStr)`

---

*[tests/network/vm_network_test.go, line 110 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzThiLG_wOSS4-lU4W-:-KzThiLG_wOSS4-lU4W0:blc32dd) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/vm_network_test.go#L110)):*
> ```Go
> 
> 	var dhcpClientVeth, hostVeth netlink.Link
> 	if err := hostNS.Do(func(ns.NetNS) (err error) {
> ```

Thanks for noticing and fixing this! :+1: 

---

*[tests/network/vm_network_test.go, line 117 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzThncmX4nsOyq6ej48:-KzThncmX4nsOyq6ej49:b-hh9p3k) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/vm_network_test.go#L117)):*
> ```Go
> 	}
> 
> 	if err := contNS.Do(func(ns.NetNS) error {
> ```

Same as above. :+1: 

---

*[tests/network/vm_network_test.go, line 164 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzThwFka1vvvlbgbplj:-KzThwFka1vvvlbgbplk:b-twqv4e) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/vm_network_test.go#L164)):*
> ```Go
> 	outerIP := addAddress(t, hostNS, hostVeth, outerAddr)
> 
> 	g := NewNetTestGroup(t, 15*time.Second)
> ```

Why 15 min ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/508)*

**Comment by ivan4th** [comment]
Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/nettools/nettools.go, line 350 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTfZBrxOlTQ1RYD4QV:-KzTiy2XpZ5FOpKQ6ypB:b-7pyv37) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/pkg/nettools/nettools.go#L350)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Please skip interfaces with `Sandbox == nil`, they don't belong to the container network namespace
</blockquote></details>

Sorry, I meant `Sandbox == ""` (it's a string)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/508)*

**Comment by ivan4th** [comment]
Review status: 0 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/nettools/nettools.go, line 350 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTfZBrxOlTQ1RYD4QV:-KzTo9U3sg9IqaqiR48L:b5wizyu) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/pkg/nettools/nettools.go#L350)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Sorry, I meant `Sandbox == ""` (it's a string)
</blockquote></details>

Ok, I see it now. Sorry, started the review in per-commit mode

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/508)*

**Comment by ivan4th** [comment]
Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[tests/network/vm_network_test.go, line 155 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTocMhF8IFUvE6hZX2:-KzTocMhF8IFUvE6hZX3:b-r81x6x) ([raw file](https://github.com/mirantis/virtlet/blob/bea7916cf84e75da276696d41b44b6a632ad4786/tests/network/vm_network_test.go#L155)):*
> ```Go
> 		mac, _ := net.ParseMAC(clientMacAddress)
> 		if err = nettools.SetHardwareAddr(dhcpClientVeth, mac); err != nil {
> 			return fmt.Errorf("can not set test mac address on client interface: %v", err)
> ```

can't set test MAC address on client interface: %v

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/508)*

**Comment by jellonek** [comment]
Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 169 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTe6eCYlFs-38IxP52:-KzV8J5L1FjRf8vCNzP7:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/cmd/vmwrapper/vmwrapper.go#L169)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Failed to unmarshal network interface info
</blockquote></details>

Done.

---

*[pkg/dhcp/server.go, line 50 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTeL2akd40wqV289fX:-KzV8JzvD7oLCNCWJgFX:btrav24) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/pkg/dhcp/server.go#L50)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Does it really make sense to return `error` here at all? This func is only called directly (e.g. not via some func type var)
</blockquote></details>

You are right, it's pointless. Done.

---

*[pkg/nettools/nettools.go, line 521 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTiPCdLuAciP0QKfK_:-KzV8rmNt35roSCqPmun:b-2wq8mc) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/pkg/nettools/nettools.go#L521)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

NsPath specifies the path to the container network namespace
</blockquote></details>

Btw. i changed there Path to NsPath - rest is your original comment from a day :P.
Done.

---

*[pkg/nettools/nettools.go, line 527 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTiJystOUv5F6dMgHI:-KzV9jb2pOtRDafmaJ63:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/pkg/nettools/nettools.go#L527)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

of CNI-created veth links
</blockquote></details>

Done.

---

*[tests/network/dhcp_test.go, line 136 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTi-AyQflBzWwDRUuy:-KzVC3piAeJSkXlKOpJV:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/dhcp_test.go#L136)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

can't set MAC address on the client interface:
</blockquote></details>

Done.

---

*[tests/network/utils_test.go, line 188 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTh-BTBJTqpvv-bo3I:-KzVAolKyNLDvZ4JMc6G:b-k9tk56) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/utils_test.go#L188)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe make a constant named dhcpcdTimeout (int)?
</blockquote></details>

Yep, that seems to be legit. Done.

---

*[tests/network/utils_test.go, line 208 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTh4vL2Ip-qzfVJ2-j:-KzVBR-qFdtP5S9a-Nvf:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/utils_test.go#L208)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

perhaps should just make `args := []string{"dhcpcd", "-T", "-t", strconv.Itoa(dhcpcdTimeout)}`, use it to construct the command (`exec.Command(args...)`) and also display it here: `return fmt.Errorf("%s failed: %v\nout\n:%s", strings.Join(args, " "), err, outStr)`
</blockquote></details>

Done.

---

*[tests/network/vm_network_test.go, line 164 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzThwFka1vvvlbgbplj:-KzVCR0GCJv5L1woHdvc:b39pxcy) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/vm_network_test.go#L164)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Why 15 min ?
</blockquote></details>

This changes timeout from 1 minute to 15sec. IMO even on very overloaded CI 15sec should be enough.

---

*[tests/network/vm_network_test.go, line 155 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTocMhF8IFUvE6hZX2:-KzVC6YdErR-WvXBlTOG:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/bea7916cf84e75da276696d41b44b6a632ad4786/tests/network/vm_network_test.go#L155)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

can't set test MAC address on client interface: %v
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/508)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/nettools/nettools.go, line 521 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzTiPCdLuAciP0QKfK_:-Kz_uAYs106CYtvDSBgY:b-ipjtyn) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/pkg/nettools/nettools.go#L521)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Btw. i changed there Path to NsPath - rest is your original comment from a day :P.
Done.
</blockquote></details>

Ok, thanks :)

---

*[tests/network/vm_network_test.go, line 164 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzThwFka1vvvlbgbplj:-Kz_uMDc0gq1eQzJ-B7l:b5jnckt) ([raw file](https://github.com/mirantis/virtlet/blob/09a57cf50b9abf20fd37d4104d60864528741ef1/tests/network/vm_network_test.go#L164)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This changes timeout from 1 minute to 15sec. IMO even on very overloaded CI 15sec should be enough.
</blockquote></details>

Oops, sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/508#-:-Kz_uQX5dAZ2vga-qBGU:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/tapmanager/tapfdsource.go, line 202 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzxW8jqX4_sI4eWM9Bf:-KzxW8jqX4_sI4eWM9Bg:b-lqod5p) ([raw file](https://github.com/mirantis/virtlet/blob/5e22c45e1f33785a254c0a28480e0f678909166f/pkg/tapmanager/tapfdsource.go#L202)):*
> ```Go
> 		}
> 		if err := nettools.ValidateAndfixCNIResult(netConfig, pnd.PodNs); err != nil {
> 			return fmt.Errorf("error in fixing cni configuration: %v", err)
> ```

It would be best not to fail hard if CNI result is broken but can be successfully extracted during SetupContainerSideNetwork. See below. Currently Weave fails here (OpenContrail can, too)

---

*[pkg/tapmanager/tapfdsource.go, line 206 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzxVut4dMj048Uo_9b-:-KzxVut4dMj048Uo_9b0:b-k0n973) ([raw file](https://github.com/mirantis/virtlet/blob/1511904bf61606d97bdf9ac13100db05c67f07c8/pkg/tapmanager/tapfdsource.go#L206)):*
> ```Go
> 		} else {
> 			fixCNIResult(netConfig, csn)
> 		}
> ```

The idea of this change was to be forgiving for CNI implementations that return bad result (e.g. Weave or OpenContrail). Please don't undo this behavior if possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/508)*

**Comment by jellonek** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/tapmanager/tapfdsource.go, line 206 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzxVut4dMj048Uo_9b-:-Kzy2Ld9kOsL_QtiLX8P:bj2koz) ([raw file](https://github.com/mirantis/virtlet/blob/1511904bf61606d97bdf9ac13100db05c67f07c8/pkg/tapmanager/tapfdsource.go#L206)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

The idea of this change was to be forgiving for CNI implementations that return bad result (e.g. Weave or OpenContrail). Please don't undo this behavior if possible.
</blockquote></details>

Looks like comment was for some other line, am I correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/508)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 4 of 14 files at r1, 8 of 10 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/tapmanager/tapfdsource.go, line 206 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/508#-KzxVut4dMj048Uo_9b-:-L-63OyURi63swo_WyEv:b14al34) ([raw file](https://github.com/mirantis/virtlet/blob/1511904bf61606d97bdf9ac13100db05c67f07c8/pkg/tapmanager/tapfdsource.go#L206)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Looks like comment was for some other line, am I correct?
</blockquote></details>

Ok, as discussed, I just missed some of the changes during the review, sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/508#-:-L-63JCdq1u4ZMz2PqjI:bnfp4nl)*

**Pull request merged**
