### PR TITLE
Fix running tests and building parts of Virtlet on Mac OS X

### PR DESCRIPTION
**Pull request by ivan4th**
- Make parts of Virtlet buildable when possible
- Make tests pass where possible
- Add documentation note
- Remove bad libvirttools -> tapmanager dependency

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/544)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

Looks good but I don't have Mac environment to validate all steps.

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/544#-:-L1qul3s3ELbRIK5sfKT:b-86ye4r)*

**Comment by jellonek** [comment]
Still after trying `./build/cmd.sh build` on clean env I have:
```
...
Successfully built e8f88bc4bc65
Successfully tagged virtlet_build:latest
docker: Error response from daemon: Mounts denied:
The path /boot
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

**Comment by jellonek** [comment]
And removal of `-v /boot:/boot:ro` from `build/cmd.sh` helps only partially - later part fails on rsync ip/port probe.

How I can test this PR? Doing local build using plain golang without our helper script?

**Comment by jellonek** [comment]
Ok, I see instructions for running tests in docs. Will try them.

**Comment by jellonek** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/devel/running-testsuite.md, line 11 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/544#-L2KvGYOBIsRxf1K8dz8:-L2KvGYOBIsRxf1K8dz9:b-rrxrgr) ([raw file](https://github.com/mirantis/virtlet/blob/fd5be444adca1c30a3a9b9ee8d83da8b33a3383f/docs/devel/running-testsuite.md#L11)):*
> ```Markdown
> mkvirtualenv docker-compose
> pip install docker-compose
> ```
> ```

It's sooo outdated, maybe it could be also removed in this PR? (I'm not insisting, it can be done in separate PR).

---

*[docs/devel/running-testsuite.md, line 73 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/544#-L2KvXbYD9cfad7L8Owh:-L2KvXbYD9cfad7L8Owi:b-lal410) ([raw file](https://github.com/mirantis/virtlet/blob/fd5be444adca1c30a3a9b9ee8d83da8b33a3383f/docs/devel/running-testsuite.md#L73)):*
> ```Markdown
> ```
> $ go test -v ./pkg/{flexvolume,imagetranslation,libvirttools,metadata,stream,utils,tapmanager}
> ```
> ```

This will not work without proper setting `GOROOT` (or `GOPATH`) and without downloading other deps which are needed by that command.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/544)*

**Comment by jellonek** [comment]
Review status: 24 of 41 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/devel/running-testsuite.md, line 56 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/544#-L2RBuf2RY1tg8oNECh-:-L2RBuf3icz-932K08Lh:b2rwb0e) ([raw file](https://github.com/mirantis/virtlet/blob/2897d6336853bb21c80c164590ec250b44e2ad18/docs/devel/running-testsuite.md#L56)):*
> ```Markdown
> ```
> 
> For information on how to run e2e tests, refer to [Runn9ng local environment](running-local-environment.md)
> ```

Typo in linked text.

---

*[docs/devel/running-testsuite.md, line 75 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/544#-L2RC0bLlmCEeLafzEVo:-L2RC0bLlmCEeLafzEVp:b42dvm0) ([raw file](https://github.com/mirantis/virtlet/blob/2897d6336853bb21c80c164590ec250b44e2ad18/docs/devel/running-testsuite.md#L75)):*
> ```Markdown
> 
> ```
> $ glide i --strip-vendor
> ```

Please use full name for glide install command.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/544)*

**Comment by ivan4th** [comment]
Review status: 24 of 41 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/devel/running-testsuite.md, line 11 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/544#-L2KvGYOBIsRxf1K8dz8:-L2RBudx2If8LkIvDqqc:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/fd5be444adca1c30a3a9b9ee8d83da8b33a3383f/docs/devel/running-testsuite.md#L11)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

It's sooo outdated, maybe it could be also removed in this PR? (I'm not insisting, it can be done in separate PR).
</blockquote></details>

Done.

---

*[docs/devel/running-testsuite.md, line 73 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/544#-L2KvXbYD9cfad7L8Owh:-L2RDfVNkxdFvVJuB8yy:bk0pl12) ([raw file](https://github.com/mirantis/virtlet/blob/fd5be444adca1c30a3a9b9ee8d83da8b33a3383f/docs/devel/running-testsuite.md#L73)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This will not work without proper setting `GOROOT` (or `GOPATH`) and without downloading other deps which are needed by that command.
</blockquote></details>

`GOROOT` concerns the details of a particular Go installation, other than that, fixed.

---

*[docs/devel/running-testsuite.md, line 56 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/544#-L2RBuf2RY1tg8oNECh-:-L2RDbP1RpVZET8YhkQV:bj3eoea) ([raw file](https://github.com/mirantis/virtlet/blob/2897d6336853bb21c80c164590ec250b44e2ad18/docs/devel/running-testsuite.md#L56)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Typo in linked text.
</blockquote></details>

Fixed, thanks.

---

*[docs/devel/running-testsuite.md, line 75 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/544#-L2RC0bLlmCEeLafzEVo:-L2RE60mo4uiqMfwsQ_9:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/2897d6336853bb21c80c164590ec250b44e2ad18/docs/devel/running-testsuite.md#L75)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Please use full name for glide install command.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/544)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r3.
Review status: 40 of 41 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/544#-:-L2RFvOOX6-jOTDzmCr6:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/devel/running-testsuite.md, line 73 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/544#-L2UpNi9rrdcRxAxU1CR:-L2UpNi9rrdcRxAxU1CS:b-rxt656) ([raw file](https://github.com/mirantis/virtlet/blob/28f5ca31a8d43199b6e30e199f894518c0158c29/docs/devel/running-testsuite.md#L73)):*
> ```Markdown
> only run on Linux. That being said, some of the tests do run on
> Mac OS X. First you need to make sure Virtlet is checked out
> as `$GOPATH/src/github.com/Mirantis/virtlet` and install glide deps:
> ```

That's the info about which i was asking earlier ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/544#-:-L2UpT55TCH6vX0rPAZr:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 26 of 28 files at r1, 15 of 18 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/544#-:-L2Uvz7fQqXUlIWk2Qto:bnfp4nl)*

**Pull request merged**
