### PR TITLE
Fix linter issues in pkg/manager/

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/606)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/manager/manager.go, line 53 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/606#-L73rlw42CdAME5N4sYt:-L73rlw42CdAME5N4sYu:bkr6oti) ([raw file](https://github.com/mirantis/virtlet/blob/c4bcdb641be756e4aa4c8491b6fce1ac7c34791a/pkg/manager/manager.go#L53)):*
> // VirtletManager provides a main part of Virtlet responding to requests
> // from kubelet, talking with tapmanager and libvirt.

Sorry @jellonek but I don't understand that sentence at all.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/606)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/manager/manager.go, line 53 at r1](https://beta.reviewable.io/reviews/mirantis/virtlet/606#-L73rlw42CdAME5N4sYt:-L74UGoWEqs8TKZ30ozH:b-aonrvq) ([raw file](https://github.com/mirantis/virtlet/blob/c4bcdb641be756e4aa4c8491b6fce1ac7c34791a/pkg/manager/manager.go#L53)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

> // VirtletManager provides a main part of Virtlet responding to requests
> // from kubelet, talking with tapmanager and libvirt.

Sorry @jellonek but I don't understand that sentence at all.
</blockquote></details>

Rephrased. PTAL again.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/606)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/manager/manager.go, line 52 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/606#-L75e3UFykZ6fXrTwNBB:-L75e3UFykZ6fXrTwNBC:b-1ww9tt) ([raw file](https://github.com/mirantis/virtlet/blob/cf9b80dd6d833a40cad385abbbfb589fd1905f32/pkg/manager/manager.go#L52)):*
> VirtletManager provides the main part of Virtlet which

---

*[pkg/manager/manager.go, line 52 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/606#-L75e63Dy1wZ1_MEISIx:-L75e63Dy1wZ1_MEISIy:bo51r0i) ([raw file](https://github.com/mirantis/virtlet/blob/cf9b80dd6d833a40cad385abbbfb589fd1905f32/pkg/manager/manager.go#L52)):*
> / V 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/606#-:-L74nXw4FCVAXXBnEmRa:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/606#-:-L79BL4nSmfLcKqPJMYC:bnfp4nl)*

**Pull request merged**
