### PR TITLE
Cleanup in examples + fedora example

### PR DESCRIPTION
**Pull request by jellonek**
Please note that additional fedora example requires fix in cloud init network data generation (will be included in next PR).

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/554)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/cirros-vm-with-additional-annotations.yaml, line 51 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zUsp0BziAQD47H9kL:-L2zUsp0BziAQD47H9kM:b-v3lhn1) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/cirros-vm-with-additional-annotations.yaml#L51)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>     # Virtlet currently ignores image tags, but their meaning may change
>     # in future, so it’s better not to set them for VM pods. If there’s no tag
>     # provided in the image specification kubelet defaults to
>     # imagePullPolicy: Always, which means that the image is always
>     # redownloaded when the pod is created. In order to make pod creation
>     # faster and more reliable, we set imagePullPolicy to IfNotPresent here
>     # so a previously downloaded image is reused if there is one
</details>

Do we need it there? Why not to put in in docs? Or at least make it shorter

---

*[examples/fedora-vm-with-testuser.yaml, line 15 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zTx78Kx3M91xeugB9:-L2zTx79BbVComCdHBqT:b-zbgqnx) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/fedora-vm-with-testuser.yaml#L15)):*
> ```YAML
>         groups: users
>         lock_passwd: false
>         passwd: "$6$rounds=4096$wPs4Hz4tfs$a8ssMnlvH.3GX88yxXKF2cKMlVULsnydoOKgkuStTErTq2dzKZiIx9R/pPWWh5JLxzoZEx7lsSX5T2jW5WISi1"
> ```

can we have info what PW is that in a comment?

---

*[examples/ubuntu-vm-with-testuser.yaml, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zU45FYdyBoR-ONaEo:-L2zU45FYdyBoR-ONaEp:badm3if) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/ubuntu-vm-with-testuser.yaml#L17)):*
> ```YAML
>         groups: users
>         lock_passwd: false
>         passwd: "$6$rounds=4096$wPs4Hz4tfs$a8ssMnlvH.3GX88yxXKF2cKMlVULsnydoOKgkuStTErTq2dzKZiIx9R/pPWWh5JLxzoZEx7lsSX5T2jW5WISi1"
> ```

can we have plain text password as comment there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/554)*

**Comment by jellonek** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/cirros-vm-with-additional-annotations.yaml, line 51 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zUsp0BziAQD47H9kL:-L2zhV01kGgwGHN9-6zK:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/cirros-vm-with-additional-annotations.yaml#L51)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

>     # Virtlet currently ignores image tags, but their meaning may change
>     # in future, so it’s better not to set them for VM pods. If there’s no tag
>     # provided in the image specification kubelet defaults to
>     # imagePullPolicy: Always, which means that the image is always
>     # redownloaded when the pod is created. In order to make pod creation
>     # faster and more reliable, we set imagePullPolicy to IfNotPresent here
>     # so a previously downloaded image is reused if there is one

Do we need it there? Why not to put in in docs? Or at least make it shorter
</blockquote></details>

Done.

---

*[examples/fedora-vm-with-testuser.yaml, line 15 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zTx78Kx3M91xeugB9:-L2zhViwqm0eQy37Ey2Z:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/fedora-vm-with-testuser.yaml#L15)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

can we have info what PW is that in a comment?
</blockquote></details>

Done.

---

*[examples/ubuntu-vm-with-testuser.yaml, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zU45FYdyBoR-ONaEo:-L2zhWBAA8qNgmoXPVVJ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/ubuntu-vm-with-testuser.yaml#L17)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

can we have plain text password as comment there?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/554)*

**Comment by ivan4th** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/fedora-vm-with-testuser.yaml, line 15 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zTx78Kx3M91xeugB9:-L32LzlvZW4QRd_R3bW0:bu79ngx) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/fedora-vm-with-testuser.yaml#L15)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please see the note about 'testuser' for ubuntu below, also applies here

---

*[examples/fedora-vm-with-testuser.yaml, line 15 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L32M2L1peVaxiezLRz2:-L32M2L1peVaxiezLRz3:b-2zhsuz) ([raw file](https://github.com/mirantis/virtlet/blob/d8ec8d726e20b44d57ba6ad68f646acc9ece0cc8/examples/fedora-vm-with-testuser.yaml#L15)):*
> ```YAML
>         groups: users
>         lock_passwd: false
>         # under this hash is encoded "testuser" as password
> ```

# the password is "testuser"

---

*[examples/fedora-vm-with-testuser.yaml, line 19 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L32KhpBue4hfRITJyBg:-L32KhpBue4hfRITJyBh:b-y6m88) ([raw file](https://github.com/mirantis/virtlet/blob/d8ec8d726e20b44d57ba6ad68f646acc9ece0cc8/examples/fedora-vm-with-testuser.yaml#L19)):*
> ```YAML
>         sudo: ALL=(ALL) NOPASSWD:ALL
>     VirtletSSHKeys: |
>       ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJEcFDXEK2ZbX0ZLS1EIYFZRbDAcRfuVjpstSc0De8+sV1aiu+dePxdkuDRwqFtCyk6dEZkssjOkBXtri00MECLkir6FcH3kKOJtbJ6vy3uaJc9w1ERo+wyl6SkAh/+JTJkp7QRXj8oylW5E20LsbnA/dIwWzAF51PPwF7A7FtNg9DnwPqMkxFo1Th/buOMKbP5ZA1mmNNtmzbMpMfJATvVyiv3ccsSJKOiyQr6UG+j7sc/7jMVz5Xk34Vd0l8GwcB0334MchHckmqDB142h/NCWTr8oLakDNvkfC1YneAfAO41hDkUbxPtVBG5M/o7P4fxoqiHEX+ZLfRxDtHB53 me@localhost
> ```

see the note for ubuntu 'testuser'

---

*[examples/ubuntu-vm-with-testuser.yaml, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zU45FYdyBoR-ONaEo:-L32LbblSRziY3rQ3_2K:b-z9l9px) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/ubuntu-vm-with-testuser.yaml#L17)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ubuntu example used to have problem of ssh key being ignored because of this 'testuser', so it's only possible to ssh into it using password. It would be better specify `ssh-authorized-keys` for testuser to make it possible to ssh into the VM using the example key, but still keeping the ability to log in with password which is handy for use with `kubectl attach` (e.g. to debug network issues that prevent ssh from working). Also, 'testuser' IIRC has some broken shell defaults unlike 'ubuntu' (maybe it's using /bin/sh or something)

---

*[examples/ubuntu-vm-with-testuser.yaml, line 17 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L32M81165SUD6amcmQj:-L32M81165SUD6amcmQk:b-2zhsuz) ([raw file](https://github.com/mirantis/virtlet/blob/d8ec8d726e20b44d57ba6ad68f646acc9ece0cc8/examples/ubuntu-vm-with-testuser.yaml#L17)):*
> ```YAML
>         groups: users
>         lock_passwd: false
>         # under this hash is encoded "testuser" as password
> ```

# the password is "testuser"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/554)*

**Comment by jellonek** [comment]
Reviewed 1 of 6 files at r2.
Review status: 1 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/ubuntu-vm-with-testuser.yaml, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zU45FYdyBoR-ONaEo:-L32XL03UhbUNGzEXIYi:b-oztjo1) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/ubuntu-vm-with-testuser.yaml#L17)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

ubuntu example used to have problem of ssh key being ignored because of this 'testuser', so it's only possible to ssh into it using password. It would be better specify `ssh-authorized-keys` for testuser to make it possible to ssh into the VM using the example key, but still keeping the ability to log in with password which is handy for use with `kubectl attach` (e.g. to debug network issues that prevent ssh from working). Also, 'testuser' IIRC has some broken shell defaults unlike 'ubuntu' (maybe it's using /bin/sh or something)
</blockquote></details>

In fedora - even if you will specify ssh key - after loging in as root with it you are asked to connect as other user, so that's probably similar to what was in ubuntu.  I will add `ssh-authorized-keys` to `testuser`, and will try also check `ssh-import-id`, because that can be probably the reason why there is no way to login on testuser with keys.
For me `testuser` is mostly usable in broken network case, precisely to login using `attach`. But as it has no preset shell - it defaults to `/bin/sh` (in `/etc/passwd` shell part is empty). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/554)*

**Comment by jellonek** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/fedora-vm-with-testuser.yaml, line 15 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zTx78Kx3M91xeugB9:-L32ccLSq0X08vfpPhgP:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/fedora-vm-with-testuser.yaml#L15)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Please see the note about 'testuser' for ubuntu below, also applies here
</blockquote></details>

Done.

---

*[examples/fedora-vm-with-testuser.yaml, line 15 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L32M2L1peVaxiezLRz2:-L32cdPWLVE-EMJorkrp:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d8ec8d726e20b44d57ba6ad68f646acc9ece0cc8/examples/fedora-vm-with-testuser.yaml#L15)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

# the password is "testuser"
</blockquote></details>

Done.

---

*[examples/fedora-vm-with-testuser.yaml, line 19 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L32KhpBue4hfRITJyBg:-L32cbt1Uw6UBJHP5G7H:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d8ec8d726e20b44d57ba6ad68f646acc9ece0cc8/examples/fedora-vm-with-testuser.yaml#L19)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

see the note for ubuntu 'testuser'
</blockquote></details>

Done.

---

*[examples/ubuntu-vm-with-testuser.yaml, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L2zU45FYdyBoR-ONaEo:-L32cT1Ghg6sNoZhipJz:bfscmav) ([raw file](https://github.com/mirantis/virtlet/blob/abaec9c5427b0ba1ae8b6c61e7cc17c91d3b22b1/examples/ubuntu-vm-with-testuser.yaml#L17)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

In fedora - even if you will specify ssh key - after loging in as root with it you are asked to connect as other user, so that's probably similar to what was in ubuntu.  I will add `ssh-authorized-keys` to `testuser`, and will try also check `ssh-import-id`, because that can be probably the reason why there is no way to login on testuser with keys.
For me `testuser` is mostly usable in broken network case, precisely to login using `attach`. But as it has no preset shell - it defaults to `/bin/sh` (in `/etc/passwd` shell part is empty). 
</blockquote></details>

Ok, after setting `ssh-authorized-keys` + `shell` - everything looks fine now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/554)*

**Comment by jellonek** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/ubuntu-vm-with-testuser.yaml, line 17 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/554#-L32M81165SUD6amcmQj:-L32cqfsq546NnQLfYA-:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/d8ec8d726e20b44d57ba6ad68f646acc9ece0cc8/examples/ubuntu-vm-with-testuser.yaml#L17)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

# the password is "testuser"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/554)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/554#-:-L32lprr_1-qRnJZzRjU:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 4 of 8 files at r1, 6 of 6 files at r2.
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/554#-:-L32s134QqwPZ0UVnRwr:bnfp4nl)*

**Pull request merged**
