### PR TITLE
 Provide interface types to vmwrapper<->tapmanager communication

### PR DESCRIPTION
**Pull request by jellonek**
Do not merge before #496.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/497)

### CODE REVIEW

**Comment by ivan4th** [comment]
Reviewed 14 of 14 files at r1, 5 of 5 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/vmwrapper/vmwrapper.go, line 168 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/497#-KyXvHKmQWSuZZjkhq-g:-KyXvHKmQWSuZZjkhq-h:b-kotc84) ([raw file](https://github.com/mirantis/virtlet/blob/1c578eb6d4bf16266fb3e87ffc6286d0e4cd688c/cmd/vmwrapper/vmwrapper.go#L168)):*
> ```Go
> 
> 			var descriptions []tapmanager.InterfaceDescription
> 			if err := json.Unmarshal(marshaledData, &descriptions); err != nil {
> ```

As I mentioned in #490, may consider encoding/gob here, but I don't insist

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/497)*

**Comment by jellonek** [comment]
Review status: 6 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/vmwrapper/vmwrapper.go, line 168 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/497#-KyXvHKmQWSuZZjkhq-g:-KypJtHouKbPEyI7sgkW:b-apn5f2) ([raw file](https://github.com/mirantis/virtlet/blob/1c578eb6d4bf16266fb3e87ffc6286d0e4cd688c/cmd/vmwrapper/vmwrapper.go#L168)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

As I mentioned in #490, may consider encoding/gob here, but I don't insist
</blockquote></details>

As discussed in priv - will keep json encoding as we are using it in other parts of fdserver (for marshaling net result from CNI). Also changing there `json.Unmarshal` to `gob.Decode` would also require additional `bytes.Reader` usage, which imo will have negative impact on overall code readability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/497)*

**Comment by ivan4th** [comment]
Reviewed 5 of 5 files at r5.
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/497)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/497#-:-KyzXLci5qfOxdNGSwq_:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r5.
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/497#-:-KyzXRktjTxJBKw4WjBU:bnfp4nl)*

**Comment by pigmej** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/497)*

**Pull request merged**
