### PR TITLE
Provide garbage collection

### PR DESCRIPTION
**Pull request by jellonek**
When something went wrong, or when host was restarted - we can leak some resources like nocloud iso images, domain definitions on libvirt side, or volumes leaved in same place.

This PR provides cleanup method, which is used during Virtlet startup. It checks metadata store for all defined sandboxes/containers (domains in our case) and tries to remove all things left behind during earlier runs, keeping intact things, which were probably created in other method than call from Virtlet.

todo:
- [ ] tests

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/377)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 25 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/libvirttools/gc.go, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/377#-Kr1YNh4dIKpxsWekr-n:-Kr1YNh4dIKpxsWekr-o:bskwvcd) ([raw file](https://github.com/mirantis/virtlet/blob/040cda7139c2de5d035a4100f5d2de9c2b82407a/pkg/libvirttools/gc.go#L35)):*
> ```Go
> 	}
> 
> 	if err := v.removeOrphanRootVolumes(ids); err != nil {
> ```

oops, looks like you've missed return

---

*[pkg/manager/manager.go, line 94 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/377#-Kr1a5EQDAfUsnPMxpp-:-Kr1a5EQDAfUsnPMxpp0:bnzn0yj) ([raw file](https://github.com/mirantis/virtlet/blob/040cda7139c2de5d035a4100f5d2de9c2b82407a/pkg/manager/manager.go#L94)):*
> ```Go
> 
> 	if err := libvirtVirtualizationTool.GarbageCollect(); err != nil {
> 		glog.Warning("Failure during garbage collection: %v", err)
> ```

`Warningf`

---

*[pkg/virt/domain_interface.go, line 104 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/377#-Kr1Z7TkPjI_bcUF-nPZ:-Kr1Z7Tl6RM7In4-bdWK:b-moryzo) ([raw file](https://github.com/mirantis/virtlet/blob/040cda7139c2de5d035a4100f5d2de9c2b82407a/pkg/virt/domain_interface.go#L104)):*
> ```Go
> 	// UUIDString() returns UUID string for this domain
> 	UUIDString() (string, error)
> 	// Name() returns name of this domain
> ```

returns the name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/377)*

**Comment by jellonek** [comment]
Review status: 0 of 25 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/libvirttools/gc.go, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/377#-Kr1YNh4dIKpxsWekr-n:-Kr1jLKbci6D7nuJ3KsT:b55al1u) ([raw file](https://github.com/mirantis/virtlet/blob/040cda7139c2de5d035a4100f5d2de9c2b82407a/pkg/libvirttools/gc.go#L35)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

oops, looks like you've missed return
</blockquote></details>

Uups. Done.

---

*[pkg/manager/manager.go, line 94 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/377#-Kr1a5EQDAfUsnPMxpp-:-Kr1jN6nd8_TcO3k3Ymq:b-bjladn) ([raw file](https://github.com/mirantis/virtlet/blob/040cda7139c2de5d035a4100f5d2de9c2b82407a/pkg/manager/manager.go#L94)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`Warningf`
</blockquote></details>

... Done.

---

*[pkg/virt/domain_interface.go, line 104 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/377#-Kr1Z7TkPjI_bcUF-nPZ:-Kr1jPGlgK_Bp-J5f0q0:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/040cda7139c2de5d035a4100f5d2de9c2b82407a/pkg/virt/domain_interface.go#L104)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

returns the name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/377)*

**Comment by jellonek** [comment]
Tests will be provided in separate PR.

**Comment by ivan4th** [comment]
Reviewed 19 of 25 files at r1, 1 of 5 files at r2.
Review status: 19 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/virsh.sh, line 28 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/377#-Kr5hI2krBbXORqLAO2z:-Kr5hI2krBbXORqLAO3-:bmw8wj2) ([raw file](https://github.com/mirantis/virtlet/blob/cb40f95d063fc57c5340fca709e8a37a44ebfc8e/examples/virsh.sh#L28)):*
> ```Shell
>       namespace_opts="-n ${namespace}"
>   fi
>   containerID=$(kubectl get pod ${namespace_opts} "${pod_name}" \
> ```

please don't use mixed case for shell vars. I'm ok with fixing it in a followup PR though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/377)*

**Comment by ivan4th** [comment]
Reviewed 1 of 25 files at r1.
Review status: 20 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/377)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 20 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/377#-:-Kr5iOmFwdu4DGdNyDct:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 20 of 25 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/377#-:-Kr5qDe7Nb4x3_zt2obi:bnfp4nl)*

**Pull request merged**
