### PR TITLE
Use flexvolumes for qcow2 and raw devices

### PR DESCRIPTION
**Pull request by ivan4th**
- [x] Introduce `VMConfig` instead of `kubeapi.ContainerCreateRequest`
- [x] Unify volume handling code
- [x] Use flexvolumes for qcow2 and raw devices
- [x] Make sure docs and examples are up to date

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/307)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/307#-:-KlwoYOYEv9OqWV06i07:bnfp4nl)*

**Comment by vefimova** [comment]
Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build/cmd.sh, line 213 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/307#-Klx4dQvvO3xHVch6VXY:-Klx4dQvvO3xHVch6VXZ:bu0dpxo) ([raw file](https://github.com/mirantis/virtlet/blob/30c01c8903ba07058086100f9377891be3f0ea01/build/cmd.sh#L213)):*
> ```Shell
>     # FIXME: exit 1 in $(virtlet_subdir) doesn't cause the script to exit
>     virtlet_subdir >/dev/null
>     vcmd "cd '$(virtlet_subdir)' && go build -gcflags -e $*"
> ```

what does `-e` build flag do (can't find)? Maybe, put comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/307)*

**Comment by vefimova** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/307#-:-KlxwiojGW3WARQTGdB-:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/volumes.md, line 137 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/307#-Km1jVi4SkLaBVd9Ief8:-Km1jVi4SkLaBVd9Ief9:b-tfy47d) ([raw file](https://github.com/mirantis/virtlet/blob/3308bcf8843b2ba69098d6bf86cec9665129a026/docs/volumes.md#L137)):*
> ```Markdown
> 1. Kubelet calls the virtlet flexvolume driver and passes volume info to it
> 1. Virtlet flexvolume driver uses standard kubelet's dir `/var/lib/kubelet/pods/<pod-id>/volumes/virtlet~flexvolume_driver/<volume-name>` to store a json file with flexvolume configuration.
> 4. Virtlet checks whether there are dirs with volume info under `/var/lib/kubelet/pods/<pod-id>/volumes/virtlet~flexvolume_driver`. If yes, virtlet parses the json configuration file and updates the domain definition accordingly.
> ```

Why `4.` instead of `1.` (auto numbering)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/307#-:-Km1kn7jkXBFp-x4_PSC:bnfp4nl)*

**Comment by vefimova** [comment]
Reviewed 12 of 15 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tests/integration/container_create_test.go, line 93 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/307#-Km1qXQbOjMUGkM9X069:-Km1qXQbOjMUGkM9X06A:bid3wvh) ([raw file](https://github.com/mirantis/virtlet/blob/3308bcf8843b2ba69098d6bf86cec9665129a026/tests/integration/container_create_test.go#L93)):*
> ```Go
> 	container := ct.containers[0]
> 	defer ct.teardown()
> 	sandbox.Annotations["VirtletVolumes"] = `[{"Name": "vol1"}, {"Name": "vol2", "Format": "qcow2", "Capacity": "2", "CapacityUnit": "MB"}, {"Name": "vol3"}]`
> ```

Could you please change here using annotations to specify disks to flexvolumes. That's the reason of current integration tests failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/307)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 3 of 15 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/307#-:-Km1vFvekbnROR2pp4nP:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[build/cmd.sh, line 213 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/307#-Klx4dQvvO3xHVch6VXY:-Km1vKonXv9zAhBsAGoV:b-hlcwq0) ([raw file](https://github.com/mirantis/virtlet/blob/30c01c8903ba07058086100f9377891be3f0ea01/build/cmd.sh#L213)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

what does `-e` build flag do (can't find)? Maybe, put comment?
</blockquote></details>

Added desc.

---

*[docs/volumes.md, line 137 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/307#-Km1jVi4SkLaBVd9Ief8:-Km1vPfXhSFSYk7SpJur:b-6v8yos) ([raw file](https://github.com/mirantis/virtlet/blob/3308bcf8843b2ba69098d6bf86cec9665129a026/docs/volumes.md#L137)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Why `4.` instead of `1.` (auto numbering)?
</blockquote></details>

Didn't change this part

---

*[tests/integration/container_create_test.go, line 93 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/307#-Km1qXQbOjMUGkM9X069:-Km1vnd3DbB_sXUbciTX:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/3308bcf8843b2ba69098d6bf86cec9665129a026/tests/integration/container_create_test.go#L93)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Could you please change here using annotations to specify disks to flexvolumes. That's the reason of current integration tests failure.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/307)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/307#-:-Km2IOyo1Mw9iCUblC-H:bnfp4nl)*

**Pull request merged**
