### PR TITLE
Per-node config

### PR DESCRIPTION
**Pull request by ivan4th**
- [x] use k8s.io/code-generator for CRDs
- [x] implement configuration object
- [x] implement per-node config
- [x] testing (incl. `virtletctl version` which may break)
- [x] update image translation code to use generated CRD interfaces
- [x] CRD validation
- [x] style fixes
- [x] update docs

For now, the CRD-related generated code is updated using the following command, which only
works if Go 1.10 is installed locally:
```
build/update-codegen.sh
```

This is to be fixed shortly after we switch to Go 1.10 which is required by k8s code generator, so it'll be done via `build/cmd.sh update-codegen` (and the docs will be updated accordingly).

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/684)

### CODE REVIEW

**Comment by jellonek** [comment]
There are only a minor nits in docs, which imo can be fixed later so :lgtm_strong: 

---

Reviewed 123 of 123 files at r1.
Review status: 1 of 2 LGTMs obtained

---

*[build/update-codegen.sh, line 11 at r1](https://reviewable.io/reviews/mirantis/virtlet/684#-LEsLcrX1xcUsDLp70vY:-LEsLcrX1xcUsDLp70vZ:b-6bd6s1) ([raw file](https://github.com/mirantis/virtlet/blob/c940c348447e0d62686d7a6d523727f4637c9202/build/update-codegen.sh#L11)):*
> ```Shell
> CODEGEN_PKG="${CODEGEN_PKG:-$(cd ${SCRIPT_ROOT}; ls -d -1 ./vendor/k8s.io/code-generator 2>/dev/null || echo ${GOPATH}/src/k8s.io/code-generator)}"
> 
> vendor/k8s.io/code-generator/generate-groups.sh all \
> ```

this assumes that script is executed in root dir of working copy - it would be nice to add above this line `cd ${SCRIPT_ROOT}`

---

*[docs/config.md, line 46 at r1](https://reviewable.io/reviews/mirantis/virtlet/684#-LEsN9l5-Ln374nLZcCw:-LEsN9l5-Ln374nLZcCx:bw0vwyf) ([raw file](https://github.com/mirantis/virtlet/blob/c940c348447e0d62686d7a6d523727f4637c9202/docs/config.md#L46)):*
> ```Markdown
> ```
> 
> You can delete Virtlet pods to have them restarted and pick up the
> ```

imo `You need to delete Virtlet pods ...`.

---

*[docs/config.md, line 51 at r1](https://reviewable.io/reviews/mirantis/virtlet/684#-LEsNnTVAUONJvrbtTok:-LEsNnTVAUONJvrbtTol:b-y4keiu) ([raw file](https://github.com/mirantis/virtlet/blob/c940c348447e0d62686d7a6d523727f4637c9202/docs/config.md#L51)):*
> ```Markdown
> All the config mappings must reside in `kube-system` namespace.  Each
> mapping can specify `nodeSelector` or `nodeName` to target a subset of
> the nodes. If neither `nodeSelector` nor `nodeName` is specified, the
> ```

If you want to be consistent with double spaces after dots - there is one missing before `If`, same with nex if and later before `config`.

---

*[docs/devel/build-tool.md, line 122 at r1](https://reviewable.io/reviews/mirantis/virtlet/684#-LEsOFEG1Cek2jGKzjUc:-LEsOFEG1Cek2jGKzjUd:b2ohpun) ([raw file](https://github.com/mirantis/virtlet/blob/c940c348447e0d62686d7a6d523727f4637c9202/docs/devel/build-tool.md#L122)):*
> ```Markdown
> ### update-docs
> 
> Updates the documentation on virtletctl an the Virtlet config.
> ```

Please enclose virtletctl with `.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/684#-:-LEsRMST8KdqPQO66iLh:b-n94y8e)*

**Comment by pigmej** [comment]
Reviewed 25 of 123 files at r1.
Review status: 1 of 2 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/684)*

**Comment by lukaszo** [comment]
Review status: 1 of 2 LGTMs obtained

---

*[docs/config.md, line 9 at r1](https://reviewable.io/reviews/mirantis/virtlet/684#-LF1pcR36qu9SjlATKrP:-LF1pcR36qu9SjlATKrQ:b-lu5pgs) ([raw file](https://github.com/mirantis/virtlet/blob/c940c348447e0d62686d7a6d523727f4637c9202/docs/config.md#L9)):*
> ```Markdown
> 
> In order to use per-node configuration, you need to create Virtlet
> CRD definitions before you deploy Virtlet:
> ```

Restart of virtlet after changes should also work?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/684)*

**Comment by jellonek** [comment]
Review status: 1 of 2 LGTMs obtained

---

*[docs/config.md, line 9 at r1](https://reviewable.io/reviews/mirantis/virtlet/684#-LF1pcR36qu9SjlATKrP:-LF1ruDx6hCXxMI-EURM:b-7cjy05) ([raw file](https://github.com/mirantis/virtlet/blob/c940c348447e0d62686d7a6d523727f4637c9202/docs/config.md#L9)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

Restart of virtlet after changes should also work?
</blockquote></details>

Yes, recreation of pod will cause usage of new values.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/684)*

**Comment by lukaszo** [comment]
:lgtm:

---

Reviewed 123 of 123 files at r1.
Review status: 1 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/684#-:-LF1vOOHEuIt-2aRxdz3:bnfp4nl)*

**Pull request merged**
