### PR TITLE
Implement release automation

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/581)

### CODE REVIEW

**Comment by ivan4th** [comment]
Removing [WiP] as a test release was successfully published

**Comment by jellonek** [comment]
Trick with kubectl.old looks interesting!

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[images/Dockerfile.build-base, line 70 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/581#-L5pQi74OFIRnF0tJPcl:-L5pQi74OFIRnF0tJPcm:b4lsmad) ([raw file](https://github.com/mirantis/virtlet/blob/737492dd59eb51075c7836481ea7abebe38ee05b/images/Dockerfile.build-base#L70)):*
> ```
> RUN curl -L https://storage.googleapis.com/kubernetes-release/release/${OLD_KUBECTL_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl.old
> RUN echo "${OLD_KUBECTL_SHA1}  /usr/local/bin/kubectl.old" | sha1sum -c
> RUN mkdir -p /usr/local/bin
> ```

that should be done before curl line IMO - in this place it's a bit nonsense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/581#-:-L5pR1os43v9tHH2J7vQ:b-7m2962)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/581#-:-L5riQpMS1HXV4VDAB78:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/581#-:-L5sk5YwCUPxyqIx6QNm:bnfp4nl)*

**Pull request merged**
