### PR TITLE
vmwrapper: Fix logging

### PR DESCRIPTION
**Pull request by jellonek**
Looks like typo. Can be seen in screenshot on #285

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/335)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/vmwrapper/vmwrapper.go, line 299 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/335#-Kn92tBqaf2ZRm63rnmD:-Kn92tBqaf2ZRm63rnmE:blzhljo) ([raw file](https://github.com/mirantis/virtlet/blob/4db82f0f95da82a3d3c4a84b3085941ba6c412ff/cmd/vmwrapper/vmwrapper.go#L299)):*
> ```Go
> 		return nil
> 	}); err != nil {
> 		glog.Errorf("Error occurred while in VM network namespace: %s", err)
> ```

Better also change %s to %v ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/335)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/vmwrapper/vmwrapper.go, line 299 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/335#-Kn92tBqaf2ZRm63rnmD:-Kn94pT2YnpJSCAzQNol:bkwgzph) ([raw file](https://github.com/mirantis/virtlet/blob/4db82f0f95da82a3d3c4a84b3085941ba6c412ff/cmd/vmwrapper/vmwrapper.go#L299)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Better also change %s to %v ...
</blockquote></details>

:+1:
Also verified rest of file and found similar case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/335)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/335#-:-Kn95uetGzHsqeI4DFjf:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/335#-:-Kn98mXiBrrMfyQUIalc:bnfp4nl)*

**Pull request merged**
