### PR TITLE
Add virtletctl virsh and ssh

### PR DESCRIPTION
**Pull request by ivan4th**
- [X] Rework virtletctl to use cobra and pflag
- [X] Add tests for virtletctl parts that use k8s API
- [X] Add virsh command
- [X] Add ssh command (by the means of port forwarding)
- [X] Add tests for virsh and ssh commands
- [X] Support installation as kubectl plugin
- [X] Include virtletctl in releases and CircleCI build artifacts
- [X] Remove vmssh.sh and virsh.sh
- [X] Update docs (incl. Mac build instructions for virtletctl)
- [X] Check that VM pods are really VM pods
- [X] Run virsh on every node if no node is specified

This PR includes the commit from #611 which needs to be merged first.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/598)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 9 of 9 files at r1, 9 of 11 files at r2.
Review status: 13 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/tools/dumpmetadata.go, line 42 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6pvcLeUvQUbwTwAdBL:-L6pvcLeUvQUbwTwAdBM:b4ffkbe) ([raw file](https://github.com/mirantis/virtlet/blob/a983e9a040be17c4c6ee2ea4c1b1d87f5f087d50/pkg/tools/dumpmetadata.go#L42)):*
> ```Go
> 
> // dumpMetadataCommand contains the data needed by the dump-metedata subcommand
> // which is used to dump the contents of Virtlet boltdb in a human-readable
> ```

s/boltdb/metadata db/
Even if now we have boltdb on lower level - this command is using interfaces so it's implementation db independent.

---

*[pkg/tools/kubeclient.go, line 128 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6ptq0Nd8T3GixUKJ7x:-L6ptq0Nd8T3GixUKJ7y:bcpwpk6) ([raw file](https://github.com/mirantis/virtlet/blob/a983e9a040be17c4c6ee2ea4c1b1d87f5f087d50/pkg/tools/kubeclient.go#L128)):*
> ```Go
> 	// the specified VM pod.
> 	GetVMPodInfo(podName string) (*VMPodInfo, error)
> 	// ExecCommandOnContainer given a pod, container, namespace and command
> ```

Hmmm... I forgotten to update this docstring after func rename.

---

*[pkg/tools/ssh.go, line 92 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6puuHS5JiIaXo9gO7T:-L6puuHV8kqmgRS8ZWey:bc0603v) ([raw file](https://github.com/mirantis/virtlet/blob/a983e9a040be17c4c6ee2ea4c1b1d87f5f087d50/pkg/tools/ssh.go#L92)):*
> ```Go
> 		fmt.Sprintf("%s@127.0.0.1", s.user),
> 	}, s.args...)
> 	fmt.Printf("ssh: %q\n", sshArgs)
> ```

That looks like debug print, maybe it could be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/598)*

**Comment by jellonek** [comment]
Reviewed 1 of 11 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/tools/ssh.go, line 47 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6pxmtcJ6Ops6Chb2ee:-L6pxmtdstjETJdYkeiQ:bx9mxi3) ([raw file](https://github.com/mirantis/virtlet/blob/a983e9a040be17c4c6ee2ea4c1b1d87f5f087d50/pkg/tools/ssh.go#L47)):*
> ```Go
> 	cmd := &cobra.Command{
> 		Use:   "ssh user@pod [ssh args...]",
> 		Short: "ssh into a VM pod",
> ```

Short description for internal "help" command is capitalized, so probably all of our commands need to follow the same rule.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/598)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/tools/ssh.go, line 87 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6pyxp2MdOS6Lk8-gXI:-L6pyxp2MdOS6Lk8-gXJ:b-uzdyfa) ([raw file](https://github.com/mirantis/virtlet/blob/a983e9a040be17c4c6ee2ea4c1b1d87f5f087d50/pkg/tools/ssh.go#L87)):*
> ```Go
> 		"StrictHostKeyChecking=no",
> 		"-o",
> 		"UserKnownHostsFile=/dev/null",
> ```

We can add there `-q` option to suppress message `Warning: Permanently added '[127.0.0.1]:37885' (ECDSA) to the list of known hosts.`
It's adding it to `/dev/null` so it's not so useful info :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/598)*

**Comment by ivan4th** [comment]
Review status: 10 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/tools/dumpmetadata.go, line 42 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6pvcLeUvQUbwTwAdBL:-L6sw3pMMDsrIJfAbwS1:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a983e9a040be17c4c6ee2ea4c1b1d87f5f087d50/pkg/tools/dumpmetadata.go#L42)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

s/boltdb/metadata db/
Even if now we have boltdb on lower level - this command is using interfaces so it's implementation db independent.
</blockquote></details>

Done.

---

*[pkg/tools/kubeclient.go, line 128 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6ptq0Nd8T3GixUKJ7x:-L6sw5DiWlQlrw0E67SR:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a983e9a040be17c4c6ee2ea4c1b1d87f5f087d50/pkg/tools/kubeclient.go#L128)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... I forgotten to update this docstring after func rename.
</blockquote></details>

Done.

---

*[pkg/tools/ssh.go, line 47 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6pxmtcJ6Ops6Chb2ee:-L6sw7-fENgLSkNVrwIG:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/a983e9a040be17c4c6ee2ea4c1b1d87f5f087d50/pkg/tools/ssh.go#L47)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Short description for internal "help" command is capitalized, so probably all of our commands need to follow the same rule.
</blockquote></details>

Done.

---

*[pkg/tools/ssh.go, line 87 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6pyxp2MdOS6Lk8-gXI:-L6swDnu4rgXTJFyyFdn:bqudg2j) ([raw file](https://github.com/mirantis/virtlet/blob/a983e9a040be17c4c6ee2ea4c1b1d87f5f087d50/pkg/tools/ssh.go#L87)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

We can add there `-q` option to suppress message `Warning: Permanently added '[127.0.0.1]:37885' (ECDSA) to the list of known hosts.`
It's adding it to `/dev/null` so it's not so useful info :)
</blockquote></details>

Thanks, I wanted to look up this option in ssh docs but forgot about it :) Fixed.

---

*[pkg/tools/ssh.go, line 92 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6puuHS5JiIaXo9gO7T:-L6swJSKViERkrtRMoTK:b-somu40) ([raw file](https://github.com/mirantis/virtlet/blob/a983e9a040be17c4c6ee2ea4c1b1d87f5f087d50/pkg/tools/ssh.go#L92)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

That looks like debug print, maybe it could be removed?
</blockquote></details>

Thanks for spotting that, removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/598)*

**Comment by jellonek** [comment]
Reviewed 3 of 5 files at r3.
Review status: 12 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/tools/kubeclient.go, line 151 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6vAYl9waQHeI0HO4TD:-L6vAYl9waQHeI0HO4TE:b-mw6cl6) ([raw file](https://github.com/mirantis/virtlet/blob/f35211a7a6004dbe1db2a1dd02225422f8fa51f9/pkg/tools/kubeclient.go#L151)):*
> ```Go
> var _ remoteExecutor = defaultExecutor{}
> 
> func (e defaultExecutor) Stream(config *rest.Config, method string, url *url.URL, options remotecommand.StreamOptions) error {
> ```

This func needs a docstring.

---

*[pkg/tools/kubeclient.go, line 167 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6vCI6al7FMwrJ25wS8:-L6vCI6al7FMwrJ25wS9:b-mw6cl6) ([raw file](https://github.com/mirantis/virtlet/blob/f35211a7a6004dbe1db2a1dd02225422f8fa51f9/pkg/tools/kubeclient.go#L167)):*
> ```Go
> var _ portForwarder = defaultPortForwarder{}
> 
> func (pf defaultPortForwarder) ForwardPorts(config *rest.Config, method string, url *url.URL, ports []string, stopChannel, readyChannel chan struct{}, out io.Writer) error {
> ```

This func needs a docstring.

---

*[pkg/tools/kubeclient.go, line 191 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6vCMmyckVLmCK1dQci:-L6vCMmyckVLmCK1dQcj:b-mw6cl6) ([raw file](https://github.com/mirantis/virtlet/blob/f35211a7a6004dbe1db2a1dd02225422f8fa51f9/pkg/tools/kubeclient.go#L191)):*
> ```Go
> var _ KubeClient = &RealKubeClient{}
> 
> func NewRealKubeClient() *RealKubeClient {
> ```

This func needs a docstring.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/598)*

**Comment by jellonek** [comment]
As we now have almost only auto generated docs - the info about that we can have kubectl plugin is quite hidden in internals of virtletctl install docs. Maybe it could be added somewhere in new section added to README.md?

---

Reviewed 1 of 5 files at r3, 67 of 67 files at r4.
Review status: 52 of 55 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/virtletctl/virtletctl.go, line 43 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L70sdCtnyOoHY-Y9AnK:-L70sdCtnyOoHY-Y9AnL:b5a1ork) ([raw file](https://github.com/mirantis/virtlet/blob/fcff445fe1b375b6fab4fb73ac49d8c4c0c9b3c7/cmd/virtletctl/virtletctl.go#L43)):*
> ```Go
> 	// Fix unwanted glog warnings, see
> 	// https://github.com/kubernetes/kubernetes/issues/17162#issuecomment-225596212
> 	flag.CommandLine.Parse([]string{})
> ```

Argh, was searching that, thx!

---

*[docs/virtletctl/virtletctl_ssh.md, line 13 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L70tSmyq_Y6z5-bl1vy:-L70tSmyq_Y6z5-bl1vz:b-rysdx) ([raw file](https://github.com/mirantis/virtlet/blob/fcff445fe1b375b6fab4fb73ac49d8c4c0c9b3c7/docs/virtletctl/virtletctl_ssh.md#L13)):*
> ```Markdown
> 
> ```
> virtletctl ssh user@pod -- [ssh args...] [flags]
> ```

Hmmm... That sucx - flags should be before -- but as it's autogenerated we probably don't have a control on that :/

---

*[docs/virtletctl/virtletctl_virsh.md, line 16 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L70vG2yqvePsblkbOiK:-L70vG2yqvePsblkbOiL:b-ag4p93) ([raw file](https://github.com/mirantis/virtlet/blob/fcff445fe1b375b6fab4fb73ac49d8c4c0c9b3c7/docs/virtletctl/virtletctl_virsh.md#L16)):*
> ```Markdown
> on the information of the VM pod. In case if no @podname
> is specified, it's necessary to provide the node name
> using the --node flag.
> ```

Hmmm... Afair shell script allowed to e.g. list domains from all instances, on all nodes, so that looks like regression.

---

*[examples/README.md, line 27 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L70rwT-vxr6SofE4CrT:-L70rwT0jiIZDU6FndmM:b82bhoq) ([raw file](https://github.com/mirantis/virtlet/blob/fcff445fe1b375b6fab4fb73ac49d8c4c0c9b3c7/examples/README.md#L27)):*
> ```Markdown
> ```
> 
> Besides [cirros-vm.yaml](cirros-vm.yaml), there's also [ubuntu-vm.yaml](ubuntu-vm.yaml) that can be used to start an Ubuntu Xenial VM. It can also be accessed using `virtletctl ssh` after it boots:
> ```

If there is info about ubuntu, imo we should also mention similar yaml for fedora. Now it looks like second-class citizen.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/598#-:-L70vhyaVwNBJyyGTnzK:b1240bn)*

**Comment by ivan4th** [comment]
Review status: 36 of 55 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/virtletctl/virtletctl.go, line 43 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L70sdCtnyOoHY-Y9AnK:-L71m0mf9X6l9h4UyKI8:b-ah0p1d) ([raw file](https://github.com/mirantis/virtlet/blob/fcff445fe1b375b6fab4fb73ac49d8c4c0c9b3c7/cmd/virtletctl/virtletctl.go#L43)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Argh, was searching that, thx!
</blockquote></details>

For such comments pls select "Satisfied" in the circle with checkmark so it doesn't count as an "unresolved discussion" in Reviewable :)

---

*[docs/virtletctl/virtletctl_ssh.md, line 13 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L70tSmyq_Y6z5-bl1vy:-L71mDZAYqXcJSpiFnzZ:bv4qwc7) ([raw file](https://github.com/mirantis/virtlet/blob/fcff445fe1b375b6fab4fb73ac49d8c4c0c9b3c7/docs/virtletctl/virtletctl_ssh.md#L13)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... That sucx - flags should be before -- but as it's autogenerated we probably don't have a control on that :/
</blockquote></details>

Done (it's easily fixable by adding `[flags]` to the `Use` string, it'll not be added there second time)

---

*[docs/virtletctl/virtletctl_virsh.md, line 16 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L70vG2yqvePsblkbOiK:-L71mQPpiQzn-G9y3YBA:b-7k7pc0) ([raw file](https://github.com/mirantis/virtlet/blob/fcff445fe1b375b6fab4fb73ac49d8c4c0c9b3c7/docs/virtletctl/virtletctl_virsh.md#L16)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... Afair shell script allowed to e.g. list domains from all instances, on all nodes, so that looks like regression.
</blockquote></details>

Fixed. Made it run on every node in this case as it was before.

---

*[examples/README.md, line 27 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L70rwT-vxr6SofE4CrT:-L71mV_dZfQLf5NsRS-o:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/fcff445fe1b375b6fab4fb73ac49d8c4c0c9b3c7/examples/README.md#L27)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

If there is info about ubuntu, imo we should also mention similar yaml for fedora. Now it looks like second-class citizen.
</blockquote></details>

Done.

---

*[pkg/tools/kubeclient.go, line 151 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6vAYl9waQHeI0HO4TD:-L71mX0I_zyLDBZBTv16:b-nia9t4) ([raw file](https://github.com/mirantis/virtlet/blob/f35211a7a6004dbe1db2a1dd02225422f8fa51f9/pkg/tools/kubeclient.go#L151)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This func needs a docstring.
</blockquote></details>

It didn't need to be capitalized, fixed.

---

*[pkg/tools/kubeclient.go, line 167 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6vCI6al7FMwrJ25wS8:-L71mfNFHuoGlKmS02UB:b-nia9t4) ([raw file](https://github.com/mirantis/virtlet/blob/f35211a7a6004dbe1db2a1dd02225422f8fa51f9/pkg/tools/kubeclient.go#L167)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This func needs a docstring.
</blockquote></details>

It didn't need to be capitalized, fixed.

---

*[pkg/tools/kubeclient.go, line 191 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/598#-L6vCMmyckVLmCK1dQci:-L71miiql0mKgbay0PK4:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/f35211a7a6004dbe1db2a1dd02225422f8fa51f9/pkg/tools/kubeclient.go#L191)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This func needs a docstring.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/598)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 9 files at r1, 49 of 67 files at r4, 19 of 19 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/598#-:-L73qZ2FHl2SsdvXPQfj:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mirantis/virtlet/598#-:-L73rZW1EAJLKg65PtDK:bnfp4nl)*

**Pull request merged**
