### PR TITLE
Tests for multiple interfaces support

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/533)

### CODE REVIEW

**Comment by pigmej** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/533)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/533#-:-L0eFIC0arvfn2L2_0vn:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/nettools/nettools_test.go, line 541 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/533#-L0iQDcKnRQ6pNu-38H6:-L0iQDcKnRQ6pNu-38H7:b-t8os4z) ([raw file](https://github.com/mirantis/virtlet/blob/6acd1da446d7df9ceff5c27d1ef42e92875aebb6/pkg/nettools/nettools_test.go#L541)):*
> ```Go
> func withMultipleInterfacesConfigured(t *testing.T, toRun func(contNS ns.NetNS, innerLinks []netlink.Link)) {
> 	withHostAndContNS(t, func(hostNS, contNS ns.NetNS) {
> 		origHostVeth0, origContVeth0, err := CreateEscapeVethPair(contNS, "eth0", 1500)
> ```

maybe could make this test a little bit prettier by using `var origHostVeth [2]netlink.Link` and so on?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/533)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/nettools/nettools_test.go, line 541 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/533#-L0iQDcKnRQ6pNu-38H6:-L0iTXt5kwHuvstY4anj:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/6acd1da446d7df9ceff5c27d1ef42e92875aebb6/pkg/nettools/nettools_test.go#L541)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe could make this test a little bit prettier by using `var origHostVeth [2]netlink.Link` and so on?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/533)*

**Comment by ivan4th** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/nettools/nettools_test.go, line 568 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/533#-L0iXOSc9UtW3-GFcMBU:-L0iXOSc9UtW3-GFcMBV:b-ujcp61) ([raw file](https://github.com/mirantis/virtlet/blob/8713affc4cf497e2168f1aafb278f51495ddd05b/pkg/nettools/nettools_test.go#L568)):*
> ```Go
> 			if err = netlink.AddrAdd(origContVeths[1], parseAddr("192.168.37.8/16")); err != nil {
> 				log.Panicf("failed to add addr for origContVeth1: %v", err)
> 			}
> ```

my idea was to replace this with a for loop to make it twice shorter ;)

---

*[pkg/nettools/nettools_test.go, line 578 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/533#-L0iXLfJq-prslf4Wl-m:-L0iXLfKitUHhCCju3Qf:bfqul6u) ([raw file](https://github.com/mirantis/virtlet/blob/8713affc4cf497e2168f1aafb278f51495ddd05b/pkg/nettools/nettools_test.go#L578)):*
> ```Go
> 			})
> 
> 			toRun(contNS, []netlink.Link{origContVeths[0], origContVeths[1]})
> ```

origContVeths[:]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/533)*

**Comment by jellonek** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/nettools/nettools_test.go, line 568 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/533#-L0iXOSc9UtW3-GFcMBU:-L0ia6vkGK1SjN2faknA:b-sb2s3r) ([raw file](https://github.com/mirantis/virtlet/blob/8713affc4cf497e2168f1aafb278f51495ddd05b/pkg/nettools/nettools_test.go#L568)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

my idea was to replace this with a for loop to make it twice shorter ;)
</blockquote></details>

Done, but IMO previous version, even when less compact, was easier to read/understand. Now it's more procedural.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/533)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/nettools/nettools_test.go, line 568 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/533#-L0iXOSc9UtW3-GFcMBU:-L0icxm5t-EIe7hHmI8J:bom4chu) ([raw file](https://github.com/mirantis/virtlet/blob/8713affc4cf497e2168f1aafb278f51495ddd05b/pkg/nettools/nettools_test.go#L568)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Done, but IMO previous version, even when less compact, was easier to read/understand. Now it's more procedural.
</blockquote></details>

Well, I thought it looked a bit like unrolled loop. Ok, let's keep it this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/533#-:-L0id9IjukbTmQxtGkjm:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/533#-:-L0ip637i5kwwVMmdObS:bnfp4nl)*

**Pull request merged**
