### PR TITLE
[WIP] vendor: Introduce vndr

### PR DESCRIPTION
**Pull request by nhlfr**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/72)

### CODE REVIEW

**Comment by jellonek** [comment]
This would require git clone of kubernetes on each build of docker container, so testing changes locally will be extremely painful for me, so I'm against this change.

**Comment by jellonek** [comment]
Ups, missclick for close instead of "comment".

**Comment by nhlfr** [comment]
It seems that @zefciu has a very good progress on using vlide with gitignored `vendor/`.

**Comment by pigmej** [comment]
https://github.com/Mirantis/k8s-AppController/pull/93 that's what @nhlfr meant.

**Pull request closed without merging**
