### PR TITLE
Use k8s 1.8 by default

### PR DESCRIPTION
**Pull request by ivan4th**
Compatibility with 1.7 is still kept

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/511)

### CODE REVIEW

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/511#-:-Kzd5IlCNJeyeaT892pA:bnfp4nl)*

**Comment by pigmej** [comment]
Starting from k8s 1.8 init containers have to be defined in PodSpec not in annotations. Therefore image-server is no longer working.

Therefore @ivan4th  examples/image-server.yaml needs to be fixed too. 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/511#-:-KzdaF1ezNfji9U0jdNu:bm532mz)*

**Comment by ivan4th** [comment]
@jnowak I've removed image-server as it's not really used by the demo.

---

Review status: 5 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/511#-:-KzdzfLrtPY7VwzNE8Ew:b-f1yohc)*

**Comment by jellonek** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/architecture.md, line 16 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/511#-Kze0U4R1QP7OnnNAPoK:-Kze0U4R1QP7OnnNAPoL:b4mt79d) ([raw file](https://github.com/mirantis/virtlet/blob/02c23931124590eeedbe6aeb92ad466a75c4c246/docs/architecture.md#L16)):*
> ```Markdown
> 
> In addition to the above, our example setup includes
> [CRI proxy](../cmd/criproxy) which provides the possibility to mix
> ```

Broken url. Can be also fixed.

---

*[examples/README.md, line 1 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/511#-Kze0jS2lEdqXufI84xQ:-Kze0jS2lEdqXufI84xR:b-xflcsr) ([raw file](https://github.com/mirantis/virtlet/blob/02c23931124590eeedbe6aeb92ad466a75c4c246/examples/README.md#L1)):*
> ```Markdown
> # Virtlet image server and pod example
> ```

Title needs update.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/511)*

**Comment by ivan4th** [comment]
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/architecture.md, line 16 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/511#-Kze0U4R1QP7OnnNAPoK:-Kze33DQg7NcYydfxXhN:b-oid1h8) ([raw file](https://github.com/mirantis/virtlet/blob/02c23931124590eeedbe6aeb92ad466a75c4c246/docs/architecture.md#L16)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Broken url. Can be also fixed.
</blockquote></details>

Done. Also I'm preparing another PR that will fix update other CRI proxy links and remove CRI proxy docs that now belong to another repo.

---

*[examples/README.md, line 1 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/511#-Kze0jS2lEdqXufI84xQ:-Kze3BUYVE6AGs1kPkh8:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/02c23931124590eeedbe6aeb92ad466a75c4c246/examples/README.md#L1)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Title needs update.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/511)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/511#-:-Kze3nopQmeUWTgl6PW5:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm: 

tested demo.sh :)

---

Reviewed 7 of 9 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/511#-:-KzfLclym9fNtpgVb1KV:bb8ncgf)*

**Comment by miha-plesko** [comment]
Ehm, ehm, we were using the image-server quite often when deploying the unikernels. Is there any other way to inject the VM image in the cluster other than uploading to the S3 and fetching it from there?

**Comment by ivan4th** [comment]
Hmm, sorry, we didn't know you use it. We can restore it as an example if necessary, just need to fix `initContainer` syntax. But basically you can use anything, e.g. `python -mSimpleHTTPServer` + appropriate image translations (see `deploy/images.yaml` and how it's used in demo.sh)

**Comment by miha-plesko** [comment]
Ok, let me try with simpleserver, I'll let you know if it works.

**Pull request merged**
