### PR TITLE
[docs] [update notes] March, 8-21

### PR DESCRIPTION
**Pull request by ologvinova**
[ci skip]

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/638)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/update-notes/Q1-18-03-21.md, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/638#-L8CNVFRzzV6709zlFP3:-L8CNVFSSUnTvdw7mOKW:b-pbk8wm) ([raw file](https://github.com/mirantis/virtlet/blob/071973ba2011bc0a7daa6bb60db34bd8c26a572a/docs/update-notes/Q1-18-03-21.md#L17)):*
> ```Markdown
> * Fixed loading of the `ebtables` module on non-Ubuntu systems.
> * Fixed handling of the HTTP errors during image pulls.
> * Added support for libvirt v3.7.0.
> ```

It's not exactly "support" as libvirt is a part of standard Virtlet container. Virtlet doesn't officially support using external libvirt or anything like this (i.e. no such setups are documented or recommended atm). Perhaps just "Updated libvirt to 3.7.0"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/638)*

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/update-notes/Q1-18-03-21.md, line 15 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/638#-L8CO6L-ts3c-D0mD3Qt:-L8CO6L-ts3c-D0mD3Qu:b-kafuum) ([raw file](https://github.com/mirantis/virtlet/blob/071973ba2011bc0a7daa6bb60db34bd8c26a572a/docs/update-notes/Q1-18-03-21.md#L15)):*
> ```Markdown
> * Fixed the CNI error handling.
> * Fixed the CNI teardown.
> * Fixed loading of the `ebtables` module on non-Ubuntu systems.
> ```

`ebtables` kernel module

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/638)*

**Comment by ologvinova** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/update-notes/Q1-18-03-21.md, line 15 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/638#-L8CO6L-ts3c-D0mD3Qt:-L8CONzBtwT1pwt5xlyJ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/071973ba2011bc0a7daa6bb60db34bd8c26a572a/docs/update-notes/Q1-18-03-21.md#L15)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

`ebtables` kernel module
</blockquote></details>

Done.

---

*[docs/update-notes/Q1-18-03-21.md, line 17 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/638#-L8CNVFRzzV6709zlFP3:-L8COIZ4gMTl445eMz1g:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/071973ba2011bc0a7daa6bb60db34bd8c26a572a/docs/update-notes/Q1-18-03-21.md#L17)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

It's not exactly "support" as libvirt is a part of standard Virtlet container. Virtlet doesn't officially support using external libvirt or anything like this (i.e. no such setups are documented or recommended atm). Perhaps just "Updated libvirt to 3.7.0"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/638)*

**Comment by ivan4th** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/638)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/638#-:-L8COp3dV-kQI5iQDGng:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/638#-:-L8CPPSP5O0YcCVnbvFD:bnfp4nl)*

**Pull request merged**
