### PR TITLE
Sriov support in virtlet

### PR DESCRIPTION
**Pull request by jellonek**
There were only 2 minor conflicts during the merge of master to this branch, so all thins should work correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/537)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r3, 3 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/537#-:-L0o7i3hbukNEEGolGJl:bnfp4nl)*

**Comment by ivan4th** [comment]
Pls rename the PR to "SR-IOV support in Virtlet"

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 106 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0ovKagAS9zln0Vin18:-L0ovKagAS9zln0Vin19:b-1t0i1) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/cmd/vmwrapper/vmwrapper.go#L106)):*
> ```Go
> 	vmwrapper_setns(my_pid, target_pid, CLONE_NEWIPC, "ipc");
> 
> 	// remount /sys for new netns
> ```

for the new netns

---

*[cmd/vmwrapper/vmwrapper.go, line 112 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0ovO7WnWxI80fU9tNB:-L0ovO7WnWxI80fU9tNC:bcfhxs7) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/cmd/vmwrapper/vmwrapper.go#L112)):*
> ```Go
> 		vmwrapper_perr("mount()");
> 
> 	// permanently drop privs if SR-IOV support is not enabled
> ```

// Permanently drop privs unless not to do so.
// Currently we don't drop privs when SR-IOV support is enabled
// because of an unresolved emulator permission problem.

---

*[cmd/vmwrapper/vmwrapper.go, line 148 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0ovnoywBvYC5dOxQ0Y:-L0ovnoywBvYC5dOxQ0Z:b-y0mpyo) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/cmd/vmwrapper/vmwrapper.go#L148)):*
> ```Go
> 	}
> 	return lastUsed
> }
> ```

I'm not sure we should do this by examining  the command line. As of now, domain XML that's has everything populated by libvirt with all the PCI addresses is retieved back after the domain is defined: https://github.com/Mirantis/virtlet/blob/70bf9d749ebca6db67dfd6d689c618330a7c3cd7/pkg/libvirttools/virtualization.go#L320 You can extract PCI address info from there and then pass it to vmwrapper using env vars.

---

*[cmd/vmwrapper/vmwrapper.go, line 245 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0owqb8K6GDwbRxnecp:-L0owqb8K6GDwbRxnecq:b-gx6jn0) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/cmd/vmwrapper/vmwrapper.go#L245)):*
> ```Go
> 	}
> 
> 	// below log hides any possible error in returned by libvirt virError
> ```

I don't quite understand what's happening there... Do you mean this?
// this Infof() call makes the emulator output unparseable by libvirt,
// thus causing it to miss the error output from qemu

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/537#-:-L0ovFNUCmJHDsCFvZmu:bymt99c)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/nettools/nettools.go, line 430 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0oxZc_rBVgK5D23QPh:-L0oxZc_rBVgK5D23QPi:bdcedkx) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/pkg/nettools/nettools.go#L430)):*
> ```Go
> 	var links []netlink.Link
> 	for _, iface := range interfaces {
> 		// if Sandbox is empty interface is on host, not in container netns
> ```

// empty Sandbox means this interface belongs to the host network namespace, so we skip it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/537)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 245 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0owqb8K6GDwbRxnecp:-L0oyn1vIAc0Kquhv41S:b-qwamds) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/cmd/vmwrapper/vmwrapper.go#L245)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I don't quite understand what's happening there... Do you mean this?
// this Infof() call makes the emulator output unparseable by libvirt,
// thus causing it to miss the error output from qemu
</blockquote></details>

This info was logged every time and it was filling whole buffer which libvirt has for description of error message. There was not even place for whole that line.
So when there was real error on qemu side and libvirt was trying to return it - this message filled whole error buffer and output of qemu with real error message could not be visible in VirError passed back to virtlet.
If it's still unclear - i'll try to reproduce and find an example of such situation - but as easy thing you can put there any incorrect qemu parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/537)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/vmwrapper/vmwrapper.go, line 245 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0owqb8K6GDwbRxnecp:-L0x2uHXMXM8e66uO7Hr:bnkknas) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/cmd/vmwrapper/vmwrapper.go#L245)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This info was logged every time and it was filling whole buffer which libvirt has for description of error message. There was not even place for whole that line.
So when there was real error on qemu side and libvirt was trying to return it - this message filled whole error buffer and output of qemu with real error message could not be visible in VirError passed back to virtlet.
If it's still unclear - i'll try to reproduce and find an example of such situation - but as easy thing you can put there any incorrect qemu parameter.
</blockquote></details>

ok then let's write it as // the following glog call makes libvirt unable to parse the error output

---

*[pkg/nettools/nettools.go, line 619 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0x4UFgaZmMdIACX2FX:-L0x4UFgaZmMdIACX2FY:b-vtdfka) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/pkg/nettools/nettools.go#L619)):*
> ```Go
> 	PCIAddresses []string
> 	// InterfaceNames contains a list of interfaces names for sr-iov interfaces
> 	InterfaceNames []string
> ```

I don't insist on doing it right now, but given how many parallel slices we have, maybe we should refactor this to use a slice of some kind of `NetworkDevice` struct? May probably do it in a followup

---

*[pkg/nettools/nettools.go, line 665 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0x3K4Bmamu7PnyiJXL:-L0x3K4Bmamu7PnyiJXM:bm1mpnz) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/pkg/nettools/nettools.go#L665)):*
> ```Go
> }
> 
> func writeStringToFile(s, path string, mode os.FileMode) error {
> ```

please use `ioutil.WriteFile(path, []byte(s), mode)` instead of this func

---

*[pkg/nettools/nettools.go, line 699 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0x3Z6HGPsYIaFk3otg:-L0x3Z6HGPsYIaFk3oth:b-ab9bex) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/pkg/nettools/nettools.go#L699)):*
> ```Go
> // Each bridge gets assigned a link-local address to be used
> // for dhcp server.
> // For SR-IOV VFs this function only prepares device to pass it to VM.
> ```

In case of SR-IOV VFs this function only sets up a device to be passed to VM.

---

*[pkg/nettools/nettools.go, line 1035 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0x3qDS2jbck721prRB:-L0x3qDS2jbck721prRC:bqnh737) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/pkg/nettools/nettools.go#L1035)):*
> ```Go
> 			return fmt.Errorf("can't move link %q to netns %q: %v", csn.InterfaceNames[i], netns.Path(), err)
> 		}
> 		netns.Do(func(ns.NetNS) error {
> ```

please don't swallow the error returned by `netns.Do()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/537)*

**Comment by ivan4th** [comment]
Please fix the comments in a followup PR.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/537#-:-L0y8AIpaHFptNPwlQWk:bdd47gx)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/537#-:-L0y8EmeQ6XSzVSAz_Qx:bnfp4nl)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[cmd/vmwrapper/vmwrapper.go, line 106 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0ovKagAS9zln0Vin18:-L0yJwSyPRKJbADyNdLw:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/cmd/vmwrapper/vmwrapper.go#L106)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

for the new netns
</blockquote></details>

Done.

---

*[cmd/vmwrapper/vmwrapper.go, line 112 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0ovO7WnWxI80fU9tNB:-L0yJwAokLWWbyyHEI8F:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/cmd/vmwrapper/vmwrapper.go#L112)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

// Permanently drop privs unless not to do so.
// Currently we don't drop privs when SR-IOV support is enabled
// because of an unresolved emulator permission problem.
</blockquote></details>

Done.

---

*[cmd/vmwrapper/vmwrapper.go, line 148 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0ovnoywBvYC5dOxQ0Y:-L0yJwv6pnxhSuQSbraq:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/cmd/vmwrapper/vmwrapper.go#L148)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'm not sure we should do this by examining  the command line. As of now, domain XML that's has everything populated by libvirt with all the PCI addresses is retieved back after the domain is defined: https://github.com/Mirantis/virtlet/blob/70bf9d749ebca6db67dfd6d689c618330a7c3cd7/pkg/libvirttools/virtualization.go#L320 You can extract PCI address info from there and then pass it to vmwrapper using env vars.
</blockquote></details>

Done.

---

*[cmd/vmwrapper/vmwrapper.go, line 245 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0owqb8K6GDwbRxnecp:-L0yJ9DH-EiWY1EhhwIG:b5ucqy9) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/cmd/vmwrapper/vmwrapper.go#L245)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

ok then let's write it as // the following glog call makes libvirt unable to parse the error output
</blockquote></details>

it's not the point. libvirt is not interpreting any error output. if qemu exits with status other than 0 - libvirt tries gathers all output and encloses it in own error - but has a buffer for that with limit for only 1024 chars. constructed in such way `virError` then is passed back to virtlet, but it can not even contain full outputed in this glog line cmdline - because it longer than 1024 chars, so any error returned by qemu to std{out,err} after this line will not be included in `virError` object.

---

*[pkg/nettools/nettools.go, line 430 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0oxZc_rBVgK5D23QPh:-L0yJ4HYjvElnsScFD7-:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/pkg/nettools/nettools.go#L430)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

// empty Sandbox means this interface belongs to the host network namespace, so we skip it
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 619 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0x4UFgaZmMdIACX2FX:-L0yGF8d4idEI2_cziPF:b-3pm8vp) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/pkg/nettools/nettools.go#L619)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I don't insist on doing it right now, but given how many parallel slices we have, maybe we should refactor this to use a slice of some kind of `NetworkDevice` struct? May probably do it in a followup
</blockquote></details>

Yes, I planned to do that. Will do that in follow up PR. Not this closest on which i'm working right now, but i hope that it will be done quite soon.

---

*[pkg/nettools/nettools.go, line 665 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0x3K4Bmamu7PnyiJXL:-L0yJzLTCa3JL7t9FyLy:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/pkg/nettools/nettools.go#L665)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

please use `ioutil.WriteFile(path, []byte(s), mode)` instead of this func
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 699 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0x3Z6HGPsYIaFk3otg:-L0yK049Oa-EfqhvMwtz:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/pkg/nettools/nettools.go#L699)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

In case of SR-IOV VFs this function only sets up a device to be passed to VM.
</blockquote></details>

Done.

---

*[pkg/nettools/nettools.go, line 1035 at r5](https://reviewable.io:443/reviews/mirantis/virtlet/537#-L0x3qDS2jbck721prRB:-L0yK3GWpuRjxxI43OoP:b-z0r2qj) ([raw file](https://github.com/mirantis/virtlet/blob/b522eff4860302834d392c098a9fd8c3bf7409c4/pkg/nettools/nettools.go#L1035)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

please don't swallow the error returned by `netns.Do()`
</blockquote></details>

Done. But that needs additional verification on hardware which i will do asap.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/537)*

**Pull request merged**
