### PR TITLE
Fix multiple volume mounting in Virtlet

### PR DESCRIPTION
**Pull request by ivan4th**
- [X] add WriteImage phase to VMVolume lifecycle (that can access full domain def retrieved from libvirt)
- [x] use `/dev/disk/by-path` instead of `/dev/sdX` for mounting
- [x] use `/dev/disk/by-path` instead of `/dev/vdX` for mounting
- [x] support mounting on udev-less systems / systems w/o proper userdata support (e.g. CirrOS or VyOS)
- [x] add e2e test that verifies the multiple-volume case
- [x] add documentation notes

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/520)

### CODE REVIEW

**Comment by pigmej** [comment]
Review status: 0 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/cloud-init-data-generation.md, line 250 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-jUJ66HwY3aCcOh1Rq:-L-jUJ66HwY3aCcOh1Rr:b-34pm02) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/docs/cloud-init-data-generation.md#L250)):*
> ```Markdown
> `VirtletSSHKeySource` unless it is set to overwrite them by `VirtletCloudInitUserData: "true"`.
> 
> ## Workarounds for volume mounting
> ```

I think it should be somewhere in more general doc too. It's kinda important message. Maybe it's time to create dedicated "limitations/workaround" section? What do you think guys?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/520)*

**Comment by jellonek** [comment]
Reviewed 32 of 33 files at r1.
Review status: 32 of 33 files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/cloud-init-data-generation.md, line 250 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rNmMw9MwWpgirmHxA:-L-rNmMw9MwWpgirmHxB:b-wam0os) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/docs/cloud-init-data-generation.md#L250)):*
> ```Markdown
> `VirtletSSHKeySource` unless it is set to overwrite them by `VirtletCloudInitUserData: "true"`.
> 
> ## Workarounds for volume mounting
> ```

Please change that to:
`## <a name="workarounds"></a> Workaroudns for volume mounting`
and than you can use it above as a link as e.g. `see [Workarounds](#workarounds)`.

---

*[docs/cloud-init-data-generation.md, line 250 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-jUJ66HwY3aCcOh1Rq:-L-rPLqReH1HmF0tXByf:b-3amv6s) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/docs/cloud-init-data-generation.md#L250)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

I think it should be somewhere in more general doc too. It's kinda important message. Maybe it's time to create dedicated "limitations/workaround" section? What do you think guys?
</blockquote></details>

@jnowak: I don't think so. It's limitation only for very specialized images which do not support a "standard" way of cloud based configuration which is cloud-init, so imo note there (ok, with some minor additional link to it somewhere in main README.md) should be enough.

---

*[examples/cirros-vm.yaml, line 19 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rPtIS-sJKX0v0Ecml:-L-rPtIS-sJKX0v0Ecmm:b-i3u2fy) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/examples/cirros-vm.yaml#L19)):*
> ```YAML
>       ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJEcFDXEK2ZbX0ZLS1EIYFZRbDAcRfuVjpstSc0De8+sV1aiu+dePxdkuDRwqFtCyk6dEZkssjOkBXtri00MECLkir6FcH3kKOJtbJ6vy3uaJc9w1ERo+wyl6SkAh/+JTJkp7QRXj8oylW5E20LsbnA/dIwWzAF51PPwF7A7FtNg9DnwPqMkxFo1Th/buOMKbP5ZA1mmNNtmzbMpMfJATvVyiv3ccsSJKOiyQr6UG+j7sc/7jMVz5Xk34Vd0l8GwcB0334MchHckmqDB142h/NCWTr8oLakDNvkfC1YneAfAO41hDkUbxPtVBG5M/o7P4fxoqiHEX+ZLfRxDtHB53 me@localhost
>     # cloud-init user data
>     # @virtlet-mount-script@ is replaced with commands that mount
> ```

Imo we should extract that to separate example file (and even we should remove more from this file) to keep this one as simple as it could be possible.
The same imo should be done in ubuntu vm example where mounts example should be moved to a separate example yaml file.

---

*[pkg/libvirttools/ceph_flexvolume.go, line 52 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rQKU-zyCQF8LmVybq:-L-rQKU-zyCQF8LmVybr:bb6mt9b) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/pkg/libvirttools/ceph_flexvolume.go#L52)):*
> ```Go
> }
> 
> var _ VMVolume = &cephVolume{}
> ```

:+1:

---

*[pkg/libvirttools/disklist.go, line 49 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rRzFo9DIYYtjJ3DNW:-L-rRzFo9DIYYtjJ3DNX:b-w07a1w) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/pkg/libvirttools/disklist.go#L49)):*
> ```Go
> }
> 
> // newDiskSet creates a diskList for the specified VMConfig, volume
> ```

looks like func has now other name than used as a first word in docstring

---

*[pkg/libvirttools/disklist.go, line 73 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rRmNu_pey9VdpMAs-:-L-rRmNu_pey9VdpMAs0:b-w07a1w) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/pkg/libvirttools/disklist.go#L73)):*
> ```Go
> }
> 
> // setupVolumes performs the setup procedure on each volume in the
> ```

looks like func has now other name than used as a first word in docstring

---

*[pkg/libvirttools/disklist.go, line 93 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rS4ty0sKsejnglO2B:-L-rS4ty0sKsejnglO2C:b-w07a1w) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/pkg/libvirttools/disklist.go#L93)):*
> ```Go
> }
> 
> // writeVolumeImages writes images for volumes that are based on
> ```

looks like func has now other name than used as a first word in docstring

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/520)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 33 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/520#-:-L09rXH9OX7b8UrG9c2o:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/cloud-init-data-generation.md, line 250 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-jUJ66HwY3aCcOh1Rq:-L09soYukLT0jXlFPgeG:bmtchsl) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/docs/cloud-init-data-generation.md#L250)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

@jnowak: I don't think so. It's limitation only for very specialized images which do not support a "standard" way of cloud based configuration which is cloud-init, so imo note there (ok, with some minor additional link to it somewhere in main README.md) should be enough.
</blockquote></details>

I updated 'volumes.md'

---

*[docs/cloud-init-data-generation.md, line 250 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rNmMw9MwWpgirmHxA:-L09ssaMKptWdhlSkhVY:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/docs/cloud-init-data-generation.md#L250)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Please change that to:
`## <a name="workarounds"></a> Workaroudns for volume mounting`
and than you can use it above as a link as e.g. `see [Workarounds](#workarounds)`.
</blockquote></details>

Done.

---

*[pkg/libvirttools/disklist.go, line 49 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rRzFo9DIYYtjJ3DNW:-L09t1uHK1UEipevsDcC:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/pkg/libvirttools/disklist.go#L49)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

looks like func has now other name than used as a first word in docstring
</blockquote></details>

Done.

---

*[pkg/libvirttools/disklist.go, line 73 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rRmNu_pey9VdpMAs-:-L09t2fswfjM1AXA8uNx:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/pkg/libvirttools/disklist.go#L73)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

looks like func has now other name than used as a first word in docstring
</blockquote></details>

Done.

---

*[pkg/libvirttools/disklist.go, line 93 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rS4ty0sKsejnglO2B:-L09t3CyLA9KIcN1EhEG:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/pkg/libvirttools/disklist.go#L93)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

looks like func has now other name than used as a first word in docstring
</blockquote></details>

Done.

---

*[examples/cirros-vm.yaml, line 19 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/520#-L-rPtIS-sJKX0v0Ecml:-L09t4Zx_954ObIRMNb4:bxasa1q) ([raw file](https://github.com/mirantis/virtlet/blob/7857e6feed948874f0bbe0c16b87e99e6ad70c18/examples/cirros-vm.yaml#L19)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Imo we should extract that to separate example file (and even we should remove more from this file) to keep this one as simple as it could be possible.
The same imo should be done in ubuntu vm example where mounts example should be moved to a separate example yaml file.
</blockquote></details>

Made a separate example for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/520)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 30 of 33 files at r1, 3 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/520#-:-L0AL1BiNjMT4NSXAr1E:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/520#-:-L0ANUBta9NYcLpe7oDB:bnfp4nl)*

**Pull request merged**
