### PR TITLE
Improve info about virtlet installation validation

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/538)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[deploy/real-cluster.md, line 80 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y8NbuV4exAo0cdUjv:-L0y8NbuV4exAo0cdUjw:b-1ksrpk) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L80)):*
> ```Markdown
> Escape character is ^]
> 
> ### Validation of ssh access to pod
> ```

Verifying ssh access to a VM pod

---

*[deploy/real-cluster.md, line 97 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y8SU7nxK1cfU0HJHj:-L0y8SU7nxK1cfU0HJHk:b-smqsib) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L97)):*
> ```Markdown
> ```
> 
> ### Validation of pod access to cluster services
> ```

Verifying accessing services from a VM pod

---

*[deploy/real-cluster.md, line 101 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y8YzQVP-jnrrtSiRE:-L0y8YzQVP-jnrrtSiRF:bqci878) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L101)):*
> ```Markdown
> After connecting to VM using one of above method you can validate VM access to
> cluster services. Use below command to display an IP address of kubernetes
> api service:
> ```

After connecting to the VM using one of the above methods you can check access from the VM to cluster services. To check DNS resolution of cluster services, use the following command:

---

*[deploy/real-cluster.md, line 107 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y8o-jpgYUSKh9FTtI:-L0y8o-jpgYUSKh9FTtJ:b-fbpsen) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L107)):*
> ```Markdown
> ```
> 
> Use below command to try to access this service:
> ```

The following command may be used to check service connectivity (note that it'll give you an authentication error):

---

*[deploy/real-cluster.md, line 113 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y9-1cFlfYDGXMdt2n:-L0y9-1cFlfYDGXMdt2o:bevfn5r) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L113)):*
> ```Markdown
> ```
> 
> Using the same method you can verify access to any service from internet, e.x.:
> ```

You can also verify Internet access from the VM:

---

*[deploy/real-cluster.md, line 116 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y94zCJBkw0JnkaRKQ:-L0y94zDZNJHH6rKbEM1:b-dtpdr2) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L116)):*
> ```Markdown
> 
> ```
> curl -k https://google.com
> ```

Also add `ping -c 1 8.8.8.8`

---

*[deploy/real-cluster.md, line 117 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y92dP_vSQ5A4hG-Lf:-L0y92dP_vSQ5A4hG-Lg:b-8un8s3) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L117)):*
> ```Markdown
> ```
> curl -k https://google.com
> ```
> ```

If you have Kubernetes Dashboard installed (it's present in kubeadm-dind-cluster installations for example), you can check dashboard access using this command:
```
curl http://kubernetes-dashboard.kube-system.svc.cluster.local
```
This should display some html from the dashboard's main page.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/538)*

**Comment by jellonek** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[deploy/real-cluster.md, line 80 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y8NbuV4exAo0cdUjv:-L0yCPJMZhJ-NQe_1fMM:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L80)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Verifying ssh access to a VM pod
</blockquote></details>

Done.

---

*[deploy/real-cluster.md, line 101 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y8YzQVP-jnrrtSiRE:-L0yCQ8s1Bh9L5FiwZt6:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L101)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

After connecting to the VM using one of the above methods you can check access from the VM to cluster services. To check DNS resolution of cluster services, use the following command:
</blockquote></details>

Done.

---

*[deploy/real-cluster.md, line 107 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y8o-jpgYUSKh9FTtI:-L0yCQeTWZiAsUogIYyL:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L107)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

The following command may be used to check service connectivity (note that it'll give you an authentication error):
</blockquote></details>

Done.

---

*[deploy/real-cluster.md, line 113 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y9-1cFlfYDGXMdt2n:-L0yCRvuxN3Rs_U8cLgA:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L113)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

You can also verify Internet access from the VM:
</blockquote></details>

Done.

---

*[deploy/real-cluster.md, line 116 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y94zCJBkw0JnkaRKQ:-L0yCTFXQfPzYCpZKJdo:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L116)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Also add `ping -c 1 8.8.8.8`
</blockquote></details>

Done.

---

*[deploy/real-cluster.md, line 117 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y92dP_vSQ5A4hG-Lf:-L0yCZDhOlIY7cNgM2IT:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L117)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

If you have Kubernetes Dashboard installed (it's present in kubeadm-dind-cluster installations for example), you can check dashboard access using this command:
```
curl http://kubernetes-dashboard.kube-system.svc.cluster.local
```
This should display some html from the dashboard's main page.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/538)*

**Comment by ivan4th** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/real-cluster.md, line 55 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0yR37PFryE0OewiujU:-L0yR37PFryE0OewiujV:bm0hyqd) ([raw file](https://github.com/mirantis/virtlet/blob/246f76428a4917ab6a1d87dabc57ed1e7e753525/deploy/real-cluster.md#L55)):*
> ```Markdown
> ## Testing the installation
> 
> ### Validation of basic pod starting
> ```

Sorry, missed this one. Should be "Checking basic pod startup"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/538)*

**Comment by jellonek** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[deploy/real-cluster.md, line 97 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0y8SU7nxK1cfU0HJHj:-L0yRqWIOTWAfwM1YS58:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/4a24c1a6080da63240939c48a57360c7090c299d/deploy/real-cluster.md#L97)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Verifying accessing services from a VM pod
</blockquote></details>

Done.

---

*[deploy/real-cluster.md, line 55 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/538#-L0yR37PFryE0OewiujU:-L0yRrJD_T9iduVQ_42w:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/246f76428a4917ab6a1d87dabc57ed1e7e753525/deploy/real-cluster.md#L55)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Sorry, missed this one. Should be "Checking basic pod startup"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/538)*

**Comment by ivan4th** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/538)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/538#-:-L0ySJlHXefIPAtG0aTX:bnfp4nl)*

**Comment by ologvinova** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/538#-:-L0yrP2zoN48_zVzKlMC:bnfp4nl)*

**Pull request merged**
