### PR TITLE
Add instructions for deploying on real clusters

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/269)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[deploy/real-cluster.md, line 3 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjEWT2nMQdIds3G1XbH:-KjEWT2nMQdIds3G1XbI:brwk555) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L3)):*
> ```Markdown
> # Installing Virtlet on a real cluster
> 
> For Virtlet and CRI proxy to work, there are the following prerequisites for the
> ```

For Virtlet and CRI proxy to work, on nodes which will run them the following prerequisites have to be fulfilled:

---

*[deploy/real-cluster.md, line 12 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjEW8M7p8NgN6-YWZGL:-KjEW8M7p8NgN6-YWZGM:bnbbnzx) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L12)):*
> ```Markdown
> the Virtlet DaemonSet.
> 
> The DaemonSet defaults to using CRI Proxy bootstrap, but the mode is
> ```

... but this mode ...

---

*[deploy/real-cluster.md, line 61 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjEYap2fGd67MyvL516:-KjEYap2fGd67MyvL517:bl9wwk1) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L61)):*
> ```Markdown
> CRI Proxy needs Kubelet config in JSON format to start its internal docker-shim server.
> You can obtain the config using the following commands on a machine with apiserver access
> (this requires `jq` utility which can be installed with `apt-get install jq` on Ubuntu):
> ```

s/on Ubuntu/on Debian derivatives or `dnf install jq` on RPM based systems/

---

*[deploy/real-cluster.md, line 75 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjEZKxEKNkvGYUMCib4:-KjEZKxEKNkvGYUMCib5:bnfr1le) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L75)):*
> ```Markdown
> Now you need to create a systemd unit that will start the CRI Proxy.
> Here we assume that kubelet is started via `kubelet.service` systemd
> unit.  Create a file named `/etc/systemd/system/criproxy.service` with
> ```

hmmm... command to create/edit such file would be `systemctl --force edit criproxy.service` - imo worth to mention.
Also double space before `Create` (it's quite common in english texts, but if it's there, it should be also used in rest of document, or even all of them).

---

*[deploy/real-cluster.md, line 104 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjE_LkoC-jeUE9YfL-V:-KjE_LkoC-jeUE9YfL-W:boshr6w) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L104)):*
> ```Markdown
> to make it use CRI Proxy:
> ```bash
> --experimental-cri --container-runtime=remote \
> ```

Is this correct? I'm not sure that `--experimental-cri` is needed.
https://github.com/kubernetes/community/pull/460/files is already merged.
Also this option is missing in https://kubernetes.io/docs/admin/kubelet/ and is set to "true" by default in https://github.com/kubernetes/kubernetes/blob/v1.6.2/cmd/kubelet/app/options/options.go#L253

---

*[deploy/real-cluster.md, line 117 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjEbA3jg_AI1HEOfTRg:-KjEbA3jg_AI1HEOfTRh:b2nreh6) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L117)):*
> ```Markdown
> ```ini
> [Service]
> Environment="KUBELET_EXTRA_ARGS=--experimental-cri --container-runtime=remote --container-runtime-endpoint=/run/criproxy.sock --image-service-endpoint=/run/criproxy.sock --enable-controller-attach-detach=false"
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/269)*

**Comment by ivan4th** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[deploy/real-cluster.md, line 3 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjEWT2nMQdIds3G1XbH:-KjEenwjk6C_BDeKbAwT:b-tapqbx) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L3)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

For Virtlet and CRI proxy to work, on nodes which will run them the following prerequisites have to be fulfilled:
</blockquote></details>

Fixed, although used a bit different wording

---

*[deploy/real-cluster.md, line 12 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjEW8M7p8NgN6-YWZGL:-KjEexV92TdMkfcLuu7Z:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L12)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

... but this mode ...
</blockquote></details>

Done.

---

*[deploy/real-cluster.md, line 61 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjEYap2fGd67MyvL516:-KjEeyM-kKNaCgtBzmKr:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L61)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

s/on Ubuntu/on Debian derivatives or `dnf install jq` on RPM based systems/
</blockquote></details>

Done.

---

*[deploy/real-cluster.md, line 75 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjEZKxEKNkvGYUMCib4:-KjEezCOExAEwnf6kzb6:bxrjdy1) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L75)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

hmmm... command to create/edit such file would be `systemctl --force edit criproxy.service` - imo worth to mention.
Also double space before `Create` (it's quite common in english texts, but if it's there, it should be also used in rest of document, or even all of them).
</blockquote></details>

Done. Note though that the document will be likely mostly used for writing playbooks, salt formulas etc. Direct editing is rather unlikely.

---

*[deploy/real-cluster.md, line 104 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjE_LkoC-jeUE9YfL-V:-KjEfBpGC_zi01B3LoqA:bze6r0p) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L104)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Is this correct? I'm not sure that `--experimental-cri` is needed.
https://github.com/kubernetes/community/pull/460/files is already merged.
Also this option is missing in https://kubernetes.io/docs/admin/kubelet/ and is set to "true" by default in https://github.com/kubernetes/kubernetes/blob/v1.6.2/cmd/kubelet/app/options/options.go#L253
</blockquote></details>

Fixed, thanks for spotted that. Copypasted too much from some older scripts :)

---

*[deploy/real-cluster.md, line 117 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/269#-KjEbA3jg_AI1HEOfTRg:-KjEfGoWiuD2idh0FW0F:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f80c4e3b084ac61443aba09397e6f3f67061d95/deploy/real-cluster.md#L117)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/269)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/269#-:-KjEjn7tHYSosbbtXiIu:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/269#-:-KjEmfYATYLwQy1sItmY:bnfp4nl)*

**Pull request merged**
