### PR TITLE
volumes: Add support for files as volumes

### LINKED ISSUE #342: Support passing /etc/hosts to VM
Now we have:
```
E0626 11:09:38.624505      47 cloudinit.go:187] Can't mount directory "/var/lib/kubelet/pods/edb18768-5a5f-11e7-bd62-02420ac00002/etc-hosts" to "/etc/hosts" inside the VM: can't get flexvolume uuid: can't read flexvolume data file "/
var/lib/kubelet/pods/edb18768-5a5f-11e7-bd62-02420ac00002/etc-hosts/virtlet-flexvolume.json": error reading json file "/var/lib/kubelet/pods/edb18768-5a5f-11e7-bd62-02420ac00002/etc-hosts/virtlet-flexvolume.json": open /var/lib/kubel
et/pods/edb18768-5a5f-11e7-bd62-02420ac00002/etc-hosts/virtlet-flexvolume.json: not a directory
```
... but this (like other mounts for regular file) can be added by extending `write_files` support, with note that this file will be only once copied into VM (if its image supports nocloud with `write_files`), so can not be used as communication method between containers on the same node.

Perfect example where this could be handy - mentioned above `/etc/hosts`.

Btw. IMO we should not treat above as an error in flex volume handling - this IMO should be not interpreted by flex volume driver, if there is no `flexvolume.json` file (same for config maps as volumes, or secrets as volumes).

### PR DESCRIPTION
**Pull request by jellonek**
closes #342

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/364)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/libvirttools/cloudinit.go, line 272 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoStb_ODr8pxGpcwzfd:-KoStb_ODr8pxGpcwzfe:b-q0ylvj) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L272)):*
> ```Go
> 		encodedContent := base64.StdEncoding.EncodeToString(content)
> 		var entries []interface{}
> 		return append(entries, map[string]interface{}{
> ```

why are you appending to nil slice here? maybe just return `[]map[string]interface{ ... }` (a slice of maps)

---

*[pkg/libvirttools/cloudinit.go, line 281 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoSss2vfdz1s1QF4Oxq:-KoSss2vfdz1s1QF4Oxr:bridjwc) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L281)):*
> ```Go
> }
> 
> func (m *WriteFilesManipulator) addFilesFor(suffix, permissions string) {
> ```

`AddFilesForVolumeType` maybe

---

*[pkg/libvirttools/cloudinit.go, line 285 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoSsMHszPjMcolSz5aA:-KoSsMHszPjMcolSz5aB:b-4fe5gm) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L285)):*
> ```Go
> 
> 	m.mountsIterator(func(path string) bool {
> 		return strings.Contains(path, filter)
> ```

Maybe some more precise check can be done here, as it's likely known how many path components are there after this plugin-specific name?

---

*[pkg/libvirttools/cloudinit.go, line 291 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoSs0VK42JQ0kwPfc4o:-KoSs0VK42JQ0kwPfc4p:b-9xvt5g) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L291)):*
> ```Go
> }
> 
> func (m *WriteFilesManipulator) mountsIterator(filter func(string) bool, entriesPreparator func(*VMMount) []interface{}) {
> ```

maybe `processMounts`? (an action)
`entriesPreparator` is a bit strange name, maybe just `generateEntries`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/364)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/libvirttools/cloudinit.go, line 272 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoStb_ODr8pxGpcwzfd:-KoSu1CB9dGhHkuGtcRG:b-1skrz4) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L272)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

why are you appending to nil slice here? maybe just return `[]map[string]interface{ ... }` (a slice of maps)
</blockquote></details>

Tried to do that  at first ;)
Return type would be then incorrect.
This is kinda workaround, because other way i would need there casting from `[]map[string]interface{}` to `[]interface{}`

---

*[pkg/libvirttools/cloudinit.go, line 281 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoSss2vfdz1s1QF4Oxq:-KoSwyk1Ph54Ux7LgER-:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L281)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`AddFilesForVolumeType` maybe
</blockquote></details>

Done.

---

*[pkg/libvirttools/cloudinit.go, line 285 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoSsMHszPjMcolSz5aA:-KoSxs3uXxyH0WjHek4x:b23732m) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L285)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Maybe some more precise check can be done here, as it's likely known how many path components are there after this plugin-specific name?
</blockquote></details>

Hmmm... It's the same filter as was used earlier. We can add there additional tests, but IMO that now it's unnecessary, can be done later, if actually current filter would not work as it should.

---

*[pkg/libvirttools/cloudinit.go, line 291 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoSs0VK42JQ0kwPfc4o:-KoSyWWgKOwU7CUazQ59:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L291)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe `processMounts`? (an action)
`entriesPreparator` is a bit strange name, maybe just `generateEntries`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/364)*

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/cloudinit.go, line 272 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoStb_ODr8pxGpcwzfd:-KoTBga652XXcU33gH-k:b-wuirx2) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L272)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Tried to do that  at first ;)
Return type would be then incorrect.
This is kinda workaround, because other way i would need there casting from `[]map[string]interface{}` to `[]interface{}`
</blockquote></details>

ok what if you use `[]interface{}{ map[string]interface{}{ "path": ... } }`

---

*[pkg/libvirttools/cloudinit.go, line 285 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoSsMHszPjMcolSz5aA:-KoTC60VUKdFIljrvTKu:b997h4d) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L285)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... It's the same filter as was used earlier. We can add there additional tests, but IMO that now it's unnecessary, can be done later, if actually current filter would not work as it should.
</blockquote></details>

well it may in theory fail if `volumes/kubernetes.io-XXX` is in the kubelet root path somehow. Which is, sure, highly unlikely, but still possible in some complicated situations...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/364)*

**Comment by jellonek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/cloudinit.go, line 272 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoStb_ODr8pxGpcwzfd:-KoTG5pZOKjhQcEg29BQ:bhlhaqk) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L272)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

ok what if you use `[]interface{}{ map[string]interface{}{ "path": ... } }`
</blockquote></details>

That works. Ok, done.

---

*[pkg/libvirttools/cloudinit.go, line 285 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoSsMHszPjMcolSz5aA:-KoTI3p80SNtKE64R_Vx:b7tfd0v) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L285)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

well it may in theory fail if `volumes/kubernetes.io-XXX` is in the kubelet root path somehow. Which is, sure, highly unlikely, but still possible in some complicated situations...
</blockquote></details>

Afair volume can not have `~` character in it (need to find that, but that's probably verified on kubelet side) so this will not be the case.
Anyway - imo we should not touch that before someone will have an issue with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/364)*

**Comment by ivan4th** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/libvirttools/cloudinit.go, line 285 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/364#-KoSsMHszPjMcolSz5aA:-KoTbFo17znZU-y_7VfK:b-uudih8) ([raw file](https://github.com/mirantis/virtlet/blob/7e0ac82737d96618bccad25296f91bf64e95c818/pkg/libvirttools/cloudinit.go#L285)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Afair volume can not have `~` character in it (need to find that, but that's probably verified on kubelet side) so this will not be the case.
Anyway - imo we should not touch that before someone will have an issue with that.
</blockquote></details>

ok, maybe I'm too paranoid about it. Let's keep it as is for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/364#-:-KoTbNMmgSnmaqHnG1q8:bnfp4nl)*

**Comment by pigmej** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/364)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/364#-:-KoTnzNMZOWJ5nIBlZcg:bnfp4nl)*

**Pull request merged**
