### PR TITLE
Fixed filtering for list requests from kubelet

### LINKED ISSUE #117: Fix filtering for get requests from kubelet
Container filtering was fixed a bit here to get rid of pod sync problem:
https://github.com/Mirantis/virtlet/pull/116
https://github.com/Mirantis/virtlet/pull/116/commits/22d4da7da40842777b823a57b82b7b5763cfa520
But that's insufficient, see for example
https://github.com/kubernetes-incubator/cri-o/blob/8d275cebb9988df2c834978c1c334682913cace1/server/container.go#L452
Also make sure that filtering other objects (pod sandboxes, images) works correctly, too.
(E.g. there's possibility we don't handle nil state in sandbox filter properly)
This part needs to get test coverage too, of course.

### PR DESCRIPTION
**Pull request by vefimova**
Fixes #117

This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/129)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/bolttools/sandbox.go, line 223 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmFWHXBrp4Y7lC6Ryf:-KXmFWHYjg38sckOcPXz:b-ss5r6k) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/sandbox.go#L223)):*
> ```Go
> 		}
> 		contIDs = make([]string, 0)
> 		err = json.Unmarshal(byteJsonContIDsList, &contIDs)
> ```

json? Why?
Simple string splitable by space or comma should be enough there. json seems to be too big overhead.

---

*[pkg/bolttools/utils.go, line 55 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmGmBC1bTCEl0jjFM8:-KXmGmBC1bTCEl0jjFM9:b-g6nkve) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L55)):*
> ```Go
> }
> 
> func RemoveElFromJsonArray(jsonArr []byte, toDelete string) ([]byte, error) {
> ```

Please do not operate in these 2 functions on `[]byte`s.
Please split this to "convert from []byte to []string", "add/remove on []string" ,  "convert from []string to []byte".

And again - instead using json - please use simple `strings.Split` and `strings.Join` using space or comma.

---

*[pkg/bolttools/utils.go, line 96 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmI9m23ZagdrnCvthM:-KXmI9m23ZagdrnCvthN:br5bi46) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L96)):*
> ```Go
> }
> 
> func dumpDB(t *testing.T, db *bolt.DB) error {
> ```

Wait a moment? Tests code in module?
Please extract this out of this file.

---

*[pkg/bolttools/utils.go, line 134 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmIrw93TOJgC_SEKoO:-KXmIrw93TOJgC_SEKoP:bjfwsol) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L134)):*
> ```Go
> 
> 	for i := 0; i < sandboxNum; i++ {
> 		name := "testName_" + strconv.Itoa(i)
> ```

Again - if this is needed by tests - this should not be in this file.

---

*[pkg/bolttools/utils.go, line 188 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmJ1Bq7LJFRN_0aW_p:-KXmJ1Bq7LJFRN_0aW_q:b1jkty3) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L188)):*
> ```Go
> }
> 
> func GetContainersConfig(sandboxConfigs []*kubeapi.PodSandboxConfig) ([]*ContainerTestConfigSet, error) {
> ```

Again test data...

---

*[pkg/bolttools/utils.go, line 210 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmJ51E6CSdOwGIpQg3:-KXmJ51E6CSdOwGIpQg4:b-rp8mxw) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L210)):*
> ```Go
> }
> 
> func SetUpBolt(t *testing.T, sandboxConfigs []*kubeapi.PodSandboxConfig, containerConfigs []*ContainerTestConfigSet) *BoltClient {
> ```

And again...

---

*[tests/integration/image_pull_test.go, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmJXOG0pcam7P7lMEo:-KXmJXOH5Knt_LYkuV6a:bb6mt9b) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/tests/integration/image_pull_test.go#L35)):*
> ```Go
> 	imageServiceClient := kubeapi.NewImageServiceClient(manager.conn)
> 
> 	imageSpec := &kubeapi.ImageSpec{Image: &imageCirrosUrl}
> ```

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/129)*

**Comment by ivan4th** [comment]
Please run ./test.sh to make sure that the tests pass. As of now test output looks like we got pod sync problem back :(

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/libvirttools/virtualization.go, line 438 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXoOzWaICbDEQQ6wfp3:-KXoOzWbSRDalo1C0epW:b-xd13dy) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/libvirttools/virtualization.go#L438)):*
> ```Go
> func filterContainer(container *kubeapi.Container, filter *kubeapi.ContainerFilter) bool {
> 	if filter != nil {
> 		if container.GetState() != filter.GetState() {
> ```

You're not handling filter.State == nil (i.e. 'any state') case here like the original code does. This is what brings pod sync problem back

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/129)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/libvirttools/virtualization.go, line 438 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXoOzWaICbDEQQ6wfp3:-KXoRNLmQvzR0zUA4Tty:bgcxt6p) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/libvirttools/virtualization.go#L438)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

You're not handling filter.State == nil (i.e. 'any state') case here like the original code does. This is what brings pod sync problem back
</blockquote></details>

I suggest reflecting the problem in tests because that bug hits us for the second time...

---

*[pkg/libvirttools/virtualization.go, line 514 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXoQh9_LV8MCWXaVNm2:-KXoQh9_LV8MCWXaVNm3:b-7ymvxy) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/libvirttools/virtualization.go#L514)):*
> ```Go
> 
> 			if filter.GetPodSandboxId() != "" {
> 				if container.GetPodSandboxId() != filter.GetPodSandboxId() {
> ```

single if with &&

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/129)*

**Comment by vefimova** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/bolttools/sandbox.go, line 223 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmFWHXBrp4Y7lC6Ryf:-KXomebnI4xx3gH3aDLO:b-wiwium) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/sandbox.go#L223)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

json? Why?
Simple string splitable by space or comma should be enough there. json seems to be too big overhead.
</blockquote></details>

Well, because I decided it's mkore universal approach if we'll need to store more in further, and also we already store labels and annotations as jsons.

---

*[pkg/bolttools/utils.go, line 55 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmGmBC1bTCEl0jjFM8:-KXooCI_Lw34oaSx-PcO:b-rhh440) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L55)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Please do not operate in these 2 functions on `[]byte`s.
Please split this to "convert from []byte to []string", "add/remove on []string" ,  "convert from []string to []byte".

And again - instead using json - please use simple `strings.Split` and `strings.Join` using space or comma.
</blockquote></details>

Well, it's because of bolt works with keys and values as []byte, after unmarshal you're working with string array, and then marshal to json back and return []byte, again because bolt works with this type.

---

*[pkg/bolttools/utils.go, line 96 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmI9m23ZagdrnCvthM:-KXomQk_3s-5Sa0KPLEh:b-gugmm8) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L96)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Wait a moment? Tests code in module?
Please extract this out of this file.
</blockquote></details>

yeah, will move it to utils_tests.go

---

*[pkg/bolttools/utils.go, line 134 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmIrw93TOJgC_SEKoO:-KXomX6HCUOhGeHisHbz:b-ho0aiu) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L134)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Again - if this is needed by tests - this should not be in this file.
</blockquote></details>

the same

---

*[pkg/bolttools/utils.go, line 188 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmJ1Bq7LJFRN_0aW_p:-KXomZj8iHQ4Q1oUDmic:b-ho0aiu) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L188)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Again test data...
</blockquote></details>

the same

---

*[pkg/bolttools/utils.go, line 210 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmJ51E6CSdOwGIpQg3:-KXom_WFUwWD9LDN-NJf:b-ho0aiu) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L210)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

And again...
</blockquote></details>

the same

---

*[pkg/libvirttools/virtualization.go, line 438 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXoOzWaICbDEQQ6wfp3:-KXopEeZ8aiEKLsm2IMT:b-xpdvha) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/libvirttools/virtualization.go#L438)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I suggest reflecting the problem in tests because that bug hits us for the second time...
</blockquote></details>

There're Get* functions in CRI api to fetch values, and return defaults if they are nil, please look at both Get* for container and filter, in case of  nil they both return ContainerState_CREATED state, so we can make a conclusion that if in such case it causes an error, then it's probably bug in kublete runtime impl, i.e it should put state explicitly or api GetState function should return smth else (probabaly, ContainerState_RUNNING) , as by defualt according to api, if it's not set it is assumed that only containers in CREATED state should be returned. So probably will publish fix/ create issue for upstream, will see. 

But as temp workaround, it's fine: I'll add checking  if filter state is nil and will retrun in such case call containers regardless of their states.
Also will cover this in integration tests, for now they passed successfully as I didn't started created domaines, hence, state checking passed fine.

---

*[pkg/libvirttools/virtualization.go, line 514 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXoQh9_LV8MCWXaVNm2:-KXomIWyCCBtmI9tLW1b:b1e2aqr) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/libvirttools/virtualization.go#L514)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

single if with &&
</blockquote></details>

yeah, will fix, it's left in such way after removed else

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/129)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/bolttools/sandbox.go, line 223 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmFWHXBrp4Y7lC6Ryf:-KXp713adQszljuT5zeI:bcs4psx) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/sandbox.go#L223)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Well, because I decided it's mkore universal approach if we'll need to store more in further, and also we already store labels and annotations as jsons.
</blockquote></details>

I'm still in favor of simple string (YAGNI). Labels and annotations are maps at least

---

*[pkg/bolttools/utils.go, line 55 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmGmBC1bTCEl0jjFM8:-KXp7iH3s5UOeTDoyFiw:b-d3qtdb) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L55)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Well, it's because of bolt works with keys and values as []byte, after unmarshal you're working with string array, and then marshal to json back and return []byte, again because bolt works with this type.
</blockquote></details>

All of this still seems somewhat baroque to me. Maybe we better should try to keep this simpler? We may switch to JSON later if/we actually need it here

---

*[pkg/bolttools/utils.go, line 96 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmI9m23ZagdrnCvthM:-KXp7Zo-EiyudIiQLF_l:b-ovgm8c) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L96)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

yeah, will move it to utils_tests.go
</blockquote></details>

Better move to some _test.go file or into a separate package that's only imported by tests. Otherwise virtlet will have all the command line flags from testing package

---

*[pkg/bolttools/utils.go, line 134 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmIrw93TOJgC_SEKoO:-KXp7y55mOeCqzRuS82o:byjlfh8) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L134)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

the same
</blockquote></details>

(see above)

---

*[pkg/bolttools/utils.go, line 188 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmJ1Bq7LJFRN_0aW_p:-KXp8-5xDtqyiIWfKIYj:byjlfh8) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L188)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

the same
</blockquote></details>

(see above)

---

*[pkg/bolttools/utils.go, line 210 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmJ51E6CSdOwGIpQg3:-KXp800PgK4IoOEDkyGV:byjlfh8) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L210)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

the same
</blockquote></details>

(see above)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/129)*

**Comment by vefimova** [comment]
Fixed all commentss, tests also passed, please have a look again.

---

Review status: 3 of 13 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/bolttools/sandbox.go, line 223 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmFWHXBrp4Y7lC6Ryf:-KXqtDy8VUY0Q1RdpHaw:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/sandbox.go#L223)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'm still in favor of simple string (YAGNI). Labels and annotations are maps at least
</blockquote></details>

Done.

---

*[pkg/bolttools/utils.go, line 55 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmGmBC1bTCEl0jjFM8:-KXqtKXf5_yXl-S_1SDL:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L55)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

All of this still seems somewhat baroque to me. Maybe we better should try to keep this simpler? We may switch to JSON later if/we actually need it here
</blockquote></details>

Done.

---

*[pkg/bolttools/utils.go, line 96 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmI9m23ZagdrnCvthM:-KXqtLGoMXYqOZLvSySB:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L96)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Better move to some _test.go file or into a separate package that's only imported by tests. Otherwise virtlet will have all the command line flags from testing package
</blockquote></details>

Done.

---

*[pkg/bolttools/utils.go, line 134 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmIrw93TOJgC_SEKoO:-KXqtM1MDG4d0Iru-uOR:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L134)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

(see above)
</blockquote></details>

Done.

---

*[pkg/bolttools/utils.go, line 188 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmJ1Bq7LJFRN_0aW_p:-KXqtMOhWwIPCz9V8z6B:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L188)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

(see above)
</blockquote></details>

Done.

---

*[pkg/bolttools/utils.go, line 210 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmJ51E6CSdOwGIpQg3:-KXqtMg8r1RVL54mGNyD:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/bolttools/utils.go#L210)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

(see above)
</blockquote></details>

Done.

---

*[pkg/libvirttools/virtualization.go, line 438 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXoOzWaICbDEQQ6wfp3:-KXqtOHW6fVDJv7PBN6h:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/libvirttools/virtualization.go#L438)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

There're Get* functions in CRI api to fetch values, and return defaults if they are nil, please look at both Get* for container and filter, in case of  nil they both return ContainerState_CREATED state, so we can make a conclusion that if in such case it causes an error, then it's probably bug in kublete runtime impl, i.e it should put state explicitly or api GetState function should return smth else (probabaly, ContainerState_RUNNING) , as by defualt according to api, if it's not set it is assumed that only containers in CREATED state should be returned. So probably will publish fix/ create issue for upstream, will see. 

But as temp workaround, it's fine: I'll add checking  if filter state is nil and will retrun in such case call containers regardless of their states.
Also will cover this in integration tests, for now they passed successfully as I didn't started created domaines, hence, state checking passed fine.
</blockquote></details>

Done.

---

*[pkg/libvirttools/virtualization.go, line 514 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXoQh9_LV8MCWXaVNm2:-KXqtP9W6RniK7JEpXas:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/pkg/libvirttools/virtualization.go#L514)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

yeah, will fix, it's left in such way after removed else
</blockquote></details>

Done.

---

*[tests/integration/image_pull_test.go, line 35 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXmJXOG0pcam7P7lMEo:-KXqtQZjnkMFgWIZAhuz:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/667eb7a9c534f62d126ee5b1e2a32e0039bfd5e1/tests/integration/image_pull_test.go#L35)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/129#-:-KXqtfMmUjvZM2_TBJew:b49nck3)*

**Comment by vefimova** [comment]
Please, look once again: removed list functions for storing containers ids, as for now only one VM can be created in pod.

**Comment by jellonek** [comment]
Please use name `mock` instead of `fake`.
Rest of comments are inlined.

---

Reviewed 4 of 10 files at r2, 5 of 6 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/bolttools/sandbox.go, line 205 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXzWbXaYDsDYRUz1Sdf:-KXzWbXbAGU4IoX-Ep7j:b-u3xz8j) ([raw file](https://github.com/mirantis/virtlet/blob/0c331b4b9c507ac68c7c98ce818ae3228e519159/pkg/bolttools/sandbox.go#L205)):*
> ```Go
> }
> 
> func (b *BoltClient) GetPodSandboxContainerList(containerId string) (string, error) {
> ```

containerId in this place is misleading -  it should be named podId
Also it's not list any more so func name should be `GetContainerIdFromPodSandbox` or something like that.

---

*[pkg/bolttools/sandbox.go, line 224 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXzWsRHvubNpPalBJ36:-KXzWsRHvubNpPalBJ37:bjyh23e) ([raw file](https://github.com/mirantis/virtlet/blob/0c331b4b9c507ac68c7c98ce818ae3228e519159/pkg/bolttools/sandbox.go#L224)):*
> ```Go
> 		}
> 
> 		return nil
> ```

When you will remove this if - you could use there simple `return err` as it was in r1 version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/129#-:-KXzYfGNLSMt82s0ydxo:b-gquyb9)*

**Comment by vefimova** [comment]
Review status: 7 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/bolttools/sandbox.go, line 205 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXzWbXaYDsDYRUz1Sdf:-KXzh1nxeceo7jSojsW6:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/0c331b4b9c507ac68c7c98ce818ae3228e519159/pkg/bolttools/sandbox.go#L205)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

containerId in this place is misleading -  it should be named podId
Also it's not list any more so func name should be `GetContainerIdFromPodSandbox` or something like that.
</blockquote></details>

Done.

---

*[pkg/bolttools/sandbox.go, line 224 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/129#-KXzWsRHvubNpPalBJ36:-KXzh2vqSx1biwEfDDSe:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/0c331b4b9c507ac68c7c98ce818ae3228e519159/pkg/bolttools/sandbox.go#L224)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

When you will remove this if - you could use there simple `return err` as it was in r1 version.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/129)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/129#-:-KXzhhdiktQoZ-lG-cwr:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/129#-:-KXziKzjBCxg0NJipPK_:bnfp4nl)*

**Pull request merged**
