### PR TITLE
Run docker-shim from criproxy

### LINKED ISSUE #190: Run docker-shim inside CRI proxy
Looks like [mixed mode](https://github.com/kubernetes/kubernetes/pull/39685) PR is not going to be accepted. We need to run docker-shim inside CRI proxy. This seems to be feasible but there can be problems with docker exec/attach that need to be resolved (e.g. `kubectl attach` can only work if the nodes are reachable from the host where `kubectl` runs).

Also need a way to pick up relevant parts of kubelet config and pass them to docker-shim.

### PR DESCRIPTION
**Pull request by ivan4th**
As of now, attaching to docker containers behind the proxy only works when the node is reachable from the host where `kubectl` is run. It also uses default config for docker-shim at the moment.

Fixes #190 

- [x] Basic support for running docker-shim
- [x] Fix kubectl exec/attach (the problem was with missing StreamingProxyRedirects feature gate for apiserver, solved on kubeadm-dind-cluster side
- [x] Fix networking in pods
- [x] Add a way to get docker-shim related kubelet options from kubelet
- [x] Deploy CRI proxy from virtlet DaemonSet
- [x] Update sample cluster config

Concerning options, one way is to make it possible to run something like `criproxy grab` before switching kubelet to using criproxy. This command will create a config file for the proxy which
contains necessary options that will be used for docker-shim.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/188)

### CODE REVIEW

**Comment by jellonek** [comment]
Quite extensive change in dependencies (next reason why criproxy should be extracted) - but looks pretty good.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/188#-:-Kadg76QG0sd7s1DblZf:bpp3vs3)*

**Comment by pigmej** [comment]
How much is it currently bound to Virtlet? How much work would be needed to extract it to separate project? What we loose then?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/188#-:-Kadn0cfI69NHMncwjBd:b-6jx6o7)*

**Comment by ivan4th** [comment]
It's not tied to virtlet besides being placed in the same github project and can be extracted in a day or less. To do this we need to make a separate github project, set up CI for it (the proxy is shipped as a binary and an image) and also choose a way for virtlet test scripts to get up-to-date binary of the proxy.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/188#-:-KafMrI-am160MG55xEv:b-s9nn3j)*

**Comment by jellonek** [comment]
Another advantage of extracting it to separate repo (beside of usage facilitation for other cri projects) is that we could still test virtlet against kubernetes original tree - now we require to switch to Ivans fork.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/188#-:-Kafa5cmT8gcmS5-qoNc:bynwkcu)*

**Comment by ivan4th** [comment]
CNI bridge testing in docker (making CNI config for kubeadm-dind-cluster, some of the commands may be useful for CNI debugging in general):
```
root@kube-master:/#   brctl addbr dind0
root@kube-master:/#   brctl addif dind0 eth0
root@kube-master:/#   ip link set dind0 up
root@kube-master:/#
root@kube-master:/#   # move ip to the bridge and restore routing via the old gateway
root@kube-master:/#   IP_CIDR=$(ip addr show eth0 | grep -w inet | awk '{ print $2; }')
root@kube-master:/#   IP=$(echo $IP_CIDR | sed 's,/.*,,')
root@kube-master:/#   NETWORK_SIZE=$(echo $IP_CIDR | sed 's,.*/,,')
root@kube-master:/#   DEFAULT_ROUTE=$(ip route | grep default | sed 's/eth0/dind0/')
root@kube-master:/#
root@kube-master:/#   ip addr del $IP_CIDR dev eth0
root@kube-master:/#   ip addr add $IP_CIDR dev dind0
root@kube-master:/#   ip route add $DEFAULT_ROUTE
root@kube-master:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=58 time=4.10 ms
^C

...

root@kube-master:/# cat /sample.conf
{
    "name": "dindnet",
    "type": "bridge",
    "bridge": "dind0",
    "ipam": {
        "type": "host-local",
        "subnet": "172.30.0.1/16",
        "rangeStart": "172.30.1.1",
        "rangeEnd": "172.30.1.254",
        "gateway": "172.30.0.1",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]
    }
}
root@kube-master:/# ip netns add a
root@kube-master:/# ip netns add b
(reverse-i-search)`C': CNI_PATH=/usr/lib/kubernetes/cni/bin CNI_IFNAME=eth0 CNI_COMMAND=ADD PATH=/usr/lib/kubernetes/cni/bin:$PATH CNI_CONTAINERID=a ^CI_NETNS=/var/run/netns/a /usr/lib/kubernetes/cni/bin/bridge </sample.conf
root@kube-master:/# CNI_PATH=/usr/lib/kubernetes/cni/bin CNI_IFNAME=eth0 CNI_COMMAND=ADD PATH=/usr/lib/kubernetes/cni/bin:$PATH CNI_CONTAINERID=a CNI_NETNS=/var/run/netns/a /usr/lib/kubernetes/cni/bin/bridge </sample.conf
{
    "ip4": {
        "ip": "172.30.1.5/16",
        "gateway": "172.30.0.1",
        "routes": [
            {
                "dst": "0.0.0.0/0"
            }
        ]
    },
    "dns": {}
root@kube-master:/# CNI_PATH=/usr/lib/kubernetes/cni/bin CNI_IFNAME=eth0 CNI_COMMAND=ADD PATH=/usr/lib/kubernetes/cni/bin:$PATH CNI_CONTAINERID=b CNI_NETNS=/var/run/netns/b /usr/lib/kubernetes/cni/bin/bridge </sample.conf
{
    "ip4": {
        "ip": "172.30.1.6/16",
        "gateway": "172.30.0.1",
        "routes": [
            {
                "dst": "0.0.0.0/0"
            }
        ]
    },
    "dns": {}
root@kube-master:/# ip netns exec a ip l set dev lo up
root@kube-master:/# ip netns exec b ip l set dev lo up
root@kube-master:/# ip netns exec a ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 0a:58:ac:1e:01:05 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.30.1.5/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::9c05:35ff:fe00:8d3c/64 scope link
       valid_lft forever preferred_lft forever
root@kube-master:/# ip netns exec b ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 0a:58:ac:1e:01:06 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.30.1.6/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::8804:a3ff:feea:8fc0/64 scope link
       valid_lft forever preferred_lft forever
root@kube-master:/# ip netns exec a ping -c1 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=58 time=4.31 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 4.315/4.315/4.315/0.000 ms
root@kube-master:/# ip netns exec b ping -c1 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=58 time=4.08 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 4.081/4.081/4.081/0.000 ms
root@kube-master:/# ip netns exec a ping -c1 172.30.1.5
PING 172.30.1.5 (172.30.1.5) 56(84) bytes of data.
64 bytes from 172.30.1.5: icmp_seq=1 ttl=64 time=0.069 ms

--- 172.30.1.5 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.069/0.069/0.069/0.000 ms
root@kube-master:/# ip netns exec a ping -c1 172.30.1.6
PING 172.30.1.6 (172.30.1.6) 56(84) bytes of data.
64 bytes from 172.30.1.6: icmp_seq=1 ttl=64 time=0.170 ms

--- 172.30.1.6 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.170/0.170/0.170/0.000 ms
root@kube-master:/# ip netns exec b ping -c1 172.30.1.5
PING 172.30.1.5 (172.30.1.5) 56(84) bytes of data.
64 bytes from 172.30.1.5: icmp_seq=1 ttl=64 time=0.129 ms

--- 172.30.1.5 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.129/0.129/0.129/0.000 ms
root@kube-master:/# ip netns exec b ping -c1 172.30.1.6
PING 172.30.1.6 (172.30.1.6) 56(84) bytes of data.
64 bytes from 172.30.1.6: icmp_seq=1 ttl=64 time=0.057 ms

--- 172.30.1.6 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.057/0.057/0.057/0.000 ms
```

**Comment by ivan4th** [comment]
Added initial CNI support (bridge plugin) to kubeadm-dind-cluster: https://github.com/Mirantis/kubeadm-dind-cluster/tree/cni-support

**Comment by ivan4th** [comment]
CRI proxy+virtlet bootstrap: Kubelet config extraction / virtlet deployment.

Prerequisites for the cluster:
1.  The following feature gates must be enabled for apiserver: ```--feature-gates=StreamingProxyRedirects=true --feature-gates=DynamicKubeletConfig=true```
2. The nodes must run systemd
3. Kubelet  should be started via systemd unit named `kubelet.service`. This is true both for 'traditional' Kargo and also for most clusters deployed with kubeadm.

With these prerequisites satisfied, it should be possible to install Virtlet with command like
```
kubectl create -f https://github.com/Mirantis/virtlet/blob/master/deploy/virtlet.yml?raw=true
```
(NB: if there are problems with Content-Type, may use an url based on https://rawgit.com/ instead)

The yaml file should be modelled after e.g. [flannel deployment yaml](https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml).
Basically it needs to include definitions for a service account needed to access
Kubernetes API and Virtlet DaemonSet.

The following steps will be taken by Virtlet pods running on the nodes (likely in init containers):
1. If current runtime is CRI proxy (NB: need to alter `Version()` handler, this will also fix `docker://...` prefix), just start virtlet in the way it's done currently and that's it.
2. Load kubelet configuration for the current node. It can be done directly from local kubelet like this:
```
curl -k https://127.0.0.1:10250/configz
```
or [from apiserver](https://github.com/kubernetes/kubernetes/blob/v1.5.2/test/e2e_node/util.go#L77). [Here](https://kubernetes.io/docs/user-guide/accessing-the-cluster/#accessing-the-api-from-a-pod) is the link describing how to access apiserver properly from a pod. 
3. Install and enable`criproxy.service` systemd unit. It should include `WantedBy=multi-user.target` in its `[Install]` section, but it should be enabled by symlinking it as `/etc/systemd/system/kubelet.service/wants/criproxy.service`. The unit should start CRI proxy using virtlet image [like this](https://docs.docker.com/engine/admin/host_integration/). It'll ensure that the container will get recreated even if it's deleted for some reason. This step is optional (can just run the container with restart=Always) but it will make the installation more stable. If docker endpoint specified in kubelet configuration is a unix domain socket, it should be mounted into the container.
4. Start CRI proxy container (virtlet image with different command) by using docker endpoint from kubelet config that was obtained. We don't want to employ extra hacks [like this](https://groups.google.com/forum/#!topic/coreos-dev/AXCs_2_J6Mc) to access host systemd for this. If docker endpoint is a unix domain socket, it should be mounted into the container.
5. Update kubelet configuration object to enable CRI and specify CRI proxy endpoint. The changes should correspond to following kubelet options: `--experimental-cri --container-runtime=remote --container-runtime-endpoint=/run/criproxy.sock --image-service-endpoint=/run/criproxy.sock`
6. Push ConfigMap object named `kubelet-NODENAME` to apiserver. For basic ideas concerning how to reconfigure kubelet dynamically see [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/dynamic_kubelet_configuration_test.go#L34) and [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/util.go#L142).
7. At this point, kubelet will be restarted. It'll use CRI proxy as the runtime/image service. To check: may require some docker cleanup after kubelet autorestart after configmap deployment. CRI proxy will be able to access Virtlet image/runtime endpoints once Virtlet daemonset restarts.

**Comment by ivan4th** [comment]
Bonus: Calico, Flannel etc. provide kubeadm-specific yamls. Likewise we can also provide one which can add extra step that injects feature gate flags into apiserver's static pod. Thus, full bootstrap with no prerequisites will be possible for kubeadm clusters (and **not** just those deployed via kubeadm-dind-cluster). Systemd prerequisite is quite optional for testing purposes (the container will restart itself anyway).

**Comment by ivan4th** [comment]
Re p.2: it's actually preferable to grab kubelet config from localhost to avoid another chicken-and-egg problem. Node name may be affected by `--hostname-override` option (`HostnameOverride` in kubelet config object), see relevant parts of the code ([1](https://github.com/kubernetes/kubernetes/blob/v1.5.2/pkg/kubelet/kubelet.go#L292), [2](https://github.com/kubernetes/kubernetes/blob/v1.5.2/pkg/util/node/node.go#L41)), and in order to request node config from apiserver, we need to know the name of the node. If we request the config from localhost instead, we may get `HostnameOverride` from there and then follow kubelet's way of choosing the node name.

**Comment by jellonek** [comment]
Looks good, with few small comments mostly about case of output messages. Also new files imo should have 2017 in copyright note ;)

---

Reviewed 1 of 1 files at r2, 14 of 14 files at r4.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[cmd/criproxy/criproxy.go, line 40 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbnsbvm9crKtTnTyV-3:-KbnsbvnJJ-TL-yjHFat:b-gk4219) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/cmd/criproxy/criproxy.go#L40)):*
> ```Go
> 	connect = flag.String("connect", "/var/run/dockershim.sock",
> 		"CRI runtime ids and unix socket(s) to connect to, e.g. /var/run/dockershim.sock,alt:/var/run/another.sock")
> 	kubeletConfigPath = flag.String("kletcfg", "/etc/criproxy/kubelet.conf", "path to saved kubelet config file")
> ```

Please use there `kubeletcfg` as command line parameter name.

---

*[pkg/criproxy/bootstrap.go, line 171 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbntZ_Uv_hqZDuRa5PK:-KbntZ_Uv_hqZDuRa5PL:bt9ja64) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap.go#L171)):*
> ```Go
> 	text, err := json.Marshal(b.kubeletCfg)
> 	if err != nil {
> 		log.Panicf("couldn't marshal kubelet config: %v", err)
> ```

This message should be capitalized.

---

*[pkg/criproxy/bootstrap.go, line 193 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbntlJ7aO3KNUlhO_LI:-KbntlJ7aO3KNUlhO_LJ:bt9ja64) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap.go#L193)):*
> ```Go
> 	_, err := os.Stat(b.config.SavedConfigPath)
> 	if err == nil {
> 		glog.V(1).Infof("config file already exists: %q", b.config.SavedConfigPath)
> ```

This message should be capitalized.

---

*[pkg/criproxy/bootstrap_test.go, line 2 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbnv0O2oym4ozuAP4Jo:-Kbnv0O2oym4ozuAP4Jp:bz12r2r) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap_test.go#L2)):*
> ```Go
> /*
> Copyright 2016 Mirantis
> ```

Year looks incorrect ;)

---

*[pkg/criproxy/bootstrap_test.go, line 56 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbnu8yLXoGqCJ67vtO5:-Kbnu8yLXoGqCJ67vtO6:b-vqy5ga) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap_test.go#L56)):*
> ```Go
> 	}
> 	if v.Kind() != reflect.Struct {
> 		log.Panicf("struct or pointer to struct expected, but got %#v", s)
> ```

This should be capitalized, but less important as it's in tests.

---

*[pkg/criproxy/bootstrap_test.go, line 65 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnuE8ZJUEiyk75dZOO:-KbnuE8ZJUEiyk75dZOP:b-3ahcot) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap_test.go#L65)):*
> ```Go
> 	vNew := getStruct(new)
> 	if vOld.Type() != vNew.Type() {
> 		log.Panicf("got different struct types")
> ```

Same again.

---

*[pkg/criproxy/bootstrap_test.go, line 331 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnujCixhd8GJHzmb6A:-KbnujCixhd8GJHzmb6B:b564a6v) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap_test.go#L331)):*
> ```Go
> exit 1
> `
> )
> ```

:+1: for keeping this in sources - using some kind of fixtures there would be painful to maintain/deploy in test env.

---

*[pkg/criproxy/dockershim.go, line 90 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnvSeKY3OGz7T-Ko_E:-KbnvSeKY3OGz7T-Ko_F:b-uq3tkt) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/dockershim.go#L90)):*
> ```Go
> }
> 
> func StartDockerShim(kubeCfg *cfg.KubeletConfiguration) (string, error) {
> ```

Can you add docstring to this and next exported func? Nothing very important, but...

---

*[pkg/criproxy/dockertools.go, line 87 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbnw7FSvDSU6nCipyUP:-Kbnw7FSvDSU6nCipyUQ:b-6nyivb) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/dockertools.go#L87)):*
> ```Go
> }
> 
> // TODO: remove containers by label(s)
> ```

Is this comment still correct? I see such func above.

---

*[pkg/criproxy/proxy.go, line 339 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnwPSBBDAoqk8pVqm-:-KbnwPSBBDAoqk8pVqm0:bt9ja64) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/proxy.go#L339)):*
> ```Go
> 	out, err := exec.Command("/usr/bin/curl", "-k", "https://127.0.0.1:10250/configz").CombinedOutput()
> 	if err != nil {
> 		glog.Errorf("failed to get kubelet config: %v", err)
> ```

This message should be capitalized.

---

*[pkg/criproxy/proxy.go, line 341 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnwWM_zyUl-6R53J88:-KbnwWM_zyUl-6R53J89:bt9ja64) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/proxy.go#L341)):*
> ```Go
> 		glog.Errorf("failed to get kubelet config: %v", err)
> 	} else {
> 		glog.Infof("kubelet config:\n%s", out)
> ```

This message should be capitalized.

---

*[pkg/criproxy/proxy.go, line 596 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnwbNKmwDVB0CoVoi2:-KbnwbNKmwDVB0CoVoi3:bodpam4) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/proxy.go#L596)):*
> ```Go
> 		out, err := exec.Command("/usr/bin/curl", "-k", "https://127.0.0.1:10250/configz").CombinedOutput()
> 		if err != nil {
> 			glog.Errorf("failed to get kubelet config: %v", err)
> ```

Same as above. Looks like good part to extract/refactor as it's the same as few lines above in `Version()`.

---

*[pkg/criproxy/proxy_test.go, line 62 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbnwxx6BNBW4YA2iJ1q:-Kbnwxx6BNBW4YA2iJ1r:bhajwk8) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/proxy_test.go#L62)):*
> ```Go
> 	go func() {
> 		if err := s.Serve(addr, readyCh); err != nil {
> 			glog.Errorf("error starting server @ %q: %v", addr, err)
> ```

This message should be capitalized. Not important, this are only tests.

---

*[pkg/criproxy/util.go, line 29 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnxBnld3aXQuVym0wQ:-KbnxBnld3aXQuVym0wR:b-kct3dt) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/util.go#L29)):*
> ```Go
> 
> const (
> 	connectAttemptInterval = 500 * time.Millisecond
> ```

Same constant defined yet another time in another package. Probably we should use single constant imported from some common place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/188#-:-KbnxcFxIv7pz7CcZMSg:b-ep67ii)*

**Comment by ivan4th** [comment]
Review status: 8 of 16 files reviewed at latest revision, 14 unresolved discussions.

---

*[pkg/criproxy/bootstrap.go, line 171 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbntZ_Uv_hqZDuRa5PK:-Kbo6ZXJK9P0IY9mSPED:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap.go#L171)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This message should be capitalized.
</blockquote></details>

Done.

---

*[pkg/criproxy/bootstrap.go, line 193 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbntlJ7aO3KNUlhO_LI:-Kbo6Yvk3vyQBLwrKxQ9:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap.go#L193)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This message should be capitalized.
</blockquote></details>

Done.

---

*[pkg/criproxy/bootstrap_test.go, line 2 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbnv0O2oym4ozuAP4Jo:-Kbo6RVsk-5_vP-6cVPY:b4k63xb) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap_test.go#L2)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Year looks incorrect ;)
</blockquote></details>

Done. For now updated just the files affected by this PR, will do this for other files as a separate PR.

---

*[pkg/criproxy/bootstrap_test.go, line 56 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbnu8yLXoGqCJ67vtO5:-Kbo6QqWeY5dFhB3inBQ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap_test.go#L56)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This should be capitalized, but less important as it's in tests.
</blockquote></details>

Done.

---

*[pkg/criproxy/bootstrap_test.go, line 65 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnuE8ZJUEiyk75dZOO:-Kbo6Q157Z4p9EBcsU-F:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap_test.go#L65)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Same again.
</blockquote></details>

Done.

---

*[pkg/criproxy/bootstrap_test.go, line 331 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnujCixhd8GJHzmb6A:-Kbo6KL12LCSwl7YDpZx:b-x0paxf) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap_test.go#L331)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

:+1: for keeping this in sources - using some kind of fixtures there would be painful to maintain/deploy in test env.
</blockquote></details>

Yes :)

---

*[pkg/criproxy/dockershim.go, line 90 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnvSeKY3OGz7T-Ko_E:-Kbo6Hwn9r-VMXSIPoGJ:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/dockershim.go#L90)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Can you add docstring to this and next exported func? Nothing very important, but...
</blockquote></details>

Done.

---

*[pkg/criproxy/proxy.go, line 339 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnwPSBBDAoqk8pVqm-:-Kbo6C971kGZ8nWgcNVj:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/proxy.go#L339)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This message should be capitalized.
</blockquote></details>

Done.

---

*[pkg/criproxy/proxy.go, line 341 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnwWM_zyUl-6R53J88:-Kbo6BecLtXSaonLVQqD:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/proxy.go#L341)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This message should be capitalized.
</blockquote></details>

Done.

---

*[pkg/criproxy/proxy.go, line 596 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-KbnwbNKmwDVB0CoVoi2:-Kbo6AnElgLziQY6-RVy:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/proxy.go#L596)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Same as above. Looks like good part to extract/refactor as it's the same as few lines above in `Version()`.
</blockquote></details>

Done.

---

*[pkg/criproxy/proxy_test.go, line 62 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbnwxx6BNBW4YA2iJ1q:-Kbo62snghO4dMzyhK9t:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/proxy_test.go#L62)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This message should be capitalized. Not important, this are only tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/188)*

**Comment by pigmej** [comment]
Review status: 8 of 16 files reviewed at latest revision, 15 unresolved discussions.

---

*[cmd/criproxy/criproxy.go, line 40 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbnsbvm9crKtTnTyV-3:-Kbo9nQtE5pmYNa1Po6K:b-kj8dd) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/cmd/criproxy/criproxy.go#L40)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Please use there `kubeletcfg` as command line parameter name.
</blockquote></details>

+1 there.

---

*[pkg/criproxy/bootstrap.go, line 2 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbo9xF-3TGT7XlZUv5G:-Kbo9xF-3TGT7XlZUv5H:b-8k88p6) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap.go#L2)):*
> ```Go
> /*
> Copyright 2016 Mirantis
> ```

2017?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/188)*

**Comment by ivan4th** [comment]
Review status: 8 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/criproxy/bootstrap.go, line 2 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbo9xF-3TGT7XlZUv5G:-KboARz0LpyN6PjwHkkL:b-x0m06e) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap.go#L2)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary><blockquote>

2017?
</blockquote></details>

It's already fixed, see on the right :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/188)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/criproxy/bootstrap_test.go, line 2 at r4](https://reviewable.io:443/reviews/mirantis/virtlet/188#-Kbnv0O2oym4ozuAP4Jo:-KboBNOzItOr_lUkNx9P:b-o1fack) ([raw file](https://github.com/mirantis/virtlet/blob/7f12cf8df7577a95d5fb307a6e8863907138b72b/pkg/criproxy/bootstrap_test.go#L2)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Done. For now updated just the files affected by this PR, will do this for other files as a separate PR.
</blockquote></details>

IMO only modified files should have to be updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/188#-:-KboB7oYV78n5ykcwtX8:bnfp4nl)*

**Pull request merged**
