### PR TITLE
Pass original MTU to VM using dhcp

### PR DESCRIPTION
**Pull request by jellonek**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/547)

### CODE REVIEW

**Comment by pigmej** [comment]
Can we documment that it's only in DCHP part? 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/547#-:-L2KEtSumXRFkyETjiZC:baklk7)*

**Comment by jellonek** [comment]
Done.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/547#-:-L2Klh5GHYYhuwZg71BO:b-896fix)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/547#-:-L2L2AYrs7SGqp_raG3s:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/networking.md, line 109 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/547#-L2Uax1LCIwQ5DgLLB77:-L2Uax1LCIwQ5DgLLB78:ba2ks7u) ([raw file](https://github.com/mirantis/virtlet/blob/9d1e8d534e7bf20ee843d360518c58e94566d0df/docs/networking.md#L109)):*
> ```Markdown
> 
> **NOTE:** At the moment Virtlet supports passing `MTU` to VM for network
> interfaces configured by CNI plugins only through it's builtin `DHCP` server.
> ```

At the moment Virtlet can only pass `MTU` values configured for the network interfaces by CNI plugins to VMs via its built-in `DHCP` server.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/547)*

**Comment by jellonek** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/networking.md, line 109 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/547#-L2Uax1LCIwQ5DgLLB77:-L2UdJ_XzYkjK7dlfNgS:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/9d1e8d534e7bf20ee843d360518c58e94566d0df/docs/networking.md#L109)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

At the moment Virtlet can only pass `MTU` values configured for the network interfaces by CNI plugins to VMs via its built-in `DHCP` server.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/547)*

**Comment by pigmej** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/547)*

**Comment by pigmej** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/547#-:-L2UxXxVck26xMopUR1M:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 2 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/547#-:-L2V1jwN7AHhRDKSAMo0:bnfp4nl)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 2 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/547#-:-L2VAQHYqWUSAKxrU6bm:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/547#-:-L2VOJCpdygVz0LM-dAk:bnfp4nl)*

**Pull request merged**
