### PR TITLE
Provide instructions/patches for building custom CirrOS image

### PR DESCRIPTION
**Pull request by jellonek**
... containing python based Cloud Init client installed in rootfs/startup sequence.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/394)

### CODE REVIEW

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/devel/building-cirros-with-cloud-init.md, line 4 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KsrbjvJppForla8wSJu:-KsrbjvJppForla8wSJv:b-ufauxu) ([raw file](https://github.com/mirantis/virtlet/blob/e363c3c0e3144c52344e882746d8a88b33af60c3/docs/devel/building-cirros-with-cloud-init.md#L4)):*
> he purpose of this document is to provide instructions for building own CirrOS
> image with installed in rootfs/init sequence python based

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/394#-:-KtLQOHNsuvmxyuEEiwh:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 14 unresolved discussions.

---

*[docs/devel/building-cirros-with-cloud-init.md, line 4 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KsrbjvJppForla8wSJu:-KtLS93hw_IziOUyo5_2:bv2x1rc) ([raw file](https://github.com/mirantis/virtlet/blob/e363c3c0e3144c52344e882746d8a88b33af60c3/docs/devel/building-cirros-with-cloud-init.md#L4)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

> he purpose of this document is to provide instructions for building own CirrOS
> image with installed in rootfs/init sequence python based

</blockquote></details>

The purpose of this document is to provide instructions for  building custom CirrOS image with Python-based [Cloud Init](http://cloudinit.readthedocs.io/en/latest/) installed in rootfs and added to the init sequence

---

*[docs/devel/building-cirros-with-cloud-init.md, line 9 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLSWeV7Oh0NgZ5SxUj:-KtLSWeV7Oh0NgZ5SxUk:b-c761cl) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L9)):*
> ```Markdown
> 
> In this example we are basing on official sources from [launchpad](https://git.launchpad.net/cirros)
> Assuming that you have already installed git, clone above repository with command:
> ```

This example is based on official sources hosted on [launchpad](https://git.launchpad.net/cirros). Assuming that you have already installed git, clone the above repository with the following command:

---

*[docs/devel/building-cirros-with-cloud-init.md, line 22 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLTM-5kB-H9GJCXIlu:-KtLTM-5kB-H9GJCXIlv:b-d886ny) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L22)):*
> ```Markdown
> ```
> 
> Prepre `downloads` directory and put into it buildroot tar:
> ```

Prepare

---

*[docs/devel/building-cirros-with-cloud-init.md, line 33 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLTSPmpihA9tt5vSsB:-KtLTSPnLbaSJgL5mzP0:b-j9rh50) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L33)):*
> ```Markdown
> Ensure that you have installed packages listed in `cirros/bin/system-setup`
> (names of packages can be different for different systems, for debian based
> system you can simply use mentioned tool to install them).
> ```

(package names can be different for different Linux distros, for Debian-based system you can simply use ... to install them)

[I didn't understand what tool do you mean there, apt-get?]

---

*[docs/devel/building-cirros-with-cloud-init.md, line 35 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLTsF8s6JbjoYOMl-r:-KtLTsF8s6JbjoYOMl-s:buz6o7q) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L35)):*
> ```Markdown
> system you can simply use mentioned tool to install them).
> 
> ## Patches applying
> ```

## Applying the patches

---

*[docs/devel/building-cirros-with-cloud-init.md, line 42 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLTvDEhHPB3yqw19dD:-KtLTvDEhHPB3yqw19dE:brimv8j) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L42)):*
> ```Markdown
> ```
> 
> ## Retrieving sources of buildroot packages
> ```

## Retrieving the sources of buildroot packages

---

*[docs/devel/building-cirros-with-cloud-init.md, line 55 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLTyuwoCYDg7p4h3Za:-KtLTyuwoCYDg7p4h3Zb:b-wfrxya) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L55)):*
> ```Markdown
> 
> The process should fail during installation of `python-cloud-init`. After this
> failure, use below command:
> ```

Use the following command after `make` fails:

---

*[docs/devel/building-cirros-with-cloud-init.md, line 62 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLU2re43lZeQDkxHnJ:-KtLU2re43lZeQDkxHnK:b2niy2w) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L62)):*
> ```Markdown
> ```
> 
> and run again previous build command:
> ```

then run the previous build command again:

---

*[docs/devel/building-cirros-with-cloud-init.md, line 68 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLU5sDBRcJzNblk2k9:-KtLU5sDBRcJzNblk2kA:bb6vxvh) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L68)):*
> ```Markdown
> ```
> 
> ## Downloading kernel and grub
> ```

GRUB

---

*[docs/devel/building-cirros-with-cloud-init.md, line 71 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLU93q5WRspfMYG94N:-KtLU93q5WRspfMYG94O:b-mypof3) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L71)):*
> ```Markdown
> 
> You need to set correct version of kernel (look for them on
> [this](https://launchpad.net/ubuntu/+source/linux) site) eg.:
> ```

You need to set a correct version of kernel (the versions are listed [here](https://launchpad.net/ubuntu/+source/linux)]

---

*[docs/devel/building-cirros-with-cloud-init.md, line 78 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLUPLB2CE1trvv8SZ1:-KtLUPLCWFANRAGJd0q4:b-lxwtf0) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L78)):*
> ```Markdown
> ```
> 
> Same for grub, looking for [this](https://launchpad.net/ubuntu/+source/grub2) site:
> ```

Same for GRUB (version list is [here](https://launchpad.net/ubuntu/+source/grub2)):

---

*[docs/devel/building-cirros-with-cloud-init.md, line 85 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLUNPwRJrnD0NhWRiI:-KtLUNPwRJrnD0NhWRiJ:bwv29g1) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L85)):*
> ```Markdown
> ```
> 
> ## Building final image
> ```

## Building the final image

---

*[docs/devel/building-cirros-with-cloud-init.md, line 92 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLUYAJkRVoyF1cufBn:-KtLUYAJkRVoyF1cufBo:b-flpgcr) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L92)):*
> ```Markdown
> ```
> 
> Final image will be available in file with `output/i386/images/disk.img` name.
> ```

The final image file will be named `output/i386/images/disk.img`.

---

*[docs/devel/README.md, line 9 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLUhFKTBOkhkp1YWKo:-KtLUhFKTBOkhkp1YWKp:b-jzuzh4) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/README.md#L9)):*
> ```Markdown
> * [Build tool usage](build-tool.md)
> * [VM logging](vm-logging.md)
> * [Building custom CirrOS image](building-cirros-with-cloud-init.md) which includes fully python based cloud init package
> ```

which includes full python-based cloud-init package

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/394)*

**Comment by jellonek** [comment]
Thx. All comments addressed.

---

Review status: 0 of 5 files reviewed at latest revision, 14 unresolved discussions.

---

*[docs/devel/building-cirros-with-cloud-init.md, line 33 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/394#-KtLTSPmpihA9tt5vSsB:-KtM5dJ2B_VlKrEfQC9p:b-hs36fr) ([raw file](https://github.com/mirantis/virtlet/blob/72c130944be61245a35a5bd2fd062eb9ff14545e/docs/devel/building-cirros-with-cloud-init.md#L33)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

(package names can be different for different Linux distros, for Debian-based system you can simply use ... to install them)

[I didn't understand what tool do you mean there, apt-get?]
</blockquote></details>

Mentioned script. To be sure that all is clear - changed that to repeat it's name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/394#-:-KtM6T0FbN6BkqBx47Mu:b-hcj7wp)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/394#-:-KtM6fKMqyprBqxygggV:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/394#-:-Ku3ve3HZev2UkjpU8lI:bnfp4nl)*

**Pull request merged**
