### PR TITLE
volumes: Fixes for issues not caught by travis tests

### LINKED ISSUE #252: If we pass wrong value in volume description - error is not handled correctly
We should return with error in https://github.com/Mirantis/virtlet/blob/3ad8dd642bf5a9d3e33bec290de7820fb8a0b587/pkg/libvirttools/storage_pool.go#L282

Fixing this in PR for raw devices support.

### PR DESCRIPTION
**Pull request by jellonek**
fixes #252, #253, #254

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/258)

### CODE REVIEW

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/258#-:-KhgViKGqG-9TbUuEgTP:bnfp4nl)*

**Comment by vefimova** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/storage_pool.go, line 267 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/258#-KhgU2-hdl9yh_2a51mX:-KhgU2-hdl9yh_2a51mY:bcbu6yr) ([raw file](https://github.com/mirantis/virtlet/blob/fcaf17c4b98164be9a33841d31c6ac01f33dfec1/pkg/libvirttools/storage_pool.go#L267)):*
> ```Go
> 
> 	for _, virtletVol := range vols {
> 		switch virtletVol.Format {
> ```

Please add this part to UnmarshalJSON, it was initially added as a single place to set defaults and validate specified settings while unmarshaling.

---

*[pkg/libvirttools/storage_pool.go, line 301 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/258#-KhgV_9Lqcf9qyCggSW5:-KhgV_9Lqcf9qyCggSW6:bribihm) ([raw file](https://github.com/mirantis/virtlet/blob/fcaf17c4b98164be9a33841d31c6ac01f33dfec1/pkg/libvirttools/storage_pool.go#L301)):*
> ```Go
> 		var volXML string
> 		switch virtletVol.Format {
> 		case "qcow2":
> ```

As above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/258)*

**Comment by jellonek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/storage_pool.go, line 267 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/258#-KhgU2-hdl9yh_2a51mX:-KhgXkT35ZGIhPm0TxjM:bxt5gur) ([raw file](https://github.com/mirantis/virtlet/blob/fcaf17c4b98164be9a33841d31c6ac01f33dfec1/pkg/libvirttools/storage_pool.go#L267)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Please add this part to UnmarshalJSON, it was initially added as a single place to set defaults and validate specified settings while unmarshaling.
</blockquote></details>

Add, or move?
Move is not an option as this is also needed for raw devices later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/258)*

**Comment by vefimova** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/storage_pool.go, line 267 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/258#-KhgU2-hdl9yh_2a51mX:-KhgYABtby_uLiRA7Iz9:byi81lf) ([raw file](https://github.com/mirantis/virtlet/blob/fcaf17c4b98164be9a33841d31c6ac01f33dfec1/pkg/libvirttools/storage_pool.go#L267)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Add, or move?
Move is not an option as this is also needed for raw devices later.
</blockquote></details>

oh, sorry, yep, I meant move. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/258)*

**Comment by vefimova** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/libvirttools/storage_pool.go, line 267 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/258#-KhgU2-hdl9yh_2a51mX:-KhgYK9myrmrXexy-udQ:bzbbgbs) ([raw file](https://github.com/mirantis/virtlet/blob/fcaf17c4b98164be9a33841d31c6ac01f33dfec1/pkg/libvirttools/storage_pool.go#L267)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

oh, sorry, yep, I meant move. :)
</blockquote></details>

Well for raw devices you will have the same structure? You probably will have some tyoe filed, to distinguish the, rigth, so you will be able to change validation accordingly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/258)*

**Pull request merged**
