### PR TITLE
Fix testability of libvirttools & improve build/cmd.sh

### PR DESCRIPTION
**Pull request by ivan4th**
- Switch to Go 1.8.3
- Add proper abstraction for libvirttools - libvirt interaction
- Add "golden master" testing for libvirttools
- Use rsync in build/cmd.sh
- Fix flexvolume tests that were broken
- Run flexvolume tests during `make check`

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/297)

### CODE REVIEW

**Comment by vefimova** [comment]
Reviewed 4 of 58 files at r1.
Review status: 4 of 58 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test.sh, line 18 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/297#-KlYtpmErSmEIIidd-RZ:-KlYtpmErSmEIIidd-R_:b-d95v0e) ([raw file](https://github.com/mirantis/virtlet/blob/d703eafddbf089749ffc9b616f7853cac3a64b1f/test.sh#L18)):*
> ```Shell
> bash -x build/cmd.sh build
> bash -x build/cmd.sh copy
> # bash -x build/cmd.sh test
> ```

uncomment this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/297)*

**Comment by vefimova** [comment]
Review status: 4 of 58 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test.sh, line 22 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/297#-KlYuEw1CDhVEIEmW9jj:-KlYuEw1CDhVEIEmW9jk:bpwae4m) ([raw file](https://github.com/mirantis/virtlet/blob/d703eafddbf089749ffc9b616f7853cac3a64b1f/test.sh#L22)):*
> ```Shell
> bash -x build/cmd.sh stop
> 
> echo "verifying VM state" >&2
> ```

Probably we need to perform it only when testing with Travis and  to add comment with explanation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/297)*

**Comment by vefimova** [comment]
Reviewed 54 of 58 files at r1, 1 of 11 files at r2.
Review status: 49 of 56 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/297)*

**Comment by vefimova** [comment]
:lgtm:

---

Reviewed 8 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/297#-:-KlZS-0tdh2GuUydf3dr:bnfp4nl)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 46 of 58 files at r1, 9 of 11 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/297#-:-Kl_354fT4pG9ibWIYcS:bnfp4nl)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test.sh, line 18 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/297#-KlYtpmErSmEIIidd-RZ:-Kl_3MAJu233YtI0Mbie:beqav7j) ([raw file](https://github.com/mirantis/virtlet/blob/d703eafddbf089749ffc9b616f7853cac3a64b1f/test.sh#L18)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

uncomment this?
</blockquote></details>

it was a tmp change while debugging Travis

---

*[test.sh, line 22 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/297#-KlYuEw1CDhVEIEmW9jj:-Kl_3P0DQkAKXxlYRwH9:bnj7hl0) ([raw file](https://github.com/mirantis/virtlet/blob/d703eafddbf089749ffc9b616f7853cac3a64b1f/test.sh#L22)):*
<details><summary><i>Previously, vefimova (Victoria Efimova) wrote…</i></summary><blockquote>

Probably we need to perform it only when testing with Travis and  to add comment with explanation?
</blockquote></details>

same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/297)*

**Pull request merged**
