### PR TITLE
Reuse `mirantis/virtlet` container image also for logger

### PR DESCRIPTION
**Pull request by miha-plesko**
Turns out that introducing a new container image mirantis/virtlet-log brings a lot of performance overhead to unit tests. Therefore we reuse mirantis/virtlet image for logger and only set it appropriate boot command.

With this commit we also deploy logger container inside same pod as virtlet is deployed so that virtlet pod now contains two containers:

* virtlet
* virtlet-log

This brings some problems since commands that were previously like:
```
$ kubectl exec -it virtlet-jadgffgd
```
now complain that they don't know what container to target with action. Therefore we modify e2e tests so that we explicitly specify container name that we're referring to:
```
$ kubectl exec -it virtlet-jadgffgd -c virtlet
```

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/309)

### CODE REVIEW

**Comment by ivan4th** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/virtlet-ds.yaml, line 117 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/309#-Km1kMl-LL0ZE7VKYHnW:-Km1kMl-LL0ZE7VKYHnX:b-lenl40) ([raw file](https://github.com/mirantis/virtlet/blob/db552ab31b635b5c25f5ee4872f75f1527bc2ab7/deploy/virtlet-ds.yaml#L117)):*
> ```YAML
>         command:
>           - /virtlet_log
>         volumeMounts:        
> ```

please remove extra space at the end of the line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/309)*

**Comment by miha-plesko** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/virtlet-ds.yaml, line 117 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/309#-Km1kMl-LL0ZE7VKYHnW:-Km1mTK0_Ib7bCyglBor:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/db552ab31b635b5c25f5ee4872f75f1527bc2ab7/deploy/virtlet-ds.yaml#L117)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

please remove extra space at the end of the line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/309)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/309#-:-Km1onw_-UJSGN_xSrs4:bnfp4nl)*

**Comment by ivan4th** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/309)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/309#-:-Km1p-ZVjx3pzz_MgVVp:bnfp4nl)*

**Pull request merged**
