### PR TITLE
Dump metadata as a subcommand for virtletctl

### PR DESCRIPTION
**Pull request by jellonek**
This PR provides a base for multi command binary `virtletctl` with beginning of first command, dump of metadata store from all instances of virtlet containers on the cluster.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/587)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/tools/common.go, line 67 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6RL5BMWAHl2SuognMv:-L6RL5BMWAHl2SuognMw:b-yzsa6n) ([raw file](https://github.com/mirantis/virtlet/blob/cfb2d722f86a1d600de762982c00a213cbcff6b2/pkg/tools/common.go#L67)):*
> ```Go
> 	stdin io.Reader, stdout, stderr io.Writer,
> 	command ...string,
> ) (int, error) {
> ```

ExecInContainer maybe?

---

*[pkg/tools/dumpmetadata.go, line 63 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6RLNiUCRXvqW2Zac61:-L6RLNiUCRXvqW2Zac62:b-ecb6j) ([raw file](https://github.com/mirantis/virtlet/blob/cfb2d722f86a1d600de762982c00a213cbcff6b2/pkg/tools/dumpmetadata.go#L63)):*
> ```Go
> 		stdin := bytes.NewBufferString("")
> 
> 		fmt.Printf("pod: %s\n", pod.Name)
> ```

"Virtlet pod name:"

---

*[pkg/tools/dumpmetadata.go, line 82 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6RL9J9QFeZTZRGN6VT:-L6RL9J9QFeZTZRGN6VU:b-pzfnsp) ([raw file](https://github.com/mirantis/virtlet/blob/cfb2d722f86a1d600de762982c00a213cbcff6b2/pkg/tools/dumpmetadata.go#L82)):*
> ```Go
> 			continue
> 		}
> 		f, err := ioutil.TempFile("/tmp", "virtlet-")
> ```

maybe it would be better to dump it to stdout, like all kubectl commands behave for example? That would provide much more flexibility

---

*[pkg/tools/subcommands.go, line 55 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6RKjy1Sn-DoMjvjX54:-L6RKjy2YjlWFR1XFzjC:bh8vzrz) ([raw file](https://github.com/mirantis/virtlet/blob/cfb2d722f86a1d600de762982c00a213cbcff6b2/pkg/tools/subcommands.go#L55)):*
> ```Go
> func ParseFlags(command string) error {
> 	flag.StringVar(&kubeconfig, "kubeconfig", "~/.kube/config", "absolute path to the kubeconfig file")
> 	flag.StringVar(&master, "master", "http://127.0.0.1:8080", "master url")
> ```

The default value must be blank and the description needs to be something like "master url (overrides the value from kubeconfig)". Otherwise the apiserver url from ~/.kube/config is never used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/587)*

**Comment by ivan4th** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/tools/dumpmetadata.go, line 82 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6RL9J9QFeZTZRGN6VT:-L6RM2NCMywMfilktGmG:b2xm6pk) ([raw file](https://github.com/mirantis/virtlet/blob/cfb2d722f86a1d600de762982c00a213cbcff6b2/pkg/tools/dumpmetadata.go#L82)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe it would be better to dump it to stdout, like all kubectl commands behave for example? That would provide much more flexibility
</blockquote></details>

Hmm oops it saves binary metadata. I thought there may be some kind of human-readable dump of it...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/587)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/tools/common.go, line 67 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6RL5BMWAHl2SuognMv:-L6RMBAVq7CG32JvSf8M:b9hsvxi) ([raw file](https://github.com/mirantis/virtlet/blob/cfb2d722f86a1d600de762982c00a213cbcff6b2/pkg/tools/common.go#L67)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

ExecInContainer maybe?
</blockquote></details>

Yep, better name.

---

*[pkg/tools/dumpmetadata.go, line 63 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6RLNiUCRXvqW2Zac61:-L6RMDUJnqXpvF84bgep:b2nhktp) ([raw file](https://github.com/mirantis/virtlet/blob/cfb2d722f86a1d600de762982c00a213cbcff6b2/pkg/tools/dumpmetadata.go#L63)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

"Virtlet pod name:"
</blockquote></details>

OK.

---

*[pkg/tools/dumpmetadata.go, line 82 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6RL9J9QFeZTZRGN6VT:-L6RMF9WIb7JYdszTpW0:b-hpjeep) ([raw file](https://github.com/mirantis/virtlet/blob/cfb2d722f86a1d600de762982c00a213cbcff6b2/pkg/tools/dumpmetadata.go#L82)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Hmm oops it saves binary metadata. I thought there may be some kind of human-readable dump of it...
</blockquote></details>

Nope. it's WIP for this moment. Finally data will be read from these files and dumped in human readable form to stdout.

---

*[pkg/tools/subcommands.go, line 55 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6RKjy1Sn-DoMjvjX54:-L6RMQbaAUfs5NFPTQEb:b-1lg1ki) ([raw file](https://github.com/mirantis/virtlet/blob/cfb2d722f86a1d600de762982c00a213cbcff6b2/pkg/tools/subcommands.go#L55)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

The default value must be blank and the description needs to be something like "master url (overrides the value from kubeconfig)". Otherwise the apiserver url from ~/.kube/config is never used
</blockquote></details>

Will do that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/587)*

**Comment by ivan4th** [comment]
I'd suggest moving the dumper to pkg/metadata and adding a simple test for it (compare output for a prefilled db to some expected output), given that there are problems in the code.

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/tools/dumpmetadata.go, line 114 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SKaBiaLu2XT2JBlAd:-L6SKaBiaLu2XT2JBlAe:b-e6omhi) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L114)):*
> ```Go
> }
> 
> func dumpMetadata(fname string) error {
> ```

I'd make a Dumper struct that should  contain the output stream and indent level. Dumper.indent(N) should return a new dumper with indent level increased. Make all print... funcs methods of the dumper

---

*[pkg/tools/dumpmetadata.go, line 141 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SJCX6ch-vyzf8HGKF:-L6SJCX6ch-vyzf8HGKG:bji450b) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L141)):*
> ```Go
> 
> 	for image := range images {
> 		printlnIndented(2, image)
> ```

This is probably a bug? It'll just print numbers starting from 0.

---

*[pkg/tools/dumpmetadata.go, line 149 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SKqiLG_7x0yedteyL:-L6SKqiLG_7x0yedteyM:bhsfw7x) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L149)):*
> ```Go
> func dumpSandbox(podid string, sandbox *metadata.PodSandboxInfo, s metadata.MetadataStore) error {
> 	printlnIndented(2, "Sandbox id: %s", podid)
> 	printlnIndented(0, spew.Sdump(sandbox))
> ```

This will probably look rather mangled. First of all, spew output should be split into separate lines via strings.Split and then these lines displayed with indent added. Second, spew sdump looks quite messy by default, I'd suggest cleaning it up a little bit, like this https://github.com/Mirantis/criproxy/blob/b6769d9d6fc4b2d3b9e191acce425e57c0a3d0e0/pkg/proxy/proxy.go#L519-L526 (although we probably need to have smth better than vanilla go-spew at some point)

---

*[pkg/tools/dumpmetadata.go, line 174 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SNBfOYNd8_1eplZfV:-L6SNBfOYNd8_1eplZfW:b6o3lnz) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L174)):*
> ```Go
> 
> func printlnIndented(level int, format string, data ...interface{}) {
> 	printIndentedWith(" ", 2*level, format+"\n", data...)
> ```

maybe `printIndented(level, format+"\n", data...)` would be better (so there's no unneeded repetition of `"  ", 2*level` with an added risk of inconsistency if we want to change the indent at some point)? Also I'd probably move `"  "` to a const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/587#-:-L6SJQQA-iwOOwCTRDK6:b-dgxrli)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/tools/dumpmetadata.go, line 114 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SKaBiaLu2XT2JBlAd:-L6WaiBsJWsGEDJHNlR-:bmxj8q2) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L114)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

I'd make a Dumper struct that should  contain the output stream and indent level. Dumper.indent(N) should return a new dumper with indent level increased. Make all print... funcs methods of the dumper
</blockquote></details>

Good idea but would like to do that as a followup.

---

*[pkg/tools/dumpmetadata.go, line 141 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SJCX6ch-vyzf8HGKF:-L6Waow3ZShdcIIK6G4m:bx1f7h6) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L141)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

This is probably a bug? It'll just print numbers starting from 0.
</blockquote></details>

No, it's map so that iterates over the keys which are string. Give it a try ;)

---

*[pkg/tools/dumpmetadata.go, line 149 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SKqiLG_7x0yedteyL:-L6Wb2n-n_ZKL0HGXJ7S:bt5qipd) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L149)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

This will probably look rather mangled. First of all, spew output should be split into separate lines via strings.Split and then these lines displayed with indent added. Second, spew sdump looks quite messy by default, I'd suggest cleaning it up a little bit, like this https://github.com/Mirantis/criproxy/blob/b6769d9d6fc4b2d3b9e191acce425e57c0a3d0e0/pkg/proxy/proxy.go#L519-L526 (although we probably need to have smth better than vanilla go-spew at some point)
</blockquote></details>

It was used to have a fast effect. Level 0 is used simply to not add any indentation for first line.
I'm not sure if we should waste more time on that, it's only a debug util with potential quite small use.

---

*[pkg/tools/dumpmetadata.go, line 174 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SNBfOYNd8_1eplZfV:-L6WbpV5JJJ8kAYdD4WF:bcvjgzp) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L174)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

maybe `printIndented(level, format+"\n", data...)` would be better (so there's no unneeded repetition of `"  ", 2*level` with an added risk of inconsistency if we want to change the indent at some point)? Also I'd probably move `"  "` to a const
</blockquote></details>

Good idea. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/587)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/tools/dumpmetadata.go, line 141 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SJCX6ch-vyzf8HGKF:-L6Wd125jE0kyOtg9CtM:b9ypdhj) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L141)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

No, it's map so that iterates over the keys which are string. Give it a try ;)
</blockquote></details>

Example output:
```
  Images:
    cirros@sha256:0615af1caf345e605e27d5419f8d4c6d087b3b41ff4b979aec094ce0399f04ab
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/587)*

**Comment by jellonek** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/tools/subcommands.go, line 55 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6RKjy1Sn-DoMjvjX54:-L6WdbBq74arLQWyxQww:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/cfb2d722f86a1d600de762982c00a213cbcff6b2/pkg/tools/subcommands.go#L55)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Will do that!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/587)*

**Comment by ivan4th** [comment]
Reviewed 2 of 5 files at r1, 1 of 2 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/tools/dumpmetadata.go, line 114 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SKaBiaLu2XT2JBlAd:-L6WhaQ9IJ4qq467hQK-:b2nhll9) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L114)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Good idea but would like to do that as a followup.
</blockquote></details>

Ok.

---

*[pkg/tools/dumpmetadata.go, line 141 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SJCX6ch-vyzf8HGKF:-L6WhcL4xEyBtNJPjlQq:blhmlq8) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L141)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Example output:
```
  Images:
    cirros@sha256:0615af1caf345e605e27d5419f8d4c6d087b3b41ff4b979aec094ce0399f04ab
```
</blockquote></details>

Sorry, dunno why I thought it was a slice. My bad.

---

*[pkg/tools/dumpmetadata.go, line 149 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6SKqiLG_7x0yedteyL:-L6Whn3VfHpJ8kQ0XY4I:bkyad2o) ([raw file](https://github.com/mirantis/virtlet/blob/34de466f34c000e6d1fee2239f43aa0638e655ea/pkg/tools/dumpmetadata.go#L149)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

It was used to have a fast effect. Level 0 is used simply to not add any indentation for first line.
I'm not sure if we should waste more time on that, it's only a debug util with potential quite small use.
</blockquote></details>

Ok let's keep it this way for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/587)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/587#-:-L6Wi0Xy8Zbem1JlF2hb:bnfp4nl)*

**Comment by lukaszo** [comment]
:lgtm:

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/tools/common.go, line 59 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/587#-L6WpmkeJ2vXYQ12LQmx:-L6WpmkeJ2vXYQ12LQmy:bnxp0hy) ([raw file](https://github.com/mirantis/virtlet/blob/9825512f0b2676a87620744a96abcfc131172a12/pkg/tools/common.go#L59)):*
> ```Go
> }
> 
> // ExecCommandOnContainer given a pod, container, namespace and command
> ```

ExecInContainer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/587#-:-L6WrkAklKS41vxIow00:bnfp4nl)*

**Pull request merged**
