### PR TITLE
 Updates e2e test to use extended cirros image

### PR DESCRIPTION
**Pull request by istalker2**
* Changes default cirros image location to github image
* Fixes incompatibilities with old tests
* Some simplification of test code

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/464)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/464)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/464#-:-Kw9UGVNGkD2ML7qrbWX:bnfp4nl)*

**Comment by ivan4th** [comment]
This PR appears to include a commit from #463 ?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/464#-:-Kw9Ua1f7sw59zDV19iw:b1whynn)*

**Comment by pigmej** [comment]
@ivan4th I think so but #463 is merged now so doesn't matter for now I think.

**Comment by ivan4th** [comment]
@pigmej no, it does matter as the commit has different id here. We'll get duplicate commits in the history.

**Comment by pigmej** [comment]
@ivan4th then it certainly does matter.

**Comment by ivan4th** [comment]
Ok, I looked at the wrong commit id.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/464#-:-Kw9X_beLBbAl18VUAua:bawo1dv)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/464#-:-Kw9XdRyxVqyAzhBB7tr:bnfp4nl)*

**Pull request merged**
