### PR TITLE
Support KVM detection in build/cmd.sh start-dind

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/329)

### CODE REVIEW

**Comment by gberginc** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/cmd.sh, line 176 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/329#-Kn3CrUNv3XH7CDPaj34:-Kn3CrUNv3XH7CDPaj35:b-c8l2s9) ([raw file](https://github.com/mirantis/virtlet/blob/fedf8a1ddf86f744da4d633c74fe91ea460c7609/build/cmd.sh#L176)):*
> ```Shell
> }
> 
> function kvm_ok {
> ```

Are you intentionally using different indentation here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/329)*

**Comment by ivan4th** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/cmd.sh, line 176 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/329#-Kn3CrUNv3XH7CDPaj34:-Kn3pLTDPVf2jshpsO5b:bz74hs5) ([raw file](https://github.com/mirantis/virtlet/blob/fedf8a1ddf86f744da4d633c74fe91ea460c7609/build/cmd.sh#L176)):*
<details><summary><i>Previously, gberginc (Gregor Berginc) wrote…</i></summary><blockquote>

Are you intentionally using different indentation here?
</blockquote></details>

Fixed, thanks. Frankly speaking, it would be nice to convert the whole file to 2-space indentation to be consistent with other scripts, e.g. `demo.sh`... But perhaps we should do this in a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/329)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/329#-:-Kn3q7OjFPlquCAENdaW:bnfp4nl)*

**Comment by vefimova** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/329#-:-Kn3xBW7zGuU-zAUuf-2:bnfp4nl)*

**Pull request merged**
