### PR TITLE
Fix log serialization

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/311)

### CODE REVIEW

**Comment by miha-plesko** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Km64dFOXWwtkr6Xv2uJ:-Km64dFOXWwtkr6Xv2uK:by7jexs) (no related file):*
Despite the one comment I gave, this looks great to me. I've tested on my local machine and everything seems to be working as a charm. Even the cirros logo
```
2017-06-08T08:59:05Z   ____               ____  ____
 2017-06-08T08:59:05Z  / __/ __ ____ ____ / __ \/ __/
 2017-06-08T08:59:05Z / /__ / // __// __// /_/ /\ \ 
 2017-06-08T08:59:05Z \___//_//_/  /_/   \____/___/ 
 2017-06-08T08:59:05Z    http://cirros-cloud.net
```
is not skewed anymore :thumbsup: 

Yet, I have no idea why Travis fails. There seems to be no error in the the whole log. At first I suspected this line to fail https://github.com/Mirantis/virtlet/blob/master/tests/e2e/e2e.sh#L124, but there should be an error in Travis saying "Checking formatted log file failed. Expected 1 line but got 0", isn't it?

---

*[pkg/log/logger.go, line 194 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Km5xB9Rwko7SDWvBczE:-Km5xB9SaL2mirNNaFsO:buwmy3m) ([raw file](https://github.com/mirantis/virtlet/blob/b98e473e7a230a7e397063a42c967f15d3439f7f/pkg/log/logger.go#L194)):*
> Convert raw line into Kubernetes json.
I'm thinking if a single problematic line should really stop whole worker. Please consider replacing `break` with `continue`.

The other day you've mentioned that `kubectl logs -f` suddenly stopped working in some cases. Could it be that there was some strange line that failed to marshall causing the whole worker to stop? Thing is that if worker stops, yes, new worker is spawned within 10 seconds, but it will truncate the file when spawn. That's because when worker is spawned, it always parses whole raw file and overrides the formatted one completely.

---

*[pkg/log/logger.go, line 194 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Km5zdCwjLE0o1qPouoR:-Km5zdCwjLE0o1qPouoS:b-jbrgaf) ([raw file](https://github.com/mirantis/virtlet/blob/b98e473e7a230a7e397063a42c967f15d3439f7f/pkg/log/logger.go#L194)):*
> ```Go
> 		if err != nil {
> 			glog.V(1).Infoln("Error marshalling the log line:", line.Err.Error())
> 			break
> ```

Also, please change severity of the log above from `Infoln` to `Warningln`.

---

*[pkg/log/logger_test.go, line 360 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Km62XYPGRK7YKFa0p_7:-Km62XYQyUOnKUEenrcx:b1o7g62) ([raw file](https://github.com/mirantis/virtlet/blob/b98e473e7a230a7e397063a42c967f15d3439f7f/pkg/log/logger_test.go#L360)):*
> ```Go
> 		}
> 		timeDiff := time.Now().Sub(logTime)
> 		if timeDiff < 0 || timeDiff > 10*time.Minute {
> ```

Job well done! I really like how we're able to test even time now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/311)*

**Comment by ivan4th** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/log/logger.go, line 194 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Km5xB9Rwko7SDWvBczE:-Km66JEBi1Go7wW5M9Yg:b-h0ukb4) ([raw file](https://github.com/mirantis/virtlet/blob/b98e473e7a230a7e397063a42c967f15d3439f7f/pkg/log/logger.go#L194)):*
<details><summary><i>Previously, miha-plesko (Miha Pleško) wrote…</i></summary><blockquote>

> Convert raw line into Kubernetes json.
I'm thinking if a single problematic line should really stop whole worker. Please consider replacing `break` with `continue`.

The other day you've mentioned that `kubectl logs -f` suddenly stopped working in some cases. Could it be that there was some strange line that failed to marshall causing the whole worker to stop? Thing is that if worker stops, yes, new worker is spawned within 10 seconds, but it will truncate the file when spawn. That's because when worker is spawned, it always parses whole raw file and overrides the formatted one completely.
</blockquote></details>

Concerning break vs continue: ok, will do this (although `json.Marshal()` erroring here must be something truly exceptional)

As of `kubectl logs -f`, I actually suspect that it's due to inotify + overlayfs problem on DIND. Perhaps kubelet doesn't invoke a proper fallback there. Will try to move pod logs to a docker volume (could use also tmpfs but this may lead to high RAM usage)

---

*[pkg/log/logger.go, line 194 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Km5zdCwjLE0o1qPouoR:-Km66hjn17uJfXRVsFWc:b-w9iv2z) ([raw file](https://github.com/mirantis/virtlet/blob/b98e473e7a230a7e397063a42c967f15d3439f7f/pkg/log/logger.go#L194)):*
<details><summary><i>Previously, miha-plesko (Miha Pleško) wrote…</i></summary><blockquote>

Also, please change severity of the log above from `Infoln` to `Warningln`.
</blockquote></details>

Will fix, thanks.

---

*[pkg/log/logger_test.go, line 360 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Km62XYPGRK7YKFa0p_7:-Km66joYIBfg7qXHvGKc:b-68xgje) ([raw file](https://github.com/mirantis/virtlet/blob/b98e473e7a230a7e397063a42c967f15d3439f7f/pkg/log/logger_test.go#L360)):*
<details><summary><i>Previously, miha-plesko (Miha Pleško) wrote…</i></summary><blockquote>

Job well done! I really like how we're able to test even time now.
</blockquote></details>

It would be better to use fake time, I'm being a bit lazy here... But I think this will do for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/311)*

**Comment by jellonek** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/e2e/e2e.sh, line 125 at r2](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Kn1UGr8Z0wpL70_o85Y:-Kn1UGr8Z0wpL70_o85Z:b-8fx2u7) ([raw file](https://github.com/mirantis/virtlet/blob/c223370899bcb85c3063200ccf01462557e8efd0/tests/e2e/e2e.sh#L125)):*
> ```Shell
> # DIND containers have jq installed so we can use it
> count=$(docker exec -it ${nodeid} /bin/bash -c "jq .log /var/log/pods/${sandboxid}/${filename}" | \
>      grep "login as 'cirros' user. default password:.*'. use 'sudo' for root" | \
> ```

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/311)*

**Comment by ivan4th** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/log/logger.go, line 194 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Km5xB9Rwko7SDWvBczE:-Kn2f_fHpp9VIw4m3TCu:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/b98e473e7a230a7e397063a42c967f15d3439f7f/pkg/log/logger.go#L194)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Concerning break vs continue: ok, will do this (although `json.Marshal()` erroring here must be something truly exceptional)

As of `kubectl logs -f`, I actually suspect that it's due to inotify + overlayfs problem on DIND. Perhaps kubelet doesn't invoke a proper fallback there. Will try to move pod logs to a docker volume (could use also tmpfs but this may lead to high RAM usage)
</blockquote></details>

Done.

---

*[pkg/log/logger.go, line 194 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Km5zdCwjLE0o1qPouoR:-Kn2fa1dwXAvd2bOVuYd:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/b98e473e7a230a7e397063a42c967f15d3439f7f/pkg/log/logger.go#L194)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Will fix, thanks.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/311)*

**Comment by jellonek** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/log/logger.go, line 193 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Kn3olCQB6fiAHQEn_Wr:-Kn3olCQB6fiAHQEn_Ws:btg3dfp) ([raw file](https://github.com/mirantis/virtlet/blob/a1bc2d4062cd76a0f0ff4a9f4817daf3c8ff57d8/pkg/log/logger.go#L193)):*
> ```Go
> 		converted, err := json.Marshal(m)
> 		if err != nil {
> 			glog.Warningln("Error marshalling the log line:", line.Err.Error())
> ```

Shouldn't that be on `V(1)` level?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/311)*

**Comment by ivan4th** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/log/logger.go, line 193 at r3](https://reviewable.io:443/reviews/mirantis/virtlet/311#-Kn3olCQB6fiAHQEn_Wr:-Kn3pnvo4-urnAQtzzK3:b39hw5x) ([raw file](https://github.com/mirantis/virtlet/blob/a1bc2d4062cd76a0f0ff4a9f4817daf3c8ff57d8/pkg/log/logger.go#L193)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Shouldn't that be on `V(1)` level?
</blockquote></details>

This was changed to `Warningln` by Miha's request below and I think it's justified as it must be something really exceptional here to have `json.Marshal()` fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/311)*

**Pull request merged**
