### PR TITLE
examples: Add a way to install virsh.sh as kubectl plugin

### PR DESCRIPTION
**Pull request by jellonek**
[ci skip]

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/virtlet/562)

### CODE REVIEW

**Comment by ivan4th** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/README.md, line 47 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/562#-L4GsMhureIr9SSJZWES:-L4GsMhureIr9SSJZWET:b-gnu82x) ([raw file](https://github.com/mirantis/virtlet/blob/6ac9c96cd31cd639f73d81962ae3ed417d3aced7/examples/README.md#L47)):*
> ```Markdown
> ```
> 
> Other option to use this script is to install it as a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/).
> ```

Another option

---

*[examples/README.md, line 48 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/562#-L4GsVHw6bdLJ71CYrBl:-L4GsVHw6bdLJ71CYrBm:bvsjdc8) ([raw file](https://github.com/mirantis/virtlet/blob/6ac9c96cd31cd639f73d81962ae3ed417d3aced7/examples/README.md#L48)):*
> ```Markdown
> 
> Other option to use this script is to install it as a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/).
> Note that this option is available only for `kubectl` starting from version `1.9.0`.
> ```

Some people may get confused here as Virtlet doesn't support k8s 1.9 yet. And using kubectl 1.9 with Kubernetes 1.8 may cause problems (e.g. IIRC StatefulSets are defined with different type spec). So perhaps we should add some notes there?

---

*[examples/virsh.sh, line 7 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/562#-L4GrsutLEK_2rnulfqr:-L4GrsuuNAg1uKcmaH1n:b-skd5ii) ([raw file](https://github.com/mirantis/virtlet/blob/6ac9c96cd31cd639f73d81962ae3ed417d3aced7/examples/virsh.sh#L7)):*
> ```Shell
> set -o errtrace
> 
> PLUGINBASEDIR=~/.kube/plugins/virt
> ```

`"${HOME}/.kube/plugins/virt"` perhaps is a bit better

---

*[examples/virsh.sh, line 21 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/562#-L4GrjST_P0qn8fIzT1z:-L4GrjST_P0qn8fIzT2-:b-h9qspj) ([raw file](https://github.com/mirantis/virtlet/blob/6ac9c96cd31cd639f73d81962ae3ed417d3aced7/examples/virsh.sh#L21)):*
> ```Shell
> function install_as_kubectl_plugin {
>   mkdir -p "${PLUGINBASEDIR}"
>   cp ${0} "${PLUGINBASEDIR}/virt"
> ```

`"${0}"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/562)*

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/README.md, line 47 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/562#-L4GsMhureIr9SSJZWES:-L4KvxZ1kzcgGPgDL0Th:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/6ac9c96cd31cd639f73d81962ae3ed417d3aced7/examples/README.md#L47)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Another option
</blockquote></details>

Done.

---

*[examples/README.md, line 48 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/562#-L4GsVHw6bdLJ71CYrBl:-L4Kvy18o0Ekr2upO9d3:b-tb0nxh) ([raw file](https://github.com/mirantis/virtlet/blob/6ac9c96cd31cd639f73d81962ae3ed417d3aced7/examples/README.md#L48)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

Some people may get confused here as Virtlet doesn't support k8s 1.9 yet. And using kubectl 1.9 with Kubernetes 1.8 may cause problems (e.g. IIRC StatefulSets are defined with different type spec). So perhaps we should add some notes there?
</blockquote></details>

Yes, that can lead to confusion, but hopefully - for not so long time. We can add some note there - but what it should contain?

---

*[examples/virsh.sh, line 7 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/562#-L4GrsutLEK_2rnulfqr:-L4KwjHmoWObSnzwEk0e:b-r7fq6r) ([raw file](https://github.com/mirantis/virtlet/blob/6ac9c96cd31cd639f73d81962ae3ed417d3aced7/examples/virsh.sh#L7)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`"${HOME}/.kube/plugins/virt"` perhaps is a bit better
</blockquote></details>

Yes, much better. Done.

---

*[examples/virsh.sh, line 21 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/562#-L4GrjST_P0qn8fIzT1z:-L4KwmIu5J-B3fGjV8t3:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/6ac9c96cd31cd639f73d81962ae3ed417d3aced7/examples/virsh.sh#L21)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

`"${0}"`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/562)*

**Comment by ivan4th** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/README.md, line 48 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/562#-L4GsVHw6bdLJ71CYrBl:-L4eq61CHnC0HXqBypt0:b-ljc4tv) ([raw file](https://github.com/mirantis/virtlet/blob/6ac9c96cd31cd639f73d81962ae3ed417d3aced7/examples/README.md#L48)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Yes, that can lead to confusion, but hopefully - for not so long time. We can add some note there - but what it should contain?
</blockquote></details>

"At the moment, Virtlet only supports Kubernetes 1.7.x and 1.8.x. You can use a newer kubectl with these Kubernetes versions but this may cause problems with some kinds of objects such as StatefulSets. So the kubectl plugin feature can be considered experimental at the moment."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/562)*

**Comment by jellonek** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/README.md, line 48 at r1](https://reviewable.io:443/reviews/mirantis/virtlet/562#-L4GsVHw6bdLJ71CYrBl:-L4jaOjJgf6USzp7snyE:b-896fix) ([raw file](https://github.com/mirantis/virtlet/blob/6ac9c96cd31cd639f73d81962ae3ed417d3aced7/examples/README.md#L48)):*
<details><summary><i>Previously, ivan4th (Ivan Shvedunov) wrote…</i></summary><blockquote>

"At the moment, Virtlet only supports Kubernetes 1.7.x and 1.8.x. You can use a newer kubectl with these Kubernetes versions but this may cause problems with some kinds of objects such as StatefulSets. So the kubectl plugin feature can be considered experimental at the moment."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/562)*

**Comment by ivan4th** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/562#-:-L4kKG8k6TXHPktwjfnx:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/virtlet/562#-:-L4qU_phaEzh-NEZsAuE:bnfp4nl)*

**Pull request merged**
